    // ==== JS_UI parça 2: ALLCAPS etiketler N-Z ====
    "NANO": "纳米",
    "NANO SWARM": "纳米虫群",
    "NANO-REGEN": "纳米再生",
    "NEURAL HIJACK": "神经劫持",
    "NEURAL INTERFACE OFFLINE": "神经接口离线",
    "NEURAL SYNERGIES": "神经协同",
    "NEVER": "从不",
    "NEW GAME": "新游戏",
    "NEW RIG": "新矿机",
    "NEXT": "下一个",
    "NO ACTIVE OBJECTIVES": "没有进行中的目标",
    "NO FUNDS": "资金不足",
    "NO GEAR IN STASH": "仓库中没有装备",
    "NO MODULE": "无模块",
    "NO MYTHIC ITEMS IN STASH": "仓库中没有 MYTHIC 物品",
    "NO THANKS": "不用了",
    "NOT ENOUGH CREDITS": "点数不足",
    "NOT ENOUGH EP": "EP 不足",
    "NOT ENOUGH INSANITY": "疯狂值不足",
    "NOT ENOUGH MONEY": "金钱不足",
    "NOT YET": "还没到时候",
    "NOTHING TO ROLL": "没有可重掷的",
    "OFFENSE": "攻击",
    "OK": "好",
    "ON DEATH": "死亡时",
    "ON HIT": "命中时",
    "ON HIT TAKEN": "受击时",
    "ON KILL": "击杀时",
    "OPERATIONS": "行动",
    "OPERATIVE": "干员",
    "OPTIONS": "选项",
    "OVERLOAD": "过载",
    "OVERWRITE": "覆盖",
    "OVERWRITE SLOT": "覆盖槽位",
    "PACK": "背包",
    "PASSIVE": "被动",
    "PASSIVE BONUSES": "被动加成",
    "PATCH CODES": "补丁代码",
    "PATCHES": "补丁",
    "PATCHES:": "补丁：",
    "PEN": "穿透",
    "PERFECT": "完美",
    "PERFORMANCE": "性能",
    "PERMA": "永久",
    "PHAGE": "噬体",
    "PHANTOM IMPLICIT": "幻影固有词条",
    "PHANTOM STRIKE": "幻影打击",
    "PHASE": "相位",
    "PHASE SHIFT": "相位偏移",
    "PISTOL": "手枪",
    "PLAN MODE": "方案模式",
    "PLAY TUTORIAL": "游玩教程",
    "POST-RAID SUMMARY": "RAID 结算",
    "PRECOGNITION": "预知",
    "PRESET LOADED": "预设已载入",
    "PRESET SAVED": "预设已保存",
    "PRESETS": "预设",
    "PRESS ANY": "按任意键",
    "PRESTIGE-SAFE": "转生保留",
    "PRIMARY": "主武器",
    "PROGRESS": "进度",
    "PROTECTIONS": "保护",
    "PROTO MAG": "原型弹匣",
    "PROTOTYPE DROP": "PROTOTYPE 掉落",
    "PROTOTYPE LOCKED": "PROTOTYPE 已锁定",
    "PULSE": "脉冲",
    "PUPPY": "幼犬",
    "QTY:": "数量：",
    "QUALITY": "品质",
    "QUANTUM": "量子",
    "QUEST ACCEPTED": "任务已接受",
    "QUEST LOG": "任务日志",
    "QUESTS ACCEPTED": "任务已接受",
    "QUICK SAVE": "快速保存",
    "R.ARM": "右臂",
    "R.LEG": "右腿",
    "RAID IN PROGRESS": "RAID 进行中",
    "RANDOM GEAR": "随机装备",
    "RANGE": "射程",
    "RANGED": "远程",
    "REACH": "触及",
    "REBIRTH": "重生",
    "REBIRTH TO UNLOCK": "重生后解锁",
    "RECOVER": "找回",
    "REFUND MODE": "退点模式",
    "REGEN": "回复",
    "REJECTED": "已拒绝",
    "RELOAD": "装填",
    "RELOADED": "装填完成",
    "RELOADING": "装填中",
    "RELOADING...": "装填中……",
    "REMOVE ALL GEAR FIRST": "先卸下所有装备",
    "REPAIR": "修理",
    "REPAIR WEAPON": "修理武器",
    "REROLL": "重掷",
    "REROLLED": "已重掷",
    "RESET KEYS": "重置按键",
    "RESET MASTERY": "重置精通",
    "RESET TREE": "重置天赋树",
    "RESISTANCE": "抗性",
    "RESONANCE // RARITY": "共振 // 稀有度",
    "RESPEC": "洗点",
    "RESPEC HARVEST": "收割洗点",
    "RESPEC PROTOCOL": "洗点协议",
    "REST": "休息",
    "RESTART": "重启",
    "RETURN TO HIDEOUT": "返回藏身处",
    "REWARD:": "奖励：",
    "REWARDS": "奖励",
    "RICOCHET": "跳弹",
    "RIFLE": "步枪",
    "RIG": "战术背心",
    "RIGHT ARM": "右臂",
    "RIGHT LEG": "右腿",
    "RIGHT-CLICK": "右键点击",
    "RIPPERDOC PATCHED YOU UP": "RIPPERDOC 把你缝好了",
    "ROLL": "掷点",
    "ROLL & EQUIP": "掷点并装备",
    "ROOT ACCESS": "根权限",
    "ROTATING STOCK": "轮换库存",
    "RUCKSACK": "行军背包",
    "RUN BEST": "跑最深层",
    "SAFE BOX": "保险箱",
    "SAFE BOX FULL": "保险箱已满",
    "SAFEBOX RETURN": "保险箱返还",
    "SALVAGE": "拆解",
    "SALVAGE ALL": "全部拆解",
    "SALVAGE ITEM": "拆解物品",
    "SALVAGED": "已拆解",
    "SAVE FAILED": "保存失败",
    "SAVE MANAGEMENT": "存档管理",
    "SAVE SIZE WARNING": "存档大小警告",
    "SAVE TO SLOT": "保存到槽位",
    "SCAVENGE": "拾荒",
    "SCOUTED:": "已侦察：",
    "SECURE": "安全存放",
    "SELECT AN AUGMENT SLOT": "选择一个义体槽位",
    "SELECT SLOTS TO FILL": "选择要填充的槽位",
    "SELECTED:": "已选择：",
    "SELL ALL": "全部出售",
    "SHADE": "阴影",
    "SHIFT + LEFT CLICK": "SHIFT + 左键",
    "SHOCKED": "触电",
    "SHOW ME": "带我看",
    "SIDEARM": "副武器",
    "SIGNAL DAMPENER": "信号阻尼器",
    "SIGNAL HARVEST": "信号收割",
    "SIGNAL MASTERY": "信号精通",
    "SIGNAL OVERCLOCK": "信号超频",
    "SIGNAL OVERLOAD": "信号过载",
    "SIGNAL WARDEN DETECTED": "检测到 SIGNAL WARDEN",
    "SIN": "罪孽",
    "SKILL POINT": "技能点",
    "SKILL POINT DRIVE": "技能点驱动器",
    "SKILL TREE UPGRADE": "技能树升级",
    "SKIP NOTES": "跳过说明",
    "SKIP TASK": "跳过任务",
    "SKIP TUTORIAL": "跳过教程",
    "SLOT": "槽位",
    "SLOT MATRIX": "槽位矩阵",
    "SLOTS": "槽位",
    "SOLD": "已出售",
    "SOULBOUND RETURN": "灵魂绑定返还",
    "SPD": "速度",
    "SPEED": "速度",
    "SPRINT": "冲刺",
    "STABILIZER CORE": "稳定核心",
    "STABLE": "稳定",
    "STAMINA": "耐力",
    "STANDING UP": "声望提升",
    "START": "开始",
    "STARTING NODES": "起始节点",
    "STASH FULL": "仓库已满",
    "STASH UPGRADE": "仓库升级",
    "STASIS LOCK": "静滞锁定",
    "STATS": "属性",
    "STATUS: LOCKED": "状态：锁定",
    "STATUS: PUPPY": "状态：幼犬",
    "STEALTH": "潜行",
    "STEP BACK": "后退一步",
    "STOCK REFRESHED": "库存已刷新",
    "STOMACH": "腹部",
    "SUCCESS": "成功",
    "SWITCH WEAPONS": "切换武器",
    "SWITCHING TO FISTS": "切换到拳头",
    "SWITCHING TO MELEE": "切换到近战",
    "SWITCHING TO RIFLE": "切换到步枪",
    "SWITCHING TO SIDEARM": "切换到副武器",
    "SYNTH": "合成",
    "SYSTEM:": "系统：",
    "TAILS": "反面",
    "TAKE A REST": "去休息吧",
    "TASK": "任务",
    "TECH MODULES": "科技模块",
    "THE BOSS": "头目",
    "THERMAL": "热能",
    "THORAX": "胸腔",
    "THREAT": "威胁",
    "TOTAL": "总计",
    "TOTAL:": "总计：",
    "TOY": "玩具",
    "TURN IN": "上交",
    "TUTORIAL COMPLETE": "教程完成",
    "UNLIMITED": "无限",
    "UNSECURE": "取出安全袋",
    "UTILITY": "功能",
    "UTILITY BELT": "工具腰带",
    "VAHLEN IS DEAD": "VAHLEN 已死",
    "VAULT": "保险库",
    "VISUAL EFFECTS": "视觉效果",
    "VOLUME CONTROLS": "音量控制",
    "WARDEN AVAILABLE": "WARDEN 可挑战",
    "WARDEN CHALLENGE": "WARDEN 挑战",
    "WARNING": "警告",
    "WARP EXTRACTION": "跃迁撤离",
    "WEAPON": "武器",
    "WEAPON HUD": "武器 HUD",
    "WEAPON SLOT EMPTY": "武器槽为空",
    "WEAPONS": "武器",
    "WEIGHT": "重量",
    "WILDCARD:": "万能牌：",
    "WIN": "胜利",
    "WIPE": "清空",
    "WIPE DRIVE": "清空驱动器",
    "WORM": "蠕虫",
    "WRAITH": "幽魂",
    "XP GAINED": "获得经验",
    "YOU": "你",
    "YOU LOST": "你输了",
