    // ==== chunk 04: loot tree ====
    "Appraiser": "鉴定师",
    "Component Scavenger": "部件拾荒",
    "Corpse Harvest": "尸体收割",
    "Data Siphon": "数据虹吸",
    "Deep Scan": "深度扫描",
    "ECHO CASCADE": "回响级联",
    "Echo Doubler": "回响倍增",
    "Fence Contacts": "销赃人脉",
    "MIDAS PROTOCOL": "点金协议",
    "Module Magnet": "模块磁铁",
    "Noise Floor": "本底噪声",
    "OVERSIGNAL": "超载信号",
    "Proto Resonance": "原型共振",
    "Signal Tap": "信号窃听",
