    // ==== chunk 11: nameTag'ler + augment slotları + sinerji/IG kısa açıklamalar ====
    "Agile": "敏捷",
    "Balanced": "均衡",
    "Covert": "隐蔽",
    "Deflecting": "偏转",
    "Ergonomic": "工学",
    "Expanded": "扩容",
    "Extended": "加长",
    "Locked": "锁定",
    "Hardened": "硬化",
    "Light": "轻量",
    "Looter": "拾荒",
    "Mono": "单分子",
    "Organized": "整理",
    "Overdriven": "超频",
    "Packrat": "囤积",
    "Piercing": "穿透",
    "Sharpened": "磨锐",
    "Plated": "镀甲",
    "Quick": "迅捷",
    "Rapid": "速装",
    "Long": "长距",
    "Scavenger": "拾荒者",
    "Servo": "伺服",
    "Shadowed": "暗影",
    "Shearing": "破甲",
    "Smuggler": "走私",
    "Streamlined": "流线",
    "Tactical": "战术",
    "Precise": "精准",
    "Vital": "活力",
    "Camoed": "迷彩",
    "Polished": "抛光",
    "Cloaked": "隐身",
    "Durable": "耐用",
    "Honed": "开刃",
    "Reliable": "可靠",
    "Finding": "探物",
    "Grabby": "抓取",
    "Taped": "缠带",
    "Grippy": "防滑",
    "Scanning": "扫描",
    "Spaced": "隔距",
    "Clocked": "加频",
    "Padded": "缓冲",
    "Tipped": "尖弹",
    "Inserted": "插板",
    "Pocketed": "带袋",
    "Reactive": "反应",
    "Reinforced": "加固",
    "Unlocked": "解限",
    "Tuned": "调校",
    "Maintained": "保养",
    "Angled": "斜角",
    "Dampened": "减震",
    "Silent": "无声",
    "Fast": "疾速",
    "Cooled": "散热",
    "Timed": "时序",
    "Vigorous": "强健",
    "Aimed": "瞄准",
    "Swift": "迅疾",
    "Heavy": "沉重",
    "OPTICS": "光学",
    "NEURAL": "神经",
    "DERMAL": "皮肤",
    "CORE": "核心",
    "ARMS": "手臂",
    "LEGS": "腿部",
    "FRAME": "骨架",
    "ORGAN": "器官",
    "MOUNT": "挂载",
    "+5 HP Regen": "+5 生命回复",
    "+30% First Strike Damage": "+30% 先攻伤害",
    "+25% Skill Damage": "+25% 技能伤害",
    "+15% Attack Speed": "+15% 攻击速度",
    "+10% Damage, +10% Speed": "+10% 伤害，+10% 速度",
    "+25 Armor": "+25 护甲",
    "+75 HP": "+75 生命",
    "+15 Stealth, +10 Evasion": "+15 潜行，+10 闪避",
    "+50% First Strike Damage": "+50% 先攻伤害",
    "+3 HP Regen": "+3 生命回复",
    "+10% Speed, +10 Evasion": "+10% 速度，+10 闪避",
    "+10% Damage": "+10% 伤害",
    "+20% Damage": "+20% 伤害",
    "+5 Scavenge": "+5 拾荒",
    "+20% Loot Quantity": "+20% 战利品数量",
    "2x auto-clicker speed": "自动点击速度 2 倍",
    "2x click damage": "点击伤害 2 倍",
    "4x golden enemy chance": "黄金敌人概率 4 倍",
    "2x insanity gain": "疯狂获取 2 倍",
    "Armor only": "仅护甲",
    "Weapons only": "仅武器",
    "0.5% MYTHIC roll": "0.5% MYTHIC 概率",
    "Boosts + permanent powers": "增益 + 永久强化",
    "High prototype odds": "高原型概率",
    "Mixed low-tier gear + boosts": "混合低阶装备 + 增益",
    "Pure insanity, paid in credits": "纯疯狂值，用点数支付",
    "Taking damage grants +10% damage for 5s (10s cooldown)": "受到伤害后获得 +10% 伤害，持续 5 秒（冷却 10 秒）",
    "+2% chance per rank that raid kills grant +1 insanity": "每级 +2% 概率使 RAID 击杀获得 +1 疯狂",
    "+1% boss cache drop chance per rank": "每级 +1% 头目补给箱掉落概率",
    "Each HOLLOW CROWN tier grants +5% trader sell price": "每层 HOLLOW CROWN 提供 +5% 商人出售价格",
    "Each HOLLOW CROWN tier grants +2% INSANITY click damage": "每层 HOLLOW CROWN 提供 +2% INSANITY 点击伤害",
    "+0.1× headshot multiplier per rank": "每级 +0.1× 爆头倍率",
    "-1% damage taken per rank": "每级 -1% 受到伤害",
    "-3% reload time per rank": "每级 -3% 装填时间",
    "+2 evasion per rank": "每级 +2 闪避",
    "+0.5% golden enemy chance per rank": "每级 +0.5% 黄金敌人概率",
    "-15% damage taken from wardens and bosses": "受 WARDEN 和头目的伤害 -15%",
    "+5% INSANITY click damage per rank": "每级 +5% INSANITY 点击伤害",
    "+2 armor per rank": "每级 +2 护甲",
    "+2% raid damage per rank": "每级 +2% RAID 伤害",
    "+1% trader coin flip chance per rank": "每级 +1% 商人抛硬币概率",
    "+1% raid damage per 1,000 unspent insanity (max +20%)": "每 1,000 未花费疯狂 +1% RAID 伤害（上限 +20%）",
    "+5% INSANITY gain per rank": "每级 +5% INSANITY 获取",
    "+2% max HP per rank": "每级 +2% 最大生命",
    "+2% fire rate per rank": "每级 +2% 射速",
    "Seed cache -20% cost, rebirth insanity cost -10%": "种子补给箱花费 -20%，重生疯狂花费 -10%",
    "+5% damage to wardens per rank": "每级对 WARDEN 伤害 +5%",
    "+2% auto-clicker speed (permanent)": "+2% 自动点击速度（永久）",
    "+1% crit chance (permanent)": "+1% 暴击概率（永久）",
    "+5% click damage (permanent)": "+5% 点击伤害（永久）",
