    // ==== parça 14: SKILL_TREE_JSON keystone açıklamaları (KAYNAKTAN birebir, 46 blok) ====
    "Gain 20% increased Status Effect Power.": "获得 20% 状态效果强度加成。",
    "Elemental Effects last 30% longer.": "元素效果持续时间延长 30%。",
    "Each active Elemental Stack\ngrants +3% increased Elemental Damage.": "每层生效的元素叠层\n提供 +3% 元素伤害加成。",
    "Gain 20% increased Elemental Damage.\nElemental Effects deal 10% increased Damage.": "获得 20% 元素伤害加成。\n元素效果造成的伤害提高 10%。",
    "Deal 25% increased Damage\nto enemies above 70% HP.": "对生命高于 70% 的敌人\n造成 25% 额外伤害。",
    "When your HP drops below 40%,\ninstantly recover 10% of your Maximum HP.\nThis effect can only trigger once per combat.": "当你的生命低于 40% 时，\n立即回复 10% 最大生命。\n此效果每场战斗只能触发一次。",
    "Gain 10 Armor Penetration.\nYour attacks ignore an additional 10% Armor.": "获得 10 点护甲穿透。\n你的攻击额外无视 10% 护甲。",
    "Each consecutive hit on the same enemy\ngrants +5% Damage, up to 25%.": "对同一敌人的每次连续命中\n提供 +5% 伤害，最多 25%。",
    "> +50% Damage\n> -30% Maximum HP": "> +50% 伤害\n> -30% 最大生命",
    "> Your shots never miss.\n> You can no longer deal Headshots.": "> 你的射击永不落空。\n> 你不再能造成爆头。",
    "%15 chance to gain +20% Damage for this combat.": "%15 概率在本场战斗获得 +20% 伤害。",
    "> %50 chance to reduce damage by 30%\n> %50 chance to take 30% more damage": "> %50 概率受到的伤害降低 30%\n> %50 概率受到的伤害提高 30%",
    "When combat begins,\nyou have a 50% chance to gain 30% increased Attack Speed\nand a 50% chance to gain 30% Damage Reduction for this combat.": "战斗开始时，\n你有 50% 概率获得 30% 攻击速度加成，\n并有 50% 概率在本场战斗获得 30% 减伤。",
    "If HP falls below 40% during combat:\n25% chance to heal 15% of max HP. Cooldown: 30 Seconds": "若战斗中生命低于 40%：\n25% 概率回复 15% 最大生命。冷却：30 秒",
    "> 50% chance to deal double damage.\n> 50% chance to deal greatly reduced damage.": "> 50% 概率造成双倍伤害。\n> 50% 概率造成大幅降低的伤害。",
    "> Toss a coin when combat starts.\n> 50% chance:\n> +100% Melee Damage\n> -50% Ranged Damage\n>\n> 50% chance:\n> +100% Ranged Damage\n> -50% Melee Damage\n>\n> You cannot switch weapons during combat.": "> 战斗开始时抛一枚硬币。\n> 50% 概率：\n> +100% 近战伤害\n> -50% 远程伤害\n>\n> 50% 概率：\n> +100% 远程伤害\n> -50% 近战伤害\n>\n> 战斗中无法切换武器。",
    "Deal 30% increased Melee Damage.": "造成 30% 额外近战伤害。",
    "Gain 10% increased Maximum HP.": "获得 10% 最大生命加成。",
    "+1% Melee Damage per 5 Armor,\ncapped at +15%.": "每 5 点护甲 +1% 近战伤害，\n上限 +15%。",
    "You cannot be stunned.\nTake 10% reduced Damage.": "你不会被眩晕。\n受到的伤害降低 10%。",
    "> -20% Damage Taken\n> 5% Chance to Deflect incoming damage\n> +30% Stamina Cost": "> 受到的伤害 -20%\n> 5% 概率偏转来袭伤害\n> 耐力消耗 +30%",
    "> +50% Maximum HP\n> +20 Armor\n> -30% RPM\n> -20% Movement Speed": "> 最大生命 +50%\n> 护甲 +20\n> 射速 -30%\n> 移动速度 -20%",
    "Gain 25% increased Damage.": "获得 25% 伤害加成。",
    "When your HP drops below 40%,\nrecover 15% of your Maximum HP.\n\nTriggers once per combat.": "当你的生命低于 40% 时，\n回复 15% 最大生命。\n\n每场战斗触发一次。",
    "Gamble effects are 10% less extreme\n(both bonuses and penalties).": "赌博效果的波动降低 10%\n（增益与惩罚皆是）。",
    "Gain 25% increased Melee Damage.": "获得 25% 近战伤害加成。",
    "Gain 25% increased Evasion.": "获得 25% 闪避加成。",
    "Each successful Melee hit grants\n+6% increased Melee Damage for this combat.\nStacks up to 30%.": "每次近战命中\n提供 +6% 近战伤害加成（本场战斗）。\n最多叠加至 30%。",
    "When combat begins,\ngain 30% increased Evasion for 5 second.": "战斗开始时，\n获得 30% 闪避加成，持续 5 秒。",
    "> +50% Attack Speed\n> -30% Maximum HP": "> +50% 攻击速度\n> -30% 最大生命",
    "> When you spot an enemy first, you sneak behind them and deal double damage on your first hit.": "> 当你先发现敌人时，你会潜行到其身后，首次攻击造成双倍伤害。",
    "Gain 50% increased Melee Damage.": "获得 50% 近战伤害加成。",
    "Your first attack in combat deals\n30% increased Damage.": "你在战斗中的首次攻击\n造成 30% 额外伤害。",
    "Execute enemies below 10% HP.": "处决生命低于 10% 的敌人。",
    "> Gain Rage when you hit an enemy.\n> Rage lasts until the raid ends.\n> Each Rage grants:\n +2% Damage\n +2% RPM\n> Maximum Rage: 25\n": "> 命中敌人时获得狂怒。\n> 狂怒持续到 RAID 结束。\n> 每层狂怒提供：\n +2% 伤害\n +2% 射速\n> 狂怒上限：25\n",
    "Occasionally loses control and throws a bottle at the enemy, stunning them briefly and switching to fists.\n\nWhile fistfighting, your punches use your weapon's damage and deal 100% increased damage.\n\nChance to trigger: 10%\nCooldown: 30 seconds": "偶尔会失控，朝敌人扔出一个酒瓶，短暂眩晕对方并切换成拳头。\n\n空手斗殴时，你的拳头使用武器的伤害，并造成 100% 额外伤害。\n\n触发概率：10%\n冷却：30 秒",
    "Gamble wins are 20% stronger. Gamble losses are 20% softer.\nEnemies deal 20% increased Damage to you.": "赌博的收益增强 20%。赌博的损失减轻 20%。\n敌人对你造成的伤害提高 20%。",
    "When combat begins,\nyou have a 30% chance to take 50% reduced damage\nfor the first hit you receive in this combat.": "战斗开始时，\n你有 30% 概率使本场战斗中\n受到的第一击伤害降低 50%。",
    "> When combat begins, you charge at the enemy.\n> Your first attack deals double damage and stuns for 2 seconds.\n> Consumes 80% Stamina.\n> Cannot trigger if you don't have enough Stamina.\n> Cooldown: 30 seconds": "> 战斗开始时，你会冲向敌人。\n> 你的首次攻击造成双倍伤害并眩晕 2 秒。\n> 消耗 80% 耐力。\n> 耐力不足时无法触发。\n> 冷却：30 秒",
    "Each time you take damage,\ngain +5% increased Melee Damage for this combat.\nStacks up to 25%.": "每次受到伤害时，\n获得 +5% 近战伤害加成（本场战斗）。\n最多叠加至 25%。",
    "While above 50% HP,\ngain 20% increased Damage Reduction.\nWhile below 50% HP,\ngain 30% increased Melee Damage.": "当生命高于 50% 时，\n获得 20% 减伤加成。\n当生命低于 50% 时，\n获得 30% 近战伤害加成。",
    "> You hook the enemy and pull them toward you.\n> The enemy is stunned for 1 second and takes 100% increased damage.\n> Cooldown: 30 seconds": "> 你用钩索把敌人拉向自己。\n> 敌人被眩晕 1 秒，并受到 100% 额外伤害。\n> 冷却：30 秒",
    "The first hit you take in combat\ndeals 20% reduced Damage.": "你在战斗中受到的第一次攻击\n造成的伤害降低 20%。",
    "If you spot the enemy first,\ngain 40% increased Melee Damage for this combat.": "若你先发现敌人，\n在本场战斗获得 40% 近战伤害加成。",
    "> Hitting enemies generates Overload.\n> Each hit grants 2 Overload points.\n> At 20 Overload, your weapon discharges on the enemy,\n> applying maximum stacks of all elemental effects.": "> 命中敌人会积累过载。\n> 每次命中获得 2 点过载。\n> 达到 20 点过载时，你的武器会对敌人放电，\n> 施加所有元素效果的最大叠层。",
    "> +3 Maximum Elemental Stacks\n> +50% Elemental Effect Power": "> +3 元素叠层上限\n> +50% 元素效果强度",
