    // ==== часть 02: названия аугментаций + способности ====
    "Unbreakable": "Несокрушимый",
    "Synthetic Adrenaline Gland": "Синтетическая адреналиновая железа",
    "Combat High": "Боевой азарт",
    "Trauma Response System": "Система реакции на травму",
    "Trauma Response": "Реакция на травму",
    "Carbon Fiber Core": "Углеродное ядро",
    "Equilibrium": "Равновесие",
    "Chameleon Mesh": "Сеть-хамелеон",
    "Ghost Strike": "Призрачный удар",
    "Crimson Gaze": "Багряный взор",
    "Energy Reactor": "Энергетический реактор",
    "Power Surge": "Всплеск энергии",
    "Fortress Chassis": "Шасси «Крепость»",
    "Unyielding": "Непреклонный",
    "Fusion Power Cell": "Термоядерный элемент питания",
    "Unlimited Power": "Безграничная энергия",
    "Grav-Drive Legs": "Гравитационные ноги",
    "Velocity Rush": "Рывок скорости",
    "Hawkeye Implant": "Имплант «Ястребиный глаз»",
    "Eagle Eye": "Орлиный глаз",
    "Hive Mind Core": "Ядро коллективного разума",
    "Kill Frenzy": "Жажда убийства",
    "Hydraulic Crushers": "Гидравлические дробилки",
    "Power Strike": "Мощный удар",
    "Micro-Rocket Pod": "Микро-ракетная установка",
    "Auto Rockets": "Авто-ракеты",
    "Nanite Swarm Arms": "Руки-рой нанитов",
    "Corrosive Touch": "Коррозийное касание",
    "Orbital Designator": "Орбитальный целеуказатель",
    "Orbital Bombardment": "Орбитальная бомбардировка",
    "Phase Striders": "Фазовые ноги",
    "Phantom Clones": "Фантомные клоны",
    "Plasma Turret": "Плазменная турель",
    "Auto-Turret": "Авто-турель",
    "Precision Servos": "Прецизионные сервоприводы",
    "Perfect Aim": "Идеальное прицеливание",
    "Predictive Matrix": "Прогностическая матрица",
    "Precognition": "Предвидение",
    "Quantum Lens": "Квантовая линза",
    "Rapid Burst": "Быстрая очередь",
    "Reactive Nanoweave": "Реактивное наноплетение",
    "Adaptive Armor": "Адаптивная броня",
    "Regenerative Membrane": "Регенерирующая мембрана",
    "Bio-Repair": "Био-ремонт",
    "Shock Absorbers": "Амортизаторы",
    "Iron Skin": "Железная кожа",
    "Synapse Accelerator": "Ускоритель синапсов",
    "Neural Overclock": "Нейронный оверклокинг",
    "Thermal Oculus": "Тепловизионный окулюс",
    "Scan": "Сканирование",
    "Titanium Exoframe": "Титановый экзоскелет",
    "Pack Mule": "Вьючный мул",
    "Void Heart": "Сердце Пустоты",
    "Life Steal": "Вампиризм",
