    // ==== JS_UI часть 1: ВСЕ ЗАГЛАВНЫЕ метки A-M ====
    "ABILITY ROLLED": "СПОСОБНОСТЬ ПЕРЕБРОШЕНА",
    "ABUSING THE GAME...": "ЗЛОУПОТРЕБЛЕНИЕ ИГРОЙ...",
    "ACCEPT": "ПРИНЯТЬ",
    "ACHIEVEMENT UNLOCKED": "ДОСТИЖЕНИЕ РАЗБЛОКИРОВАНО",
    "ACQUISITIONS": "ЗАКУПКИ",
    "ACTION FAILED": "ДЕЙСТВИЕ НЕУДАЧНО",
    "ACTIVE": "АКТИВНО",
    "ADULT": "ВЗРОСЛЫЙ",
    "ADVANCED": "ПРОДВИНУТЫЙ",
    "ALL": "ВСЕ",
    "ALWAYS": "ВСЕГДА",
    "ALWAYS IN STOCK": "ВСЕГДА В НАЛИЧИИ",
    "ANCHOR CODES": "ЯКОРНЫЕ КОДЫ",
    "ANYTHING": "ЛЮБОЕ",
    "ARM": "РУКА",
    "ARMOR": "БРОНЯ",
    "ARMOR PEN": "ПРОБИТИЕ БРОНИ",
    "ATK SPD": "СКОРОСТЬ АТ.",
    "ATTACK SPEED": "СКОРОСТЬ АТАКИ",
    "ATTRIBUTES": "ХАРАКТЕРИСТИКИ",
    "AUGMENT COMPONENTS": "КОМПОНЕНТЫ АУГМЕНТАЦИИ",
    "AUGMENT DETAILS": "ДЕТАЛИ АУГМЕНТАЦИИ",
    "AUGMENT LOCKER": "СКЛАД АУГМЕНТАЦИИ",
    "AUGMENT MATS": "МАТЕРИАЛЫ АУГМЕНТАЦИИ",
    "AUGMENT MISSIONS": "МИССИИ АУГМЕНТАЦИИ",
    "AUGMENT MODULES": "МОДУЛИ АУГМЕНТАЦИИ",
    "AUGMENTS": "АУГМЕНТАЦИИ",
    "AUTO-CLICKER": "АВТОКЛИКЕР",
    "AUTO-LOADOUT": "АВТО-LOADOUT",
    "AUTO-MOD COMPLETE": "АВТО-МОД ЗАВЕРШЕН",
    "AUTO-MOD STOPPED": "АВТО-МОД ОСТАНОВЛЕН",
    "AUTO-RECOVERY ACTIVE": "АВТО-ВОССТАНОВЛЕНИЕ АКТИВНО",
    "AUTO-RECOVERY FAILED": "АВТО-ВОССТАНОВЛЕНИЕ НЕУДАЧНО",
    "AUTO-REPAIR": "АВТО-РЕМОНТ",
    "AUTO-REPAIR SKIPPED": "АВТО-РЕМОНТ ПРОПУЩЕН",
    "AUTO-SALVAGE": "АВТО-РАЗБОР",
    "AUTO-SELL": "АВТО-ПРОДАЖА",
    "AUTOMATION": "АВТОМАТИЗАЦИЯ",
    "BACK TO HUB": "НАЗАД В HUB",
    "BACK TO MAIN MENU": "НАЗАД В ГЛАВНОЕ МЕНЮ",
    "BACKPACK": "РЮКЗАК",
    "BEST FRIEND UNLOCKED": "ЛУЧШИЙ ДРУГ РАЗБЛОКИРОВАН",
    "BEST LAYER": "ЛУЧШИЙ СЛОЙ",
    "BIT ROT": "БИТОВАЯ ГНИЛЬ",
    "BLINK HUNTER": "ОХОТНИК ЗА МЕРЦАНИЕМ",
    "BLOCK": "БЛОК",
    "BONDING PROGRESS": "ПРОГРЕСС СВЯЗИ",
    "BONDING...": "СВЯЗЬ...",
    "BOOSTED": "УСИЛЕНО",
    "BOOSTED MODS": "УСИЛЕННЫЕ МОДЫ",
    "BOSS KILLS": "УБИЙСТВА БОССОВ",
    "BOSS SECTOR": "СЕКТОР БОССОВ",
    "BRICKED": "ОКИРПИЧЕНО",
    "BRICKED:": "ОКИРПИЧЕНО:",
    "BULK SALVAGE": "МАССОВЫЙ РАЗБОР",
    "BULK SELL": "МАССОВАЯ ПРОДАЖА",
    "BURNING": "ГОРЕНИЕ",
    "BUTTON": "КНОПКА",
    "BUY": "КУПИТЬ",
    "BYPASSED": "ОБХОД ВЫПОЛНЕН",
    "CACHE MAGNET": "МАГНИТ ДЛЯ CACHES",
    "CACHES": "CACHES",
    "CLAIMED": "ПОЛУЧЕНО",
    "CANNOT ROLL": "НЕЛЬЗЯ ПЕРЕБРОСИТЬ",
    "CANNOT SALVAGE": "НЕЛЬЗЯ РАЗОБРАТЬ",
    "CANNOT SAVE": "НЕЛЬЗЯ СОХРАНИТЬ",
    "CANNOT SELL": "НЕЛЬЗЯ ПРОДАТЬ",
    "CANNOT UPGRADE": "НЕЛЬЗЯ УЛУЧШИТЬ",
    "CAPACITOR": "КОНДЕНСАТОР",
    "CAPACITOR FAILED": "ОШИБКА КОНДЕНСАТОРА",
    "CAPACITOR LOCKED": "КОНДЕНСАТОР ЗАБЛОКИРОВАН",
    "CAPACITOR SUCCESS": "КОНДЕНСАТОР УСПЕШНО",
    "CAPACITY": "ВМЕСТИМОСТЬ",
    "CARNAGE // OFFENSE": "РЕЗНЯ // АТАКА",
    "CARRY CAP": "ЛИМИТ ВМЕСТИМОСТИ",
    "CASCADE": "КАСКАД",
    "CHARACTER": "ПЕРСОНАЖ",
    "CHASSIS": "ШАССИ",
    "CHECKPOINT:": "ЧЕКПОИНТ:",
    "CHEST RIG": "ТАКТИЧЕСКИЙ ЖИЛЕТ",
    "CLASS": "КЛАСС",
    "CLEAN PATCH SWAP": "ЧИСТАЯ ЗАМЕНА ПАТЧА",
    "CLEANUP": "ОЧИСТКА",
    "CLEAR GUIDE": "УДАЛИТЬ ГАЙД",
    "CLICK DMG": "УРОН ОТ КЛИКА",
    "CLICK TO PET": "КЛИКНИ, ЧТОБЫ ПОГЛАДИТЬ",
    "CODE DISCOVERED": "КОД ОБНАРУЖЕН",
    "CODES:": "КОДЫ:",
    "COIN FLIP": "ОРЕЛ ИЛИ РЕШКА",
    "COLD": "ХОЛОД",
    "COMBAT": "БОЙ",
    "COMBAT AUTOMATION": "АВТОМАТИЗАЦИЯ БОЯ",
    "COMBAT START": "НАЧАЛО БОЯ",
    "COMBO SLOT": "СЛОТ КОМБО",
    "COMMUNION // SYNERGY": "ПРИЧАЩЕНИЕ // СИНЕРГИЯ",
    "COMPANION": "НАПАРНИК",
    "COMPANION DESIGNATION:": "ПОЗЫВНОЙ НАПАРНИКА:",
    "COMPANION NOT DETECTED": "НАПАРНИК НЕ ОБНАРУЖЕН",
    "COMPLETE": "ЗАВЕРШИТЬ",
    "COMPLETED": "ЗАВЕРШЕНО",
    "CONFIRM": "ПОДТВЕРДИТЬ",
    "CONTAINER": "КОНТЕЙНЕР",
    "COOLDOWN:": "ПЕРЕЗАРЯДКА:",
    "CORRUPTION": "ИСКАЖЕНИЕ",
    "COST": "СТОИМОСТЬ",
    "CRAFTING:": "ПРОИЗВОДСТВО:",
    "CRAWLER": "ПОЛЗУН",
    "CRIT": "КРИТ",
    "CRIT CHANCE": "ШАНС КРИТА",
    "CRIT DMG": "КРИТ. УРОН",
    "CRITICAL": "КРИТИЧЕСКИЙ",
    "CRYO": "КРИО",
    "DAILY CONTRACTS": "ЕЖЕДНЕВНЫЕ КОНТРАКТЫ",
    "DAMAGE": "УРОН",
    "DATA": "ДАННЫЕ",
    "DEAL COMPLETE": "СДЕЛКА ЗАВЕРШЕНА",
    "DEATH LOOP DETECTED": "ОБНАРУЖЕНА ПЕТЛЯ СМЕРТИ",
    "DEFENSE": "ЗАЩИТА",
    "DELETE": "УДАЛИТЬ",
    "DELETE & START": "УДАЛИТЬ И НАЧАТЬ",
    "DELETE PLAN": "УДАЛИТЬ ПЛАН",
    "DELETE SAVE": "УДАЛИТЬ СОХРАНЕНИЕ",
    "DESIGNATION:": "ПОЗЫВНОЙ:",
    "DETECTION": "ОБНАРУЖЕНИЕ",
    "DISPLAY MODE": "РЕЖИМ ОТОБРАЖЕНИЯ",
    "DISTORTION": "ИСКАЖЕНИЕ",
    "DMG": "УРОН",
    "DODGE": "УВОРОТ",
    "DOG": "СОБАКА",
    "DONE": "ГОТОВО",
    "DOOM CLOCK: DETONATED": "ЧАСЫ РОКА: ВЗОРВАНЫ",
    "DOUBLE DEFENSE": "ДВОЙНАЯ ЗАЩИТА",
    "DRAG": "ТЯНУТЬ",
    "DURABILITY": "ПРОЧНОСТЬ",
    "ECHO": "ЭХО",
    "ECHO // QUANTITY": "ЭХО // КОЛИЧЕСТВО",
    "ECHO-TAP ROUTINE": "ПРОТОКОЛ ЭХО-ПЕРЕХВАТА",
    "ECONOMY": "ЭКОНОМИКА",
    "ELECTRO": "ЭЛЕКТРО",
    "ELEM": "ЭЛЕМ.",
    "ELEMENTAL": "СТИХИЙНЫЙ",
    "ELEMENTAL SYNC": "СТИХИЙНАЯ СИНХРОНИЗАЦИЯ",
    "EMP OVERLOAD": "ЭМИ-ПЕРЕГРУЗКА",
    "EMPTY": "ПУСТО",
    "ENDGAME MISSIONS": "МИССИИ ЭНДГЕЙМА",
    "ENEMY AC": "БРОНЯ ВРАГА",
    "ENEMY DMG": "УРОН ВРАГА",
    "ENEMY HP": "HP ВРАГА",
    "ENSURE": "СТРАХОВКА",
    "ENSURE ITEM": "СТРАХОВАТЬ ПРЕДМЕТ",
    "EQUIP": "ЭКИПИРОВАТЬ",
    "ESCAPING...": "ПОБЕГ...",
    "EVA": "УВОРОТ",
    "EVASION": "УВОРОТ",
    "EXECUTED": "ИСПОЛНЕН",
    "EXIT": "ВЫХОД",
    "EXIT TO DESKTOP": "ВЫЙТИ НА РАБОЧИЙ СТОЛ",
    "EXIT TO MAIN MENU": "ВЫЙТИ В ГЛАВНОЕ МЕНЮ",
    "EXPANSION": "РАСШИРЕНИЕ",
    "EXPERIENCE": "ОПЫТ",
    "EXTRA ENEMIES": "ДОПОЛНИТЕЛЬНЫЕ ВРАГИ",
    "EXTRACT": "EXTRACT",
    "EXTRACT AVAILABLE": "EXTRACT ДОСТУПЕН",
    "EXTRACT POINT": "ТОЧКА EXTRACT",
    "FAILURE RESULTS IN -1 LEVEL": "НЕУДАЧА ПРИВЕДЕТ К -1 УРОВНЮ",
    "FATAL ERROR": "КРИТИЧЕСКАЯ ОШИБКА",
    "FEEDBACK": "ОБРАТНАЯ СВЯЗЬ",
    "FIELD LOG": "ПОЛЕВОЙ ЖУРНАЛ",
    "FIELD NOTES": "ПОЛЕВЫЕ ЗАМЕТКИ",
    "FIELD ORIENTATION": "ПОЛЕВОЕ ОЗНАКОМЛЕНИЕ",
    "FIEND": "ИЗГОЙ",
    "FIGHT": "БОЙ",
    "FILTER": "ФИЛЬТР",
    "FIRE": "ОГОНЬ",
    "FIST": "КУЛАК",
    "FLUX CORE SLOT": "СЛОТ ЯДРА FLUX",
    "FOOD": "ЕДА",
    "FOUND:": "НАЙДЕНО:",
    "FREE": "БЕСПЛАТНО",
    "FREE KIT": "БЕСПЛАТНЫЙ НАБОР",
    "FREE KIT DEPLOYED": "БЕСПЛАТНЫЙ НАБОР ВЫДАН",
    "FREQUENCY UNCHARTED": "НЕИЗВЕСТНАЯ ЧАСТОТА",
    "FROZEN": "ЗАМОРОЖЕНО",
    "FUEL EMPTY": "ТОПЛИВО КОНЧИЛОСЬ",
    "FULL BODY": "ВСЕ ТЕЛО",
    "FUNDS": "ФОНДЫ",
    "GEAR": "СНАРЯЖЕНИЕ",
    "GEAR CANNOT BE SECURED": "СНАРЯЖЕНИЕ НЕЛЬЗЯ ЗАСТРАХОВАТЬ",
    "GEAR WEIGHT": "ВЕС СНАРЯЖЕНИЯ",
    "GENERAL": "ОБЩЕЕ",
    "GLITCH CLONE": "КЛОН GLITCH",
    "GLITCH CODES": "КОДЫ GLITCH",
    "GLITCH MOTE": "ЧАСТИЦА GLITCH",
    "GLITCH PROTOCOL": "ПРОТОКОЛ GLITCH",
    "GO TO QUEST": "К ЗАДАНИЮ",
    "GOD PROTOCOL ACTIVE": "ПРОТОКОЛ БОГА АКТИВИРОВАН",
    "GOGGLES": "ОЧКИ",
    "GOLEM": "ГОЛЕМ",
    "GOT IT": "ПОНЯЛ",
    "GROWTH STAGE": "СТАДИЯ РОСТА",
    "GUARANTEED": "ГАРАНТИРОВАНО",
    "GUARANTEED DROP": "ГАРАНТИРОВАННЫЙ ДРОП",
    "GUIDE ME": "ВЕДИ МЕНЯ",
    "GUNSMITH QUESTS": "ЗАДАНИЯ GUNSMITH",
    "HACKING": "ВЗЛОМ",
    "HANDLING": "ВЛАДЕНИЕ",
    "HAPPINESS": "СЧАСТЬЕ",
    "HEAD": "ГОЛОВА",
    "HEADS": "ПЕРЕД",
    "HEADSET": "ГАРНИТУРА",
    "HEADSHOT DMG": "УРОН В ГОЛОВУ",
    "HEAL": "ЛЕЧЕНИЕ",
    "HEALED": "ИСЦЕЛЕНО",
    "HEALTH": "ЗДОРОВЬЕ",
    "HEAT": "НАГРЕВ",
    "HINT": "ПОДСКАЗКА",
    "HOSTILES DOWN": "ВРАГИ УНИЧТОЖЕНЫ",
    "HOW IT WORKS": "КАК ЭТО РАБОТАЕТ",
    "HP REGEN": "РЕГЕНЕРАЦИЯ HP",
    "HS MULT": "МНОЖИТЕЛЬ ХЕДШОТА",
    "HUNGER": "ГОЛОД",
    "HUSK": "ПУСТЫШКА",
    "HUSK // DEFENSE": "ОБОЛОЧКА // ЗАЩИТА",
    "IF SWAPPED": "ПРИ ЗАМЕНЕ",
    "IN PROGRESS": "В ПРОЦЕССЕ",
    "INCOMPATIBLE": "НЕ СОВМЕСТИМО",
    "INFO": "ИНФО",
    "INJECT FLOW:": "ПОТОК ИНЪЕКЦИИ:",
    "INJECT QUEUE": "ОЧЕРЕДЬ ИНЪЕКЦИИ",
    "INSPECT": "ОСМОТР",
    "INSTANT LOOT": "МГНОВЕННЫЙ ДОБЫЧА",
    "INSURANCE FAILED": "СТРАХОВКА НЕУДАЧНА",
    "INSURANCE RETURN": "ВЫПЛАТА ПО СТРАХОВКЕ",
    "ITEM": "ПРЕДМЕТ",
    "ITEM BONUS": "БОНУС ПРЕДМЕТА",
    "ITEM FIND": "ПОИСК ПРЕДМЕТОВ",
    "ITEM LOCKED": "ПРЕДМЕТ ЗАБЛОКИРОВАН",
    "ITEM RECOVERED": "ПРЕДМЕТ ВОЗВРАЩЕН",
    "ITEM RECOVERY": "ВОЗВРАТ ПРЕДМЕТА",
    "ITEMS LOOTED": "ДОБЫЧА ПРЕДМЕТОВ",
    "JAM CHANCE": "ШАНС ЗАЖИМА",
    "JOIN THE DISCORD": "ПРИСОЕДИНИТЬСЯ К DISCORD",
    "JUNK": "ХЛАМ",
    "JUVENILE": "МОЛОДОЙ",
    "KERNEL": "ЯДРО",
    "KERNEL CODES": "КОДЫ ЯДРА",
    "KERNEL REAPER": "ЖНЕЦ ЯДРА",
    "KERNEL SLOT INJECTION": "ИНЪЕКЦИЯ В СЛОТ ЯДРА",
    "KERNELS": "ЯДРА",
    "KERNELS:": "ЯДРА:",
    "KEY RESERVED": "КЛАВИША ЗАБРОНИРОВАНА",
    "KEY TAKEN OVER": "КЛАВИША ЗАНЯТА",
    "KILL": "УБИТЬ",
    "KILLS": "УБИЙСТВА",
    "L.ARM": "Л. РУКА",
    "L.LEG": "Л. НОГА",
    "LANGUAGE": "ЯЗЫК",
    "LAST": "ПОСЛЕДНИЙ",
    "LATER": "ПОЗЖЕ",
    "LAYER": "СЛОЙ",
    "LEFT ARM": "ЛЕВАЯ РУКА",
    "LEFT LEG": "ЛЕВАЯ НОГА",
    "LEVEL UP": "ПОВЫШЕНИЕ УРОВНЯ",
    "LIGHTNING": "МОЛНИЯ",
    "LOAD": "ЗАГРУЗКА",
    "LOAD FAILED": "ОШИБКА ЗАГРУЗКИ",
    "LOAD FROM SLOT": "ЗАГРУЗИТЬ ИЗ СЛОТА",
    "LOAD SAVE": "ЗАГРУЗИТЬ СОХРАНЕНИЕ",
    "LOOT": "ДОБЫЧА",
    "LOOT FILTERS": "ФИЛЬТРЫ ДОБЫЧИ",
    "LOOT MULT": "МНОЖИТЕЛЬ ДОБЫЧИ",
    "LOOT SENSE": "ЧУТЬЕ ДОБЫЧИ",
    "LOOT VALUE": "ЦЕННОСТЬ ДОБЫЧИ",
    "LOSE": "ПРОИГРЫШ",
    "LOW RISK": "НИЗКИЙ РИСК",
    "LOYALTY: 100%": "ЛОЯЛЬНОСТЬ: 100%",
    "MADNESS PROTOCOL": "ПРОТОКОЛ БЕЗУМИЯ",
    "INSANITY": "БЕЗУМИЕ",
    "FLUX": "FLUX",
    "PRESTIGE": "ПРЕСТИЖ",
    "PRESTIGE AVAILABLE": "ПРЕСТИЖ ДОСТУПЕН",
    "PRESTIGE REWARDS": "НАГРАДЫ ПРЕСТИЖА",
    "PRESTIGE:": "ПРЕСТИЖ:",
    "[ INSANITY ]": "[ БЕЗУМИЕ ]",
    "░▒▓ INSANITY ▓▒░": "░▒▓ БЕЗУМИЕ ▓▒░",
    "MAG": "МАГАЗИН",
    "MAG SIZE": "РАЗМЕР МАГАЗИНА",
    "MAGAZINE": "МАГАЗИН",
    "MAKE OFFER": "СДЕЛАТЬ ПРЕДЛОЖЕНИЕ",
    "MALWARE": "ВРЕДОНОСНОЕ ПО",
    "MAP ENTER": "ВХОД НА КАРТУ",
    "MASK": "МАСКА",
    "MASTERY": "МАСТЕРСТВО",
    "MASTERY UNLOCKED": "МАСТЕРСТВО РАЗБЛОКИРОВАНО",
    "MAW": "ПАСТЬ",
    "MAX": "МАКС.",
    "MAX ITEMS": "МАКС. ПРЕДМЕТОВ",
    "MAXED": "МАКСИМАЛЬНЫЙ",
    "MAXIMUM ENHANCEMENT": "МАКСИМАЛЬНОЕ УЛУЧШЕНИЕ",
    "MEDICAL": "МЕДИЦИНА",
    "MELEE": "БЛИЖНИЙ БОЙ",
    "MENU HOTKEYS": "ГОРЯЧИЕ КЛАВИШИ МЕНЮ",
    "MIDDLE CLICK": "НАЖАТИЕ КОЛЕСИКОМ",
    "MINING:": "ДОБЫЧА:",
    "MODIFY": "МОДИФИКАЦИЯ",
    "MODULE ACQUIRED": "МОДУЛЬ ПОЛУЧЕН",
    "MODULE CLASS FLIP": "ПЕРЕКЛЮЧЕНИЕ ТИПА МОДУЛЯ",
    "MORE UPDATES AND CONTENT TO COME": "БОЛЬШЕ ОБНОВЛЕНИЙ И КОНТЕНТА СКОРО",
    "MOUSE": "МЫШЬ",
    "MOVE": "ДВИЖЕНИЕ",
    "MULTI-BREACH": "МУЛЬТИ-ВЗЛОМ",
