    // ==== JS_UI parça 1: ALLCAPS etiketler A-M ====
    "ABILITY ROLLED": "能力已重掷",
    "ABUSING THE GAME...": "滥用游戏机制……",
    "ACCEPT": "接受",
    "ACHIEVEMENT UNLOCKED": "成就已解锁",
    "ACQUISITIONS": "收购",
    "ACTION FAILED": "操作失败",
    "ACTIVE": "生效中",
    "ADULT": "成年",
    "ADVANCED": "进阶",
    "ALL": "全部",
    "ALWAYS": "总是",
    "ALWAYS IN STOCK": "常备库存",
    "ANCHOR CODES": "锚定代码",
    "ANYTHING": "任意物品",
    "ARM": "手臂",
    "ARMOR": "护甲",
    "ARMOR PEN": "护甲穿透",
    "ATK SPD": "攻速",
    "ATTACK SPEED": "攻击速度",
    "ATTRIBUTES": "属性",
    "AUGMENT COMPONENTS": "义体部件",
    "AUGMENT DETAILS": "义体详情",
    "AUGMENT LOCKER": "义体储物柜",
    "AUGMENT MATS": "义体材料",
    "AUGMENT MISSIONS": "义体任务",
    "AUGMENT MODULES": "义体模块",
    "AUGMENTS": "义体",
    "AUTO-CLICKER": "自动点击器",
    "AUTO-LOADOUT": "自动配装",
    "AUTO-MOD COMPLETE": "自动改装完成",
    "AUTO-MOD STOPPED": "自动改装停止",
    "AUTO-RECOVERY ACTIVE": "自动恢复生效",
    "AUTO-RECOVERY FAILED": "自动恢复失败",
    "AUTO-REPAIR": "自动修理",
    "AUTO-REPAIR SKIPPED": "自动修理已跳过",
    "AUTO-SALVAGE": "自动拆解",
    "AUTO-SELL": "自动出售",
    "AUTOMATION": "自动化",
    "BACK TO HUB": "返回基地",
    "BACK TO MAIN MENU": "返回主菜单",
    "BACKPACK": "背包",
    "BEST FRIEND UNLOCKED": "挚友已解锁",
    "BEST LAYER": "最深层数",
    "BIT ROT": "比特腐蚀",
    "BLINK HUNTER": "闪现猎手",
    "BLOCK": "格挡",
    "BONDING PROGRESS": "羁绊进度",
    "BONDING...": "羁绊中……",
    "BOOSTED": "已强化",
    "BOOSTED MODS": "强化模组",
    "BOSS KILLS": "头目击杀",
    "BOSS SECTOR": "头目区域",
    "BRICKED": "已变砖",
    "BRICKED:": "已变砖：",
    "BULK SALVAGE": "批量拆解",
    "BULK SELL": "批量出售",
    "BURNING": "燃烧",
    "BUTTON": "按键",
    "BUY": "购买",
    "BYPASSED": "已绕过",
    "CACHE MAGNET": "补给磁铁",
    "CACHES": "补给箱",
    "CLAIMED": "已领取",
    "CANNOT ROLL": "无法重掷",
    "CANNOT SALVAGE": "无法拆解",
    "CANNOT SAVE": "无法保存",
    "CANNOT SELL": "无法出售",
    "CANNOT UPGRADE": "无法升级",
    "CAPACITOR": "电容器",
    "CAPACITOR FAILED": "电容器失败",
    "CAPACITOR LOCKED": "电容器锁定",
    "CAPACITOR SUCCESS": "电容器成功",
    "CAPACITY": "容量",
    "CARNAGE // OFFENSE": "杀戮 // 攻击",
    "CARRY CAP": "负重上限",
    "CASCADE": "级联",
    "CHARACTER": "角色",
    "CHASSIS": "底盘",
    "CHECKPOINT:": "检查点：",
    "CHEST RIG": "战术背心",
    "CLASS": "职业",
    "CLEAN PATCH SWAP": "无损补丁替换",
    "CLEANUP": "清理",
    "CLEAR GUIDE": "清除引导",
    "CLICK DMG": "点击伤害",
    "CLICK TO PET": "点击抚摸",
    "CODE DISCOVERED": "发现代码",
    "CODES:": "代码：",
    "COIN FLIP": "抛硬币",
    "COLD": "寒冷",
    "COMBAT": "战斗",
    "COMBAT AUTOMATION": "战斗自动化",
    "COMBAT START": "战斗开始",
    "COMBO SLOT": "组合槽位",
    "COMMUNION // SYNERGY": "共融 // 协同",
    "COMPANION": "同伴",
    "COMPANION DESIGNATION:": "同伴代号：",
    "COMPANION NOT DETECTED": "未检测到同伴",
    "COMPLETE": "完成",
    "COMPLETED": "已完成",
    "CONFIRM": "确认",
    "CONTAINER": "容器",
    "COOLDOWN:": "冷却：",
    "CORRUPTION": "侵蚀",
    "COST": "花费",
    "CRAFTING:": "制作：",
    "CRAWLER": "爬行者",
    "CRIT": "暴击",
    "CRIT CHANCE": "暴击率",
    "CRIT DMG": "暴击伤害",
    "CRITICAL": "危急",
    "CRYO": "冰霜",
    "DAILY CONTRACTS": "每日契约",
    "DAMAGE": "伤害",
    "DATA": "数据",
    "DEAL COMPLETE": "交易完成",
    "DEATH LOOP DETECTED": "检测到死亡循环",
    "DEFENSE": "防御",
    "DELETE": "删除",
    "DELETE & START": "删除并开始",
    "DELETE PLAN": "删除方案",
    "DELETE SAVE": "删除存档",
    "DESIGNATION:": "代号：",
    "DETECTION": "侦测",
    "DISPLAY MODE": "显示模式",
    "DISTORTION": "畸变",
    "DMG": "伤害",
    "DODGE": "闪避",
    "DOG": "狗",
    "DONE": "完成",
    "DOOM CLOCK: DETONATED": "末日时钟：已引爆",
    "DOUBLE DEFENSE": "双倍防御",
    "DRAG": "拖动",
    "DURABILITY": "耐久",
    "ECHO": "回响",
    "ECHO // QUANTITY": "回响 // 数量",
    "ECHO-TAP ROUTINE": "回响窃听例程",
    "ECONOMY": "经济",
    "ELECTRO": "电击",
    "ELEM": "元素",
    "ELEMENTAL": "元素",
    "ELEMENTAL SYNC": "元素同步",
    "EMP OVERLOAD": "EMP 过载",
    "EMPTY": "空",
    "ENDGAME MISSIONS": "终局任务",
    "ENEMY AC": "敌方护甲",
    "ENEMY DMG": "敌方伤害",
    "ENEMY HP": "敌方生命",
    "ENSURE": "投保",
    "ENSURE ITEM": "为物品投保",
    "EQUIP": "装备",
    "ESCAPING...": "逃跑中……",
    "EVA": "闪避",
    "EVASION": "闪避",
    "EXECUTED": "已处决",
    "EXIT": "退出",
    "EXIT TO DESKTOP": "退出到桌面",
    "EXIT TO MAIN MENU": "退出到主菜单",
    "EXPANSION": "扩容",
    "EXPERIENCE": "经验",
    "EXTRA ENEMIES": "额外敌人",
    "EXTRACT": "撤离",
    "EXTRACT AVAILABLE": "可以撤离",
    "EXTRACT POINT": "撤离点",
    "FAILURE RESULTS IN -1 LEVEL": "失败将导致 -1 级",
    "FATAL ERROR": "致命错误",
    "FEEDBACK": "反馈",
    "FIELD LOG": "战地日志",
    "FIELD NOTES": "战地笔记",
    "FIELD ORIENTATION": "战地入门",
    "FIEND": "恶鬼",
    "FIGHT": "战斗",
    "FILTER": "筛选",
    "FIRE": "火焰",
    "FIST": "拳头",
    "FLUX CORE SLOT": "FLUX 核心槽",
    "FOOD": "食物",
    "FOUND:": "找到：",
    "FREE": "免费",
    "FREE KIT": "免费装备包",
    "FREE KIT DEPLOYED": "免费装备包已发放",
    "FREQUENCY UNCHARTED": "未知频率",
    "FROZEN": "冰冻",
    "FUEL EMPTY": "燃料耗尽",
    "FULL BODY": "全身",
    "FUNDS": "资金",
    "GEAR": "装备",
    "GEAR CANNOT BE SECURED": "装备无法放入安全袋",
    "GEAR WEIGHT": "装备重量",
    "GENERAL": "常规",
    "GLITCH CLONE": "GLITCH 分身",
    "GLITCH CODES": "GLITCH 代码",
    "GLITCH MOTE": "GLITCH 微尘",
    "GLITCH PROTOCOL": "GLITCH 协议",
    "GO TO QUEST": "前往任务",
    "GOD PROTOCOL ACTIVE": "神明协议生效",
    "GOGGLES": "护目镜",
    "GOLEM": "魔像",
    "GOT IT": "知道了",
    "GROWTH STAGE": "成长阶段",
    "GUARANTEED": "保底",
    "GUARANTEED DROP": "保底掉落",
    "GUIDE ME": "带我去",
    "GUNSMITH QUESTS": "GUNSMITH 任务",
    "HACKING": "骇入",
    "HANDLING": "操控性",
    "HAPPINESS": "快乐值",
    "HEAD": "头部",
    "HEADS": "正面",
    "HEADSET": "耳机",
    "HEADSHOT DMG": "爆头伤害",
    "HEAL": "治疗",
    "HEALED": "已治疗",
    "HEALTH": "生命",
    "HEAT": "过热",
    "HINT": "提示",
    "HOSTILES DOWN": "敌人已消灭",
    "HOW IT WORKS": "运作方式",
    "HP REGEN": "生命回复",
    "HS MULT": "爆头倍率",
    "HUNGER": "饱食度",
    "HUSK": "空壳",
    "HUSK // DEFENSE": "躯壳 // 防御",
    "IF SWAPPED": "若替换",
    "IN PROGRESS": "进行中",
    "INCOMPATIBLE": "不兼容",
    "INFO": "信息",
    "INJECT FLOW:": "注入流程:",
    "INJECT QUEUE": "注入队列",
    "INSPECT": "检视",
    "INSTANT LOOT": "即时拾取",
    "INSURANCE FAILED": "保险失败",
    "INSURANCE RETURN": "保险返还",
    "ITEM": "物品",
    "ITEM BONUS": "物品加成",
    "ITEM FIND": "寻物",
    "ITEM LOCKED": "物品已锁定",
    "ITEM RECOVERED": "物品已找回",
    "ITEM RECOVERY": "物品找回",
    "ITEMS LOOTED": "拾取物品",
    "JAM CHANCE": "卡壳率",
    "JOIN THE DISCORD": "加入 DISCORD",
    "JUNK": "垃圾",
    "JUVENILE": "幼年",
    "KERNEL": "内核",
    "KERNEL CODES": "内核代码",
    "KERNEL REAPER": "内核收割者",
    "KERNEL SLOT INJECTION": "内核槽注入",
    "KERNELS": "内核",
    "KERNELS:": "内核：",
    "KEY RESERVED": "按键已保留",
    "KEY TAKEN OVER": "按键已被占用",
    "KILL": "击杀",
    "KILLS": "击杀",
    "L.ARM": "左臂",
    "L.LEG": "左腿",
    "LANGUAGE": "语言",
    "LAST": "上次",
    "LATER": "稍后",
    "LAYER": "层",
    "LEFT ARM": "左臂",
    "LEFT LEG": "左腿",
    "LEVEL UP": "升级",
    "LIGHTNING": "闪电",
    "LOAD": "载入",
    "LOAD FAILED": "载入失败",
    "LOAD FROM SLOT": "从槽位载入",
    "LOAD SAVE": "载入存档",
    "LOOT": "战利品",
    "LOOT FILTERS": "战利品筛选",
    "LOOT MULT": "战利品倍率",
    "LOOT SENSE": "战利品感知",
    "LOOT VALUE": "战利品价值",
    "LOSE": "失败",
    "LOW RISK": "低风险",
    "LOYALTY: 100%": "忠诚：100%",
    "MADNESS PROTOCOL": "疯狂协议",
    "INSANITY": "疯狂",
    "FLUX": "通量",
    "PRESTIGE": "转生",
    "PRESTIGE AVAILABLE": "可以转生",
    "PRESTIGE REWARDS": "转生奖励",
    "PRESTIGE:": "转生：",
    "[ INSANITY ]": "[ 疯狂 ]",
    "░▒▓ INSANITY ▓▒░": "░▒▓ 疯狂 ▓▒░",
    "MAG": "弹匣",
    "MAG SIZE": "弹匣容量",
    "MAGAZINE": "弹匣",
    "MAKE OFFER": "出价",
    "MALWARE": "恶意软件",
    "MAP ENTER": "进入地图",
    "MASK": "面罩",
    "MASTERY": "精通",
    "MASTERY UNLOCKED": "精通已解锁",
    "MAW": "巨口",
    "MAX": "最大",
    "MAX ITEMS": "物品上限",
    "MAXED": "已满级",
    "MAXIMUM ENHANCEMENT": "最大强化",
    "MEDICAL": "医疗",
    "MELEE": "近战",
    "MENU HOTKEYS": "菜单快捷键",
    "MIDDLE CLICK": "中键点击",
    "MINING:": "挖矿：",
    "MODIFY": "改装",
    "MODULE ACQUIRED": "获得模块",
    "MODULE CLASS FLIP": "模块类型翻转",
    "MORE UPDATES AND CONTENT TO COME": "更多更新与内容即将到来",
    "MOUSE": "鼠标",
    "MOVE": "移动",
    "MULTI-BREACH": "多重突破",
