    // ==== часть 11: теги имен + слоты аугментаций + синергия/IG краткие описания ====
    "Agile": "Ловкий",
    "Balanced": "Сбалансированный",
    "Covert": "Скрытный",
    "Deflecting": "Отклоняющий",
    "Ergonomic": "Эргономичный",
    "Expanded": "Расширенный",
    "Extended": "Удлиненный",
    "Locked": "Заблокированный",
    "Hardened": "Закаленный",
    "Light": "Легкий",
    "Looter": "Мародер",
    "Mono": "Моно",
    "Organized": "Организованный",
    "Overdriven": "Разогнанный",
    "Packrat": "Скупщик",
    "Piercing": "Пробивающий",
    "Sharpened": "Заточенный",
    "Plated": "Бронированный",
    "Quick": "Быстрый",
    "Rapid": "Скоростной",
    "Long": "Дальнобойный",
    "Scavenger": "Собиратель",
    "Servo": "Серво",
    "Shadowed": "Теневой",
    "Shearing": "Срезающий",
    "Smuggler": "Контрабандист",
    "Streamlined": "Оптимизированный",
    "Tactical": "Тактический",
    "Precise": "Точный",
    "Vital": "Жизненный",
    "Camoed": "Камуфляжный",
    "Polished": "Полированный",
    "Cloaked": "Скрытый",
    "Durable": "Прочный",
    "Honed": "Отточенный",
    "Reliable": "Надежный",
    "Finding": "Поиск",
    "Grabby": "Захват",
    "Taped": "Обмотанный",
    "Grippy": "Цепкий",
    "Scanning": "Сканирование",
    "Spaced": "С зазором",
    "Clocked": "Разогнанный",
    "Padded": "Амортизирующий",
    "Tipped": "Заостренный",
    "Inserted": "Вставленный",
    "Pocketed": "С карманами",
    "Reactive": "Реактивный",
    "Reinforced": "Усиленный",
    "Unlocked": "Разблокированный",
    "Tuned": "Настроенный",
    "Maintained": "Обслуженный",
    "Angled": "Под углом",
    "Dampened": "Демпфированный",
    "Silent": "Бесшумный",
    "Fast": "Быстрый",
    "Cooled": "Охлажденный",
    "Timed": "Тайминг",
    "Vigorous": "Бодрый",
    "Aimed": "Прицельный",
    "Swift": "Стремительный",
    "Heavy": "Тяжелый",
    "OPTICS": "ОПТИКА",
    "NEURAL": "НЕЙРО",
    "DERMAL": "ДЕРМАЛЬНЫЙ",
    "CORE": "ЯДРО",
    "ARMS": "РУКИ",
    "LEGS": "НОГИ",
    "FRAME": "КАРКАС",
    "ORGAN": "ОРГАН",
    "MOUNT": "КРЕПЛЕНИЕ",
    "+5 HP Regen": "+5 регенерации ОЗ",
    "+30% First Strike Damage": "+30% урона первого удара",
    "+25% Skill Damage": "+25% урона навыков",
    "+15% Attack Speed": "+15% скорости атаки",
    "+10% Damage, +10% Speed": "+10% урона, +10% скорости",
    "+25 Armor": "+25 брони",
    "+75 HP": "+75 ОЗ",
    "+15 Stealth, +10 Evasion": "+15 скрытности, +10 уклонения",
    "+50% First Strike Damage": "+50% урона первого удара",
    "+3 HP Regen": "+3 регенерации ОЗ",
    "+10% Speed, +10 Evasion": "+10% скорости, +10 уклонения",
    "+10% Damage": "+10% урона",
    "+20% Damage": "+20% урона",
    "+5 Scavenge": "+5 к Scavenge",
    "+20% Loot Quantity": "+20% количества добычи",
    "2x auto-clicker speed": "2x скорость авто-кликера",
    "2x click damage": "2x урон от клика",
    "4x golden enemy chance": "4x шанс золотого врага",
    "2x insanity gain": "2x прирост безумия",
    "Armor only": "Только броня",
    "Weapons only": "Только оружие",
    "0.5% MYTHIC roll": "0.5% шанс MYTHIC",
    "Boosts + permanent powers": "Бусты + перманентные силы",
    "High prototype odds": "Высокий шанс прототипов",
    "Mixed low-tier gear + boosts": "Смешанное снаряжение низкого тира + бусты",
    "Pure insanity, paid in credits": "Чистое безумие, оплата кредитами",
    "Taking damage grants +10% damage for 5s (10s cooldown)": "Получение урона дает +10% урона на 5 сек (КД 10 сек)",
    "+2% chance per rank that raid kills grant +1 insanity": "+2% шанс за ранг, что убийства в RAID дадут +1 безумия",
    "+1% boss cache drop chance per rank": "+1% шанс выпадения тайника босса за ранг",
    "Each HOLLOW CROWN tier grants +5% trader sell price": "Каждый уровень HOLLOW CROWN дает +5% к цене продажи торговцу",
    "Each HOLLOW CROWN tier grants +2% INSANITY click damage": "Каждый уровень HOLLOW CROWN дает +2% к урону от клика INSANITY",
    "+0.1× headshot multiplier per rank": "+0.1× множитель хедшота за ранг",
    "-1% damage taken per rank": "-1% получаемого урона за ранг",
    "-3% reload time per rank": "-3% времени перезарядки за ранг",
    "+2 evasion per rank": "+2 уклонения за ранг",
    "+0.5% golden enemy chance per rank": "+0.5% шанс золотого врага за ранг",
    "-15% damage taken from wardens and bosses": "-15% урона от WARDEN и боссов",
    "+5% INSANITY click damage per rank": "+5% урона от клика INSANITY за ранг",
    "+2 armor per rank": "+2 брони за ранг",
    "+2% raid damage per rank": "+2% урона в RAID за ранг",
    "+1% trader coin flip chance per rank": "+1% шанс подброса монеты торговца за ранг",
    "+1% raid damage per 1,000 unspent insanity (max +20%)": "+1% урона в RAID за каждые 1,000 не потраченного безумия (макс. +20%)",
    "+5% INSANITY gain per rank": "+5% прироста INSANITY за ранг",
    "+2% max HP per rank": "+2% макс. ОЗ за ранг",
    "+2% fire rate per rank": "+2% темпа стрельбы за ранг",
    "Seed cache -20% cost, rebirth insanity cost -10%": "SEED тайник: -20% стоимости, стоимость безумия при перерождении -10%",
    "+5% damage to wardens per rank": "+5% урона по WARDEN за ранг",
    "+2% auto-clicker speed (permanent)": "+2% скорость авто-кликера (перманентно)",
    "+1% crit chance (permanent)": "+1% шанс крита (перманентно)",
    "+5% click damage (permanent)": "+5% урон от клика (перманентно)",
