    // ==== часть 03: враги безумия + названия классов + остальное ====
    "ARCHIVLICH": "ARCHIVLICH Лич",
    "SEGFAULT PRIME": "SEGFAULT PRIME",
    "THE COMPILER": "Компилятор",
    "STATIC": "Статика",
    "NULL": "Нуль",
    "HEX": "Хекс",
    "BIT": "Бит",
    "ROT": "Гниение",
    "OBSIDIAN": "Обсидиан",
    "DEADLOCK": "Дедлок",
    "SPECTRE": "Спектр",
    "VIPER": "Вайпер",
    "RAILGUN": "Рейлган",
    "HELLSTORM": "Хеллшторм",
    "SINGULARITY": "Сингулярность",
    "PHANTOM": "Фантом",
    "PUNISHER": "Панишер",
    "CONDUIT": "Кондуит",
    "TITAN": "Титан",
    "GAMBLER": "Гемблер",
    "ESC": "ESC",
    "SIPHON // VALUE": "SIPHON // ЦЕННОСТЬ",
    "RECOMPILER": "Рекомпилятор",
    "OPTIMIZER": "Оптимизатор",
    "MIL-CAP": "MIL-CAP",
    "RECOMP": "Рекомпиляция",
