    // ==== JS_UI часть 8: 4-й тур (механики CL, боевой текст, хакерская мини-игра, статы, полевая статистика) ====
    "SELECT SLOT TO LOAD": "ВЫБЕРИТЕ СЛОТ ДЛЯ ЗАГРУЗКИ",
    "SELECT SAVE SLOT": "ВЫБЕРИТЕ СЛОТ СОХРАНЕНИЯ",
    "Left an IFAK in your stash. On the house.": "Оставил IFAK в твоем хранилище. Мой подарок.",
    "Enemies regenerate HP each combat tick": "Враги восстанавливают HP каждый тик боя",
    "Enemy hits reduce your armor temporarily": "Удары врагов временно снижают вашу броню",
    "Healing effectiveness reduced by 30%": "Эффективность лечения снижена на 30%",
    "Enemies below 30% HP deal +50% damage": "Враги с HP ниже 30% наносят +50% урона",
    "Enemies spawn with a shield equal to 15% of max HP": "Враги появляются с щитом, равным 15% от макс. HP",
    "Random damage ticks during movement between POIs": "Случайные тики урона при перемещении между POI",
    "15% chance killed enemies spawn a clone": "15% шанс, что убитые враги создадут клона",
    "10% chance enemy hits bypass armor and evasion": "10% шанс, что удары врагов игнорируют броню и уклонение",
    "Signal Static becomes more frequent and intense": "Signal Static становится чаще и интенсивнее",
    "All damage has ±50% variance": "Весь урон имеет разброс ±50%",
    "ALARM!": "ТРЕВОГА!",
    "AMBUSH!": "ЗАДСАДА!",
    "CHEAT DEATH!": "ОБМАНУТЬ СМЕРТЬ!",
    "DANGER SENSE!": "ЧУТЬЕ ОПАСНОСТИ!",
    "DODGED!": "УКЛОНЕНИЕ!",
    "DOUBLE!": "ДВОЙНОЙ УДАР!",
    "LAST STAND!": "ПОСЛЕДНИЙ РУБЕЖ!",
    "MELTDOWN!": "РАСПЛАВЛЕНИЕ!",
    "MISS!": "ПРОМАХ!",
    "NOTHING!": "НИЧЕГО!",
    "ONE-TAP!": "В ОДИН УДАР!",
    "OVERHEAT!": "ПЕРЕГРЕВ!",
    "PAINKILLER!": "ОБЕЗБОЛИВАЮЩЕЕ!",
    "SECOND WIND!": "ВТОРОЕ ДЫХАНИЕ!",
    "SLIDE!": "СЛАЙД!",
    "WEAPON BROKEN!": "ОРУЖИЕ СЛОМАНО!",
    "+1 INS · BLOOD TITHE": "+1 INS · КРОВАВАЯ ДЕСЯТИНА",
    "ENCRYPTED": "ЗАШИФРОВАНО",
    "BLOCKED": "ЗАБЛОКИРОВАНО",
    "DENIED": "ОТКАЗАНО",
    "TIMEOUT": "ТАЙМАУТ",
    "ACCESS_PORT": "ACCESS_PORT",
    "Press SPACE when cursor is on ACCESS_PORT!": "Нажмите SPACE, когда курсор на ACCESS_PORT!",
    "[SPACE] EXECUTE": "[SPACE] ВЫПОЛНИТЬ",
    "EXECUTE": "ВЫПОЛНИТЬ",
    "HP": "HP",
    "HP:": "HP:",
    "Headshot Chance": "Шанс хедшота",
    "Headshot Mult": "Множитель хедшота",
    "Maximum Vitals": "Макс. показатели жизнеобеспечения",
    "Weight Capacity": "Грузоподъемность",
    "Scavenging": "Собирательство",
    "Stealth": "Скрытность",
    "Speed": "Скорость",
    "elemental damage": "стихийный урон",
    "Damage Dealt": "Нанесенный урон",
    "Deaths": "Смерти",
    "Items Looted": "Собрано предметов",
    "Items Salvaged": "Разобрано предметов",
    "Money Earned": "Заработано денег",
    "Flux Earned": "Получено FLUX",
    "Highest CL": "Макс. CL",
    "Corrupted Raids": "Зараженные RAID",
    "Wardens Defeated": "Побеждено WARDEN",
    "Salvage all items up to a rarity tier?": "Разобрать все предметы до уровня редкости?",
    "for crafting materials?": "для материалов производства?",
    "Expected:": "Ожидается:",
    "custom weapon": "кастомное оружие",
    "custom armor": "кастомная броня",
    "player level": "уровень игрока",
    "Reload": "Перезарядка",
    "Mag Size": "Размер магазина",
    "STATIC": "ПОМЕХИ",
    "DISTORTION": "ИСКАЖЕНИЕ",
    "FEEDBACK": "ОБРАТНАЯ СВЯЗЬ",
