    // ==== parça 19: quest ödül bildirimi + yer etiketi fallback kelimeleri ====
    "No rewards": "无奖励",
    "Make room in your stash to claim rewards.": "请在仓库腾出空间以领取奖励。",
    "Shotgun": "霰弹枪",
    "Rifle": "步枪",
    "Sniper": "狙击枪",
    "Clip": "弹夹",
    "Magazine": "弹匣",
    "Vest": "背心",
    "Medkit": "医疗包",
    "Stim": "兴奋剂",
    "Axe": "斧",
    "Ammo": "弹药",
    "LOCKER": "储物柜",
    "+1% crit chance (permanent). Chance caps at 60%, excess boosts crit multiplier": "+1% 暴击几率（永久）。几率上限为 60%，超出部分转化为暴击倍率",
