    // ==== JS_UI parça 10: audit 2. dalga (settings etiketleri, keystone'lar, kategoriler) ====
    "CRT Effects": "CRT 效果",
    "Menu Animations": "菜单动画",
    "Particles": "粒子效果",
    "Loot Beams": "战利品光柱",
    "Screen Shake": "屏幕震动",
    "Damage Numbers": "伤害数字",
    "Combat Text": "战斗文本",
    "Combat Text Size": "战斗文本大小",
    "FPS Limit": "帧率上限",
    "VFX Intensity": "特效强度",
    "Master Volume": "主音量",
    "Loot SFX": "战利品音效",
    "Combat SFX": "战斗音效",
    "Menu SFX": "菜单音效",
    "Mute All": "全部静音",
    "Mode": "模式",
    "Monitor": "显示器",
    "UI Scale": "界面缩放",
    "Font Size": "字体大小",
    "Language": "语言",
    "Navigation Panel": "导航面板",
    "Ask Before Quick Actions": "快捷操作前询问",
    "Auto Accept and Complete Quests": "任务自动接受与完成",
    "Automatically heal to full HP after raid ($)": "RAID 后自动治疗至满生命（$）",
    "Opens a screen from anywhere outside a raid. Click a binding, then press a key or a mouse side button. ESC cancels, DELETE clears. Raid keys, left click, right click and the wheel stay with the game.": "在 RAID 之外的任何地方打开界面。点击一个绑定，然后按键盘键或鼠标侧键。ESC 取消，DELETE 清除。RAID 按键、左键、右键和滚轮保留给游戏。",
    "Bad (unprotected) base tiers get sold/salvaged even above Max Rarity. Needs Protect Base Tier. Never touches Prototype, Mythic, protected or disabled types": "劣质（未保护）基础品阶即使高于最高稀有度也会被出售/拆解。需要开启保护基础品阶。绝不涉及 PROTOTYPE、MYTHIC、受保护或已禁用的类型",
    "Bloody Knuckles": "血拳",
    "Bull Rush": "蛮牛冲锋",
    "Coin Toss": "抛硬币",
    "Double or Nothing": "孤注一掷",
    "Degenerate Gambler": "堕落赌徒",
    "Evasive Instinct": "闪避本能",
    "Heavy Load": "重装上阵",
    "Iron Body": "钢铁之躯",
    "Lingering Effects": "延续效应",
    "No Retreat": "绝不后退",
    "Painkiller": "止痛剂",
    "Maximum HP": "最大生命",
    "Melee Damage": "近战伤害",
    "Movement Speed": "移动速度",
    "Stamina Cost": "耐力消耗",
    "Attack Speed": "攻击速度",
    "Maximum Elemental Stacks": "元素叠层上限",
    "Elemental Effect Power": "元素效果强度",
    "Chance to Deflect incoming damage": "偏转来袭伤害的概率",
    "Helmets": "头盔类",
    "Magazines": "弹匣类",
    "Mining GPUs": "矿用显卡",
    "Medkits, Stims": "急救包、兴奋剂",
    "Junk / Barter / Food items": "垃圾 / 交易品 / 食物",
    "General looting efficiency": "总体拾荒效率",
    "Maximum carry weight": "最大负重",
    "Mitigates physical damage": "减轻物理伤害",
    "Ignores enemy armor": "无视敌人护甲",
    "Headshot": "爆头",
    "Base Sell Value": "基础出售价值",
    "Damage": "伤害",
    "Armor": "护甲",
    "Evasion": "闪避",
    "Mag": "弹匣",
    "Heat": "过热",
    "Durability Loss": "耐久损耗",
    "(empty)": "（空）",
    "Ensured ✓": "已投保 ✓",
    "Hide completed": "隐藏已完成",
    "Hold Z": "按住 Z",
    "NOTABLE LOOT": "特殊战利品",
    "NOTABLE": "特殊",
    "KEYSTONE": "楔石",
    "MEDIUM": "中等",
    "JAM!": "卡壳！",
    "HELMET": "头盔",
    "AUTO SPRINT: ON": "自动冲刺：开",
    "AUTO SPRINT: OFF": "自动冲刺：关",
    "Hood": "兜帽",
    "Iron": "铁",
    "Engine": "引擎",
    "Bearings": "轴承",
    "Detergent": "洗涤剂",
    "Blade": "刀锋",
    "Mask": "面罩",
    "Holo-Projector": "全息投影仪",
    "Bolt-Action": "栓动步枪",
    "DMR": "精射步枪",
    "Glitch": "GLITCH",
    "Prototype": "PROTOTYPE",
    "Mythic": "MYTHIC",
    "DOG*": "狗*",
    "PATCH (Ripperdoc)": "PATCH（Ripperdoc）",
    "AUGMENT MISSION": "义体任务",
    "Game will be saved. Close the application?": "游戏将被保存。关闭应用程序？",
    "Game will be saved. Return to main menu?": "游戏将被保存。返回主菜单？",
    "Hit NEXT when you're ready.": "准备好了就按下一步。",
    "Try it now.": "现在试试。",
    "Open it now.": "现在就打开。",
    "Go on, click one.": "来，点一个。",
