    // ==== JS_UI часть 13: мифические/прото аффиксы, мета модов, босс INSANITY/перерождение ====
    "flat damage": "Плоский урон",
    "damage": "Урон",
    "armor": "Броня",
    "evasion": "Уклонение",
    "health": "Здоровье",
    "fire rate": "Скорострельность",
    "armor penetration": "Пробитие брони",
    "lifesteal on hit": "Вампиризм при попадании",
    "headshot multiplier": "Множитель хедшота",
    "magazine capacity": "Ёмкость магазина",
    "damage reduction": "Снижение урона",
    "max HP per second": "Макс. HP в сек.",
    "accuracy": "Точность",
    "handling": "владение",
    "HP Regen": "Регенерация HP",
    "Health regeneration per second": "Регенерация здоровья в сек.",
    "Flat damage reduction": "Фикс. снижение урона",
    "EYE": "ГЛАЗ",
    "BRAIN": "МОЗГ",
    "TORSO": "ТУЛОВИЩЕ",
    "SKIN": "КОЖА",
    "LEG": "НОГА",
    "SKELETON": "СКЕЛЕТ",
    "INTERNAL": "ВНУТРЕННИЕ ОРГАНЫ",
    "SHOULDER": "ПЛЕЧО",
    "COMMON": "ОБЫЧНЫЙ",
    "RARE": "РЕДКИЙ",
    "EPIC": "ЭПИЧЕСКИЙ",
    "LEGENDARY": "ЛЕГЕНДАРНЫЙ",
    "AR": "Штурмовая винтовка",
    "MYTHIC AFFIXES": "MYTHIC аффиксы",
    "ABILITIES": "Способности",
    "PASSIVE ABILITY": "Пассивная способность",
    "TRIGGERED ABILITY": "Активная способность",
    "CONFIRM REBIRTH?": "Подтвердить перерождение?",
    "// MAXED": "// МАКС. УРОВЕНЬ",
    "MADNESS PROTOCOL is live. Spend your INSANITY: LOADOUT > MASTERY tab.": "Протокол MADNESS запущен. Тратьте INSANITY: LOADOUT > вкладка MASTERY.",
    "Eye lasers vaporize the target at the start of every combat. Your weapon holds fire.": "Лазеры из глаз испаряют цель в начале каждого боя. Ваше оружие не стреляет.",
    "Fully surround the Flux Capacitor with modules": "Полностью окружите Flux Capacitor модулями",
    "Cannot trigger if you don't have enough Stamina.": "Не может сработать при нехватке выносливости.",
    "Toss a coin when combat starts.": "Подбросьте монетку в начале боя.",
    "Gain Rage when you hit an enemy.": "Получайте Rage при попадании по врагу.",
    "ranged": "дальний",
    "melee": "ближний",
    "universal": "универсальный",
    "dot": "DOT",
    "domino": "домино",
    "square": "квадрат",
    "ammo": "боеприпасы",
    "barrel": "ствол",
    "cool": "охлаждение",
    "optic": "оптика",
    "pierce": "пронзание",
    "shock": "шок",
    "servo": "серво",
    "plate": "пластина",
    "med": "мед.",
    "shield": "щит",
    "power": "энергия",
    "bleed": "кровотечение",
    "edge": "лезвие",
    "flux": "flux",
    "Bleed": "Кровотечение",
    "Optic": "Оптика",
    "Servo": "Серво",
    "Power": "Энергия",
    "Coolant": "Охладитель",
    "Shock": "Шок",
