    // ==== JS_UI часть 10: аудит 2-й волны (настройки, keystone, категории) ====
    "CRT Effects": "CRT-эффекты",
    "Menu Animations": "Анимация меню",
    "Particles": "Частицы",
    "Loot Beams": "Световые столбы добычи",
    "Screen Shake": "Тряска экрана",
    "Damage Numbers": "Числа урона",
    "Combat Text": "Боевой текст",
    "Combat Text Size": "Размер боевого текста",
    "FPS Limit": "Лимит FPS",
    "VFX Intensity": "Интенсивность VFX",
    "Master Volume": "Общая громкость",
    "Loot SFX": "Звуки добычи",
    "Combat SFX": "Звуки боя",
    "Menu SFX": "Звуки меню",
    "Mute All": "Выключить всё",
    "Mode": "Режим",
    "Monitor": "Монитор",
    "UI Scale": "Масштаб интерфейса",
    "Font Size": "Размер шрифта",
    "Language": "Язык",
    "Navigation Panel": "Панель навигации",
    "Ask Before Quick Actions": "Спрашивать перед быстрыми действиями",
    "Auto Accept and Complete Quests": "Автопринятие и выполнение заданий",
    "Automatically heal to full HP after raid ($)": "Авто-лечение до полного HP после RAID ($)",
    "Opens a screen from anywhere outside a raid. Click a binding, then press a key or a mouse side button. ESC cancels, DELETE clears. Raid keys, left click, right click and the wheel stay with the game.": "Открывает экран из любого места вне RAID. Нажмите на привязку, затем клавишу или боковую кнопку мыши. ESC отменяет, DELETE очищает. Клавиши RAID, левая/правая кнопки мыши и колесико остаются за игрой.",
    "Bad (unprotected) base tiers get sold/salvaged even above Max Rarity. Needs Protect Base Tier. Never touches Prototype, Mythic, protected or disabled types": "Низкое (незащищенное) базовое качество будет продано/разобрано, даже если оно выше максимальной редкости. Требуется функция Protect Base Tier. Никогда не затрагивает типы PROTOTYPE, MYTHIC, защищенные или отключенные типы.",
    "Bloody Knuckles": "Кровавые костяшки",
    "Bull Rush": "Бычий натиск",
    "Coin Toss": "Бросок монеты",
    "Double or Nothing": "Всё или ничего",
    "Degenerate Gambler": "Азартный безумец",
    "Evasive Instinct": "Инстинкт уклонения",
    "Heavy Load": "Тяжелая ноша",
    "Iron Body": "Стальное тело",
    "Lingering Effects": "Длительные эффекты",
    "No Retreat": "Ни шагу назад",
    "Painkiller": "Обезболивающее",
    "Maximum HP": "Макс. HP",
    "Melee Damage": "Урон в ближнем бою",
    "Movement Speed": "Скорость передвижения",
    "Stamina Cost": "Расход выносливости",
    "Attack Speed": "Скорость атаки",
    "Maximum Elemental Stacks": "Макс. стаков стихий",
    "Elemental Effect Power": "Сила стихийного эффекта",
    "Chance to Deflect incoming damage": "Шанс отразить входящий урон",
    "Helmets": "Шлемы",
    "Magazines": "Магазины",
    "Mining GPUs": "Видеокарты для майнинга",
    "Medkits, Stims": "Аптечки, стимуляторы",
    "Junk / Barter / Food items": "Хлам / Бартер / Еда",
    "General looting efficiency": "Общая эффективность добычи",
    "Maximum carry weight": "Макс. переносимый вес",
    "Mitigates physical damage": "Смягчает физический урон",
    "Ignores enemy armor": "Игнорирует броню врага",
    "Headshot": "Хедшот",
    "Base Sell Value": "Базовая цена продажи",
    "Damage": "Урон",
    "Armor": "Броня",
    "Evasion": "Уклонение",
    "Mag": "Маг.",
    "Heat": "Нагрев",
    "Durability Loss": "Потеря прочности",
    "(empty)": "(пусто)",
    "Ensured ✓": "Гарантировано ✓",
    "Hide completed": "Скрыть выполненные",
    "Hold Z": "Удерживайте Z",
    "NOTABLE LOOT": "ЦЕННАЯ ДОБЫЧА",
    "NOTABLE": "ЦЕННЫЙ",
    "KEYSTONE": "KEYSTONE",
    "MEDIUM": "СРЕДНИЙ",
    "JAM!": "ЗАКЛИНИЛО!",
    "HELMET": "ШЛЕМ",
    "AUTO SPRINT: ON": "АВТО-БЕГ: ВКЛ",
    "AUTO SPRINT: OFF": "АВТО-БЕГ: ВЫКЛ",
    "Hood": "Капюшон",
    "Iron": "Железо",
    "Engine": "Двигатель",
    "Bearings": "Подшипники",
    "Detergent": "Моющее средство",
    "Blade": "Лезвие",
    "Mask": "Маска",
    "Holo-Projector": "Голо-проектор",
    "Bolt-Action": "Болтовая винтовка",
    "DMR": "DMR",
    "Glitch": "GLITCH",
    "Prototype": "PROTOTYPE",
    "Mythic": "MYTHIC",
    "DOG*": "DOG*",
    "PATCH (Ripperdoc)": "PATCH (Ripperdoc)",
    "AUGMENT MISSION": "ЗАДАНИЕ НА АУГМЕНТАЦИЮ",
    "Game will be saved. Close the application?": "Игра будет сохранена. Закрыть приложение?",
    "Game will be saved. Return to main menu?": "Игра будет сохранена. Вернуться в главное меню?",
    "Hit NEXT when you're ready.": "Нажми «ДАЛЕЕ», когда будешь готов.",
    "Try it now.": "Попробуй сейчас.",
    "Open it now.": "Открыть сейчас.",
    "Go on, click one.": "Давай, выбери один.",
