    // ==== JS_UI parça 12: keystone'lar, terminal TAM çeviri, audit 4 ====
    "Complete the Welcome Gift quest": "完成欢迎礼物任务",
    "All Bets Down": "全部押上",
    "Back Against the Wall": "退无可退",
    "Blur": "残影",
    "Clean Kill": "干净利落",
    "Controlled Burst": "受控点射",
    "Elemental Pressure": "元素压制",
    "Feeling Lucky": "手气正旺",
    "Ghost Step": "鬼步",
    "Glass Cannon": "玻璃大炮",
    "Heavy Hands": "重手",
    "High Stakes": "豪赌",
    "Pain or Profit": "痛苦或利润",
    "Rage": "狂怒",
    "Relentless Fire": "无情火力",
    "Ricochet": "跳弹",
    "Roll With It": "顺势而为",
    "Unwavering Aim": "稳定瞄准",
    "Overload": "过载",
    "Amplify": "增幅",
    "Acid": "酸蚀",
    "Armor Piercer Rounds": "穿甲弹",
    "When combat begins,": "战斗开始时，",
    "The first hit you take in combat": "你在战斗中受到的第一次攻击",
    "for the first hit you receive in this combat.": "（作用于本场战斗你受到的第一击）。",
    "Each active Elemental Stack": "每层生效的元素叠层",
    "Each consecutive hit on the same enemy": "对同一敌人的每次连续命中",
    "applying maximum stacks of all elemental effects.": "施加所有元素效果的最大叠层。",
    "Hitting enemies generates Overload.": "命中敌人会积累过载。",
    "When combat begins, you charge at the enemy.": "战斗开始时，你会冲向敌人。",
    "You hook the enemy and pull them toward you.": "你用钩索把敌人拉向自己。",
    "Your shots never miss.": "你的射击永不落空。",
    "You can no longer deal Headshots.": "你不再能造成爆头。",
    "Status Effect Power": "状态效果强度",
    "Armor Penetration": "护甲穿透",
    "Atk Spd": "攻速",
    "STAM": "耐力",
    "Health": "生命",
    "Scavenge": "拾荒",
    "Hold": "按住",
    "Treats": "零食",
    "Phone": "手机",
    "Plank": "木板",
    "CLOTH": "布料",
    "MECHANICAL": "机械",
    "enhanced": "强化",
    "custom": "定制",
    "No eligible items found.": "没有符合条件的物品。",
    "module codes": "模块代码",
    "over time.": "（随时间累积）。",
    "no stat change": "属性无变化",
    "ROOT": "根权限",
    "FLASH": "刷写",
    "MILCAP": "军规电容",
    "Kernel": "内核",
    "Patch": "补丁",
    "AUTO-CLICKER": "自动点击器",
    "> All subsystems operational. Type \"help\" for commands.": "> 所有子系统运行正常。输入 \"help\" 查看命令。",
    "CURRENCIES (type \"cur\" for inventory):": "货币（输入 \"cur\" 查看库存）：",
    "anchor <mod_name>        Lock mod with anchor code": "anchor <模组名>        用锚定代码锁定模组",
    "clear                    Clear terminal": "clear                    清空终端",
    "currencies (cur)         Show currency inventory": "currencies (cur)         显示货币库存",
    "help glitch              Show glitch protocol details": "help glitch              显示 GLITCH 协议详情",
    "help mods [category]     Show available mods": "help mods [类别]         显示可用模组",
    "inject <code>            Add code to inject queue": "inject <代码>            将代码加入注入队列",
    "mining                   Show mining status": "mining                   显示挖矿状态",
    "mining add               Install GPU from stash": "mining add               从仓库安装显卡",
    "mining remove            Remove GPU to stash": "mining remove            将显卡移回仓库",
    "mining start             Start mining rig": "mining start             启动矿机",
    "mining stop              Stop mining rig": "mining stop              停止矿机",
    "refuel generator         Refuel with BTC": "refuel generator         用 BTC 加燃料",
    "select <n>               Select item by index": "select <n>               按序号选择物品",
    "status                   Show full item status": "status                   显示完整物品状态",
    "stop                     Stop auto-mod": "stop                     停止自动改装",
    "use <currency>           Use currency on item": "use <货币>               对物品使用货币",
    "use <currency> until <mod>  Auto-repeat until mod": "use <货币> until <模组>  自动重复直到出现该模组",
    "use <currency> x<n>      Use currency n times": "use <货币> x<n>          使用货币 n 次",
    "root     Jailbreaks [Standard] to [Enhanced].": "root     将 [Standard] 越狱升级为 [Enhanced]。",
    "flash    Reflashes properties on [Enhanced].": "flash    重刷 [Enhanced] 的属性。",
    "kernel   Upgrades [Enhanced] to [Custom].": "kernel   将 [Enhanced] 升级为 [Custom]。",
    "milcap   Overclocks [Custom] with powerful mod.": "milcap   用强力模组为 [Custom] 超频。",
    "slot     Solders a new mod onto [Enhanced].": "slot     在 [Enhanced] 上焊接一个新模组。",
    "opt      Optimizes numeric performance of mods.": "opt      优化模组的数值表现。",
    "recomp   Resets and rebuilds a [Custom] item.": "recomp   重置并重构一件 [Custom] 物品。",
    "wipe     Removes all, reverts to [Standard].": "wipe     移除所有属性，还原为 [Standard]。",
    "glitch   Corrupts item. Unpredictable. Locks.": "glitch   侵蚀物品。不可预测。锁定。",
    "click code to add to queue | use 'inject <code>' in terminal": "点击代码加入队列 | 在终端使用 'inject <代码>'",
    "- no codes -": "- 无代码 -",
    "* effects vary by item type (armor/melee/ranged) - type 'help glitch' in terminal": "* 效果因物品类型而异（护甲/近战/远程）- 在终端输入 'help glitch'",
    "No item selected. Use \"select <n>\" first.": "未选择物品。请先使用 \"select <n>\"。",
    "sell btc <amount>": "sell btc <数量>",
    "target crafting": "定向制作",
    "Inject collected codes for": "注入收集到的代码以进行",
