    // ==== часть 01: синергия / эндгейм / префикс врага ====
    "Endurance Protocol": "Протокол выносливости",
    "Shadow Assault": "Теневая атака",
    "War Machine": "Машина войны",
    "Berserker": "Берсерк",
    "Fortress": "Крепость",
    "Ghost": "Призрак",
    "Predator": "Хищник",
    "Technomancer": "Техномант",
    "God Protocol": "Протокол Божества",
    "Neural Commerce": "Нейроторговля",
    "Armored": "Бронированный",
    "Enraged": "Яростный",
    "Fortified": "Укрепленный",
