    // ==== chunk 02: augment adları + yetenekleri ====
    "Unbreakable": "牢不可破",
    "Synthetic Adrenaline Gland": "合成肾上腺体",
    "Combat High": "战斗亢奋",
    "Trauma Response System": "创伤响应系统",
    "Trauma Response": "创伤响应",
    "Carbon Fiber Core": "碳纤维核心",
    "Equilibrium": "平衡态",
    "Chameleon Mesh": "变色龙网膜",
    "Ghost Strike": "幽灵打击",
    "Crimson Gaze": "猩红凝视",
    "Energy Reactor": "能量反应堆",
    "Power Surge": "能量涌动",
    "Fortress Chassis": "堡垒底盘",
    "Unyielding": "不屈",
    "Fusion Power Cell": "聚变电池",
    "Unlimited Power": "无限能量",
    "Grav-Drive Legs": "重力驱动腿",
    "Velocity Rush": "极速冲刺",
    "Hawkeye Implant": "鹰眼植入体",
    "Eagle Eye": "鹰眼",
    "Hive Mind Core": "蜂群思维核心",
    "Kill Frenzy": "杀戮狂热",
    "Hydraulic Crushers": "液压碎击臂",
    "Power Strike": "强力打击",
    "Micro-Rocket Pod": "微型火箭巢",
    "Auto Rockets": "自动火箭",
    "Nanite Swarm Arms": "纳米虫群臂",
    "Corrosive Touch": "腐蚀之触",
    "Orbital Designator": "轨道标记器",
    "Orbital Bombardment": "轨道轰炸",
    "Phase Striders": "相位跃行腿",
    "Phantom Clones": "幻影分身",
    "Plasma Turret": "等离子炮塔",
    "Auto-Turret": "自动炮塔",
    "Precision Servos": "精密伺服",
    "Perfect Aim": "完美瞄准",
    "Predictive Matrix": "预测矩阵",
    "Precognition": "预知",
    "Quantum Lens": "量子透镜",
    "Rapid Burst": "急速连发",
    "Reactive Nanoweave": "反应纳米织层",
    "Adaptive Armor": "自适应护甲",
    "Regenerative Membrane": "再生膜",
    "Bio-Repair": "生物修复",
    "Shock Absorbers": "避震装置",
    "Iron Skin": "铁肤",
    "Synapse Accelerator": "突触加速器",
    "Neural Overclock": "神经超频",
    "Thermal Oculus": "热感目镜",
    "Scan": "扫描",
    "Titanium Exoframe": "钛合金外骨骼",
    "Pack Mule": "驮骡",
    "Void Heart": "虚空之心",
    "Life Steal": "生命偷取",
