    // ==== chunk 06: kalan quest adları ====
    "Meat Grinder": "绞肉机",
    "Overclock": "超频",
    "Beyond Human": "超越人类",
    "Scrap Run": "拾荒差事",
    "Chop Shop": "拆解作坊",
    "First Dose": "第一针",
    "Static in the Blood": "血中静噪",
    "Cage Fight": "笼中斗",
    "Protocol: UNHUMAN": "协议：UNHUMAN",
    "First Chrome": "初装义体",
    "Nerve Damage": "神经损伤",
    "First Signal": "初次信号",
    "Interference": "干扰",
    "Feedback Loop": "反馈回路",
    "Cascade Event": "级联事件",
    "Singularity": "奇点",
    "Thread Count": "织线计数",
    "Quiet Run": "无声一趟",
    "Prototype Weave": "原型织物",
    "Iron Veil": "铁幕",
    "Man's Best Friend": "人类最好的朋友",
    "Supply Chain": "供应链",
    "Terminal Access": "终端权限",
    "Big Haul": "大丰收",
    "Deep Pockets": "财大气粗",
    "Glitch Touch": "GLITCH 之触",
    "Salvage King": "拆解之王",
    "Rare Thread": "稀有织线",
