    // ==== часть 12: описания аугментаций/предметов/мусора (теги тиров [Standard] и т.д. на латинице) ====
    "+3% insanity gain (permanent)": "+3% прироста безумия (перманентно)",
    "Indestructible spine with crowd control immunity.": "Неразрушимый позвоночник с иммунитетом к эффектам контроля.",
    "Artificial gland for combat adrenaline surge.": "Искусственная железа для выброса боевого адреналина.",
    "Embedded trauma unit that activates during combat.": "Встроенный модуль травмы, активирующийся во время боя.",
    "Lightweight frame with balanced stat enhancement.": "Легкий каркас со сбалансированным усилением характеристик.",
    "Power core that supercharges combat abilities.": "Энергетическое ядро, перегружающее боевые способности.",
    "Heavy-duty frame with emergency revival system.": "Тяжелый каркас с системой экстренного возрождения.",
    "Unlimited power source for skill enhancement.": "Безграничный источник энергии для усиления навыков.",
    "Anti-gravity propulsion for enhanced mobility.": "Антигравитационная тяга для повышенной мобильности.",
    "Enhanced targeting optics. Passively increases damage.": "Улучшенная прицельная оптика. Пассивно увеличивает урон.",
    "Neural network that amplifies damage with each kill.": "Нейронная сеть, увеличивающая урон с каждым убийством.",
    "Every 5th strike triggers devastating power strike.": "Каждый 5-й удар вызывает разрушительный силовой удар.",
    "Shoulder-mounted rocket launcher.": "Ракетная установка на плече.",
    "Nanite-infused arms that apply corrosive damage over time.": "Руки с нанитами, наносящие периодический коррозийный урон.",
    "Calls orbital bombardment at combat start.": "Вызывает орбитальную бомбардировку в начале боя.",
    "Automated turret that attacks nearby enemies.": "Автоматическая турель, атакующая ближайших врагов.",
    "High-precision servo motors for perfect aim.": "Высокоточные сервомоторы для идеального прицеливания.",
    "Quantum tech fires rapid burst at combat start.": "Квантовые технологии выпускают быструю очередь в начале боя.",
    "Adaptive armor that hardens on impact.": "Адаптивная броня, которая твердеет при ударе.",
    "Bio-synthetic skin with rapid healing capabilities.": "Биосинтетическая кожа с возможностью быстрого исцеления.",
    "Each hit taken increases armor, stacking through combat.": "Каждое полученное попадание увеличивает броню, стакается в бою.",
    "Neural boost for faster looting and movement.": "Нейронный буст для ускоренного лута и перемещения.",
    "Industrial-grade skeleton for increased carrying capacity.": "Промышленный скелет для увеличения грузоподъемности.",
    "Dark energy core that drains life from enemies.": "Ядро темной энергии, высасывающее жизнь из врагов.",
    "Helps you find items and detects enemies up ahead.": "Помогает искать предметы и обнаруживает врагов впереди.",
    "Basic dog food. Restores 50% hunger. Lasts 1 hour.": "Базовый корм для собак. Восстанавливает 50% сытости. Хватает на 1 час.",
    "High quality dog food. Fully restores hunger. Lasts 2 hours.": "Высококачественный корм для собак. Полностью восстанавливает сытость. Хватает на 2 часа.",
    "A classic tennis ball. +5 happiness per pet. 100 durability.": "Классический теннисный мячик. +5 к счастью за каждое поглаживание. Прочность 100.",
    "Durable rope toy. +8 happiness per pet. 150 durability.": "Прочная веревочная игрушка. +8 к счастью за каждое поглаживание. Прочность 150.",
    "Basic mining GPU. +0.0001 BTC/min. Install in mining rig.": "Базовая видеокарта для майнинга. +0.0001 BTC/мин. Установить в майнинг-риг.",
    "Advanced mining GPU. +0.0002 BTC/min. Higher hash rate.": "Продвинутая видеокарта для майнинга. +0.0002 BTC/мин. Выше хешрейт.",
    "Elite mining GPU. +0.0003 BTC/min. Maximum performance.": "Элитная видеокарта для майнинга. +0.0003 BTC/мин. Максимальная производительность.",
    "Universal AR magazine. Standard capacity.": "Универсальный магазин для AR. Стандартная емкость.",
    "Bolt-action stripper clip. For internal magazines.": "Клипса для винтовки Bolt-action. Для внутренних магазинов.",
    "Universal DMR magazine. Round count varies by weapon.": "Универсальный магазин для DMR. Количество патронов зависит от оружия.",
    "Universal pistol magazine. Ammo count varies by weapon.": "Универсальный магазин для пистолета. Количество патронов зависит от оружия.",
    "Universal shotgun magazine. Shell count varies by weapon.": "Универсальный магазин для дробовика. Количество патронов зависит от оружия.",
    "Universal SMG magazine. High capacity.": "Универсальный магазин для SMG. Большая емкость.",
    "Flawless energy core. Doubles upgrade success chance.": "Безупречное энергетическое ядро. Удваивает шанс успеха улучшения.",
    "Multiple First Aid Kit. 400 uses.": "Набор аптечек. 400 использований.",
    "Advanced First Aid Kit. 200 uses.": "Продвинутая аптечка. 200 использований.",
    "Individual First Aid Kit. 100 uses.": "Индивидуальная аптечка. 100 использований.",
    "You feel like you can conquer the world.": "Вы чувствуете, что можете покорить мир.",
    "Jailbreaks [Standard] gear to [Enhanced].": "Взламывает снаряжение [Standard] до [Enhanced].",
    "Reflashes properties on [Enhanced] gear.": "Перезаписывает свойства снаряжения [Enhanced].",
    "Some men just want to watch the world burn.": "Некоторым людям просто хочется смотреть, как мир горит.",
    "Outputs more energy than it receives. Physics hates this.": "Выдает больше энергии, чем потребляет. Физика это ненавидит.",
    "Records events before they happen. Playback not recommended.": "Записывает события до того, как они произойдут. Воспроизведение не рекомендуется.",
    "Deez nuts.": "Дец натс.",
    "Rusty, bent, and sharp. Like everyone else in this city.": "Ржавый, погнутый и острый. Как и все остальные в этом городе.",
    "Corroded beyond recognition. Might be art, might be trash.": "Разъедено до неузнаваемости. Может искусство, а может мусор.",
    "Holds the world together. Every pipe, every wall, every lie.": "Держит мир вместе. Каждую трубу, каждую стену, каждую ложь.",
    "Hit it until it works. Engineering 101.": "Стучи, пока не заработает. Основы инженерии.",
    "Still spins when you touch it. No one knows why.": "Все еще крутится, если дотронуться. Никто не знает почему.",
    "RIP": "RIP",
    "Solders a new mod onto [Enhanced] gear.": "Припаивает новый мод к снаряжению [Enhanced].",
    "I bet there is 100 BTC in there.": "Спорим, там лежит 100 BTC.",
    "An experimental core that seems to bend reality around it.": "Экспериментальное ядро, которое, кажется, искривляет реальность вокруг себя.",
    "Half empty or half full? Completely empty.": "Наполовину пусто или наполовину полно? Совершенно пусто.",
    "Keeps the rain out. That's about it.": "Защищает от дождя. Больше ничего.",
    "Could be a car door. Could be a fridge. Nobody remembers.": "Может, дверь от машины. Может, холодильник. Никто не помнит.",
    "Lighter than guilt, stronger than excuses.": "Легче вины, сильнее оправданий.",
    "Data once moved through this faster than bad news.": "Когда-то данные проходили через это быстрее, чем плохие новости.",
    "Upgrades [Enhanced] to [Custom] with new mod.": "Улучшает [Enhanced] до [Custom] с новым модом.",
    "Military-grade. Built by the lowest bidder.": "Военного уровня. Сделано самым дешевым подрядчиком.",
    "Worth more than you. Per gram, at least.": "Стоит больше тебя. По крайней мере, на грамм.",
    "Doesn't mesh with anything. Story of my life.": "Ни с чем не стыкуется. История моей жизни.",
    "Still has some bounce. Unlike morale around here.": "Все еще немного пружинит. В отличие от местного боевого духа.",
    "Red means stop. Green means go. Both are stuck.": "Красный — стоп. Зеленый — вперед. Оба застряли.",
    "Connects nothing to nowhere. Essential infrastructure.": "Соединяет ничто с ничем. Важнейшая инфраструктура.",
    "Stopped at 3:47 AM. Someone's last bad night.": "Остановилось в 3:47 утра. Последняя плохая ночь кого-то.",
    "Smooth. Unlike everything else around here.": "Гладкое. В отличие от всего остального в этих краях.",
    "Keeps spinning no matter which way the world tilts.": "Продолжает вращаться, как бы ни кренился мир.",
    "The muscle behind every door that slammed in your face.": "Сила, стоящая за каждой дверью, захлопнувшейся перед вашим носом.",
    "Overclocks [Custom] gear with a powerful mod.": "Разгоняет снаряжение [Custom] мощным модом.",
    "Enough pressure to move a wall. Or what's left of one.": "Давления достаточно, чтобы сдвинуть стену. Или то, что от нее осталось.",
    "Still sparks. Some things refuse to die.": "Все еще искрит. Некоторые вещи отказываются умирать.",
    "Wrong head for every screw you'll ever find.": "Не та головка для любого винта, что вы найдете.",
    "Grip strength of a desperate man.": "Сила хватки отчаявшегося человека.",
    "Every mechanic's first and last resort.": "Первое и последнее средство любого механика.",
    "Cuts wire. Also cuts fingers if you're not careful.": "Режет провод. А если не осторожен — и пальцы.",
    "14 tools in one. 13 of them are knives.": "14 инструментов в одном. 13 из них — ножи.",
    "Tip's seen better days. Haven't we all.": "Наконечник видел лучшие времена. Как и все мы.",
    "Fixes metal. Fixes people too, technically.": "Чинит металл. Технически, чинит и людей тоже.",
    "Every locked door is an opportunity. This makes it official.": "Каждая запертая дверь — это возможность. Это делает ее официальной.",
    "Completely resets and rebuilds a [Custom] item.": "Полностью сбрасывает и пересобирает предмет [Custom].",
    "0% charge, 100% optimism.": "0% заряда, 100% оптимизма.",
    "Sticks to everything except what you want.": "Прилипает ко всему, кроме того, что нужно.",
    "Cleans everything except your conscience.": "Отмывает всё, кроме вашей совести.",
    "Smells like progress. Don't ask how it tastes.": "Пахнет прогрессом. Не спрашивайте, каков он на вкус.",
    "Dissolves bonds. Molecular and emotional.": "Растворяет связи. Молекулярные и эмоциональные.",
    "Apply, ignite, stand back. Way back.": "Нанеси, подожги, отойди. Подальше.",
    "Handle with care. Or don't. Natural selection.": "Обращаться осторожно. Или нет. Естественный отбор.",
    "Could be a shirt. Could be a bandage. Probably both.": "Может быть рубашкой. Может, бинтом. Скорее всего, и тем, и другим.",
    "Optimizes the numeric performance of mods.": "Оптимизирует числовые показатели модов.",
    "Filtered air for about a week. Now it's decoration.": "Фильтровал воздух около недели. Теперь это просто декор.",
    "Thread count: don't ask.": "Количество нитей: не спрашивайте.",
    "One boot. Size unknown. Dreams of being a pair.": "Один ботинок. Размер неизвестен. Мечтает стать парой.",
    "Left hand only. Somewhere out there is a lonely right one.": "Только для левой руки. Где-то там бродит одинокий правый.",
    "Three bullet holes and a coffee stain. Lived a full life.": "Три пулевых отверстия и пятно от кофе. Прожил полноценную жизнь.",
    "Six pockets. Four have holes. Two have secrets.": "Шесть карманов. В четырех дыры. В двух — секреты.",
    "Plates are gone. Carrier's still good. Mostly.": "Пластины исчезли. Основа все еще цела. По большей части.",
    "Peeled off someone's vest. He doesn't need it anymore.": "Сорвано с чьего-то жилета. Ему оно больше не нужно.",
    "Corrupts an item. Unpredictable outcomes. Locks item.": "Повреждает предмет. Непредсказуемые последствия. Блокирует предмет.",
    "Fabric that stops bullets. Doesn't stop bad decisions.": "Ткань, которая останавливает пули. Но не плохие решения.",
    "Type-C. No wait, micro. Actually, who knows anymore.": "Type-C. Нет, подождите, micro. Да кто их теперь разберет.",
    "Once lit up someone's gaming setup. RGB dreams, dead.": "Когда-то подсвечивала чью-то игровую зону. RGB-мечты мертвы.",
    "Missing the W, A, S, and D keys. Gamer confirmed.": "Отсутствуют клавиши W, A, S и D. Геймер подтвержден.",
    "8 gigs of memories. None of them yours.": "8 гигабайт воспоминаний. И ни одно не ваше.",
    "Smells like ambition and burnt silicon.": "Пахнет амбициями и горелым кремнием.",
    "50 terabytes. Contents unknown. Probably memes.": "50 терабайт. Содержимое неизвестно. Скорее всего, мемы.",
    "Picks up frequencies that shouldn't exist.": "Улавливает частоты, которых не должно существовать.",
    "4K resolution. Last footage: someone running.": "Разрешение 4K. Последняя запись: кто-то бежит.",
    "Removes all properties, reverting item to [Standard].": "Удаляет все свойства, возвращая предмет к состоянию [Standard].",
    "Still projects, but only static and sadness.": "Все еще проецирует, но только статику и печаль.",
    "256-bit encryption. The password is probably 'admin'.": "256-битное шифрование. Пароль, скорее всего, 'admin'.",
    "A family. Smiling. From before.": "Семья. Улыбаются. Из прошлого.",
    "Reads: 'If you find this, I'm already gone.'": "Там написано: «Если вы это нашли, меня уже нет».",
    "Photo doesn't match anyone alive.": "Фотография не совпадает ни с кем из живых.",
    "Redacted so heavily it's basically abstract art.": "Замазано так сильно, что это практически абстрактное искусство.",
