    // ==== JS_UI parça 7: kullanıcı 3. tur (modaller, filtre, tipler, hint parçaları, daily) ====
    "Starting a new game will delete your existing save data. This cannot be undone.": "开始新游戏将删除你现有的存档数据。此操作无法撤销。",
    "Enter Name...": "输入名字……",
    "Enter Name": "输入名字",
    "TECH TABLE": "科技工作台",
    "Bad (unprotected)": "劣质（未保护）",
    "On killed: heal → equip best gear from stash → redeploy. If stash empty: scav gear + Silent Expanse CL0.": "死亡时：治疗 → 从仓库装备最好的装备 → 重新部署。仓库为空时：拾荒者装备 + 寂静旷野 CL0。",
    "After stamina runs low, sprint resumes once it refills to this level. Lower = sprint kicks back in sooner, in shorter bursts; sprint always pauses below 20%": "耐力耗尽后，恢复到此水平时继续冲刺。数值越低 = 冲刺恢复越快、节奏越碎；耐力低于 20% 时冲刺始终暂停",
    "Which weapon a raid starts with. Empty slot falls back to primary, secondary, melee. Q still switches mid raid": "RAID 开始时使用的武器。槽位为空时按主武器、副武器、近战顺延。RAID 中仍可用 Q 切换",
    "MATERIAL": "材料",
    "CHEMICAL": "化学品",
    "MEDKIT": "急救包",
    "ELECTRONICS": "电子产品",
    "COMPONENT": "部件",
    "VALUABLE": "贵重品",
    "DOCUMENT": "文件",
    "TOOL": "工具",
    "AMMO": "弹药",
    "ARTIFACT": "造物",
    "CONSUMABLE": "消耗品",
    "IFAK": "单兵急救包",
    "AFAK": "高级急救包",
    "MFAK": "多人急救包",
    "HLM": "头盔",
    "ACC": "配件",
    "MED": "医疗",
    "OPT": "光学",
    "GPU": "显卡",
    "Primary": "主武器",
    "Secondary": "副武器",
    "Melee": "近战",
    "Enhanced": "强化",
    "Enhanced+": "强化+",
    "Custom": "定制",
    "Custom+": "定制+",
    "Glitch+": "GLITCH+",
    "Prototype+": "PROTOTYPE+",
    "and click items to quickly equip or unequip gear.": "并点击物品即可快速穿脱装备。",
    "and drag over items in your stash to quickly add them to the sell queue.": "并在仓库物品上拖动，快速将它们加入出售队列。",
    "in the terminal to sell BTC for cash ($70K each).": "在终端中出售 BTC 换取现金（每枚 $70K）。",
    ". Guarantees specific mods on your gear.": "。保证在装备上获得指定模组。",
    "Trader stock refreshes every": "商人库存刷新周期：每",
    ". Check back after leveling up for new inventory.": "。升级后回来看看新货。",
    "trades in FLUX currency. Stock refreshes every 2h. Items here can't be bargained.": "以通量交易。库存每 2 小时刷新。这里的物品不能议价。",
    "breaks down gear into tech currencies. Higher tier items yield rarer materials.": "将装备分解为科技货币。品阶越高的物品产出越稀有的材料。",
    "unlocked! Wardens are powerful bosses with guaranteed loot. Defeat the Warden to unlock the": "已解锁！WARDEN 是拥有保底战利品的强大头目。击败 WARDEN 以解锁",
    "slot and equip from your augment locker.": "槽位，并从义体储物柜中装备。",
    "TIP: Use": "提示：使用",
    "to quickly break down multiple items by rarity filter.": "按稀有度筛选快速分解多件物品。",
    "unlocked! Mastery nodes give permanent bonuses that persist across prestiges.": "已解锁！精通节点提供跨转生保留的永久加成。",
    "tab unlocked! Check": "页已解锁！查看",
    "to spend flux on permanent bonuses.": "以将通量花在永久加成上。",
    "shows detailed item stats, mod breakdown, and comparison with equipped gear.": "显示物品详细属性、模组明细，以及与已装备装备的对比。",
    "Check your": "查看你的",
