    // ==== JS_UI parça 13: mythic/proto affixler, modul metalari, insanity boss/rebirth ====
    "flat damage": "固定伤害",
    "damage": "伤害",
    "armor": "护甲",
    "evasion": "闪避",
    "health": "生命",
    "fire rate": "射速",
    "armor penetration": "护甲穿透",
    "lifesteal on hit": "命中吸血",
    "headshot multiplier": "爆头倍率",
    "magazine capacity": "弹匣容量",
    "damage reduction": "减伤",
    "max HP per second": "每秒最大生命",
    "accuracy": "命中",
    "handling": "操控性",
    "HP Regen": "生命回复",
    "Health regeneration per second": "每秒生命回复",
    "Flat damage reduction": "固定减伤",
    "EYE": "眼部",
    "BRAIN": "大脑",
    "TORSO": "躯干",
    "SKIN": "皮肤",
    "LEG": "腿部",
    "SKELETON": "骨架",
    "INTERNAL": "内脏",
    "SHOULDER": "肩部",
    "COMMON": "普通",
    "RARE": "稀有",
    "EPIC": "史诗",
    "LEGENDARY": "传说",
    "AR": "突击步枪",
    "MYTHIC AFFIXES": "MYTHIC 词条",
    "ABILITIES": "能力",
    "PASSIVE ABILITY": "被动能力",
    "TRIGGERED ABILITY": "触发能力",
    "CONFIRM REBIRTH?": "确认重生？",
    "// MAXED": "// 已满级",
    "MADNESS PROTOCOL is live. Spend your INSANITY: LOADOUT > MASTERY tab.": "疯狂协议已启动。去花你的疯狂值：配装 > 精通页。",
    "Eye lasers vaporize the target at the start of every combat. Your weapon holds fire.": "每场战斗开始时眼部激光汽化目标。你的武器暂不开火。",
    "Fully surround the Flux Capacitor with modules": "用模块完全包围通量电容器",
    "Cannot trigger if you don't have enough Stamina.": "耐力不足时无法触发。",
    "Toss a coin when combat starts.": "战斗开始时抛一枚硬币。",
    "Gain Rage when you hit an enemy.": "命中敌人时获得狂怒。",
    "ranged": "远程",
    "melee": "近战",
    "universal": "通用",
    "dot": "点",
    "domino": "骨牌",
    "square": "方块",
    "ammo": "弹药",
    "barrel": "枪管",
    "cool": "冷却",
    "optic": "光学",
    "pierce": "穿刺",
    "shock": "电击",
    "servo": "伺服",
    "plate": "装甲板",
    "med": "医疗",
    "shield": "护盾",
    "power": "能量",
    "bleed": "流血",
    "edge": "锋刃",
    "flux": "通量",
    "Bleed": "流血",
    "Optic": "光学",
    "Servo": "伺服",
    "Power": "能量",
    "Coolant": "冷却剂",
    "Shock": "电击",
