    // ==== часть 02: усиление безумия / тайник / мастерство ====
    "2× AUTO SPEED": "2× автоскорость",
    "2× DAMAGE": "2× урон",
    "GOLD RUSH": "Золотая лихорадка",
    "2× INSANITY": "2× безумие",
    "AEGIS CACHE": "AEGIS тайник",
    "ARMORY CACHE": "ARMORY тайник",
    "MYTHIC CACHE": "MYTHIC тайник",
    "POWER CACHE": "POWER тайник",
    "PROTO CACHE": "PROTO тайник",
    "SCRAP CACHE": "SCRAP тайник",
    "SEED CACHE": "SEED тайник",
    "BLOOD DEBT": "Кровавый долг",
    "BLOOD TITHE": "Кровавая десятина",
    "CACHE INSTINCT": "Инстинкт тайника",
    "CROWN'S EDGE": "Грань короны",
    "CROWN RESONANCE": "Резонанс короны",
    "DEAD CALM": "Мертвая тишина",
    "DULLED PAIN": "Притупленная боль",
    "FAST HANDS": "Быстрые руки",
    "GHOST STEP": "Призрачный шаг",
    "GOLDEN MADNESS": "Золотое безумие",
    "HOLLOW SHELL": "Пустая оболочка",
    "LUCID NIGHTMARE": "Осознанный кошмар",
    "PLATED HUSK": "Бронированный панцирь",
    "RAGE SIGNAL": "Сигнал ярости",
    "RIGGED COIN": "Подтасованная монета",
    "SIN FRENZY": "Греховное безумие",
    "SIN SIPHON": "Сифон грехов",
    "THICK SKIN": "Толстая кожа",
    "TRIGGER DISCIPLINE": "Дисциплина спуска",
    "VOID BARGAIN": "Сделка с Пустотой",
    "WARDEN'S BANE": "Бич WARDEN",
    "SERVO TUNING": "Настройка сервопривода",
    "DEAD EYE": "Меткий глаз",
    "NEURAL SPIKE": "Нейронный шип",
    "SIN HARVESTER": "Жнец грехов",
