    // ==== chunk 01: augment quest adları ====
    "Optic Calibration": "光学校准",
    "Neural Sync": "神经同步",
    "Hive Frequency": "蜂巢频率",
    "Adaptive Skin": "自适应皮肤",
    "Reactor Integration": "反应堆整合",
    "Nanite Infusion": "纳米注入",
    "Shock Dampening": "冲击缓冲",
    "Carbon Reinforcement": "碳素强化",
    "Fusion Core": "聚变核心",
    "Plasma Armament": "等离子武装",
    "Quantum Sight": "量子视觉",
    "Predictive Override": "预测超控",
    "Dermal Graft": "真皮移植",
    "Regenerative Protocol": "再生协议",
    "Void Integration": "虚空整合",
    "Precision Engineering": "精密工程",
    "Phase Walk": "相位行走",
    "Adamantine Spine": "精金脊柱",
    "Bio-Filtration": "生物过滤",
    "Orbital Link": "轨道链接",
    "Core Implant": "核心植入体",
    "Arm Augmentation": "手臂义体化",
    "Leg Enhancement": "腿部强化",
    "Frame Reconstruction": "骨架重构",
    "Organ Replacement": "器官置换",
    "Mount Installation": "挂载安装",
    "Thermal Recalibration": "热能再校准",
