    // ==== JS_UI parça 5: cümleler (glitch sonuçları, mythic yetenekler, filtre açıklamaları, ending) ====
    "Some mods were deleted": "部分模组已被删除",
    "Nothing happened, but the item is locked": "什么都没发生，但物品被锁定了",
    "All mods rerolled with bad values": "所有模组以糟糕的数值重掷",
    "All positive stats x6, blocks manual repair": "所有正面属性 x6，禁止手动修理",
    "25% chance to infuse weapon with random element.": "25% 概率为武器注入随机元素。",
    "Corrupts an item. Unpredictable outcomes. Locks.": "侵蚀一件物品。结果不可预测。锁定。",
    "Removes all properties, reverting to [Standard].": "移除所有属性，还原为 [Standard]。",
    "Any hit instantly kills non-boss enemies below 20% HP": "任意攻击立即处决生命低于 20% 的非头目敌人",
    "Attack speed +8%/sec the longer combat lasts (no cap)": "战斗持续越久攻速越快，每秒 +8%（无上限）",
    "Combat start: 2s untouchable while dealing damage": "战斗开始：2 秒无敌并持续输出",
    "Combat start: 3s stun + heal suppress + armor shred (boss: no stun)": "战斗开始：3 秒眩晕 + 治疗压制 + 破甲（头目：无眩晕）",
    "Combat start: after 2s, 25% max HP explosion (boss 8%)": "战斗开始：2 秒后引爆敌人最大生命 25%（头目 8%）",
    "Combat start: armor-ignoring massive flat shot (boss included)": "战斗开始：无视护甲的巨额固定伤害（含头目）",
    "Combat start: black hole pulls enemy in + 5s stun (boss: pull only)": "战斗开始：黑洞牵引敌人 + 5 秒眩晕（头目：仅牵引）",
    "Combat start: enemy takes % max HP as DoT over 3s (boss halved)": "战斗开始：敌人在 3 秒内受到最大生命百分比持续伤害（头目减半）",
    "Combat start: enemy takes +40% damage all fight (boss +15%)": "战斗开始：敌人整场受到 +40% 伤害（头目 +15%）",
    "Combat start: freeze 4s, +50% damage taken while frozen (boss 1.5s)": "战斗开始：冰冻 4 秒，冰冻期间受伤 +50%（头目 1.5 秒）",
    "Combat start: nanobot drone chips enemy HP all fight": "战斗开始：纳米无人机整场削减敌人生命",
    "Combat start: phantom clone mirrors your damage": "战斗开始：幻影分身复制你的伤害",
    "Combat start: roll a random powerful buff": "战斗开始：随机获得一个强力增益",
    "Combat start: sky lightning deals a headshot-power weapon strike (boss included)": "战斗开始：天雷造成一次爆头级武器打击（含头目）",
    "Each kill this raid stacks permanent +damage": "本场 RAID 每次击杀永久叠加伤害",
    "Every 4th hit is a guaranteed headshot at +100% power": "每第 4 次攻击必定爆头且威力 +100%",
    "Every kill drops guaranteed bonus flux/currency": "每次击杀必定掉落额外 FLUX/货币",
    "Instantly teleport to extraction with all loot": "带着全部战利品瞬移到撤离点",
    "Once per raid: revive at 50% HP on lethal damage": "每场 RAID 一次：受到致命伤害时以 50% 生命复活",
    "Reveal all enemies + foresee every drop: rarity tags on POIs & enemies": "显示所有敌人 + 预见所有掉落：POI 和敌人带稀有度标签",
    "Scan + teleport to enemies, kill, then POIs": "扫描并瞬移到敌人，击杀后再瞬移到 POI",
    "POI searches resolve instantly: all loot drops the moment you start searching": "POI 搜索立即完成：开始搜索的瞬间掉落全部战利品",
    "~2% per hit to disintegrate the enemy (boss included)": "每次攻击约 2% 概率湮灭敌人（含头目）",
    "+0.5 HS mult. Each adjacent module: +0.12 more": "+0.5 爆头倍率。每个相邻模块：额外 +0.12",
    "+25 damage. Each adjacent module: +25 more": "+25 伤害。每个相邻模块：额外 +25",
    "+30 damage for EACH module touching it (surround it!)": "每有一个模块与它相邻 +30 伤害（把它围起来！）",
    "-30% heat. Each adjacent module: -15% more": "-30% 过热。每个相邻模块：额外 -15%",
    "Boosts adjacent +10%. If fully surrounded by modules, UNLOCKS a bonus weapon ability": "相邻模块 +10%。若被模块完全包围，解锁一个额外武器能力",
    "Barrel + Power → infuse FIRE (Burning) element": "枪管 + 能量 → 注入火焰（燃烧）元素",
    "Coolant + Optic → infuse COLD (Frozen) element": "冷却剂 + 光学 → 注入寒冷（冰冻）元素",
    "Coolant + Shock → unlocks an ABILITY SLOT": "冷却剂 + 电击 → 解锁一个能力槽",
    "Shock + Servo → infuse LIGHTNING (Electrified) element": "电击 + 伺服 → 注入闪电（触电）元素",
    "Drops: CL7+ Wardens, P9+ bosses, Ironfall CL10": "掉落来源：CL7+ WARDEN、P9+ 头目、铁陨防线 CL10",
    "Auto-complete lockpick/hacking (10s wait, -15% loot)": "自动完成撬锁/骇入（等待 10 秒，战利品 -15%）",
    "Automatically start next raid after extraction": "撤离后自动开始下一场 RAID",
    "Center-screen notification + sound when Warden progress hits 12/12": "WARDEN 进度达到 12/12 时屏幕中央通知 + 音效",
    "In the filter panel: AUTOMATION section, tick the Auto Deploy checkbox.": "在筛选面板的自动化区域勾选自动部署。",
    "ON: salvaged up to Max Rarity. OFF: never salvaged": "开：拆解至最高稀有度为止。关：从不拆解",
    "ON: sold up to Max Rarity. OFF: never sold": "开：出售至最高稀有度为止。关：从不出售",
    "On raid start: auto-target the extraction POI and walk straight there": "RAID 开始时：自动锁定撤离 POI 并径直前往",
    "Protected items are never auto-sold or salvaged, no matter what": "受保护的物品在任何情况下都不会被自动出售或拆解",
    "Protects good base tiers (T1 is best). Manual, trader and bulk selling unaffected": "保护优质基础品阶（T1 最佳）。手动、商人和批量出售不受影响",
    "Protects this rarity and higher. Loot pickup (LOOT FILTERS above) unaffected": "保护此稀有度及以上。战利品拾取（上方的战利品筛选）不受影响",
    "Rolls random gear (Standard / Enhanced / Custom)": "掷出随机装备（Standard / Enhanced / Custom）",
    "Salvage gear into tech materials after each raid (uses the same Max Rarity)": "每次 RAID 后将装备拆解为科技材料（使用同一最高稀有度设置）",
    "Skip locked/hacked caches entirely (no wait, loot forfeited)": "完全跳过上锁/需骇入的补给箱（不等待，放弃战利品）",
    "Stop automation after 3 consecutive deaths": "连续死亡 3 次后停止自动化",
    "Total amount of loot you can carry in a raid.": "你在一场 RAID 中能携带的战利品总量。",
    "Total damage of your accurate shots.": "你命中射击的总伤害。",
    "Reduces damage received from enemies.": "减少从敌人处受到的伤害。",
    "Shortens the combat turn duration, allowing you to attack more frequently.": "缩短战斗回合时长，让你更频繁地攻击。",
    "Gives a chance to dodge enemy attacks. (Will be active in future builds)": "提供闪避敌人攻击的概率。（将在未来版本中生效）",
    "Increases loot efficiency and quality. (Will be active in future builds)": "提升战利品效率与品质。（将在未来版本中生效）",
    "Insanity level. (Will be active in future builds)": "疯狂等级。（将在未来版本中生效）",
    "Reduces the chance of being detected during a raid. (Will be active in future builds)": "降低 RAID 中被发现的概率。（将在未来版本中生效）",
    "Activates a flappy-style escape route minigame. Dodge the barriers without crashing for a": "启动一个 flappy 风格的逃脱小游戏。躲开障碍别撞上，即可获得",
    "chance to flee from combat": "逃离战斗的机会",
    "Permanent upgrades bought with insanity.": "用疯狂值购买的永久升级。",
    "Complete your first REBIRTH in the INSANITY terminal to attune.": "在 INSANITY 终端完成你的首次重生以调谐。",
    "Defeat a Warden or complete an INSANITY minigame REBIRTH to unlock": "击败一个 WARDEN 或完成一次 INSANITY 小游戏重生以解锁",
    "No corruption modifiers active. Select a higher level for increased challenge & rewards.": "没有生效的侵蚀词条。选择更高等级以获得更高挑战与奖励。",
    "Obtain augments through quests and boss drops": "通过任务和头目掉落获取义体",
    "Click a slot to view details and upgrade options": "点击槽位查看详情和升级选项",
    "Visit Ripperdoc to initiate the Evolution Protocol.": "拜访 RIPPERDOC 以启动进化协议。",
    "Configure your mining rigs to passively generate": "配置你的矿机以被动产出",
    "Insured items are prioritized when re-equipping.": "重新装备时优先使用已投保物品。",
    "MYTHIC gear will be destroyed permanently!": "MYTHIC 装备将被永久摧毁！",
    "Jumps to any screen. Drag the header to move it, dash to shrink. Hidden during raids.": "一键跳转到任意界面。拖动标题栏移动，点击横杠收起。RAID 中自动隐藏。",
    "LOADOUT stash sidebar: click the padlock button, then click the items you want to protect.": "配装仓库侧栏：点击挂锁按钮，再点击你想保护的物品。",
    "Bulk sell at any trader: LOCK the few pieces you actually use first.": "在任意商人处批量出售：先锁定你真正在用的那几件。",
    "Hold the RIPPERDOC title bar (or my face) with left click and drag.": "左键按住 RIPPERDOC 标题栏（或我的脸）拖动。",
    "TECH terminal: click the command line, type use root and press Enter.": "科技终端：点击命令行，输入 use root 并按回车。",
    "HUB screen: the INSANITY entry (hotkey 2).": "基地界面：INSANITY 入口（快捷键 2）。",
    "HUB: SKILLS. Pick a starting class node first.": "基地：技能。先选择一个起始职业节点。",
    "INSANITY terminal: the CACHES panel on the right side.": "INSANITY 终端：右侧的补给箱面板。",
    "All of it lives in the TECH terminal. Type HELP there when you are curious.": "这一切都在科技终端里。好奇的话在那里输入 HELP。",
    "Go. Make money. Come back when something hurts.": "去吧。赚钱。哪里疼了再回来。",
    "Deploying without offensive capabilities significantly reduces survival chance.": "在没有攻击手段的情况下部署会显著降低生存概率。",
    "Your HP is critically low. Deploying in this condition is extremely risky.": "你的生命值极低。在这种状态下部署极其危险。",
    "Healing...": "治疗中……",
    "System Ready": "系统就绪",
    "Rest well, operator.": "好好休息，干员。",
    "There is no going back.": "没有回头路了。",
    "The clinic is silent. The man who built you, piece by piece, is gone.": "诊所一片寂静。那个把你一块一块拼起来的男人，已经不在了。",
    "I just hope you remember what you paid for it.": "我只希望你记得自己为此付出了什么。",
    "Hey. It's me, the developer.": "嘿。是我，开发者。",
    "This was my first game. I built it alone, learning as I went,": "这是我的第一款游戏。我独自打造了它，边做边学，",
    "Thank you. Not just for playing, but for caring enough to reach this moment.": "谢谢你。不只是因为你玩了这款游戏，更因为你在乎它，一路走到了这一刻。",
    "UNHUMAN keeps evolving. Be part of what comes next.": "UNHUMAN 仍在进化。来见证接下来的一切。",
    "has decided to follow you.": "决定跟随你了。",
    "stray dog": "流浪狗",
    "VERY LOW": "极低",
    "MID LOW": "中低",
    "MID": "中等",
    "VERY HIGH": "极高",
    "EXTREME": "极端",
    "LOW": "低",
    "HIGH": "高",
    "MODERATE": "中等",
    "HIGH RISK": "高风险",
