    // ==== parça 25: tam kapsamlı süpürme (bildirimler + combat floatlar) ====
    "Diamond": "钻石",
    "Durability": "耐久",
    "Extract Point": "撤离点",
    "Juvenile": "少年期",
    "primary": "主武器",
    "secondary": "副武器",
    "+1 Skill Point acquired.": "获得 +1 技能点。",
    "2x raid speed active.": "2x 突袭速度已激活。",
    "All drops foreseen.": "所有掉落皆在预见之中。",
    "Free stash space first": "请先腾出仓库空间",
    "Free stash space first.": "请先腾出仓库空间。",
    "Free stash space to complete the deal": "腾出仓库空间以完成交易",
    "INSUFFICIENT FUNDS": "资金不足",
    "Instant teleport to extract ready.": "即时传送至撤离点已就绪。",
    "Item move cancelled": "物品移动已取消",
    "Mining stopped. Out of fuel.": "挖矿已停止。燃料耗尽。",
    "Mythic items are priceless, no trader will touch them.": "MYTHIC 物品无价，没有商人敢收。",
    "Restock costs $10,000": "补货费用 $10,000",
    "Saving is disabled during a raid": "突袭期间无法保存",
    "Signal Harvest (Loadout > Mastery)": "信号收割（配装 > 精通）",
    "Teleport-hunting online.": "传送狩猎已上线。",
    "The flip stands but there is no space": "结果有效，但没有空间了",
    "The flip stands but you cannot pay": "结果有效，但你付不起",
    "The trader accepted but you cannot pay": "商人接受了，但你付不起",
    "This item already owns every ability it can hold.": "这件物品已拥有它能持有的全部能力。",
    "This item cannot be salvaged": "这件物品无法拆解",
    "This item cannot be sold": "这件物品无法出售",
    "Unlock it first to sell or salvage": "先解锁才能出售或拆解",
    "Unlock this item to sell it.": "解锁后才能出售。",
    "Visit Ripperdoc in the TRADERS tab to initiate the Evolution Protocol.": "前往商人页的 RIPPERDOC 启动进化协议。",
    "You do not own that module.": "你没有那个模块。",
    "Your companion is not for sale.": "你的伙伴是非卖品。",
    "Save data is getting large. Claim pending GUNSMITH QUESTS items and free stash space.": "存档数据偏大。请领取 GUNSMITH 任务页暂存的物品并腾出仓库空间。",
    "\"CRIMSON GAZE\" added to your augment locker.\nHe kept it for you. Just in case.": "\"CRIMSON GAZE\"已放入你的义体储物柜。他一直替你留着。以防万一。",
    "All class keystones are now available.": "所有职业基石现已可用。",
    "All slots full. Free a slot first": "所有槽位已满。请先腾出一个",
    "Automation stopped after 3 consecutive deaths.": "连续死亡 3 次后自动化已停止。",
    "Check your gear and filters before continuing.": "请检查装备与筛选后再继续。",
    "Close this tab to exit": "关闭此标签页以退出",
    "Complete your raid first, then visit the Ripperdoc in the TRADERS tab.": "先完成当前突袭，再前往商人页拜访 RIPPERDOC。",
    "ESCAPE FAILED": "逃脱失败",
    "I see you.": "我看见你了。",
    "If stash is empty: Scav gear + Silent Expanse CL0": "若仓库为空：拾荒装备 + Silent Expanse CL0",
    "Loading save...": "正在载入存档...",
    "No materials recovered.": "未回收任何材料。",
    "On death: Auto-heal → Equip best gear from stash → Redeploy": "死亡时：自动治疗 → 从仓库装备最佳装备 → 重新部署",
    "Route collapsed": "路线坍塌",
    "Skill Point Drive now available at Ripperdoc.": "技能点驱动器现已在 RIPPERDOC 处有售。",
    "Slot data not found": "未找到栏位数据",
    "Something was left behind for you. Return to the hideout later.": "有东西留给了你。稍后回藏身处看看。",
    "Storage error while loading. Free stash space and try again.": "载入时存储出错。请腾出仓库空间后重试。",
    "Storage is full. Delete a save slot and try again.": "存储已满。请删除一个存档栏位后重试。",
    "Storage is full. Delete a save slot to free space.": "存储已满。请删除一个存档栏位以腾出空间。",
    "The rest is up to you, Operator.": "剩下的路要你自己走了，操作员。",
    "◆ MYTHIC CACHE": "◆ 神话补给箱",
    "RICOCHET!": "跳弹！",
    "__patterns": [
        ["^(-?\\d+) HEADSHOT! x2!$", "$1 爆头！x2！"],
        ["^(-?\\d+) HEADSHOT!$", "$1 爆头！"],
        ["^(-?\\d+) (L\\.ARM|R\\.ARM|L\\.LEG|R\\.LEG|BODY|HEAD|THORAX|STOMACH) EXHAUSTION!$", "$1 $2 力竭！", "T"],
        ["^(-?\\d+) (L\\.ARM|R\\.ARM|L\\.LEG|R\\.LEG|BODY)$", "$1 $2", "T"],
        ["^No (.+) weapon equipped, using (.+)$", "未装备$1，改用$2", "T"],
        ["^\\+(\\d+) ECHO POINTS?$", "+$1 回声点数"],
        ["^(.+) cannot fit this item type\\.$", "$1 无法收购这类物品。"],
        ["^(.+) has no key now$", "$1 已无钥匙"],
        ["^(.+) is used in raids or the workbench$", "$1 在突袭或工作台中会用到"],
        ["^(\\d+) item\\(s\\) held, go to GUNSMITH QUESTS to claim$", "$1 件物品被暂存，前往 GUNSMITH 任务页领取"],
        ["^(.+) returned to stash\\.$", "$1 已放回仓库。"],
        ["^Auto-refuel needs \\$([\\d.,]+)$", "自动加油需要 $$$1"],
        ["^Current filters saved to slot (\\d+)$", "当前筛选已保存到栏位 $1"],
        ["^Filter preset (\\d+) applied$", "已应用筛选预设 $1"],
        ["^Found: (.+)$", "发现：$1"],
        ["^Insurance costs \\$([\\d.,]+)$", "保险费用 $$$1"],
        ["^Level (\\d+) \\+(\\d+) Skill Points?$", "等级 $1，+$2 技能点"],
        ["^Need \\$([\\d.,]+) · ([\\d.,]+) flux · ([\\d.,]+) insanity$", "需要 $$$1 · $2 通量 · $3 疯狂"],
        ["^Need \\$([\\d.,]+)$", "需要 $$$1"],
        ["^Prestige points follow main progression here \\(P(\\d+) = (\\d+) points\\)\\. Your mastery was reset for free, re-allocate anytime\\.$", "转生点数现与主线进度同步（P$1 = $2 点）。你的精通已免费重置，可随时重新分配。"],
        ["^Saved to slot (.+)$", "已保存到栏位 $1"],
        ["^(.+) transferred\\. Keep moving\\.$", "$1 已转移。继续前进。"],
        ["^(\\d+) item\\(s\\) lost: stash full$", "$1 件物品丢失：仓库已满"],
        ["^(\\d+) slots? equipped$", "$1 个槽位已装备"],
        ["^Fight Warden CL(\\d+) ready \\((\\d+)/(\\d+) available\\)$", "可挑战 WARDEN CL$1（$2/$3 可用）"],
        ["^Insufficient funds for healing\\. Need \\$([\\d.,]+) to recover\\.$", "治疗资金不足。恢复需要 $$$1。"],
        ["^SALVAGED (.+)$", "已拆解 $1"],
        ["^CL(\\d+) UNLOCKED!$", "CL$1 已解锁！"],
        ["^(PAINKILLER|SECOND WIND) \\+(\\d+) HP$", "$1 +$2 生命", "T"],
        ["^SWITCHED: (.+)$", "已切换：$1", "T"],
        ["^BURST (\\d+)$", "爆发 $1"],
        ["^CLONE (\\d+)$", "克隆 $1"],
        ["^DBL \\+(\\d+)$", "双倍 +$1"],
        ["^DEFLECT (\\d+)$", "偏转 $1"],
        ["^MELTDOWN (\\d+)$", "熔毁 $1"],
        ["^ORBITAL (\\d+)$", "轨道打击 $1"],
        ["^QUANTUM (\\d+)$", "量子 $1"],
        ["^REFLECT (\\d+)$", "反射 $1"],
        ["^STRIKE \\+(\\d+)$", "打击 +$1"],
        ["^TAP \\+(\\d+)$", "点击 +$1"],
        ["^AUTO-CLICKER ([IVX]+)$", "自动点击器 $1"],
        ["^(-?\\d+) (HEAD|THORAX|STOMACH|LEFT ARM|RIGHT ARM|LEFT LEG|RIGHT LEG|FULL BODY) EXHAUSTION!$", "$1 $2 力竭！", "T"],
        ["^(-?\\d+) (HEAD|THORAX|STOMACH|LEFT ARM|RIGHT ARM|LEFT LEG|RIGHT LEG|FULL BODY)$", "$1 $2", "T"],
        ["^ROCKET (\\d+)$", "火箭 $1"],
        ["^SLAM (\\d+)$", "猛击 $1"],
        ["^ORB (\\d+)$", "能量球 $1"],
        ["^(\\d+) weapon\\(s\\)$", "$1 件武器"],
        ["^> ESCAPE_ROUTE: (\\d+)/(\\d+)$", "> 逃生路线：$1/$2"],
        ["^(.+): (.+) \\((\\d+:\\d+)\\)$", "$1：$2（$3）", "T"],
        ["^(.+): (.+) ×(\\d+)$", "$1：$2 ×$3", "T"],
        ["^FRENZY (\\d+)/(\\d+): \\+(\\d+)% DMG per kill$", "狂热 $1/$2：每击杀 +$3% 伤害"],
        ["^IRON (\\d+)/(\\d+): \\+(\\d+) AC per hit taken$", "铁壁 $1/$2：每受击 +$3 护甲"],
        ["^NANO (\\d+)/(\\d+): \\+(\\d+) AC \\(adaptive armor\\)$", "纳米 $1/$2：+$3 护甲（自适应装甲）"],
        ["^RAGE (\\d+)/(\\d+): \\+(\\d+)% DMG$", "狂怒 $1/$2：+$3% 伤害"],
        ["^CHAIN (\\d+)/(\\d+): \\+(\\d+)% melee DMG$", "连击 $1/$2：+$3% 近战伤害"],
        ["^CHAIN (\\d+)/(\\d+): \\+(\\d+)% ranged DMG$", "连击 $1/$2：+$3% 远程伤害"],
        ["^SURGE (\\d+)/(\\d+): bonus DMG shots$", "涌流 $1/$2：额外伤害射击"],
        ["^COIN: (.+), match type \\+50% DMG$", "硬币：$1，对应类型 +50% 伤害"],
        ["^BET: (.+), \\+30% attack speed$", "赌注：$1，+30% 攻击速度"],
        ["^BET: (.+), \\+30% damage reduction$", "赌注：$1，+30% 减伤"],
        ["^OVERLOAD (\\d+)/(\\d+): max stacks → all elements$", "过载 $1/$2：满层 → 全元素"],
        ["^Raid damage \\+(\\d+)% \\(permanent\\)\\. Every 10 rebirths adds \\+(\\d+)%\\. Crown complete\\.$", "RAID 伤害 +$1%（永久）。每 10 次重生 +$2%。王冠已集满。"],
        ["^Raid damage \\+(\\d+)% \\(permanent\\)\\. Every 10 rebirths adds \\+(\\d+)%, up to \\+100%\\.$", "RAID 伤害 +$1%（永久）。每 10 次重生 +$2%，上限 +100%。"],
        ["^EVOLUTION COMPLETE · PRESTIGE (\\d+)$", "进化完成 · 转生 $1"],
        ["^\\+([A-Z].{2,})$", "+$1", "T"],
        ["^(\\d+)% \\(cap\\) ×([\\d.]+)$", "$1%（上限）×$2"],
        ["^-(\\d+)% map below level$", "-$1%（地图低于你的等级）"],
        ["^FOUND: (.+)$", "发现：$1"],
        ["^SCOUTED: (.+)$", "侦察到：$1"],
        ["^(.+) FOUND (\\d+) ITEMS$", "$1 找到了 $2 件物品"],
        ["^TURRET (\\d+)$", "炮塔 $1"],
        ["^Auto-fires (\\d+)x at (\\d+)% player DMG every ([\\d.]+)s\\.$", "每 $3 秒自动开火 $1 次，每发造成玩家伤害的 $2%。"],
        ["^Install: ([\\d.]+) clicks/sec$", "安装：每秒 $1 次点击"],
        ["^([\\d.]+) clicks/sec \\(MAX\\)$", "每秒 $1 次点击（最大）"],
        ["^([\\d.]+) → ([\\d.]+) clicks/sec$", "每秒点击 $1 → $2"],
        ["^([\\d.,K]+%) → ([\\d.,K]+%) raid damage$", "RAID 伤害 $1 → $2"],
        ["^([\\d.]+)% HP/sec$", "每秒 $1% 生命"],
        ["^([\\d.]+)% \\(full\\)$", "$1%（已满）"],
        ["^HOLLOW CROWN ([IVX]+): \\+(\\d+)% raid damage \\(MAX\\)$", "HOLLOW CROWN $1：+$2% RAID 伤害（最大）"],
        ["^HOLLOW CROWN ([IVX]+): \\+(\\d+)% raid damage · next \\+(\\d+)% at rebirth (\\d+)$", "HOLLOW CROWN $1：+$2% RAID 伤害 · 下一档 +$3% 于第 $4 次重生"],
        ["^> (\\d+) EP per first-time CL clear \\(warden kill\\) on each map · (\\d+) nodes, tree costs more than the max (\\d+) EP pool$", "> 每张地图每个 CL 首次通关（击杀 WARDEN）获得 $1 EP · 共 $2 个节点，全树花费超过 EP 上限 $3 点"],
        ["^> Permanent upgrades bought with INSANITY · rank cost grows ×([\\d.]+) · earned in the INSANITY terminal$", "> 用疯狂购买的永久升级 · 每级花费 ×$1 递增 · 疯狂在疯狂终端获取"],
        ["^Cost: ([\\d.,]+) Flux$", "花费：$1 通量"],
        ["^RESET MASTERY · ([\\d.,]+) FLUX$", "重置精通 · $1 通量"],
        ["^RESPEC · ([\\d.,]+) FLUX$", "重置加点 · $1 通量"],
        ["^ALLOCATE · ([\\d.,]+) EP$", "分配 · $1 EP"],
        ["^ALLOCATE · ([\\d.,]+) INS$", "分配 · $1 疯狂"],
        ["^COMBO x(\\d+)$", "连击 x$1"],
        ["^FLUX: ([\\d.,]+)$", "通量：$1"],
        ["^INSANITY: ([\\d.,]+)$", "疯狂：$1"],
        ["^ECHO POINTS: (\\d+)/(\\d+)$", "回声点数：$1/$2"],
        ["^✓ (.+)$", "✓ $1", "T"],
        ["^\\((module|combo|grid|core)\\)$", "（$1）", "T"],
        ["^([A-Z]+) SLOT$", "$1插槽", "T"],
        ["^Holds: (.+) \\(unlocks with the condition\\)$", "持有：$1（达成条件后解锁）", "T"],
        ["^Holds: (.+)$", "持有：$1", "T"],
        ["^GRID BONUS: (.+)$", "网格加成：$1", "T"],
        ["^GRID: (.+)$", "网格：$1", "T"],
        ["^\\+(\\d+) rows$", "+$1 行"],
        ["^Expand stash \\(\\+(\\d+) rows\\) \\[Lv(\\d+)/(\\d+)\\]$", "扩充仓库（+$1 行）[Lv$2/$3]"],
        ["^BOOST PROTO \\+([\\d.]+)% \\$([\\d.,]+)$", "PROTO 强化 +$1% $$$2"],
        ["^GAMBLE \\$([\\d.,]+)$", "豪赌 $$$1"],
        ["^([\\d,.]+) FLX$", "$1 通量"],
        ["^([\\d,.]+) INS$", "$1 疯狂"],
        ["^(.+): \\$([\\d.,]+) · ([\\d.,]+) FLX · ([\\d.,]+) INS$", "$1：$$$2 · $3 通量 · $4 疯狂", "T"],
        ["^([\\d.,]+) items → \\$([\\d.,]+) from (.+)$", "$1 件物品 → $$$2（来自 $3）"],
        ["^BULK SALVAGE: ([\\d.,]+) items$", "批量拆解：$1 件物品"],
        ["^(\\d+)\\. empty (\\.+)$", "$1. 空 $2"],
        ["^PROTOTYPE SYNC: ([\\d.]+)%$", "PROTOTYPE 同步率：$1%"],
        ["^SYNC: ([\\d.]+)%$", "同步率：$1%"],
        ["^\\[([A-Z]+)\\]$", "[$1]", "T"],
        ["^· (.+) · placing (.+) \\($", "· $1 · 放置 $2（", "T"],
        ["^([A-Za-z][A-Za-z ]+) \\+([\\d.,]+)$", "$1 +$2", "T"],
        ["^LOCKED: REACH LV (\\d+)$", "锁定：需要等级 $1"],
        ["^LAYER (\\d+)$", "第 $1 层"],
        ["^LVL (\\d+)$", "等级 $1"],
        ["^LVL\\.(\\d+)$", "等级 $1"],
        ["^CHECKPOINT: (\\d+)$", "检查点：$1"],
        ["^ENHANCE TO \\+(\\d+)$", "强化到 +$1"],
        ["^TASK (\\d+)/(\\d+)$", "任务 $1/$2"],
        ["^PHASE (\\d+)$", "阶段 $1"],
        ["^SEC: (.+)$", "区域：$1"],
        ["^SECTOR: (.+)$", "区域：$1", "T"],
        ["^ROOT works on STANDARD gear only\\. This item is ([A-Z]+)\\.$", "ROOT 只对 STANDARD 装备有效。这件物品是 $1。"],
        ["^AUTO-I(NSANITY)? OVERCLOCK$", "自动疯狂超频"],
        ["^REWARD: (.+)$", "奖励：$1"],
        ["^WAVE (\\d+)$", "第 $1 波"],
        ["^SLOT (\\d+)$", "槽位 $1"],
        ["^RANK (\\d+)$", "等级 $1"],
        ["^\\+(\\d+) INSANITY$", "+$1 疯狂"],
        ["^(\\d+) KILLS$", "$1 击杀"],
        ["^REBIRTH #(\\d+)$", "重生 #$1"],
        ["^Rebirths: (\\d+)$", "重生次数：$1"],
        ["^REQ: P(\\d+) · CL(\\d+)$", "需求：P$1 · CL$2"],
        ["^COMBO x(\\d+)$", "连击 x$1"],
        ["^HEAL \\((.+)\\)$", "治疗（$1）"],
        ["^LAYER (\\d+) - CLAIMED$", "第 $1 层 - 已领取"],
        ["^OPERATIVE (.+)$", "干员 $1"],
        ["^QUEST COMPLETE: (.+)$", "任务完成：$1", "T"],
        ["^\\+([\\d.]+)(%?) (.+) per point, max \\+([\\d.]+)%$", "每点 +$1$2 $3，上限 +$4%", "T"],
        ["^\\+([\\d.]+)(%?) (.+) per point$", "每点 +$1$2 $3", "T"],
        ["^\\+([\\d.]+)% (.+)$", "+$1% $2", "T"],
        ["^\\+([\\d.]+) (.+)$", "+$1 $2", "T"],
        ["^-([\\d.]+)% (.+)$", "-$1% $2", "T"],
        ["^(.+): (\\d+)/(\\d+)$", "$1：$2/$3", "T"],
        ["^(.+) standing \\+(\\d+)$", "$1 声望 +$2"],
        ["^Kill (\\d+) enemies$", "击杀 $1 名敌人"],
        ["^Kill (\\d+) enemies on (.+)$", "在$2击杀 $1 名敌人", "T"],
        ["^Kill (\\d+) at CL(\\d+)\\+$", "在 CL$2+ 击杀 $1"],
        ["^Extract (\\d+) times$", "撤离 $1 次"],
        ["^Extract from (.+)$", "从$1撤离", "T"],
        ["^Loot items worth \\$(\\d+)$", "拾取价值 $$$1 的物品"],
        ["^Salvage (\\d+) items$", "拆解 $1 件物品"],
        ["^Sell \\$(\\d+) to any trader$", "向任意商人出售 $$$1"],
        ["^Loot a (.+)\\+ item$", "拾取一件 $1+ 物品", "T"],
        ["^Extract with \\$(\\d+)\\+ loot value$", "携带 $$$1+ 战利品价值撤离"],
        ["^(.+) Boss$", "$1头目", "T"],
        ["^ECHO (.+)$", "回响 $1", "T"],
        ["^\\[ (.+) \\]$", "[ $1 ]", "T"],
        ["^(.+): (\\d+) ?/ ?(\\d+)$", "$1：$2/$3", "T"],
        ["^(.+) \\((\\d+)/(\\d+)\\)$", "$1（$2/$3）", "T"],
        ["^(.+) FOUND (\\d+) ITEMS$", "$1 找到了 $2 件物品"],
        ["^(.+) instantly finds (\\d+) items at the start of every raid\\. Mark what to search for[:：]$", "$1 会在每场 RAID 开始时立即找到 $2 件物品。勾选要搜寻的目标："],
        ["^Quicksave (\\d+)/(\\d+) (\\d+):(\\d+)$", "快速存档 $1/$2 $3:$4"],
        ["^This keystone belongs to (.+)$", "这个楔石属于$1", "T"],
        ["^When your HP drops below (\\d+)%,$", "当你的生命低于 $1% 时，"],
        ["^instantly recover (\\d+)% of your Maximum HP\\.$", "立即回复 $1% 最大生命。"],
        ["^recover (\\d+)% of your Maximum HP\\.$", "回复 $1% 最大生命。"],
        ["^While above (\\d+)% HP,$", "当生命高于 $1% 时，"],
        ["^While below (\\d+)% HP,$", "当生命低于 $1% 时，"],
        ["^gain (\\d+)% increased (.+?)\\.?$", "获得 $1% $2加成。", "T"],
        ["^Take (\\d+)% reduced Damage\\.$", "受到的伤害降低 $1%。"],
        ["^\\+(\\d+)% increased (.+) for this combat\\.$", "本场战斗 +$1% $2。", "T"],
        ["^Stacks up to (\\d+)%\\.$", "最多叠加至 $1%。"],
        ["^capped at \\+(\\d+)%\\.$", "上限 +$1%。"],
        ["^\\+(\\d+)% (.+) per (\\d+) (.+),$", "每 $3 $4 +$1% $2，", "T"],
        ["^Gamble effects are (\\d+)% less extreme$", "赌博效果的波动降低 $1%"],
        ["^(\\d+)% increased Damage\\.$", "$1% 额外伤害。"],
        ["^Restore (.+) to full durability\\?$", "将 $1 恢复至满耐久？", "T"],
        ["^Prototypes only \\((\\d+) items?\\)$", "仅 PROTOTYPE（$1 件）"],
        ["^Total: \\$([\\d.,]+)$", "总计：$$$1"],
        ["^room for (\\d+)$", "容纳 $1 发"],
        ["^\\[Stash: (\\d+)\\]$", "[仓库：$1]"],
        ["^Standing Lv\\.(\\d+)$", "声望 Lv.$1"],
        ["^REBIRTHS: (\\d+) · ×(\\d+) DMG & HP$", "重生次数：$1 · ×$2 伤害与生命"],
        ["^Reach layer (\\d+) this cycle \\(now (\\d+)\\)$", "本轮到达第 $1 层（当前 $2）"],
        ["^RESTOCK \\$(\\d+)K$", "补货 $$$1K"],
        ["^UPGRADE \\$(\\d+)K$", "升级 $$$1K"],
        ["^RIG-(\\d+)$", "矿机-$1"],
        ["^(\\S+) (Smartframe|Vanta|Kestrel|Ironclad|RustTek) (.+)$", "$1 $2 $3", "T"],
        ["^(Smartframe|Vanta|Kestrel|Ironclad|RustTek) (\\w+)( T\\d)?$", "$1 $2$3", "T"],
        ["^✦ GOLDEN (.+)$", "✦ 黄金$1", "T"],
        ["^GOLDEN (.+)$", "黄金$1", "T"],
        ["^(Swift|Heavy|Armored|Shielded|Enraged|Fortified) (.+)$", "$1$2", "T"],
        ["^Raid movement speed: \\+(\\d+)% per point, max \\+(\\d+)%$", "RAID 移动速度：每点 +$1%，上限 +$2%"],
        ["^\\+([\\d.]+) (.+) and \\+([\\d.]+) (.+) per point$", "每点 +$1 $2 和 +$3 $4", "T"],
        ["^Deal (\\d+)% increased (.+?)\\.?$", "造成 $1% 额外$2。", "T"],
        ["^to enemies above (\\d+)% HP\\.$", "（对生命高于 $1% 的敌人）"],
        ["^Execute enemies below (\\d+)% HP\\.$", "处决生命低于 $1% 的敌人。"],
        ["^Gain (\\d+) (.+?)\\.$", "获得 $1 点$2。", "T"],
        ["^Your attacks ignore an additional (\\d+)% Armor\\.$", "你的攻击额外无视 $1% 护甲。"],
        ["^grants \\+(\\d+)% (?:increased )?(.+?)\\.?$", "给予 +$1% $2。", "T"],
        ["^grants \\+(\\d+)% (.+), up to (\\d+)%\\.$", "给予 +$1% $2，最多 $3%。", "T"],
        ["^gain (\\d+)% increased (.+?) for (\\d+) seconds?\\.$", "获得 $1% $2加成，持续 $3 秒。", "T"],
        ["^you have a (\\d+)% chance to gain (\\d+)% increased (.+)$", "有 $1% 概率获得 $2% $3加成", "T"],
        ["^and a (\\d+)% chance to gain (\\d+)% (.+)$", "并有 $1% 概率获得 $2% $3", "T"],
        ["^you have a (\\d+)% chance to take (\\d+)% reduced damage$", "有 $1% 概率使受到的伤害降低 $2%"],
        ["^deals (\\d+)% reduced Damage\\.$", "造成的伤害降低 $1%。"],
        ["^If HP falls below (\\d+)% during combat:$", "若战斗中生命低于 $1%："],
        ["^(\\d+)% chance to heal (\\d+)% of max HP\\. Cooldown: (\\d+) Seconds$", "$1% 概率回复 $2% 最大生命。冷却：$3 秒"],
        ["^%(\\d+) chance to (gain|reduce|take) (.+)$", "%$1 概率$2 $3", "T"],
        ["^Each hit grants (\\d+) Overload points?\\.$", "每次命中获得 $1 点过载。"],
        ["^At (\\d+) Overload, your weapon discharges on the enemy,$", "达到 $1 点过载时，你的武器会对敌人放电，"],
        ["^Your first attack deals double damage and stuns for (\\d+) seconds?\\.$", "你的首次攻击造成双倍伤害并眩晕 $1 秒。"],
        ["^The enemy is stunned for (\\d+) seconds? and takes (\\d+)% increased damage\\.$", "敌人被眩晕 $1 秒，并受到 $2% 额外伤害。"],
        ["^Consumes (\\d+) Stamina\\.$", "消耗 $1 点耐力。"],
        ["^Cooldowns?: (\\d+) [Ss]econds?\\.?$", "冷却：$1 秒。"],
        ["^Gamble wins are (\\d+)% stronger\\. Gamble losses are (\\d+)% softer\\.$", "赌博的收益增强 $1%。赌博的损失减轻 $2%。"],
        ["^Enemies deal (\\d+)% increased Damage to you\\.$", "敌人对你造成的伤害提高 $1%。"],
        ["^SEED CACHE ×(\\d+)$", "种子补给箱 ×$1"],
        ["^OPEN AGAIN \\((\\d+)\\)$", "再次打开（$1）"],
        ["^CL(\\d+) (.+)$", "CL$1 $2", "T"],
        ["^EQUIPPED · (.+)$", "已装备 · $1", "T"],
        ["^SALVAGED (.+)$", "已拆解 $1", "T"],
        ["^(\\d+) new objectives?$", "$1 个新目标"],
        ["^iLvl: (\\d+)$", "物品等级：$1"],
        ["^Install: (.+)$", "安装：$1", "T"],
        ["^KERNELS \\[(\\d+)/(\\d+)\\]$", "内核 [$1/$2]"],
        ["^PATCHES \\[(\\d+)/(\\d+)\\]$", "补丁 [$1/$2]"],
        ["^INJECT Q \\((\\d+)/(\\d+)\\)$", "注入队列（$1/$2）"],
        ["^QUEUED (\\d+)/(\\d+)$", "已入列 $1/$2"],
        ["^(\\d+)x (.+)$", "$1x $2", "T"],
        ["^\\+([A-Z][A-Z ]+)$", "+$1", "T"],
        ["^(\\d+) empty \\.+$", "$1 空位 ……"],
        ["^Expected: (.+)$", "预期：$1"],
        ["^element +(\\d+)% chance to infuse with element\\.$", "element  $1% 概率注入元素。"],
        ["^glitch code +-> use 'glitch' to corrupt the selected item$", "glitch 代码   -> 使用 'glitch' 侵蚀所选物品"],
        ["^anchor code +-> use 'anchor <mod_name>' to lock a mod$", "锚定代码      -> 使用 'anchor <模组名>' 锁定模组"],
        ["^kernel codes +-> use 'kernel' \\(Enhanced -> Custom upgrade\\)$", "内核代码      -> 使用 'kernel'（Enhanced -> Custom 升级）"],
        ["^patch codes +-> use 'flash' / 'slot' / etc on Enhanced item$", "补丁代码      -> 对 Enhanced 物品使用 'flash' / 'slot' 等"],
        ["^Example: Queue (\\d+) kernel codes -> use 'kernel' on item -> both apply\\.$", "示例：排入 $1 个内核代码 -> 对物品使用 'kernel' -> 两者都会生效。"],
        ["^═+ TECH CRAFT v(\\d+) COMMANDS ═+$", "═══════════ 科技制作 v$1 命令 ═══════════"],
        ["^║ +TECH TERMINAL v(\\d+) - INITIALIZED +║$", "║         科技终端 v$1 - 已初始化         ║"],
        ["^© (\\d+) UNHUMAN\\. All Rights Reserved\\.$", "© $1 UNHUMAN. 版权所有。"],
        ["^◣ (.+) · LAYER (\\d+) ◢$", "◣ $1 · 第 $2 层 ◢", "T"],
        ["^(.+) ×(\\d+)$", "$1 ×$2", "T"],
        ["^(.+) \\((\\d+)m\\)$", "$1（$2 分钟）", "T"],
        ["^AUTO-CLICKER (I{1,3}|IV|V)$", "自动点击器 $1"],
        ["^AUTO-(I{1,3}|IV|V) OVERCLOCK$", "自动疯狂超频 $1"],
        ["^REBIRTH #(\\d+) · ×([\\d.,]+)$", "重生 #$1 · ×$2"],
        ["^REBIRTHS: (\\d+) · ×([\\d.,]+) DMG & HP$", "重生次数：$1 · ×$2 伤害与生命"],
        ["^Reset to layer (\\d+) · gain ×([\\d.,]+) \\(→ ×([\\d.,]+)\\)$", "重置到第 $1 层 · 获得 ×$2（→ ×$3）"],
        ["^ALLOCATE · (\\d+) INS$", "分配 · $1 疯狂"],
        ["^RESET MASTERY · (\\d+) FLUX$", "重置精通 · $1 通量"],
        ["^RESPEC · (\\d+) FLUX$", "洗点 · $1 通量"],
        ["^Requires: (.+?) (\\d+)$", "需求：$1 $2", "T"],
        ["^(\\d+) FLX$", "$1 通量"],
        ["^FLUX: (\\d+)$", "通量：$1"],
        ["^INSANITY: (\\d+)$", "疯狂：$1"],
        ["^PRESTIGE POINTS: (\\d+)/(\\d+)$", "转生点数：$1/$2"],
        ["^([\\d.,]+)/sec$", "$1/秒"],
        ["^(\\d+) \\(capped\\)$", "$1（已达上限）"],
        ["^(\\d+) clicks/sec \\(MAX\\)$", "$1 次点击/秒（最大）"],
        ["^crit ×([\\d.,]+) → ×([\\d.,]+)$", "暴击 ×$1 → ×$2"],
        ["^(\\d+) flux \\+ (.+)$", "$1 通量 + $2", "T"],
        ["^(\\d+)% CHANCE$", "$1% 概率"],
        ["^(\\d+)K?% → (\\d+)K?% (.+)$", "$1% → $2% $3", "T"],
        ["^(\\d+)× (.+?) → unlocks an ABILITY SLOT$", "$1× $2 → 解锁一个能力槽", "T"],
        ["^(.+?) \\+ (.+?) → unlocks an ABILITY SLOT$", "$1 + $2 → 解锁一个能力槽", "T"],
        ["^(.+?) \\+ (.+?) → (.+)$", "$1 + $2 → $3", "T"],
        ["^(.+) has no key now$", "$1 目前没有按键", "T"],
        ["^(STANDARD|ENHANCED|CUSTOM|GLITCH|PROTOTYPE|MYTHIC) (GEAR|WEAPON)$", "$1 $2", "T"],
        ["^(\\S+) (SMARTFRAME|VANTA|KESTREL|IRONCLAD|RUSTTEK) (.+)$", "$1 $2 $3", "T"],
        ["^(.+) → STASH$", "$1 → 仓库", "T"],
        ["^Grid (\\d+)×(\\d+)$", "网格 $1×$2"],
        ["^UPGRADE → (\\d+)×(\\d+)$", "升级 → $1×$2"],
        ["^· (.+) · click a module, then hover the grid$", "· $1 · 点击模块，然后悬停在网格上", "T"],
        ["^Synergy tags: (.+)$", "协同标签：$1", "T"],
        ["^(\\w+) · (\\S+)$", "$1 · $2", "T"],
        ["^(\\w+) · (\\S+) \\((\\d+)×(\\d+)\\) · (\\w+)$", "$1 · $2（$3×$4)· $5", "T"],
        ["^Complete any ability combo \\((.+)\\)$", "完成任意能力组合（$1）", "T"],
        ["^Consumes (\\d+)% stamina\\.$", "消耗 $1% 耐力。"],
        ["^gain \\+(\\d+)% increased (.+?) for this combat\\.?$", "本场战斗获得 +$1% $2。", "T"],
        ["^Fires (\\d+) rockets dealing (\\d+) damage each\\. (\\d+)s CD\\.$", "发射 $1 枚火箭，每枚造成 $2 伤害。冷却 $3 秒。"],
        ["^Fires (\\d+) burst shots at combat start\\. (\\d+)s CD\\.$", "战斗开始时连射 $1 发。冷却 $2 秒。"],
        ["^Massive hit dealing (\\d+)% player damage\\. (\\d+)s CD\\.$", "巨力一击，造成玩家伤害的 $1%。冷却 $2 秒。"],
        ["^Cloak for (\\d+)s\\. First hit \\+(\\d+)% crit\\.$", "隐身 $1 秒。首次攻击 +$2% 暴击。"],
        ["^Every (\\d+)th hit: \\+(\\d+)% bonus damage \\+ (\\d+)s stun\\.$", "每第 $1 次攻击：+$2% 额外伤害 + $3 秒眩晕。"],
        ["^Spawns phantom clones, stunning enemy for (\\d+)s\\. (\\d+)s CD\\.$", "生成幻影分身，眩晕敌人 $1 秒。冷却 $2 秒。"],
        ["^Revive once per raid at (\\d+)% HP\\.$", "每场 RAID 以 $1% 生命复活一次。"],
        ["^Auto-fires (\\d+)x at (\\d+)% player DMG every (\\d+)s\\.$", "每 $3 秒自动开火 $1 次，造成玩家伤害的 $2%。"],
        ["^Applies (\\d+)% max HP DoT over (\\d+)s\\. Max (\\d+) stacks\\.$", "在 $2 秒内施加 $1% 最大生命的持续伤害。最多 $3 层。"],
        ["^First (\\d+) shots deal \\+(\\d+)% damage\\. (\\d+)s CD\\.$", "前 $1 发子弹 +$2% 伤害。冷却 $3 秒。"],
        ["^First hit -(\\d+)%\\. \\+(\\d+) AC per hit taken \\(max (\\d+)\\)\\.$", "第一击 -$1%。每次受击 +$2 护甲（最多 $3）。"],
        ["^Regenerate (\\d+) HP out of combat\\. (\\d+)% faster healing\\.$", "脱战时每秒回复 $1 生命。治疗速度 +$2%。"],
        ["^Regenerate (\\d+) HP/s during combat\\. (\\d+)% damage reduction\\.$", "战斗中每秒回复 $1 生命。减伤 $2%。"],
        ["^Increases loot speed by (\\d+)% \\(max (\\d+)%\\)\\.$", "拾取速度提高 $1%（上限 $2%）。"],
        ["^Passively increases damage by (\\d+)%\\.$", "被动提高 $1% 伤害。"],
        ["^Auto-scans on map entry, revealing (\\d+) enemies\\.$", "进入地图时自动扫描，显示 $1 名敌人。"],
        ["^Stun immunity\\. \\+(\\d+) bonus HP\\.$", "免疫眩晕。+$1 额外生命。"],
        ["^(\\d+)% lifesteal\\. \\+(\\d+) HP on kill\\.$", "$1% 吸血。击杀时 +$2 生命。"],
        ["^(\\d+)% auto-dodge chance\\. Immune to ambushes\\.$", "$1% 自动闪避概率。免疫伏击。"],
        ["^\\+(\\d+)% fire rate for (\\d+)s\\. (\\d+)s CD\\.$", "+$1% 射速，持续 $2 秒。冷却 $3 秒。"],
        ["^\\+(\\d+)% damage per kill\\. Max (\\d+) stacks\\. Persists through raid\\.$", "每次击杀 +$1% 伤害。最多 $2 层。整场 RAID 持续。"],
        ["^\\+(\\d+)% AC, HP & Damage\\. (\\d+)% damage reduction\\.$", "+$1% 护甲、生命与伤害。$2% 减伤。"],
        ["^\\+(\\d+)% augment skill damage\\. (\\d+)% cooldown reduction\\.$", "+$1% 义体技能伤害。$2% 冷却缩减。"],
        ["^\\+(\\d+)kg weight capacity\\. \\+(\\d+) SCV\\.$", "+$1kg 负重。+$2 拾荒。"],
        ["^\\+(\\d+) accuracy\\. \\+(\\d+) handling\\.$", "+$1 命中。+$2 操控性。"],
        ["^\\+(\\d+) AC per hit\\. Max (\\d+) stacks\\.$", "每次命中 +$1 护甲。最多 $2 层。"],
        ["^\\+(\\d+) damage, \\+(\\d+) armor pen$", "+$1 伤害，+$2 护甲穿透"],
        ["^\\+(\\d+) permanent damage per kill this raid$", "本场 RAID 每次击杀永久 +$1 伤害"],
        ["^\\+(\\d+)% damage vs enemies above (\\d+)% HP$", "对生命高于 $2% 的敌人 +$1% 伤害"],
        ["^\\+(\\d+)% max HP per second$", "每秒 +$1% 最大生命"],
        ["^\\+(\\d+)% move speed\\. \\+(\\d+) evasion\\.$", "+$1% 移动速度。+$2 闪避。"],
        ["^FIELD NOTES (\\d+)/(\\d+): (.+)$", "战地笔记 $1/$2：$3", "T"],
        ["^(.+?) Hit NEXT when you're ready\\.$", "$1 准备好了就按下一步。", "T"],
        ["^(.+?) Try it now\\.$", "$1 现在试试。", "T"],
        ["^(.+?) Open it now\\.$", "$1 现在就打开。", "T"],
        ["^(.+?) Go on, click one\\.$", "$1 来，点一个。", "T"],
        ["^([+\\/-]) (.+)$", "$1 $2", "T"],
        ["^(.+) \\/ (.+)$", "$1 / $2", "T"],
        ["^(.+) -([\\d.]+)(%?)$", "$1 -$2$3", "T"],
        ["^(.+) \\[([A-Z+]+)\\]$", "$1 [$2]", "T"],
        ["^Insure (.+) against loss on death\\?$", "为 $1 投保以防死亡丢失？", "T"],
        ["^Gain (\\d+)% increased (.+)\\.$", "$2提升 $1%。", "T"],
        ["^FOUND: (.+)$", "找到：$1", "T"],
        ["^FROM: (.+) \\/\\/ (.+)$", "来自：$1 // $2", "T"],
        ["^FROM: (.+)$", "来自：$1", "T"],
        ["^(\\d+) items?$", "$1 件"],
        ["^BULK SELL: (\\d+) items?$", "批量出售：$1 件"],
        ["^(\\d+) items? → \\$([\\d.,]+) from (.+)$", "$1 件 → $$$2 来自 $3"],
        ["^Glitch and below \\((\\d+) items?\\)$", "GLITCH及以下（$1 件）"],
        ["^Mythic and below \\((\\d+) items?\\)$", "MYTHIC及以下（$1 件）"],
        ["^Mythics only \\((\\d+) items?\\) · (\\d+)% module$", "仅 MYTHIC（$1 件）· $2% 模块"],
        ["^Junk only, keeps artifacts \\((\\d+) items?\\)$", "仅垃圾，保留造物（$1 件）"],
        ["^(\\d+)% chance to return on death$", "$1% 概率死亡后返还"],
        ["^\\$([\\d.,]+) transferred\\. Keep moving\\.$", "$$$1 已转账。继续前进。"],
        ["^\\$([\\d.,]+) \\+ (.+) transferred\\. Keep moving\\.$", "$$$1 + $2 已转账。继续前进。", "T"],
        ["^\\+(\\d+) FLUX transferred\\. Keep moving\\.$", "+$1 通量已转账。继续前进。"],
        ["^(\\d+) ROOT, (\\d+) FLASH, (\\d+) KERNEL chips transferred\\. Spend them\\.$", "$1 ROOT、$2 FLASH、$3 KERNEL 芯片已转账。花掉它们。"],
        ["^\\+\\$([\\d.,]+) earned$", "+$$$1 收入"],
        ["^\\+(\\d+) (.+) standing XP$", "+$1 $2 声望经验"],
        ["^GAMBLE \\$([\\d.,]+)$", "赌一把 $$$1"],
        ["^BOOST PROTO \\+(\\d+)% \\$([\\d.,]+)$", "强化原型 +$1% $$$2"],
        ["^I want \\$([\\d.,]+)$", "我要 $$$1"],
        ["^Need (\\d+) points? \\(have (\\d+)\\)$", "需要 $1 点（拥有 $2）"],
        ["^LVL (\\d+)\\+$", "等级 $1+"],
        ["^LAYER (\\d+) · BOSS$", "第 $1 层 · 头目"],
        ["^LAYER (\\d+) ◦ CLAIMED$", "第 $1 层 ◦ 已领取"],
        ["^Level (\\d+) \\+(\\d+) Skill Points?$", "等级 $1 +$2 技能点"],
        ["^P(\\d+) · Lv(\\d+) · (\\d+) Aug (.+)$", "P$1 · Lv$2 · $3 义体 $4"],
        ["^> (.+)$", "> $1", "T"],
        ["^\"(.+)\"$", "\"$1\"", "T"],
        ["^(.+) \\[DONE\\]$", "$1 [完成]", "T"],
        ["^([A-Z]+)·([A-Z]+)$", "$1·$2", "T"],
        ["^(\\d+)\\. (.+)$", "$1. $2", "T"],
        ["^(\\d+) ACTIVE$", "$1 个生效中"],
        ["^Cost: (\\d+) points?$", "花费：$1 点"],
        ["^(\\d+)pts$", "$1 点"],
        ["^(\\d+) (\\w[\\w \/]*)$", "$1 $2", "T"],
        ["^([\\d.]+)(%?) → ([\\d.]+)(%?) (.+)$", "$1$2 → $3$4 $5", "T"],
        ["^([\\d.]+)× → ([\\d.]+)× (.+)$", "$1× → $2× $3", "T"],
        ["^Class: (.+) \\(YOUR CLASS\\)$", "职业：$1（你的职业）", "T"],
        ["^Class: (.+) \\(RESTRICTED\\)$", "职业：$1（受限）", "T"],
        ["^Automatically heal to full HP after raid \\(\\$([\\d.,]+)\\)$", "RAID 后自动治疗至满生命（$$$1)", ""],
        ["^Basic T(\\d) gear issued and wounds treated\\. Available again after your next raid if still broke\\.$", "已发放基础 T$1 装备并处理了伤口。若你仍身无分文，下次 RAID 后可再次领取。"],
        ["^Elemental Effects last (\\d+)% longer\\.$", "元素效果持续时间延长 $1%。"],
        ["^(.+):$", "$1：", "T"],
        ["^(0x[0-9A-F]+): (.+)$", "$1: $2", "T"],
        ["^(.+) \\+([\\d.,]+)(%?)$", "$1 +$2$3", "T"],
        ["^(.+) and below \\((\\d+) items?\\)$", "$1及以下（$2 件）", "T"],
        ["^\\$([\\d.,]+) \\+ (.+)$", "$$$1 + $2", "T"]
    ],
