    // ==== часть 01: названия патчей ====
    "Camo Pattern Overlay": "Оверлей камуфляжного узора",
    "Capacity Spacer": "Разделитель емкости",
    "Chamber Polish": "Полировка патронника",
    "Cloak Field Hotfix": "Хотфикс поля маскировки",
    "Micro-Deflector Array": "Микро-массив отклонения",
    "Field Service Script": "Скрипт полевого обслуживания",
    "Edge Hone Macro": "Макрос заточки кромки",
    "Ergonomic Strap System": "Эргономичная система ремней",
    "Fast-Mag Macro": "Макрос быстрой смены магазина",
    "Fault Tolerance": "Отказоустойчивость",
    "Item Finder Script": "Скрипт поиска предметов",
    "Footwork Assist Script": "Скрипт помощи в перемещении",
    "Grab-Assist Script": "Скрипт помощи при захвате",
    "Grip Tape Hotfix": "Хотфикс ленты на рукояти",
    "Grip Profile": "Профиль рукояти",
    "Loot Scanner Macro": "Макрос сканера лута",
    "Micro-Reach Spacer": "Микро-разделитель дистанции",
    "Micro-Overclock": "Микро-оверклокинг",
    "Impact Padding Layer": "Амортизирующий слой",
    "Pen Tip Guidance": "Направляющая наконечника пробития",
    "Armor Plate Insert": "Вставка бронепластины",
    "Extra Pocket Module": "Модуль дополнительного кармана",
    "Reflex Booster Patch": "Патч усилителя рефлексов",
    "Reinforcement Layer": "Укрепляющий слой",
    "Safety Limit Bypass": "Обход ограничений безопасности",
    "Wrist Servo Tune": "Настройка сервопривода запястья",
    "Field Sharpen Routine": "Протокол полевой заточки",
    "Shear Angle Guidance": "Направляющая угла среза",
    "Shock Dampeners": "Демпферы удара",
    "Silent Zipper Mod": "Мод бесшумной молнии",
    "Sound Dampening Mesh": "Звукопоглощающая сетка",
    "Sprint Optimization": "Оптимизация спринта",
    "Thermal Budgeting": "Управление тепловым бюджетом",
    "Thrust Timing Patch": "Патч тайминга рывка",
    "Vigor Module Script": "Скрипт модуля бодрости",
    "Vital Assist Hotfix": "Хотфикс помощи уязвимым точкам",
