    // ==== JS_UI часть 5: фразы (результаты глитчей, мифические способности, описания фильтров, концовка) ====
    "Some mods were deleted": "Некоторые моды были удалены",
    "Nothing happened, but the item is locked": "Ничего не произошло, но предмет заблокирован",
    "All mods rerolled with bad values": "Все моды переброшены с плохими значениями",
    "All positive stats x6, blocks manual repair": "Все положительные статы x6, запрещает ручной ремонт",
    "25% chance to infuse weapon with random element.": "25% шанс наделить оружие случайным элементом.",
    "Corrupts an item. Unpredictable outcomes. Locks.": "Повреждает предмет. Непредсказуемые результаты. Блокировка.",
    "Removes all properties, reverting to [Standard].": "Удаляет все свойства, возвращая к [Standard].",
    "Any hit instantly kills non-boss enemies below 20% HP": "Любое попадание мгновенно убивает врагов (не боссов) ниже 20% HP",
    "Attack speed +8%/sec the longer combat lasts (no cap)": "Скорость атаки +8%/сек по мере длительности боя (без лимита)",
    "Combat start: 2s untouchable while dealing damage": "Начало боя: 2 сек. неуязвимости при нанесении урона",
    "Combat start: 3s stun + heal suppress + armor shred (boss: no stun)": "Начало боя: 3 сек. оглушения + подавление лечения + пробитие брони (босс: без оглушения)",
    "Combat start: after 2s, 25% max HP explosion (boss 8%)": "Начало боя: через 2 сек. взрыв 25% макс. HP (босс 8%)",
    "Combat start: armor-ignoring massive flat shot (boss included)": "Начало боя: мощный прямой выстрел, игнорирующий броню (включая боссов)",
    "Combat start: black hole pulls enemy in + 5s stun (boss: pull only)": "Начало боя: черная дыра притягивает врага + 5 сек. оглушения (босс: только притяжение)",
    "Combat start: enemy takes % max HP as DoT over 3s (boss halved)": "Начало боя: враг получает % от макс. HP в виде DoT в течение 3 сек. (у босса вдвое меньше)",
    "Combat start: enemy takes +40% damage all fight (boss +15%)": "Начало боя: враг получает +40% урона весь бой (босс +15%)",
    "Combat start: freeze 4s, +50% damage taken while frozen (boss 1.5s)": "Начало боя: заморозка на 4 сек., +50% к получаемому урону во время заморозки (босс 1.5 сек.)",
    "Combat start: nanobot drone chips enemy HP all fight": "Начало боя: нано-дрон постепенно снижает HP врага весь бой",
    "Combat start: phantom clone mirrors your damage": "Начало боя: фантомный клон дублирует твой урон",
    "Combat start: roll a random powerful buff": "Начало боя: случайный мощный бафф",
    "Combat start: sky lightning deals a headshot-power weapon strike (boss included)": "Начало боя: небесная молния наносит удар мощностью как хедшот (включая боссов)",
    "Each kill this raid stacks permanent +damage": "Каждое убийство в этом RAID дает постоянный бонус к урону",
    "Every 4th hit is a guaranteed headshot at +100% power": "Каждый 4-й удар — гарантированный хедшот с +100% мощностью",
    "Every kill drops guaranteed bonus flux/currency": "Каждое убийство гарантированно дает бонусный FLUX/валюту",
    "Instantly teleport to extraction with all loot": "Мгновенная телепортация на EXTRACT со всем лутом",
    "Once per raid: revive at 50% HP on lethal damage": "Раз за RAID: воскрешение с 50% HP при получении смертельного урона",
    "Reveal all enemies + foresee every drop: rarity tags on POIs & enemies": "Обнаружение всех врагов + предвидение всех дропов: теги редкости на POI и врагах",
    "Scan + teleport to enemies, kill, then POIs": "Сканирование + телепортация к врагам, убийство, затем к POI",
    "POI searches resolve instantly: all loot drops the moment you start searching": "Поиск в POI завершается мгновенно: весь лут выпадает в момент начала поиска",
    "~2% per hit to disintegrate the enemy (boss included)": "~2% шанс на дезинтеграцию врага при каждом попадании (включая боссов)",
    "+0.5 HS mult. Each adjacent module: +0.12 more": "+0.5 к множителю хедшота. Каждый соседний модуль: +0.12 дополнительно",
    "+25 damage. Each adjacent module: +25 more": "+25 к урону. Каждый соседний модуль: +25 дополнительно",
    "+30 damage for EACH module touching it (surround it!)": "+30 к урону за КАЖДЫЙ касающийся модуль (окружите его!)",
    "-30% heat. Each adjacent module: -15% more": "-30% к нагреву. Каждый соседний модуль: -15% дополнительно",
    "Boosts adjacent +10%. If fully surrounded by modules, UNLOCKS a bonus weapon ability": "Усиливает соседние +10%. Если полностью окружен модулями, РАЗБЛОКИРУЕТ дополнительную способность оружия",
    "Barrel + Power → infuse FIRE (Burning) element": "Ствол + Энергия → элемент ОГНЯ (Горение)",
    "Coolant + Optic → infuse COLD (Frozen) element": "Охладитель + Оптика → элемент ХОЛОДА (Заморозка)",
    "Coolant + Shock → unlocks an ABILITY SLOT": "Охладитель + Электричество → разблокирует СЛОТ СПОСОБНОСТИ",
    "Shock + Servo → infuse LIGHTNING (Electrified) element": "Электричество + Сервопривод → элемент МОЛНИИ (Электрический заряд)",
    "Drops: CL7+ Wardens, P9+ bosses, Ironfall CL10": "Дроп: CL7+ WARDEN, P9+ боссы, Ironfall CL10",
    "Auto-complete lockpick/hacking (10s wait, -15% loot)": "Автоматический взлом замков/хакинг (ожидание 10 сек, лут -15%)",
    "Automatically start next raid after extraction": "Автоматический запуск следующего RAID после EXTRACT",
    "Center-screen notification + sound when Warden progress hits 12/12": "Уведомление в центре экрана + звук, когда прогресс WARDEN достигает 12/12",
    "In the filter panel: AUTOMATION section, tick the Auto Deploy checkbox.": "В панели фильтров: раздел AUTOMATION, отметьте чекбокс Auto Deploy.",
    "ON: salvaged up to Max Rarity. OFF: never salvaged": "ВКЛ: разбор до Max Rarity. ВЫКЛ: никогда не разбирать",
    "ON: sold up to Max Rarity. OFF: never sold": "ВКЛ: продажа до Max Rarity. ВЫКЛ: никогда не продавать",
    "On raid start: auto-target the extraction POI and walk straight there": "При старте RAID: авто-наведение на POI для EXTRACT и движение прямо к нему",
    "Protected items are never auto-sold or salvaged, no matter what": "Защищенные предметы никогда не будут проданы или разобраны автоматически, несмотря ни на что",
    "Protects good base tiers (T1 is best). Manual, trader and bulk selling unaffected": "Защищает качественные базовые тиры (T1 — лучший). Ручная, торговая и массовая продажа не затронуты",
    "Protects this rarity and higher. Loot pickup (LOOT FILTERS above) unaffected": "Защищает эту редкость и выше. Подбор лута (фильтры лута выше) не затронут",
    "Rolls random gear (Standard / Enhanced / Custom)": "Выпадение случайного снаряжения (Standard / Enhanced / Custom)",
    "Salvage gear into tech materials after each raid (uses the same Max Rarity)": "Разбор снаряжения в тех. материалы после каждого RAID (использует тот же Max Rarity)",
    "Skip locked/hacked caches entirely (no wait, loot forfeited)": "Полный пропуск запертых/взломанных тайников (без ожидания, лут теряется)",
    "Stop automation after 3 consecutive deaths": "Остановить автоматизацию после 3 смертей подряд",
    "Total amount of loot you can carry in a raid.": "Общее количество лута, которое вы можете нести в RAID.",
    "Total damage of your accurate shots.": "Общий урон от ваших точных выстрелов.",
    "Reduces damage received from enemies.": "Снижает получаемый от врагов урон.",
    "Shortens the combat turn duration, allowing you to attack more frequently.": "Сокращает длительность боевого хода, позволяя атаковать чаще.",
    "Gives a chance to dodge enemy attacks. (Will be active in future builds)": "Дает шанс уклониться от атак врага. (Будет доступно в будущих сборках)",
    "Increases loot efficiency and quality. (Will be active in future builds)": "Повышает эффективность и качество лута. (Будет доступно в будущих сборках)",
    "Insanity level. (Will be active in future builds)": "Уровень безумия. (Будет доступно в будущих сборках)",
    "Reduces the chance of being detected during a raid. (Will be active in future builds)": "Снижает шанс обнаружения во время RAID. (Будет доступно в будущих сборках)",
    "Activates a flappy-style escape route minigame. Dodge the barriers without crashing for a": "Активирует мини-игру в стиле Flappy для побега. Уворачивайтесь от препятствий, чтобы получить",
    "chance to flee from combat": "шанс сбежать из боя",
    "Permanent upgrades bought with insanity.": "Постоянные улучшения, покупаемые за безумие.",
    "Complete your first REBIRTH in the INSANITY terminal to attune.": "Завершите свой первый REBIRTH в терминале INSANITY, чтобы настроиться.",
    "Defeat a Warden or complete an INSANITY minigame REBIRTH to unlock": "Победите WARDEN или завершите REBIRTH в мини-игре INSANITY, чтобы разблокировать",
    "No corruption modifiers active. Select a higher level for increased challenge & rewards.": "Нет активных модификаторов порчи. Выберите более высокий уровень для повышенной сложности и наград.",
    "Obtain augments through quests and boss drops": "Получайте аугментации через квесты и дроп с боссов",
    "Click a slot to view details and upgrade options": "Нажмите на слот, чтобы просмотреть детали и варианты улучшения",
    "Visit Ripperdoc to initiate the Evolution Protocol.": "Посетите RIPPERDOC, чтобы запустить Протокол Эволюции.",
    "Configure your mining rigs to passively generate": "Настройте свои буровые установки для пассивной генерации",
    "Insured items are prioritized when re-equipping.": "Застрахованные предметы имеют приоритет при переоснащении.",
    "MYTHIC gear will be destroyed permanently!": "MYTHIC снаряжение будет уничтожено навсегда!",
    "Jumps to any screen. Drag the header to move it, dash to shrink. Hidden during raids.": "Переход к любому экрану. Перетащите заголовок, чтобы переместить, или нажмите полоску, чтобы свернуть. Скрывается во время RAID.",
    "LOADOUT stash sidebar: click the padlock button, then click the items you want to protect.": "Боковая панель склада LOADOUT: нажмите кнопку замка, затем выберите предметы, которые хотите защитить.",
    "Bulk sell at any trader: LOCK the few pieces you actually use first.": "Массовая продажа у любого торговца: сначала ЗАБЛОКИРУЙТЕ те несколько вещей, которые вы реально используете.",
    "Hold the RIPPERDOC title bar (or my face) with left click and drag.": "Зажмите левой кнопкой мыши заголовок RIPPERDOC (или мое лицо) и тяните.",
    "TECH terminal: click the command line, type use root and press Enter.": "TECH терминал: нажмите на командную строку, введите use root и нажмите Enter.",
    "HUB screen: the INSANITY entry (hotkey 2).": "Экран HUB: вход в INSANITY (горячая клавиша 2).",
    "HUB: SKILLS. Pick a starting class node first.": "HUB: SKILLS. Сначала выберите узел начального класса.",
    "INSANITY terminal: the CACHES panel on the right side.": "INSANITY терминал: панель CACHES справа.",
    "All of it lives in the TECH terminal. Type HELP there when you are curious.": "Все это находится в TECH терминале. Если любопытно, введите там HELP.",
    "Go. Make money. Come back when something hurts.": "Иди. Зарабатывай деньги. Возвращайся, когда что-то заболит.",
    "Deploying without offensive capabilities significantly reduces survival chance.": "Развертывание без атакующих возможностей значительно снижает шансы на выживание.",
    "Your HP is critically low. Deploying in this condition is extremely risky.": "Ваше HP критически низкое. Развертывание в таком состоянии крайне рискованно.",
    "Healing...": "Лечение...",
    "System Ready": "Система готова",
    "Rest well, operator.": "Отдыхай, оператор.",
    "There is no going back.": "Пути назад нет.",
    "The clinic is silent. The man who built you, piece by piece, is gone.": "В клинике тишина. Человека, который собирал тебя по кусочкам, больше нет.",
    "I just hope you remember what you paid for it.": "Я лишь надеюсь, ты помнишь, какую цену за это заплатил.",
    "Hey. It's me, the developer.": "Эй. Это я, разработчик.",
    "This was my first game. I built it alone, learning as I went,": "Это была моя первая игра. Я создавал ее в одиночку, учась на ходу,",
    "Thank you. Not just for playing, but for caring enough to reach this moment.": "Спасибо. Не только за то, что играешь, но и за то, что тебе не все равно, раз ты дошел до этого момента.",
    "UNHUMAN keeps evolving. Be part of what comes next.": "UNHUMAN продолжает эволюционировать. Стань частью того, что будет дальше.",
    "has decided to follow you.": "решил следовать за тобой.",
    "stray dog": "бродячая собака",
    "VERY LOW": "ОЧЕНЬ НИЗКИЙ",
    "MID LOW": "НИЖЕ СРЕДНЕГО",
    "MID": "СРЕДНИЙ",
    "VERY HIGH": "ОЧЕНЬ ВЫСОКИЙ",
    "EXTREME": "ЭКСТРЕМАЛЬНЫЙ",
    "LOW": "НИЗКИЙ",
    "HIGH": "ВЫСОКИЙ",
    "MODERATE": "УМЕРЕННЫЙ",
    "HIGH RISK": "ВЫСОКИЙ РИСК",
