    // ==== JS_UI часть 7: пользователь 3-й тур (модалки, фильтры, типы, подсказки, дейли) ====
    "Starting a new game will delete your existing save data. This cannot be undone.": "Начало новой игры удалит ваши текущие данные сохранения. Это действие нельзя отменить.",
    "Enter Name...": "Введите имя...",
    "Enter Name": "Введите имя",
    "TECH TABLE": "Техно-верстак",
    "Bad (unprotected)": "Плохое (незащищенное)",
    "On killed: heal → equip best gear from stash → redeploy. If stash empty: scav gear + Silent Expanse CL0.": "При смерти: лечение → экипировка лучшего снаряжения из хранилища → REDEPLOY. Если хранилище пусто: собирайте снаряжение + Silent Expanse CL0.",
    "After stamina runs low, sprint resumes once it refills to this level. Lower = sprint kicks back in sooner, in shorter bursts; sprint always pauses below 20%": "Когда выносливость на исходе, спринт возобновляется, когда она восстановится до этого уровня. Чем ниже значение = тем быстрее и короче рывки спринта; спринт всегда приостанавливается, если выносливость ниже 20%.",
    "Which weapon a raid starts with. Empty slot falls back to primary, secondary, melee. Q still switches mid raid": "Оружие, с которым начинается RAID. Если слот пуст, используется основное, дополнительное или холодное оружие. Клавиша Q по-прежнему переключает оружие во время RAID.",
    "MATERIAL": "МАТЕРИАЛ",
    "CHEMICAL": "ХИМИКАТЫ",
    "MEDKIT": "MEDKIT",
    "ELECTRONICS": "ЭЛЕКТРОНИКА",
    "COMPONENT": "КОМПОНЕНТ",
    "VALUABLE": "ЦЕННОСТЬ",
    "DOCUMENT": "ДОКУМЕНТ",
    "TOOL": "ИНСТРУМЕНТ",
    "AMMO": "БОЕПРИПАСЫ",
    "ARTIFACT": "АРТЕФАКТ",
    "CONSUMABLE": "РАСХОДНИКИ",
    "IFAK": "IFAK",
    "AFAK": "AFAK",
    "MFAK": "MFAK",
    "HLM": "Шлем",
    "ACC": "Аксессуары",
    "MED": "Мед.",
    "OPT": "Оптика",
    "GPU": "Видеокарта",
    "Primary": "Основное",
    "Secondary": "Дополнительное",
    "Melee": "Ближний бой",
    "Enhanced": "Улучшенное",
    "Enhanced+": "Улучшенное+",
    "Custom": "Кастомное",
    "Custom+": "Кастомное+",
    "Glitch+": "GLITCH+",
    "Prototype+": "PROTOTYPE+",
    "and click items to quickly equip or unequip gear.": "и кликайте по предметам, чтобы быстро экипировать или снять снаряжение.",
    "and drag over items in your stash to quickly add them to the sell queue.": "и перетаскивайте предметы в хранилище, чтобы быстро добавить их в очередь продажи.",
    "in the terminal to sell BTC for cash ($70K each).": "в терминале, чтобы продать BTC за наличные (по $70K за штуку).",
    ". Guarantees specific mods on your gear.": ". Гарантирует наличие определенных модов на вашем снаряжении.",
    "Trader stock refreshes every": "Обновление ассортимента торговца каждые:",
    ". Check back after leveling up for new inventory.": ". Заходите после повышения уровня, чтобы увидеть новинки.",
    "trades in FLUX currency. Stock refreshes every 2h. Items here can't be bargained.": "торгует за валюту FLUX. Ассортимент обновляется каждые 2 часа. Торг здесь невозможен.",
    "breaks down gear into tech currencies. Higher tier items yield rarer materials.": "разбирает снаряжение на технологические валюты. Предметы более высокого тира дают более редкие материалы.",
    "unlocked! Wardens are powerful bosses with guaranteed loot. Defeat the Warden to unlock the": "разблокировано! WARDEN — это мощные боссы с гарантированной добычей. Победите WARDEN, чтобы разблокировать",
    "slot and equip from your augment locker.": "слот и экипируйте из своего шкафчика имплантов.",
    "TIP: Use": "ПОДСКАЗКА: используйте",
    "to quickly break down multiple items by rarity filter.": "чтобы быстро разобрать сразу несколько предметов через фильтр редкости.",
    "unlocked! Mastery nodes give permanent bonuses that persist across prestiges.": "разблокировано! Узлы мастерства дают постоянные бонусы, которые сохраняются после престижа.",
    "tab unlocked! Check": "вкладка разблокирована! Проверьте",
    "to spend flux on permanent bonuses.": "чтобы тратить FLUX на постоянные бонусы.",
    "shows detailed item stats, mod breakdown, and comparison with equipped gear.": "показывает подробные характеристики предмета, состав модов и сравнение с надетым снаряжением.",
    "Check your": "Проверьте ваш",
