    // ==== часть 04: древо добычи ====
    "Appraiser": "Оценщик",
    "Component Scavenger": "Сбор компонентов",
    "Corpse Harvest": "Сбор с трупов",
    "Data Siphon": "Сифон данных",
    "Deep Scan": "Глубокое сканирование",
    "ECHO CASCADE": "ECHO каскад",
    "Echo Doubler": "Удвоитель ECHO",
    "Fence Contacts": "Связи со скупщиками",
    "MIDAS PROTOCOL": "MIDAS протокол",
    "Module Magnet": "Магнит для модулей",
    "Noise Floor": "Порог шума",
    "OVERSIGNAL": "OVERSIGNAL",
    "Proto Resonance": "Proto резонанс",
    "Signal Tap": "Перехват сигнала",
