    // ==== chunk 01: patch adları ====
    "Camo Pattern Overlay": "迷彩涂层",
    "Capacity Spacer": "容量隔板",
    "Chamber Polish": "枪膛抛光",
    "Cloak Field Hotfix": "隐身力场热修",
    "Micro-Deflector Array": "微型偏转阵列",
    "Field Service Script": "战地维护脚本",
    "Edge Hone Macro": "磨刃宏",
    "Ergonomic Strap System": "人体工学背带",
    "Fast-Mag Macro": "快弹匣宏",
    "Fault Tolerance": "容错模块",
    "Item Finder Script": "物品探测脚本",
    "Footwork Assist Script": "步法辅助脚本",
    "Grab-Assist Script": "抓取辅助脚本",
    "Grip Tape Hotfix": "握把胶带热修",
    "Grip Profile": "握把配置",
    "Loot Scanner Macro": "战利品扫描宏",
    "Micro-Reach Spacer": "微距隔板",
    "Micro-Overclock": "微型超频",
    "Impact Padding Layer": "缓冲衬层",
    "Pen Tip Guidance": "穿甲弹头引导",
    "Armor Plate Insert": "装甲插板",
    "Extra Pocket Module": "附加口袋模块",
    "Reflex Booster Patch": "反射增强补丁",
    "Reinforcement Layer": "强化衬层",
    "Safety Limit Bypass": "安全限制旁路",
    "Wrist Servo Tune": "腕部伺服调校",
    "Field Sharpen Routine": "战地磨刃例程",
    "Shear Angle Guidance": "剪切角引导",
    "Shock Dampeners": "减震器",
    "Silent Zipper Mod": "静音拉链改装",
    "Sound Dampening Mesh": "消音网层",
    "Sprint Optimization": "冲刺优化",
    "Thermal Budgeting": "热量管控",
    "Thrust Timing Patch": "突刺时序补丁",
    "Vigor Module Script": "活力模块脚本",
    "Vital Assist Hotfix": "要害辅助热修",
