    // ==== JS_UI часть 12: keystone, ПОЛНЫЙ перевод терминала, аудит 4 ====
    "Complete the Welcome Gift quest": "Выполни задание «Приветственный подарок»",
    "All Bets Down": "Ва-банк",
    "Back Against the Wall": "Прижатый к стене",
    "Blur": "Шлейф",
    "Clean Kill": "Чистое убийство",
    "Controlled Burst": "Контролируемая очередь",
    "Elemental Pressure": "Стихийное давление",
    "Feeling Lucky": "Везунчик",
    "Ghost Step": "Призрачный шаг",
    "Glass Cannon": "Стеклянная пушка",
    "Heavy Hands": "Тяжелые руки",
    "High Stakes": "Высокие ставки",
    "Pain or Profit": "Боль или прибыль",
    "Rage": "Ярость",
    "Relentless Fire": "Беспощадный огонь",
    "Ricochet": "Рикошет",
    "Roll With It": "Подстраивайся",
    "Unwavering Aim": "Непоколебимый прицел",
    "Overload": "Перегрузка",
    "Amplify": "Усиление",
    "Acid": "Кислота",
    "Armor Piercer Rounds": "Бронебойные патроны",
    "When combat begins,": "Когда начинается бой,",
    "The first hit you take in combat": "Первый удар, полученный в бою,",
    "for the first hit you receive in this combat.": "(действует на первый удар, полученный в этом бою).",
    "Each active Elemental Stack": "Каждый активный стихийный стак",
    "Each consecutive hit on the same enemy": "Каждое последовательное попадание по одному и тому же врагу",
    "applying maximum stacks of all elemental effects.": "накладывает максимальное количество стаков всех стихийных эффектов.",
    "Hitting enemies generates Overload.": "Попадания по врагам накапливают Overload.",
    "When combat begins, you charge at the enemy.": "Когда начинается бой, вы бросаетесь на врага.",
    "You hook the enemy and pull them toward you.": "Вы цепляете врага и притягиваете его к себе.",
    "Your shots never miss.": "Ваши выстрелы никогда не промахиваются.",
    "You can no longer deal Headshots.": "Вы больше не можете наносить хедшоты.",
    "Status Effect Power": "Сила эффектов состояния",
    "Armor Penetration": "Пробитие брони",
    "Atk Spd": "Скорость атаки",
    "STAM": "Выносливость",
    "Health": "Здоровье",
    "Scavenge": "Сбор лута",
    "Hold": "Удерживать",
    "Treats": "Лакомства",
    "Phone": "Телефон",
    "Plank": "Доска",
    "CLOTH": "Ткань",
    "MECHANICAL": "Механическое",
    "enhanced": "улучшенное",
    "custom": "кастомное",
    "No eligible items found.": "Подходящих предметов не найдено.",
    "module codes": "коды модулей",
    "over time.": "(со временем).",
    "no stat change": "без изменения характеристик",
    "ROOT": "ROOT",
    "FLASH": "FLASH",
    "MILCAP": "MILCAP",
    "Kernel": "Kernel",
    "Patch": "Patch",
    "AUTO-CLICKER": "Автокликер",
    "> All subsystems operational. Type \"help\" for commands.": "> Все подсистемы работают. Введите «help» для получения команд.",
    "CURRENCIES (type \"cur\" for inventory):": "ВАЛЮТЫ (введите «cur» для инвентаря):",
    "anchor <mod_name>        Lock mod with anchor code": "anchor <mod_name>        Заблокировать мод кодом anchor",
    "clear                    Clear terminal": "clear                    Очистить терминал",
    "currencies (cur)         Show currency inventory": "currencies (cur)         Показать инвентарь валют",
    "help glitch              Show glitch protocol details": "help glitch              Показать детали протокола glitch",
    "help mods [category]     Show available mods": "help mods [category]     Показать доступные моды",
    "inject <code>            Add code to inject queue": "inject <code>            Добавить код в очередь инъекции",
    "mining                   Show mining status": "mining                   Показать статус майнинга",
    "mining add               Install GPU from stash": "mining add               Установить GPU из тайника",
    "mining remove            Remove GPU to stash": "mining remove            Убрать GPU в тайник",
    "mining start             Start mining rig": "mining start             Запустить майнинг-ферму",
    "mining stop              Stop mining rig": "mining stop              Остановить майнинг-ферму",
    "refuel generator         Refuel with BTC": "refuel generator         Заправить генератор с помощью BTC",
    "select <n>               Select item by index": "select <n>               Выбрать предмет по индексу",
    "status                   Show full item status": "status                   Показать полный статус предмета",
    "stop                     Stop auto-mod": "stop                     Остановить авто-мод",
    "use <currency>           Use currency on item": "use <currency>           Использовать валюту на предмете",
    "use <currency> until <mod>  Auto-repeat until mod": "use <currency> until <mod>  Авто-повтор до появления <mod>",
    "use <currency> x<n>      Use currency n times": "use <currency> x<n>          Использовать валюту n раз",
    "root     Jailbreaks [Standard] to [Enhanced].": "root     Разблокирует [Standard] до [Enhanced].",
    "flash    Reflashes properties on [Enhanced].": "flash    Перепрошивает свойства на [Enhanced].",
    "kernel   Upgrades [Enhanced] to [Custom].": "kernel   Улучшает [Enhanced] до [Custom].",
    "milcap   Overclocks [Custom] with powerful mod.": "milcap   Разгоняет [Custom] мощным модом.",
    "slot     Solders a new mod onto [Enhanced].": "slot     Припаивает новый мод к [Enhanced].",
    "opt      Optimizes numeric performance of mods.": "opt      Оптимизирует числовые показатели модов.",
    "recomp   Resets and rebuilds a [Custom] item.": "recomp   Сбрасывает и пересобирает предмет [Custom].",
    "wipe     Removes all, reverts to [Standard].": "wipe     Удаляет всё, возвращая к [Standard].",
    "glitch   Corrupts item. Unpredictable. Locks.": "glitch   Повреждает предмет. Непредсказуемо. Блокирует.",
    "click code to add to queue | use 'inject <code>' in terminal": "кликните по коду, чтобы добавить в очередь | используйте «inject <code» в терминале",
    "- no codes -": "- нет кодов -",
    "* effects vary by item type (armor/melee/ranged) - type 'help glitch' in terminal": "* эффекты зависят от типа предмета (броня/ближний/дальний бой) - введите «help glitch» в терминале",
    "No item selected. Use \"select <n>\" first.": "Предмет не выбран. Сначала используйте «select <n>».",
    "sell btc <amount>": "sell btc <amount>",
    "target crafting": "целевой крафт",
    "Inject collected codes for": "Инъекция собранных кодов для",
