    // ==== JS_UI часть 11: аудит 3 (программа наставника, keystone, полные описания настроек, чипы) ====
    "S sells, X salvages the hovered item. NEVER skips every prompt, mythic included: a misclick is final.": "S — продать, X — разобрать выбранный предмет. НИКОГДА — пропускает все окна подтверждения, включая MYTHIC: ошибка клика необратима.",
    "Takes and finishes every quest you qualify for, raids included. Needs stash room for the rewards. Prestige, endgame and reward-choice quests stay yours.": "Принимает и завершает все доступные задания, включая RAID. Требуется место в хранилище для наград. Задания на престиж, эндгейм и задания с выбором награды остаются за вами.",
    "Caps internal update work to save CPU. Display output follows your monitor's refresh rate (engine limit): for a hard FPS cap use your GPU driver's frame limiter.": "Ограничивает внутренние обновления для экономии CPU. Вывод изображения соответствует частоте обновления монитора (лимит движка): для жесткого ограничения FPS используйте ограничитель кадров в драйвере видеокарты.",
    "Reduces recoil per shot. Also sets your headshot chance: handling / 5, capped at 20%": "Снижает отдачу за выстрел. Также определяет ваш шанс хедшота: управление / 5, максимум 20%",
    "Protections always win, then Tier Cleanup force-sells bad bases, then Max Rarity sells the rest": "Защита всегда в приоритете, затем Tier Cleanup принудительно продает плохие базы, затем Max Rarity продает остальное",
    "Run a raid and come back alive": "Выполни RAID и вернись живым",
    "Press HEAL on the extraction screen": "Нажми HEAL на экране эвакуации",
    "Use root, flash and kernel on a STANDARD item": "Используй root, flash и kernel на предмете STANDARD",
    "Spend a skill point in the skill tree": "Потрать очко навыка в дереве навыков",
    "Click to allocate": "Нажми, чтобы распределить",
    "Must connect to allocated node": "Должен быть подключен к распределенному узлу",
    "Start nodes are assigned by class": "Начальные узлы назначаются классом",
    "Sharp Edge": "Острое лезвие",
    "Relentless Strikes": "Безжалостные удары",
    "Unshakable": "Непоколебимый",
    "Unstable Power": "Нестабильная мощь",
    "House Edge": "Преимущество заведения",
    "Stacker": "Стакер",
    "Weight of Steel": "Тяжесть стали",
    "Damage Reduction": "Снижение урона",
    "Elemental Damage": "Стихийный урон",
    "This effect can only trigger once per combat.": "Этот эффект может сработать только один раз за бой.",
    "Triggers once per combat.": "Срабатывает один раз за бой.",
    "You cannot be stunned.": "Вас нельзя оглушить.",
    "Each time you take damage,": "Каждый раз, когда вы получаете урон,",
    "Each successful Melee hit grants": "Каждое успешное попадание в ближнем бою дает",
    "If you spot the enemy first,": "Если вы первым заметили врага,",
    "(both bonuses and penalties).": "(как бонусы, так и штрафы).",
    "Elemental Effects deal": "Стихийные эффекты наносят",
    "Restart interface to apply language? Progress is saved.": "Перезапустить интерфейс, чтобы применить язык? Прогресс будет сохранен.",
    "This cannot be undone.": "Это действие нельзя отменить.",
    "Overwrite": "Перезаписать",
    "Delete": "Удалить",
    "Show completed": "Показать выполненные",
    "Skip the rest of the field notes?": "Пропустить остальные полевые заметки?",
    "Sell all items up to a rarity tier?": "Продать все предметы до определенного уровня редкости?",
    "Not enough money": "Недостаточно денег",
    "[AUTO:ON]": "[AUTO: ВКЛ]",
    "RLD": "RLD",
    "STL": "STL",
    "SCV": "SCV",
    "HND": "HND",
    "HS": "HS",
    "HSM": "HSM",
    "RCH": "RCH",
    "SLT": "SLT",
    "RCO": "RCO",
    "WGT": "WGT",
    "WEI": "WEI",
    "STIM": "STIM",
    "SHOTGUN": "Дробовик",
    "SMALL": "Малый",
    "CURRENCY": "Валюта",
    "Weapons": "Оружие",
    "Tactical Rigs": "Тактические разгрузки",
    "Pack": "Рюкзак",
    "Helmet": "Шлем",
    "Pistol": "Пистолет",
    "Rig": "Разгрузка",
    "Headset": "Гарнитура",
    "AMB": "AMB",
    "BLO": "BLO",
    "BLU": "BLU",
    "DoN": "DoN",
    "EDG": "EDG",
    "ELE": "ELE",
    "EXE": "EXE",
    "GHO": "GHO",
    "HEA": "HEA",
    "HOU": "HOU",
    "IRO": "IRO",
    "PAI": "PAI",
    "REL": "REL",
    "SEC": "SEC",
    "SHA": "SHA",
    "UNS": "UNS",
    "Rounds per minute": "Выстрелов в минуту",
    "Weapon damage range": "Диапазон урона оружия",
    "Total health points": "Общее количество HP",
    "Reduces enemy detection chance": "Снижает шанс обнаружения врагом",
    "Raids start with sprint enabled (same stamina rules; SHIFT still toggles mid-raid)": "RAID начинаются с включенным спринтом (те же правила выносливости; SHIFT по-прежнему переключает режим во время RAID)",
    "Repair equipped weapons after raid ($)": "Ремонтировать экипированное оружие после RAID ($)",
    "Strapped your crafted piece on you. The old one is in your stash.": "Созданный предмет экипирован. Старый отправлен в хранилище.",
