    // ==== parça 15: mythic modüller + trader replikleri + skill tree UI + bölünmüş node parçaları ====
    "+0.4 HS multiplier": "+0.4 爆头倍率",
    "+0.4 attack speed": "+0.4 攻击速度",
    "+2% accuracy per hit (max +30%)": "每次命中 +2% 命中率（上限 +30%）",
    "+20 HP on enemy kill": "击杀敌人时回复 20 生命",
    "+30% extra items from POI": "POI 额外物品 +30%",
    "+40% POI search speed": "POI 搜索速度 +40%",
    "+50% currency from salvage": "拆解获得的货币 +50%",
    "+55 damage (shock synergy)": "+55 伤害（电击协同）",
    "+70 damage (bleed synergy)": "+70 伤害（流血协同）",
    "+80% carry capacity": "负重上限 +80%",
    "-70% POI search time": "POI 搜索时间 -70%",
    "15% chance to stun for 0.5s": "15% 概率眩晕 0.5 秒",
    "2% chance instant kill (not bosses)": "2% 概率即死（Boss 除外）",
    "25% chance for free 2nd hit": "25% 概率免费追加一击",
    "5-10% life steal on hit": "命中时 5-10% 生命偷取",
    "50% chance to upgrade drop rarity +1": "50% 概率使掉落稀有度 +1",
    "70-80% headshot chance": "70-80% 爆头概率",
    "Countdown; at zero all map enemies die (boss excluded)": "倒计时；归零时地图上所有敌人死亡（Boss 除外）",
    "Deletes 3 enemies at raid start; their loot goes straight to your bag (bosses excluded)": "RAID 开始时抹除 3 个敌人；其战利品直接进入你的背包（Boss 除外）",
    "Faster heat buildup; overheat releases a nova + instant cooldown": "热量积累更快；过热时释放新星爆发并立即冷却",
    "Glitch Clone": "GLITCH 克隆",
    "If you want clean work, stop asking dirty questions.": "想要干净利落的活儿，就别问脏问题。",
    "Breathe in. Don't waste my precision.": "吸气。别浪费我的精准。",
    "The new part will take. Your pride might not.": "新零件会适应你。你的自尊可未必。",
    "Don't tell me your story. Tell me your budget.": "别跟我讲你的故事。告诉我你的预算。",
    "I don't lie. I just charge for the truth.": "我不撒谎。我只是为真相收费。",
    "Size.": "尺码。",
    "Point to what you want.": "指给我看你要什么。",
    "Don't waste my time with opinions.": "别拿意见浪费我的时间。",
    "You want comfort? Buy a pillow.": "想要舒服？去买个枕头。",
    "Trade carefully. The signal doesn't forgive mistakes.": "交易谨慎点。信号不会原谅错误。",
    "I've seen legends born from a single roll.": "我见过一次抽取造就的传奇。",
    "SKILL_TREE.exe": "技能树.exe",
    "RESET_TREE": "重置技能树",
    "REFUND_MODE": "退点模式",
    "PLAN_MODE": "方案模式",
    "RESET_CONFIRM": "重置确认",
    "Search nodes...": "搜索节点...",
    "Expand stash by": "将仓库扩充",
    ", press R to rotate)": "，按 R 旋转）",
    "· click a module, then hover the grid": "· 点击一个模块，然后悬停在网格上",
    "⚡ ABILITIES": "⚡ 能力",
    "✦ MYTHIC AFFIXES": "✦ MYTHIC 词条",
    "HS Mult": "爆头倍率",
    "Pen": "穿透",
    "Reach": "攻击距离",
    "> Gain Rage when you hit an enemy.\n> Rage lasts until the raid ends.\n> Each Rage grants:\n +2% Damage\n +2% RPM\n> Maximum Rage: 25": "> 命中敌人时获得狂怒。\n> 狂怒持续到 RAID 结束。\n> 每层狂怒提供：\n +2% 伤害\n +2% 射速\n> 狂怒上限：25",
