    // ==== часть 16: полные тексты мифических модулей/комбо + тултипы персонажей + сброс мастерства/сбора + магазин безумия ====
    "+25 magazine capacity": "+25 к емкости магазина",
    "+90 damage, +20 armor pen": "+90 урона, +20 пробития брони",
    "+60 armor penetration": "+60 пробития брони",
    "+110 damage, +30 armor pen": "+110 урона, +30 пробития брони",
    "+70 damage, +1.0 reach": "+70 урона, +1.0 дистанция",
    "+40 fire rate / +0.2 attack speed": "+40 темп стрельбы / +0.2 скорость атаки",
    "+40 damage": "+40 урона",
    "+90 armor": "+90 брони",
    "+45 armor, +10 evasion": "+45 брони, +10 уклонения",
    "+70 health, periodic combat heal": "+70 ОЗ, периодическое лечение в бою",
    "+120 health": "+120 ОЗ",
    "Optic + Servo → +20 evasion, +0.5 HS mult": "Оптика + Сервопривод → +20 уклонения, +0.5 множитель HS",
    "Bleed + Optic → unlocks an ABILITY SLOT": "Кровотечение + Оптика → разблокирует слот способности",
    "3× Power → unlocks an ABILITY SLOT": "3× Энергия → разблокирует слот способности",
    "All Elemental": "Все стихии",
    "All Stats": "Все характеристики",
    "Bonus cold damage": "Бонус к урону холодом",
    "Bonus fire damage": "Бонус к урону огнем",
    "Bonus lightning damage": "Бонус к урону молнией",
    "Bonus to all elements": "Бонус ко всем стихиям",
    "Chance for extra loot drops": "Шанс дополнительного выпадения добычи",
    "Chance for higher tier drops": "Шанс выпадения предметов более высокого тира",
    "Chance to ricochet bullets": "Шанс рикошета пуль",
    "Chance to survive a fatal hit": "Шанс пережить смертельный удар",
    "Cheat Death": "Обман смерти",
    "Damage Bonus": "Бонус к урону",
    "Equilibrium-type passives: multiplies Armor, HP and Damage by this percent. Included in the values shown": "Пассивки типа Equilibrium: умножают Броню, ОЗ и Урон на этот процент. Учитывается в отображаемых значениях",
    "HP recovered from damage dealt": "ОЗ, восстанавливаемые пропорционально нанесенному урону",
    "Max Stacks": "Макс. стаков",
    "Maximum status effect stacks": "Максимальное число стаков эффектов статуса",
    "No weapon equipped": "Оружие не экипировано",
    "RPM Bonus": "Бонус к RPM",
    "Skill tree damage bonus": "Бонус к урону из древа навыков",
    "Skill tree fire rate bonus": "Бонус к темпу стрельбы из древа навыков",
    "Status effect duration": "Длительность эффекта статуса",
    "Status effect strength": "Сила эффекта статуса",
    "INTERFERENCE": "ПОМЕХИ",
    "MELTDOWN": "РАСПЛАВЛЕНИЕ",
    "VOID": "ПУСТОТА",
    "SINGULAR": "СИНГУЛЯРНОСТЬ",
    "CDR": "CDR",
    "DMG%": "DMG%",
    "WPN": "WPN",
    "LVL": "LVL",
    "Reset ALL mastery nodes? Returns all Prestige Points.": "Сбросить ВСЕ узлы мастерства? Вернет все очки Prestige.",
    "Reset ALL Signal Harvest nodes? Echo Points are refunded.": "Сбросить ВСЕ узлы Signal Harvest? Очки Echo будут возвращены.",
    "Reset ALL Madness Protocol nodes? Spent insanity is fully refunded.": "Сбросить ВСЕ узлы Madness Protocol? Потраченное безумие будет полностью возвращено.",
    "module": "модуль",
    "combo": "комбо",
    "grid": "сетка",
    "core": "ядро",
