    // ==== chunk 13: junk açıklama kalanı + loot tree/mastery açıklamaları + mentor raid ipuçları ====
    "Password-protected. Someone died keeping this secret.": "有密码保护。有人为守住这个秘密而死。",
    "Hand-drawn. Routes crossed out. One circled in red.": "手绘的。路线被划掉了。有一条用红笔圈了出来。",
    "Last words recorded: 'What the hell is—'": "录下的最后一句话：'那到底是什……'",
    "Translation: 'They're not coming to save us.'": "翻译：'他们不会来救我们了。'",
    "EYES ONLY. Every eye that read this is now closed.": "绝密亲阅。读过它的每双眼睛都已闭上。",
    "Heads: a symbol you don't recognize. Tails: the same symbol.": "正面：一个你不认识的符号。反面：同一个符号。",
    "Nobody remembers what it does. Probably important.": "没人记得它是干什么的。八成很重要。",
    "Stores more data than a server farm. Size of a marble.": "存储量超过一个服务器农场。只有弹珠大小。",
    "Plays the same 3 seconds on loop. A voice saying 'don't'.": "循环播放同样的 3 秒。一个声音在说'不要'。",
    "Touch it and your watch runs backwards for a second.": "碰它一下，你的手表会倒走一秒。",
    "Triple-sealed glass. It moves when you're not looking.": "三重密封玻璃。你不看它的时候，它会动。",
    "The space inside is bigger than the space outside.": "里面的空间比外面的大。",
    "+5%/rank junk & artifact value": "每级 +5% 垃圾和造物价值",
    "+3%/rank chance: enemy kills drop a second item": "每级 +3% 概率：击杀敌人掉落第二件物品",
    "+5%/rank currency drop chance (POI + kills)": "每级 +5% 货币掉落概率（POI + 击杀）",
    "+4%/rank chance: POI yields +1 item": "每级 +4% 概率：POI 多产出 1 件物品",
    "Double loot procs have 25% chance to drop a third item": "双倍战利品触发时有 25% 概率掉落第三件物品",
    "+2%/rank double loot (stacks with Echo Harvest mastery)": "每级 +2% 双倍战利品（与回响收割精通叠加）",
    "+3%/rank sell price at traders": "每级 +3% 商人出售价格",
    "All dropped loot value x1.20": "所有掉落战利品价值 x1.20",
    "Mythic module drop chances x1.5 (warden/boss/Ironfall)": "MYTHIC 模块掉落概率 x1.5（WARDEN/头目/铁陨防线）",
    "On CL5+ maps, Standard gear drops become Enhanced": "在 CL5+ 地图上，掉落的 Standard 装备变为 Enhanced",
    "Failed uplift rolls retry once": "失败的品阶提升判定重试一次",
    "+10%/rank Prototype roll weight": "每级 +10% PROTOTYPE 判定权重",
    "+5% value on all dropped loot": "所有掉落战利品价值 +5%",
    "+10%/rank salvage yield": "每级 +10% 拆解产出",
    "Artifact drop chance 0.5% → 0.75% per kill": "每次击杀造物掉落概率 0.5% → 0.75%",
    "+1 POI on every map": "每张地图 +1 个 POI",
    "Press E to open your raid inventory. Open it now.": "按 E 打开 RAID 背包。现在就打开。",
    "Now close the inventory. Press E again.": "现在关闭背包。再按一次 E。",
    "Q switches between primary, secondary and melee.": "Q 在主武器、副武器和近战之间切换。",
    "+2% damage per CL per level": "每级每 CL +2% 伤害",
    "+5% double loot chance per level": "每级 +5% 双倍战利品概率",
    "+10% flux earned per level": "每级 +10% FLUX 获取",
    "+5% loot rarity per CL per level": "每级每 CL +5% 战利品稀有度",
    "+6% Prototype effectiveness per level (base: 40%)": "每级 +6% PROTOTYPE 效能（基础：40%）",
    "+10% Signal Static resistance per level": "每级 +10% 信号静噪抗性",
    "+10% damage vs Wardens per level": "每级对 WARDEN 伤害 +10%",
    "One weapon. On the house. First and last time.": "一把武器。算我请客。仅此一次，下不为例。",
    "Fifteen targets. Any map. Show me consistency, not luck.": "十五个目标。地图随意。让我看到稳定，而不是运气。",
    "Ten extractions. Luck runs out. Patience doesn't.": "十次撤离。运气会耗尽，耐心不会。",
