    // ==== JS_UI часть 4: смешанные метки (фильтры, мифические модули, POI, враги безумия) ====
    "Ability Slots": "СЛОТЫ СПОСОБНОСТЕЙ",
    "Ablative Plate": "АБЛЯЦИОННАЯ ПЛАСТИНА",
    "Adaptive Calibration": "АДАПТИВНАЯ КАЛИБРОВКА",
    "Active quest items are never sold": "Активные предметы заданий никогда не продаются",
    "Add items to SELL first, then bargain": "Сначала добавьте предметы для ПРОДАЖИ, затем торгуйтесь",
    "Added to stash": "Добавлено в хранилище",
    "Adjacent AMMO modules give +50% more": "Соседние модули AMMO дают +50% бонуса",
    "Adult": "Взрослый",
    "Aegis": "Эгида",
    "Alert When Warden Available": "Оповещать, когда доступен WARDEN",
    "All Elemental Damage": "Весь стихийный урон",
    "All Rarities": "Все редкости",
    "All Types": "Все типы",
    "All enemies visible on map": "Все враги видны на карте",
    "Ammo Feed": "Подача патронов",
    "Amount": "Количество",
    "Amplifier Node": "Узел усилителя",
    "Anchor Lock": "Якорный замок",
    "Ancient Artifact": "Древний артефакт",
    "Armor (ARM)": "Броня (ARM)",
    "Armor Penetration": "Пробитие брони",
    "Armor Shatter": "Разрушение брони",
    "Armor Shredder": "Разрушитель брони",
    "Attacks cost no stamina": "Атаки не тратят выносливость",
    "Auto (default)": "Авто (по умолчанию)",
    "Auto Deploy": "Авто-дислокация",
    "Auto Sprint": "Авто-спринт",
    "Auto-Buy Mag": "Авто-покупка магазина",
    "Auto-Heal After Raid": "Авто-лечение после RAID",
    "Auto-Medic": "Авто-медик",
    "Auto-Recover on Death": "Авто-восстановление при смерти",
    "Auto-Repair Nanites": "Авто-ремонт нанитов",
    "Auto-Repair Weapons": "Авто-ремонт оружия",
    "Auto-Rush to Extraction": "Авто-рывок к ЭВАКУАЦИИ",
    "Auto-Salvage Gear": "Авто-разбор снаряжения",
    "Auto-Sell Loot": "Авто-продажа добычи",
    "Auto-Use Adrenaline": "Авто-использование адреналина",
    "Auto-Use Medkit": "Авто-использование аптечки",
    "Autosave": "Автосохранение",
    "Balance after": "Баланс после",
    "Base Price:": "Базовая цена:",
    "Below": "Ниже",
    "Below 20% HP: 90% damage reduction (5s)": "Ниже 20% HP: 90% снижения урона (5 сек)",
    "Below 30% HP: +100% damage": "Ниже 30% HP: +100% к урону",
    "Berserker Protocol": "Протокол берсерка",
    "Bit Rot": "БИТОВАЯ ГНИЛЬ",
    "Blink Hunter": "Охотник за мерцанием",
    "Block Raider": "Рейдер кварталов",
    "Bloodthirst": "Жажда крови",
    "Body": "Туловище",
    "Boosts each adjacent module by +10%": "Усиливает каждый соседний модуль на +10%",
    "Bulwark Protocol": "Протокол оплота",
    "Bunker": "Бункер",
    "Cannot Be Stunned": "Нельзя оглушить",
    "Cannot Headshot": "Нельзя попасть в голову",
    "Cheat Death Chance": "Шанс обмануть смерть",
    "Clean Patch Swap": "Чистая замена патча",
    "Click anywhere to continue": "Нажмите в любом месте, чтобы продолжить",
    "Click items in YOUR STASH or drag to add": "Нажмите на предметы в ВАШЕМ ХРАНИЛИЩЕ или перетащите, чтобы добавить",
    "Click to continue": "Нажмите, чтобы продолжить",
    "Click to use": "Нажмите, чтобы использовать",
    "Combat Stimulant": "Боевой стимулятор",
    "Combat start: stun the enemy 1.5s": "Начало боя: оглушение врага на 1.5 сек",
    "Combos": "Комбо",
    "Complete \"Man's Best Friend\" quest": "Выполнить задание «Лучший друг человека»",
    "Complete first EVOLUTION to unlock": "Завершите первую ЭВОЛЮЦИЮ, чтобы разблокировать",
    "Contact: WEAVER @ TRADERS": "Контакт: WEAVER @ ТОРГОВЦЫ",
    "Coolant Cell": "Ячейка охладителя",
    "Core Reactor": "Реактор ядра",
    "Corner Stabilizer": "Угловой стабилизатор",
    "Corrupted Reroll": "Поврежденный переброс",
    "Cost": "Стоимость",
    "Credits": "Кредиты",
    "Critical Edge": "Критическая кромка",
    "Cryo Damage": "Крио-урон",
    "Cryo Infusion": "Крио-наполнение",
    "Cyclic Booster": "Циклический ускоритель",
    "DMG +50% | REGEN +50% | AC +25%": "УРОН +50% | РЕГЕН +50% | БРОНЯ +25%",
    "Damage (DMG)": "Урон (DMG)",
    "Damage Amplifier": "Усилитель урона",
    "Damage Taken": "Получаемый урон",
    "Danger Sense": "Чутье опасности",
    "Data Loss": "Потеря данных",
    "Data Terminal": "Терминал данных",
    "Data Vampire": "Дата-вампир",
    "Deadeye": "Меткий глаз",
    "Death Loop Protection": "Защита от петли смерти",
    "Designate identification tag:": "Укажите идентификационный тег:",
    "Do not pick up loot below this rarity": "Не подбирать добыча ниже этой редкости",
    "Dodge first hit in each combat": "Уворачиваться от первого удара в каждом бою",
    "Don't ask again (glitch+ still confirms)": "Больше не спрашивать (GLITCH+ все равно подтверждает)",
    "Doom Clock": "Часы рока",
    "Double Tap Chip": "Чип двойного нажатия",
    "Double Tap Module": "Модуль двойного нажатия",
    "Double loot quantity from enemies": "Двойное количество добычи с врагов",
    "EMP Overload": "ЭМИ-перегрузка",
    "Eagle Eye HUD": "HUD «Орлиный глаз»",
    "Echo-Tap Routine": "Протокол эхо-перехвата",
    "Edge + Bleed → +120 damage": "Кромка + Кровотечение → +120 урона",
    "Electro Damage": "Электро-урон",
    "Electronics Only": "Только электроника",
    "Elemental Sync": "Стихийная синхронизация",
    "Encrypted Data Drive": "Зашифрованный накопитель данных",
    "Enemy takes a DoT that doubles every 2s": "Враг получает DoT, который удваивается каждые 2 сек",
    "Entire raid runs at 2x speed": "Весь RAID проходит на скорости x2",
    "Escape": "Побег",
    "Evasion (EVA)": "Уворот (EVA)",
    "Every POI search yields +1 bonus item": "Каждый поиск в POI дает +1 бонусный предмет",
    "Executioner": "Палач",
    "Extended Coil Mag": "Удлиненный катушечный магазин",
    "Extraction Accelerator": "Ускоритель EXTRACT",
    "Extraction Guard": "Страж EXTRACT",
    "Fatal Error": "Фатальная ошибка",
    "Fee:": "Сбор:",
    "Field Med Tent": "Полевая медпалатка",
    "Fire Rate": "Скорострельность",
    "Flamer Unit": "Огнеметный модуль",
    "Fortress Wall": "Стена крепости",
    "Full repair after each raid": "Полный ремонт после каждого RAID",
    "Gas Station": "Газозаправочная станция",
    "Ghost Weave": "Призрачное плетение",
    "Gold Bar": "Золотой слиток",
    "Hallway Sentry": "Часовой коридора",
    "Handling": "Управление",
    "Harvester Mech": "Механик-сборщик",
    "Headshot Multiplier": "Множитель хедшота",
    "Heal 15% max HP after every combat": "Исцеление 15% макс. HP после каждого боя",
    "Heals you periodically during combat": "Периодически лечит вас во время боя",
    "Hemorrhage": "Кровоизлияние",
    "Hidden Wall Safe": "Скрытый настенный сейф",
    "Hospital": "Госпиталь",
    "House": "Дом",
    "Hypervelocity": "Гиперскорость",
    "Ignore 70% of enemy armor": "Игнорирует 70% брони врага",
    "Ignore ALL enemy armor": "Игнорирует ВСЮ броню врага",
    "Ignore items below this value": "Игнорировать предметы ниже этой стоимости",
    "Infinite Magazine": "Бесконечный магазин",
    "Insanity (INS)": "Безумие (INS)",
    "Install:": "Установка:",
    "Instant Loot": "Мгновенный добыча",
    "Instant extraction": "Мгновенный EXTRACT",
    "Instantly finds 10 items per raid": "Мгновенно находит 10 предметов за RAID",
    "Ironfall Artillery Core": "Артиллерийское ядро Ironfall",
    "Ironfall Commander": "Командир Ironfall",
    "Ironfall War Mech": "Боевой мех Ironfall",
    "Item Effects": "Эффекты предметов",
    "Items:": "Предметы:",
    "Jam Chance": "Шанс заклинивания",
    "Juggernaut": "Джаггернаут",
    "Junk Picker": "Сборщик хлама",
    "Kernel Slot Injection": "Инъекция в слот ядра",
    "Laser Convergence": "Лазерная конвергенция",
    "Last Stand": "Последний рубеж",
    "Last Stand Protocol": "Протокол последнего рубежа",
    "Level": "Уровень",
    "Lifesteal a % of all damage dealt": "Вампиризм в % от нанесенного урона",
    "Locked Safe": "Запертый сейф",
    "Loot Multiplier": "Множитель добычи",
    "Loot Quantity": "Количество добычи",
    "Loot Rarity": "Редкость добычи",
    "Loot Sense": "Чутье добычи",
    "Magnetic Receiver": "Магнитный приемник",
    "Maintenance Drone": "Дрон техобслуживания",
    "Malware Injection": "Инъекция вредоносного ПО",
    "Max HP": "Макс. HP",
    "Max Rarity": "Макс. редкость",
    "Max Status Stacks": "Макс. стаков статуса",
    "Med + Plate → +180 health, +60 armor": "Med + Plate → +180 здоровья, +60 брони",
    "Med-Injector": "Мед-инъектор",
    "Medical Only": "Только медицина",
    "Melee Damage": "Урон в ближнем бою",
    "Midas Protocol": "Протокол Мидаса",
    "Military Plans": "Военные планы",
    "Min Loot Rarity": "Мин. редкость добычи",
    "Min Loot Value": "Мин. стоимость добычи",
    "Minigame Idle Mode": "Режим бездействия в мини-игре",
    "Module Class Flip": "Переключение типа модуля",
    "Module drop rate x2": "Шанс выпадения модуля x2",
    "Modules": "Модули",
    "Monomol Edge": "Мономолекулярная кромка",
    "Mortar Tech": "Техник минометов",
    "Nanite Weave": "Нано-плетение",
    "Nano Swarm": "Нано-рой",
    "Nano-Regen Matrix": "Матрица нано-регенерации",
    "Navigate obstacles to flee": "Маневрируйте между препятствиями, чтобы сбежать",
    "Neural Hijack": "Нейронный перехват",
    "Never Miss": "Никогда не промахнешься",
    "No GPUs in stash": "В хранилище нет видеокарт",
    "No active quests": "Нет активных заданий",
    "No active synergies": "Нет активных синергий",
    "No modules owned": "Модули не найдены",
    "No quests for this trader": "У этого торговца нет заданий",
    "No reload, unlimited ammo": "Без перезарядки, бесконечные патроны",
    "No stored augments for this slot": "В этом слоте нет сохраненных аугментаций",
    "None": "Нет",
    "Null Result": "Пустой результат",
    "Off": "Выкл",
    "Old Mainframe": "Старая мейнфрейм-система",
    "One-Tap Protocol": "Протокол одного удара",
    "Orbital Nuke": "Орбитальный ядерный удар",
    "Overcharge Protocol": "Протокол перегрузки",
    "Overclock Chip": "Чип разгона",
    "Overheat Meltdown": "Расплавление при перегреве",
    "Overkill": "Избыточный урон",
    "Overkiller": "Убийца-переборщик",
    "Overload Surge": "Всплеск перегрузки",
    "Overwatch": "Наблюдение",
    "Penetrator Core": "Ядро-проникатель",
    "Penetrator Rounds": "Пробивающие патроны",
    "Phantom Implicit": "Фантомное скрытое свойство",
    "Phantom Weave": "Призрачное плетение",
    "Phase Shift": "Фазовый сдвиг",
    "Piercing + Barrel → +80 armor pen": "Piercing + Barrel → +80 пробития брони",
    "Piercing Rounds": "Пробивающие патроны",
    "Plate + Shield → +150 armor, +120 health": "Plate + Shield → +150 брони, +120 здоровья",
    "Points": "Очки",
    "Police Station": "Полицейский участок",
    "Power + Flux → unlocks an ABILITY SLOT": "Power + Flux → разблокирует СЛОТ СПОСОБНОСТИ",
    "Power Cell": "Энергоячейка",
    "Pre-load Autosave": "Автосохранение перед загрузкой",
    "Press GAMBLE to roll random gear": "Нажмите GAMBLE, чтобы выбить случайное снаряжение",
    "Primary Only": "Только основное",
    "Prioritize specific item types": "Приоритет определенных типов предметов",
    "Protect Base Tier": "Защищать базовый тир",
    "Protect Rarity": "Защищать редкость",
    "Protect T1 only": "Защищать только T1",
    "Protect T1-T2": "Защищать T1-T2",
    "Protect T1-T3": "Защищать T1-T3",
    "Protect T1-T4": "Защищать T1-T4",
    "Prototype Chip": "Прототипный чип",
    "Pulse Emitter": "Импульсный излучатель",
    "Puppy": "Щенок",
    "Purchased": "Куплено",
    "Pyro Infusion": "Пиро-наполнение",
    "Quantum Crit": "Квантовый крит",
    "Railbreaker": "Разрушитель рельс",
    "Railgun Pierce": "Пробитие рельсотрона",
    "Railtuned Barrel": "Настроенный рельсовый ствол",
    "Rarity Amplifier": "Усилитель редкости",
    "Reach Prestige 9+, farm high CL / bosses": "Достигните PRESTIGE 9+, фармите высокий CL / боссов",
    "Reactive Weave": "Реактивное плетение",
    "Reality Delete": "Удаление реальности",
    "Reaper Actuator": "Привод Жнеца",
    "Recoil": "Отдача",
    "Recon Drone Mk.I": "Разведывательный дрон Mk.I",
    "Recon Drone Mk.II": "Разведывательный дрон Mk.II",
    "Redline": "Красная черта",
    "Reflex": "Рефлекс",
    "Regenerator": "Регенератор",
    "Reinforced Casing": "Усиленный корпус",
    "Reload Speed": "Скорость перезарядки",
    "Remove from Rig": "Удалить из RIG",
    "Repair Bay": "Ремонтный отсек",
    "Requires: Level 88": "Требуется: Уровень 88",
    "Return Rate": "Коэффициент возврата",
    "Returns to stash on death": "Возвращается в хранилище при смерти",
    "Reveals all enemies on the map": "Показывает всех врагов на карте",
    "Revive once per raid at 50% HP": "Воскрешение раз за RAID с 50% HP",
    "Ricochet Chance": "Шанс рикошета",
    "Rig Gunner": "Стрелок RIG",
    "Rocket Barrage": "Ракетный залп",
    "Rows": "Ряды",
    "Salvage Scanner": "Сканер для разбора",
    "Salvage Types": "Типы разбора",
    "Scav Drifter": "Бродяга-скавенджер",
    "Scav Magnet": "Магнит скавенджера",
    "Scavenger Core": "Ядро скавенджера",
    "Scavenging (SCV)": "Сбор (SCV)",
    "Search Speed Overdrive": "Перегрузка скорости поиска",
    "Second Wind": "Второе дыхание",
    "Secondary": "Вторичное",
    "Select GPU": "Выбрать GPU",
    "Select a quest to view details": "Выберите задание, чтобы просмотреть детали",
    "Select a slot to view locker": "Выберите слот, чтобы просмотреть шкафчик",
    "Select an item from STOCK to bargain": "Выберите предмет из STOCK для торга",
    "Select an item to purchase": "Выберите предмет для покупки",
    "Sell Below Value": "Продавать ниже стоимости",
    "Sell Types": "Типы продажи",
    "Sell Value": "Стоимость продажи",
    "Sell loot after each raid": "Продавать добыча после каждого RAID",
    "Sell/salvage this rarity and below": "Продавать/разбирать эту редкость и ниже",
    "Serrated Fang": "Зазубренный клык",
    "Servo + Ammo → +fire rate & attack speed": "Servo + Ammo → +скорострельность и скорость атаки",
    "Servo Hands": "Серворуки",
    "Shield Capacitor": "Щитовой конденсатор",
    "Shockwave Slam": "Удар ударной волной",
    "Signal Overclock": "Разгон сигнала",
    "Skill Point Drive": "Драйвер очков навыков",
    "Skip Minigame Caches": "Пропускать кэши мини-игр",
    "Skip Quest Items": "Пропускать предметы заданий",
    "Soulbound": "Привязанный к душе",
    "Soulbound Core": "Привязанное к душе ядро",
    "Soulbound Plating": "Привязанная к душе обшивка",
    "Speed (SPD)": "Скорость (SPD)",
    "Sprint Resume At": "Возобновление спринта при",
    "Stagger Protocol": "Протокол пошатывания",
    "Stamina": "Выносливость",
    "Standard": "Standard",
    "Starting Weapon": "Стартовое оружие",
    "Stasis Lock": "Стазис-лок",
    "Stats reduced, upgrade Prototype Sync": "Статы снижены, улучшите Prototype Sync",
    "Status Duration": "Длительность статуса",
    "Status Power": "Сила статуса",
    "Stealth (STL)": "Скрытность (STL)",
    "Stock:": "Склад:",
    "Store": "Магазин",
    "Storm Infusion": "Штормовое наполнение",
    "Success: 50% chance | CD: 60s": "Успех: 50% шанс | КД: 60 сек",
    "System Ready": "Система готова",
    "Targeting AI": "ИИ наведения",
    "Targeting Module": "Модуль наведения",
    "Tent": "Палатка",
    "Thermal Damage": "Тепловой урон",
    "Thermal Optic": "Тепловизионная оптика",
    "Thermal Shock": "Тепловой шок",
    "Thor's Might": "Мощь Тора",
    "Tier": "Тир",
    "Tier Cleanup": "Очистка тиров",
    "Titan Rounds": "Титановые патроны",
    "Transit Enforcer": "Транзитный каратель",
    "Trench Raider": "Окопный рейдер",
    "Triage Matrix": "Матрица сортировки",
    "Tunnel Sniper": "Тоннельный снайпер",
    "Type Preference": "Предпочтение по типу",
    "Undying": "Бессмертный",
    "Unlimited Ammo": "Бесконечные патроны",
    "Valuables Only": "Только ценности",
    "Vampiric Coating": "Вампирическое покрытие",
    "Vampiric Rounds": "Вампирические патроны",
    "Vampiric Surge": "Вампирический всплеск",
    "Vibro Core": "Виброядро",
    "Villa": "Вилла",
    "Viral Strike": "Вирусный удар",
    "Volatile Rounds": "Нестабильные патроны",
    "Warehouse": "Складское здание",
    "Warp Extraction": "Варп-экстракция",
    "Weapons Only": "Только оружие",
    "Weight Negator": "Компенсатор веса",
    "Weighted Core": "Утяжеленное ядро",
    "Wildcard Protocol": "Протокол «Джокер»",
    "X-Ray Scanner": "Рентгеновский сканер",
    "XP Bonus": "Бонус к опыту",
    "YOU TRADED YOUR DOG FOR AN UPGRADE": "ТЫ ОБМЕНЯЛ СВОЮ СОБАКУ НА УЛУЧШЕНИЕ",
    "Zero Stamina": "Нулевая выносливость",
    "Zero stamina consumption": "Нулевое потребление выносливости",
    "[ ABILITIES ]": "[ СПОСОБНОСТИ ]",
    "[ AUGMENTATION MODULE ]": "[ МОДУЛЬ АУГМЕНТАЦИИ ]",
    "[ CLEAR ]": "[ ОЧИСТИТЬ ]",
    "[ CLICK TO BEGIN ]": "[ НАЖМИТЕ, ЧТОБЫ НАЧАТЬ ]",
    "[ COMPANION MODULE ]": "[ МОДУЛЬ НАПАРНИКА ]",
    "[ CONFIRM DESIGNATION ]": "[ ПОДТВЕРДИТЬ ПОЗЫВНОЙ ]",
    "[ EQUIPMENT ]": "[ СНАРЯЖЕНИЕ ]",
    "[ GROWTH DATA ]": "[ ДАННЫЕ РОСТА ]",
    "[ INITIATE UPGRADE ]": "[ НАЧАТЬ УЛУЧШЕНИЕ ]",
    "[ MAX GROWTH ACHIEVED ]": "[ ДОСТИГНУТ МАКСИМАЛЬНЫЙ РОСТ ]",
    "[ NEW COMPANION DETECTED ]": "[ ОБНАРУЖЕН НОВЫЙ НАПАРНИК ]",
    "[ SEARCH TARGET ]": "[ ПОИСК ЦЕЛИ ]",
    "[ SIGNAL MASTERY ]": "[ МАСТЕРСТВО СИГНАЛА ]",
    "[ VITAL SIGNS ]": "[ ПОКАЗАТЕЛИ ЖИЗНИ ]",
    "[LOCKED]": "[ЗАБЛОКИРОВАНО]",
    "[OTHER]": "[ПРОЧЕЕ]",
    "- EMPTY -": "- ПУСТО -",
    "◆ COMPONENTS": "◆ КОМПОНЕНТЫ",
    "◇ READY TO ROLL": "◇ ГОТОВ К ПЕРЕБРОСУ",
    "◈ MAX GRID 10×10": "◈ МАКС. СЕТКА 10×10",
    "★ PROTOTYPE AFFIXES": "★ СВОЙСТВА PROTOTYPE",
    "⚔ COMBAT ENGAGED ⚔": "⚔ НАЧАЛО БОЯ ⚔",
    "✦ MYTHIC DROP": "✦ MYTHIC ДРОП",
