    // ==== часть 03: уникальные названия мифических/прото-предметов ====
    "Nemesis Mk.Ω": "Немезида Mk.Ω",
    "Leviathan Warframe": "Боевой каркас Левиафан",
    "Godspike Railgun": "Рельсотрон Шип Бога",
    "Oblivion Marksman": "Марксман Забвение",
    "Ascendant Neural Crown": "Нейронная корона Восходящего",
    "Reality Cleaver": "Рассекатель Реальности",
    "Singularity Sidearm": "Пистолет Сингулярности",
    "Apocalypse Breacher": "Разрушитель Апокалипсиса",
    "Wraith Stormneedle": "Штормовая игла Призрак",
    "Spectre Mk.X": "Спектр Mk.X",
    "Titan Exoframe": "Экзокаркас Титан",
    "Railspike": "Railspike",
    "Deadlock Marksman": "Марксман Дэдлок",
    "Wraith Neural Helm": "Нейрошлем Призрак",
    "Obsidian Edge": "Обсидиановое лезвие",
    "Phantom": "Фантом",
    "Hellstorm Breacher": "Разрушитель Адский Шторм",
    "Viper Needler": "Иглострел Гадюка",
