    // ==== часть 05: продолжение древа лута + карты + мастерство сигнала + названия заданий ====
    // ПРИМЕЧАНИЕ: SteamAchievements.NAMES.* не внесены, названия достижений НАМЕРЕННО оставлены на английском (см. GLOSSARY.md).
    "Strip Mining": "Strip Mining",
    "Uplift Amplifier": "Усилитель Подъёма",
    "Void Attunement": "Настройка Пустоты",
    "Wide Net": "Широкая сеть",
    "Zero-Day Exploit": "Эксплойт нулевого дня",
    "Blackstar Hold": "Крепость Blackstar",
    "Deadflare Zone": "Зона Deadflare",
    "Eclipse Bastion": "Бастион Eclipse",
    "Frontline Outskirts": "Окраины передовой",
    "Greyhall District": "Район Greyhall",
    "Ironfall Perimeter": "Периметр Ironfall",
    "Oblivion Nexus": "Нексус Oblivion",
    "Redline Fields": "Поля Redline",
    "Rustveil Transit": "Транзитный узел Rustveil",
    "Silent Expanse": "Silent Expanse",
    "Corrupted Rounds": "Зараженные снаряды",
    "Echo Harvest": "Сбор ECHO",
    "Flux Capacitor": "Потоковый конденсатор",
    "Frequency Tuning": "Настройка частот",
    "Prototype Sync": "Синхронизация Prototype",
    "Signal Static Resistance": "Сопротивление помехам сигнала",
    "Void Walker": "Странник Пустоты",
    "Warden Slayer": "Убийца WARDEN",
    "Welcome Gift": "Приветственный подарок",
    "First Blood": "Первая кровь",
    "Boss Hunt": "Охота на босса",
    "Apex Predator": "Высший хищник",
    "Body Count": "Счетчик тел",
    "Frontline Sweep": "Зачистка передовой",
    "Extraction Run": "Extraction Run",
    "High Value Target": "Высокоценная цель",
    "Corrupted Hostiles": "Зараженные враги",
    "District War": "Война в районе",
    "Warden Trophy": "Трофей WARDEN",
    "Deadflare Operations": "Операция Deadflare",
    "Dead Zone Delivery": "Доставка в Dead Zone",
