    // ==== часть 02: теги ALLCAPS N-Z ====
    "NANO": "НАНО",
    "NANO SWARM": "НАНОРОЙ",
    "NANO-REGEN": "НАНО-РЕГЕНЕРАЦИЯ",
    "NEURAL HIJACK": "НЕЙРОВЗЛОМ",
    "NEURAL INTERFACE OFFLINE": "НЕЙРОИНТЕРФЕЙС ОФЛАЙН",
    "NEURAL SYNERGIES": "НЕЙРОСИНЕРГИЯ",
    "NEVER": "НИКОГДА",
    "NEW GAME": "НОВАЯ ИГРА",
    "NEW RIG": "НОВЫЙ РИГ",
    "NEXT": "ДАЛЕЕ",
    "NO ACTIVE OBJECTIVES": "НЕТ АКТИВНЫХ ЦЕЛЕЙ",
    "NO FUNDS": "НЕДОСТАТОЧНО СРЕДСТВ",
    "NO GEAR IN STASH": "В ХРАНИЛИЩЕ НЕТ СНАРЯЖЕНИЯ",
    "NO MODULE": "НЕТ МОДУЛЯ",
    "NO MYTHIC ITEMS IN STASH": "В ХРАНИЛИЩЕ НЕТ MYTHIC ПРЕДМЕТОВ",
    "NO THANKS": "НЕТ, СПАСИБО",
    "NOT ENOUGH CREDITS": "НЕДОСТАТОЧНО КРЕДИТОВ",
    "NOT ENOUGH EP": "НЕДОСТАТОЧНО EP",
    "NOT ENOUGH INSANITY": "НЕДОСТАТОЧНО БЕЗУМИЯ",
    "NOT ENOUGH MONEY": "НЕДОСТАТОЧНО ДЕНЕГ",
    "NOT YET": "НЕ СЕЙЧАС",
    "NOTHING TO ROLL": "НЕЧЕГО ПЕРЕБРАСЫВАТЬ",
    "OFFENSE": "АТАКА",
    "OK": "ОК",
    "ON DEATH": "ПРИ СМЕРТИ",
    "ON HIT": "ПРИ ПОПАДАНИИ",
    "ON HIT TAKEN": "ПРИ ПОЛУЧЕНИИ УДАРА",
    "ON KILL": "ПРИ УБИЙСТВЕ",
    "OPERATIONS": "ОПЕРАЦИИ",
    "OPERATIVE": "ОПЕРАТИВНИК",
    "OPTIONS": "НАСТРОЙКИ",
    "OVERLOAD": "ПЕРЕГРУЗКА",
    "OVERWRITE": "ПЕРЕЗАПИСАТЬ",
    "OVERWRITE SLOT": "ПЕРЕЗАПИСАТЬ СЛОТ",
    "PACK": "РЮКЗАК",
    "PASSIVE": "ПАССИВНО",
    "PASSIVE BONUSES": "ПАССИВНЫЕ БОНУСЫ",
    "PATCH CODES": "КОДЫ ПАТЧЕЙ",
    "PATCHES": "ПАТЧИ",
    "PATCHES:": "ПАТЧИ:",
    "PEN": "ПРОБИТИЕ",
    "PERFECT": "ИДЕАЛЬНО",
    "PERFORMANCE": "ПРОИЗВОДИТЕЛЬНОСТЬ",
    "PERMA": "ПЕРМА",
    "PHAGE": "ФАГ",
    "PHANTOM IMPLICIT": "ФАНТОМНЫЙ ИМПЛИЦИТ",
    "PHANTOM STRIKE": "ФАНТОМНЫЙ УДАР",
    "PHASE": "ФАЗА",
    "PHASE SHIFT": "ФАЗОВЫЙ СДВИГ",
    "PISTOL": "ПИСТОЛЕТ",
    "PLAN MODE": "РЕЖИМ ПЛАНИРОВАНИЯ",
    "PLAY TUTORIAL": "ИГРАТЬ ОБУЧЕНИЕ",
    "POST-RAID SUMMARY": "ИТОГИ RAID",
    "PRECOGNITION": "ПРЕДВИДЕНИЕ",
    "PRESET LOADED": "ПРЕСЕТ ЗАГРУЖЕН",
    "PRESET SAVED": "ПРЕСЕТ СОХРАНЕН",
    "PRESETS": "ПРЕСЕТЫ",
    "PRESS ANY": "НАЖМИТЕ ЛЮБУЮ",
    "PRESTIGE-SAFE": "PRESTIGE-SAFE",
    "PRIMARY": "ОСНОВНОЕ",
    "PROGRESS": "ПРОГРЕСС",
    "PROTECTIONS": "ЗАЩИТА",
    "PROTO MAG": "PROTO МАГАЗИН",
    "PROTOTYPE DROP": "ПРОТОТИП ДРОП",
    "PROTOTYPE LOCKED": "PROTOTYPE ЗАБЛОКИРОВАН",
    "PULSE": "ИМПУЛЬС",
    "PUPPY": "ЩЕНОК",
    "QTY:": "КОЛ-ВО:",
    "QUALITY": "КАЧЕСТВО",
    "QUANTUM": "КВАНТОВЫЙ",
    "QUEST ACCEPTED": "ЗАДАНИЕ ПРИНЯТ",
    "QUEST LOG": "ЖУРНАЛ ЗАДАНИЙ",
    "QUESTS ACCEPTED": "ЗАДАНИЯ ПРИНЯТЫ",
    "QUICK SAVE": "БЫСТРОЕ СОХРАНЕНИЕ",
    "R.ARM": "П.РУКА",
    "R.LEG": "П.НОГА",
    "RAID IN PROGRESS": "RAID ИДЕТ",
    "RANDOM GEAR": "СЛУЧАЙНОЕ СНАРЯЖЕНИЕ",
    "RANGE": "ДИСТАНЦИЯ",
    "RANGED": "ДАЛЬНИЙ",
    "REACH": "ДИСТАНЦИЯ",
    "REBIRTH": "ПЕРЕРОЖДЕНИЕ",
    "REBIRTH TO UNLOCK": "ПЕРЕРОЖДЕНИЕ ДЛЯ РАЗБЛОКИРОВКИ",
    "RECOVER": "ВОССТАНОВИТЬ",
    "REFUND MODE": "РЕЖИМ ВОЗВРАТА",
    "REGEN": "РЕГЕН",
    "REJECTED": "ОТКЛОНЕНО",
    "RELOAD": "ПЕРЕЗАРЯДКА",
    "RELOADED": "ПЕРЕЗАРЯЖЕНО",
    "RELOADING": "ПЕРЕЗАРЯДКА",
    "RELOADING...": "ПЕРЕЗАРЯДКА...",
    "REMOVE ALL GEAR FIRST": "СНАЧАЛА СНИМИТЕ ВСЕ СНАРЯЖЕНИЕ",
    "REPAIR": "РЕМОНТ",
    "REPAIR WEAPON": "РЕМОНТ ОРУЖИЯ",
    "REROLL": "ПЕРЕБРОС",
    "REROLLED": "ПЕРЕБРОШЕНО",
    "RESET KEYS": "СБРОС КЛАВИШ",
    "RESET MASTERY": "СБРОС МАСТЕРСТВА",
    "RESET TREE": "СБРОС ДРЕВА",
    "RESISTANCE": "СОПРОТИВЛЕНИЕ",
    "RESONANCE // RARITY": "РЕЗОНАНС // РЕДКОСТЬ",
    "RESPEC": "РЕСПЕК",
    "RESPEC HARVEST": "RESPEC HARVEST",
    "RESPEC PROTOCOL": "RESPEC PROTOCOL",
    "REST": "ОТДЫХ",
    "RESTART": "ПЕРЕЗАПУСК",
    "RETURN TO HIDEOUT": "ВЕРНУТЬСЯ В УБЕЖИЩЕ",
    "REWARD:": "НАГРАДА:",
    "REWARDS": "НАГРАДЫ",
    "RICOCHET": "РИКОШЕТ",
    "RIFLE": "ВИНТОВКА",
    "RIG": "РАЗГРУЗКА",
    "RIGHT ARM": "ПРАВАЯ РУКА",
    "RIGHT LEG": "ПРАВАЯ НОГА",
    "RIGHT-CLICK": "ПКМ",
    "RIPPERDOC PATCHED YOU UP": "RIPPERDOC ЗАЛАТАЛ ТЕБЯ",
    "ROLL": "БРОСОК",
    "ROLL & EQUIP": "БРОСОК И ЭКИПИРОВКА",
    "ROOT ACCESS": "ROOT ДОСТУП",
    "ROTATING STOCK": "РОТАЦИЯ ЗАПАСОВ",
    "RUCKSACK": "РЮКЗАК",
    "RUN BEST": "БЕГИ В ГЛУБИНУ",
    "SAFE BOX": "СЕЙФ",
    "SAFE BOX FULL": "СЕЙФ ПОЛЕН",
    "SAFEBOX RETURN": "ВОЗВРАТ ИЗ СЕЙФА",
    "SALVAGE": "РАЗБОР",
    "SALVAGE ALL": "РАЗОБРАТЬ ВСЁ",
    "SALVAGE ITEM": "РАЗОБРАТЬ ПРЕДМЕТ",
    "SALVAGED": "РАЗОБРАНО",
    "SAVE FAILED": "ОШИБКА СОХРАНЕНИЯ",
    "SAVE MANAGEMENT": "УПРАВЛЕНИЕ СОХРАНЕНИЯМИ",
    "SAVE SIZE WARNING": "ПРЕДУПРЕЖДЕНИЕ О РАЗМЕРЕ СОХРАНЕНИЯ",
    "SAVE TO SLOT": "СОХРАНИТЬ В СЛОТ",
    "SCAVENGE": "СБОР",
    "SCOUTED:": "РАЗВЕДЕНО:",
    "SECURE": "ЗАБЛОКИРОВАТЬ",
    "SELECT AN AUGMENT SLOT": "ВЫБЕРИТЕ СЛОТ АУГМЕНТАЦИИ",
    "SELECT SLOTS TO FILL": "ВЫБЕРИТЕ СЛОТЫ ДЛЯ ЗАПОЛНЕНИЯ",
    "SELECTED:": "ВЫБРАНО:",
    "SELL ALL": "ПРОДАТЬ ВСЁ",
    "SHADE": "ТЕНЬ",
    "SHIFT + LEFT CLICK": "SHIFT + ЛКМ",
    "SHOCKED": "ПОЛУЧИЛ УДАР ТОКОМ",
    "SHOW ME": "ПОКАЖИ МНЕ",
    "SIDEARM": "ПРИКЛАДНОЕ",
    "SIGNAL DAMPENER": "ГЛУШИТЕЛЬ СИГНАЛА",
    "SIGNAL HARVEST": "SIGNAL HARVEST",
    "SIGNAL MASTERY": "SIGNAL MASTERY",
    "SIGNAL OVERCLOCK": "SIGNAL OVERCLOCK",
    "SIGNAL OVERLOAD": "SIGNAL OVERLOAD",
    "SIGNAL WARDEN DETECTED": "ОБНАРУЖЕН SIGNAL WARDEN",
    "SIN": "ГРЕХ",
    "SKILL POINT": "ОЧКО НАВЫКА",
    "SKILL POINT DRIVE": "SKILL POINT DRIVE",
    "SKILL TREE UPGRADE": "УЛУЧШЕНИЕ ДРЕВА НАВЫКОВ",
    "SKIP NOTES": "ПРОПУСТИТЬ ЗАМЕТКИ",
    "SKIP TASK": "ПРОПУСТИТЬ ЗАДАЧУ",
    "SKIP TUTORIAL": "ПРОПУСТИТЬ ОБУЧЕНИЕ",
    "SLOT": "СЛОТ",
    "SLOT MATRIX": "МАТРИЦА СЛОТОВ",
    "SLOTS": "СЛОТЫ",
    "SOLD": "ПРОДАНО",
    "SOULBOUND RETURN": "ВОЗВРАТ ДУШИ",
    "SPD": "СКОР.",
    "SPEED": "СКОРОСТЬ",
    "SPRINT": "СПРИНТ",
    "STABILIZER CORE": "СТАБИЛИЗИРУЮЩЕЕ ЯДРО",
    "STABLE": "СТАБИЛЬНО",
    "STAMINA": "ВЫНОСЛИВОСТЬ",
    "STANDING UP": "ПРЕСТИЖ",
    "START": "НАЧАТЬ",
    "STARTING NODES": "НАЧАЛЬНЫЕ УЗЛЫ",
    "STASH FULL": "ХРАНИЛИЩЕ ПОЛНО",
    "STASH UPGRADE": "УЛУЧШЕНИЕ ХРАНИЛИЩА",
    "STASIS LOCK": "СТАЗИС-ЗАМК",
    "STATS": "ХАРАКТЕРИСТИКИ",
    "STATUS: LOCKED": "СТАТУС: ЗАБЛОКИРОВАНО",
    "STATUS: PUPPY": "СТАТУС: ЩЕНОК",
    "STEALTH": "СКРЫТНОСТЬ",
    "STEP BACK": "ОТСТУПИТЕ",
    "STOCK REFRESHED": "ЗАПАС ОБНОВЛЕН",
    "STOMACH": "ЖИВОТ",
    "SUCCESS": "УСПЕХ",
    "SWITCH WEAPONS": "СМЕНИТЬ ОРУЖИЕ",
    "SWITCHING TO FISTS": "ПЕРЕКЛЮЧЕНИЕ НА КУЛАКИ",
    "SWITCHING TO MELEE": "ПЕРЕКЛЮЧЕНИЕ НА БЛИЖНИЙ БОЙ",
    "SWITCHING TO RIFLE": "ПЕРЕКЛЮЧЕНИЕ НА ВИНТОВКУ",
    "SWITCHING TO SIDEARM": "ПЕРЕКЛЮЧЕНИЕ НА ПРИКЛАДНОЕ",
    "SYNTH": "СИНТ",
    "SYSTEM:": "СИСТЕМА:",
    "TAILS": "РЕШКА",
    "TAKE A REST": "ОТДОХНИТЕ",
    "TASK": "ЗАДАЧА",
    "TECH MODULES": "ТЕХ-МОДУЛИ",
    "THE BOSS": "БОСС",
    "THERMAL": "ТЕПЛОВОЙ",
    "THORAX": "ГРУДНАЯ КЛЕТКА",
    "THREAT": "УГРОЗА",
    "TOTAL": "ИТОГО",
    "TOTAL:": "ИТОГО:",
    "TOY": "ИГРУШКА",
    "TURN IN": "СДАТЬ",
    "TUTORIAL COMPLETE": "ОБУЧЕНИЕ ЗАВЕРШЕНО",
    "UNLIMITED": "БЕЗЛИМИТНО",
    "UNSECURE": "ИЗВЛЕЧЬ ИЗ SECURE",
    "UTILITY": "ПОЛЕЗНОЕ",
    "UTILITY BELT": "ПОЯС С ИНСТРУМЕНТАМИ",
    "VAHLEN IS DEAD": "VAHLEN мертв",
    "VAULT": "ХРАНИЛИЩЕ",
    "VISUAL EFFECTS": "ВИЗУАЛЬНЫЕ ЭФФЕКТЫ",
    "VOLUME CONTROLS": "УПРАВЛЕНИЕ ГРОМКОСТЬЮ",
    "WARDEN AVAILABLE": "WARDEN ДОСТУПЕН",
    "WARDEN CHALLENGE": "ВЫЗОВ WARDEN",
    "WARNING": "ВНИМАНИЕ",
    "WARP EXTRACTION": "ВАРП-ЭВАКУАЦИЯ",
    "WEAPON": "ОРУЖИЕ",
    "WEAPON HUD": "WEAPON HUD",
    "WEAPON SLOT EMPTY": "СЛОТ ОРУЖИЯ ПУСТ",
    "WEAPONS": "ОРУЖИЕ",
    "WEIGHT": "ВЕС",
    "WILDCARD:": "ВАЙЛДКАРД:",
    "WIN": "ПОБЕДА",
    "WIPE": "СБРОС",
    "WIPE DRIVE": "ОЧИСТИТЬ ДРАЙВ",
    "WORM": "ЧЕРВЬ",
    "WRAITH": "WRAITH",
    "XP GAINED": "ПОЛУЧЕНО XP",
    "YOU": "ТЫ",
    "YOU LOST": "ТЫ ПРОИГРАЛ",
