    // ==== chunk 07: quest hedefleri (boss/trader özel adları Latin, nameplate ile eşleşsin) ====
    "Kill 1 enemy": "击杀 1 名敌人",
    "Kill 5 enemies": "击杀 5 名敌人",
    "Kill 15 enemies": "击杀 15 名敌人",
    "Kill 30 enemies": "击杀 30 名敌人",
    "Kill 15 enemies at CL1+": "在 CL1+ 击杀 15 名敌人",
    "Kill 30 enemies at CL2+": "在 CL2+ 击杀 30 名敌人",
    "Kill 50 enemies at CL3+": "在 CL3+ 击杀 50 名敌人",
    "Kill 60 enemies at CL4+": "在 CL4+ 击杀 60 名敌人",
    "Kill 10 enemies in Frontline Outskirts": "在前线外围击杀 10 名敌人",
    "Kill 25 enemies in Greyhall District": "在灰厅区击杀 25 名敌人",
    "Kill 30 enemies in Greyhall District": "在灰厅区击杀 30 名敌人",
    "Kill 40 enemies in Redline Fields": "在红线原野击杀 40 名敌人",
    "Kill 40 enemies in Deadflare Zone": "在死耀区击杀 40 名敌人",
    "Kill 80 enemies in Ironfall Perimeter": "在铁陨防线击杀 80 名敌人",
    "Kill 100 enemies in Ironfall Perimeter": "在铁陨防线击杀 100 名敌人",
    "Kill a Signal Warden": "击杀 1 个 Signal Warden",
    "Kill 2 Signal Wardens": "击杀 2 个 Signal Warden",
    "Kill 3 Signal Wardens": "击杀 3 个 Signal Warden",
    "Kill 5 Signal Wardens": "击杀 5 个 Signal Warden",
    "Kill 8 Signal Wardens": "击杀 8 个 Signal Warden",
    "Kill 3 Bosses": "击杀 3 个头目",
    "Kill the Nexus Avatar": "击杀 Nexus Avatar",
    "Kill the Blackstar Warlord": "击杀 Blackstar Warlord",
    "Kill the Eclipse Core": "击杀 Eclipse Core",
    "Extract from Silent Expanse": "从寂静旷野撤离",
    "Extract 3 times": "撤离 3 次",
    "Extract 5 times": "撤离 5 次",
    "Extract 10 times": "撤离 10 次",
    "Extract 20 times": "撤离 20 次",
    "Extract 5 times from Rustveil Transit": "从锈幕中转站撤离 5 次",
    "Extract 5 times from Eclipse Bastion": "从蚀日堡垒撤离 5 次",
    "Extract 8 times from Greyhall District": "从灰厅区撤离 8 次",
    "Extract 10 times from Redline Fields": "从红线原野撤离 10 次",
    "Extract 10 times from Deadflare Zone": "从死耀区撤离 10 次",
    "Reach Corruption Level 1": "达到侵蚀等级 1",
    "Reach Corruption Level 3": "达到侵蚀等级 3",
    "Reach Corruption Level 5": "达到侵蚀等级 5",
    "Reach Corruption Level 7": "达到侵蚀等级 7",
    "Reach Corruption Level 8": "达到侵蚀等级 8",
    "Reach Corruption Level 9": "达到侵蚀等级 9",
    "Reach Corruption Level 10": "达到侵蚀等级 10",
    "Turn in The First Flame": "上交「初火」",
    "Turn in Ghost Frequency": "上交「幽灵频率」",
    "Turn in The Architect's Core": "上交「架构师核心」",
    "Turn in Null Shard": "上交「空无碎片」",
    "Turn in Omega Protocol": "上交「欧米茄协议」",
    "Speak with Vulture": "与 Vulture 对话",
    "Upgrade any augment to +3": "将任意义体升级到 +3",
    "Upgrade any augment to +7": "将任意义体升级到 +7",
    "Loot $3,000 worth of items in raids": "在 RAID 中拾取价值 $3,000 的物品",
    "Loot $8,000 worth of items in raids": "在 RAID 中拾取价值 $8,000 的物品",
    "Loot $20,000 worth of items in raids": "在 RAID 中拾取价值 $20,000 的物品",
    "Sell $5,000 worth to traders": "向商人出售价值 $5,000 的物品",
    "Salvage 5 items": "拆解 5 件物品",
    "Salvage 25 items": "拆解 25 件物品",
    "Find Nano-Tape": "找到纳米胶带",
    "Find Matches": "找到火柴",
    "Find 2x Nano-Tape": "找到 2x 纳米胶带",
    "Find 3x Dog Treats": "找到 3x 狗零食",
    "Use the Tech Table once": "使用科技工作台 1 次",
    "Use the Tech Table 3 times": "使用科技工作台 3 次",
    "Find a Prototype item in raid": "在 RAID 中找到一件 PROTOTYPE 物品",
    "Find a Custom+ item in raid": "在 RAID 中找到一件 Custom+ 物品",
