    // ==== chunk 05: loot tree devam + haritalar + signal mastery + quest adları ====
    // NOT: SteamAchievements.NAMES.* girilmedi, achievement adları BİLİNÇLİ İngilizce (GLOSSARY.md).
    "Strip Mining": "露天开采",
    "Uplift Amplifier": "提升增幅器",
    "Void Attunement": "虚空调谐",
    "Wide Net": "广撒网",
    "Zero-Day Exploit": "零日漏洞",
    "Blackstar Hold": "黑星要塞",
    "Deadflare Zone": "死耀区",
    "Eclipse Bastion": "蚀日堡垒",
    "Frontline Outskirts": "前线外围",
    "Greyhall District": "灰厅区",
    "Ironfall Perimeter": "铁陨防线",
    "Oblivion Nexus": "湮灭枢纽",
    "Redline Fields": "红线原野",
    "Rustveil Transit": "锈幕中转站",
    "Silent Expanse": "寂静旷野",
    "Corrupted Rounds": "侵蚀弹药",
    "Echo Harvest": "回响收割",
    "Flux Capacitor": "通量电容器",
    "Frequency Tuning": "频率调谐",
    "Prototype Sync": "原型同步",
    "Signal Static Resistance": "信号静噪抗性",
    "Void Walker": "虚空行者",
    "Warden Slayer": "WARDEN 杀手",
    "Welcome Gift": "欢迎礼物",
    "First Blood": "第一滴血",
    "Boss Hunt": "猎杀头目",
    "Apex Predator": "顶级掠食者",
    "Body Count": "击杀记录",
    "Frontline Sweep": "前线扫荡",
    "Extraction Run": "撤离行动",
    "High Value Target": "高价值目标",
    "Corrupted Hostiles": "受蚀敌人",
    "District War": "城区战争",
    "Warden Trophy": "WARDEN 战利品",
    "Deadflare Operations": "死耀行动",
    "Dead Zone Delivery": "死区投送",
