    // ==== JS_UI parça 3: insanity düşmanları + sınıf adları + kalanlar ====
    "ARCHIVLICH": "档案巫妖",
    "SEGFAULT PRIME": "段错误至尊",
    "THE COMPILER": "编译者",
    "STATIC": "静噪",
    "NULL": "空值",
    "HEX": "咒术",
    "BIT": "比特",
    "ROT": "腐蚀",
    "OBSIDIAN": "黑曜石",
    "DEADLOCK": "死锁",
    "SPECTRE": "鬼影",
    "VIPER": "毒蛇",
    "RAILGUN": "轨道炮",
    "HELLSTORM": "地狱风暴",
    "SINGULARITY": "奇点",
    "PHANTOM": "幻影",
    "PUNISHER": "惩罚者",
    "CONDUIT": "导管",
    "TITAN": "泰坦",
    "GAMBLER": "赌徒",
    "ESC": "ESC",
    "SIPHON // VALUE": "虹吸 // 价值",
    "RECOMPILER": "重编译器",
    "OPTIMIZER": "优化器",
    "MIL-CAP": "军规电容",
    "RECOMP": "重编译",
