    // ==== JS_UI parça 9: trader replikleri + audit 1. dalga ====
    "Bring cash. I don't accept hope.": "带现金来。我不收希望。",
    "Cheap thrills cost fifty thousand.": "廉价的刺激也要五万块。",
    "Don't ask where I get them. Ask what they can do.": "别问我从哪弄来的。问它们能做什么。",
    "Don't think. Just pay and pray.": "别想。付钱，然后祈祷。",
    "Every corruption carries a gift. For those who can afford it.": "每一次侵蚀都藏着馈赠。给付得起的人。",
    "Every roll is a fresh chance at glory.": "每一次掷点都是通往荣耀的新机会。",
    "Everything works… until you start asking for guarantees.": "一切都好用……直到你开始要保修。",
    "Fifty grand says you're feeling lucky.": "五万块赌你今天手气不错。",
    "Flux flows. I merely redirect.": "通量在流动。我只是改个道。",
    "Fortune doesn't knock. She charges admission.": "财富女神不敲门。她收门票。",
    "Hold steady. The future doesn't wait for shaking hands.": "拿稳了。未来不等发抖的手。",
    "I can smell an empty wallet from across the room.": "隔着房间我都能闻出空钱包的味。",
    "I don't care where you got shot.": "你在哪挨的枪我不关心。",
    "I don't fix people. I refit them.": "我不修人。我改装人。",
    "If it fits, it leaves.": "装得下，就带走。",
    "If you're shopping, you're already losing.": "开始逛，就已经在输了。",
    "Next.": "下一位。",
    "No refunds. No reversals. Choose with your eyes open.": "不退款。不撤销。睁大眼睛选。",
    "Prices change when the streets get hungry.": "街头一饿，价格就变。",
    "Quiet hands. Quick choices.": "手要稳。选要快。",
    "Rare costs more. Fear costs even more.": "稀有很贵。恐惧更贵。",
    "Rarity is just probability wearing a disguise.": "稀有度不过是概率戴了张面具。",
    "Reality bends for a price. My price.": "现实可以弯曲，只要出价。出我的价。",
    "Sit still. I'm not here to comfort you.": "坐好别动。我不是来安慰你的。",
    "Straps. Buckles. Done.": "绑带。扣具。搞定。",
    "The deeper you go, the more I can offer.": "你走得越深，我能给的越多。",
    "The house always wins. But sometimes, so do you.": "庄家永远赢。但有时候，你也赢。",
    "The signal chose me. Your flux chooses what I share.": "信号选中了我。你的通量决定我分享什么。",
    "The signal remembers what the flesh forgets.": "血肉遗忘的，信号都记得。",
    "These aren't tools. They're keys to what's underneath.": "这些不是工具。是通往底层之物的钥匙。",
    "This is an upgrade, not a miracle.": "这是升级，不是奇迹。",
    "Try it. Pay. Move.": "试试。付钱。走人。",
    "Walk away rich or walk away lighter. Your call.": "满载而归，或者两袖清风。你选。",
    "You hear static? I hear opportunity.": "你听到的是静噪？我听到的是机会。",
    "You want it cheap? Go wish somewhere else.": "想要便宜？上别处许愿去。",
    "You'll pay twice out there if you try to save here.": "在这省的钱，出去要加倍还。",
    "You'll walk out improved, just not the way you imagined.": "你会带着提升走出去，只是未必是你想的那种。",
    "Your body's behind schedule. I can catch it up.": "你的身体落后于时代了。我能帮它赶上。",
    "Your standing here? It tips the scales.": "你在这里的声望？它能压秤。",
    "Enemy Detection Range": "敌人侦测范围",
    "Autosave": "自动存档",
    "* INJECT QUEUE": "* 注入队列",
    "AUGMENTED": "已义体化",
    "Accessories": "配饰",
    "Backpacks": "背包",
    "Body Armor": "护甲",
    "Ambusher": "伏击者",
    "Any unsaved progress will be lost.": "任何未保存的进度都将丢失。",
    "Are you sure you want to reset the skill tree?": "你确定要重置技能树吗？",
    "Chance to avoid attacks": "闪避攻击的概率",
    "Chance to hit vital areas": "命中要害的概率",
    "Damage multiplier on headshots": "爆头伤害倍率",
    "Assassinate": "暗杀",
    "Deflect": "偏转",
    "Edge of Death": "死亡边缘",
    "Chop Chop!": "咔嚓咔嚓！",
    "DEPLOY ANYWAY": "仍然部署",
    "INS": "疯狂",
    "Tech": "科技",
    "HP/sec": "生命/秒",
    "boss cache chance": "头目补给箱概率",
    "crit chance": "暴击率",
    "raid damage": "RAID 伤害",
    "damage taken": "受到伤害",
    "cases per open": "每次开启箱数",
    "clicks/sec": "点击/秒",
    "nodes remaining": "剩余节点",
    "Standing XP": "声望经验",
    "When you spot an enemy first, you sneak behind them and deal double damage on your first hit.": "当你先发现敌人时，你会潜行到其身后，首次攻击造成双倍伤害。",
    "Codes injected via vault are guaranteed in the next roll.": "通过保险库注入的代码将在下一次掷点中保底出现。",
    "Open Code Vault tab. Click a code to add it to inject queue.": "打开代码保险库页。点击代码将其加入注入队列。",
    "Switch to Terminal tab. Use the matching currency:": "切换到终端页。使用对应的货币：",
