    // ==== часть 22: тултипы бустов/баффов + миграция em-dash ====
    "+180 damage (only in a grid corner)": "+180 урона (только в углу сетки)",
    "FRENZY": "БЕШЕНСТВО",
    "IRON SKIN": "ЖЕЛЕЗНАЯ КОЖА",
    "NANOWEAVE": "НАНОПЛЕТЕНИЕ",
    "HYDRAULIC": "ГИДРАВЛИКА",
    "SURGE": "ВСПЛЕСК",
    "COIN": "МОНЕТА",
    "BET": "СТАВКА",
    "BLOOD DEBT: +10% damage": "КРОВАВЫЙ ДОЛГ: +10% урона",
    "BLUR: +30% evasion (5s)": "РАЗМЫТИЕ: +30% уклонения (5 сек.)",
    "The warden relinquished a MYTHIC CACHE. Open it in the CACHES panel.": "WARDEN оставил MYTHIC тайник. Откройте его на панели тайников.",
    "Type 'help' for commands...": "Введите 'help' для команд...",
