    // ==== часть 25: полный охват (уведомления + боевые флоаты) ====
    "Diamond": "Алмаз",
    "Durability": "Прочность",
    "Extract Point": "Точка эвакуации",
    "Juvenile": "Молодой",
    "primary": "Основное оружие",
    "secondary": "Вторичное оружие",
    "+1 Skill Point acquired.": "+1 очко навыка получено.",
    "2x raid speed active.": "2x скорость RAID активирована.",
    "All drops foreseen.": "Все дропы предвидены.",
    "Free stash space first": "Сначала освободите место в хранилище",
    "Free stash space first.": "Сначала освободите место в хранилище.",
    "Free stash space to complete the deal": "Освободите место в хранилище, чтобы завершить сделку",
    "INSUFFICIENT FUNDS": "НЕДОСТАТОЧНО СРЕДСТВ",
    "Instant teleport to extract ready.": "Мгновенная телепортация к точке эвакуации готова.",
    "Item move cancelled": "Перемещение предмета отменено",
    "Mining stopped. Out of fuel.": "Добыча остановлена. Топливо закончилось.",
    "Mythic items are priceless, no trader will touch them.": "MYTHIC предметы бесценны, ни один торговец к ним не прикоснется.",
    "Restock costs $10,000": "Пополнение запасов стоит $10,000",
    "Saving is disabled during a raid": "Сохранение во время RAID отключено",
    "Signal Harvest (Loadout > Mastery)": "Signal Harvest (Loadout > Mastery)",
    "Teleport-hunting online.": "Охота за телепортами запущена.",
    "The flip stands but there is no space": "Решение в силе, но нет места",
    "The flip stands but you cannot pay": "Решение в силе, но вы не можете заплатить",
    "The trader accepted but you cannot pay": "Торговец принял, но вы не можете заплатить",
    "This item already owns every ability it can hold.": "Этот предмет уже обладает всеми возможными способностями.",
    "This item cannot be salvaged": "Этот предмет нельзя разобрать",
    "This item cannot be sold": "Этот предмет нельзя продать",
    "Unlock it first to sell or salvage": "Сначала разблокируйте, чтобы продать или разобрать",
    "Unlock this item to sell it.": "Разблокируйте этот предмет, чтобы продать его.",
    "Visit Ripperdoc in the TRADERS tab to initiate the Evolution Protocol.": "Посетите RIPPERDOC во вкладке TRADERS, чтобы начать протокол Эволюции.",
    "You do not own that module.": "У вас нет этого модуля.",
    "Your companion is not for sale.": "Ваш напарник не продается.",
    "Save data is getting large. Claim pending GUNSMITH QUESTS items and free stash space.": "Размер сохранений растет. Заберите предметы из GUNSMITH QUESTS и освободите место в хранилище.",
    "\"CRIMSON GAZE\" added to your augment locker.\nHe kept it for you. Just in case.": "\"CRIMSON GAZE\" добавлен в ваш шкаф аугментаций.\nОн приберег его для вас. На всякий случай.",
    "All class keystones are now available.": "Все ключевые навыки классов теперь доступны.",
    "All slots full. Free a slot first": "Все слоты заняты. Сначала освободите слот",
    "Automation stopped after 3 consecutive deaths.": "Автоматизация остановлена после 3 смертей подряд.",
    "Check your gear and filters before continuing.": "Проверьте снаряжение и фильтры перед продолжением.",
    "Close this tab to exit": "Закройте эту вкладку, чтобы выйти",
    "Complete your raid first, then visit the Ripperdoc in the TRADERS tab.": "Сначала завершите свой RAID, затем посетите RIPPERDOC во вкладке TRADERS.",
    "ESCAPE FAILED": "ПОБЕГ ПРОВАЛЕН",
    "I see you.": "Я тебя вижу.",
    "If stash is empty: Scav gear + Silent Expanse CL0": "Если хранилище пусто: Scav-снаряжение + Silent Expanse CL0",
    "Loading save...": "Загрузка сохранения...",
    "No materials recovered.": "Материалы не получены.",
    "On death: Auto-heal → Equip best gear from stash → Redeploy": "При смерти: Авто-лечение → Экипировка лучшего снаряжения из хранилища → Передислокация",
    "Route collapsed": "Путь обрушен",
    "Skill Point Drive now available at Ripperdoc.": "Skill Point Drive теперь доступен у RIPPERDOC.",
    "Slot data not found": "Данные слота не найдены",
    "Something was left behind for you. Return to the hideout later.": "Что-то осталось для вас. Вернитесь в убежище позже.",
    "Storage error while loading. Free stash space and try again.": "Ошибка хранилища при загрузке. Освободите место в хранилище и попробуйте снова.",
    "Storage is full. Delete a save slot and try again.": "Хранилище полно. Удалите слот сохранения и попробуйте снова.",
    "Storage is full. Delete a save slot to free space.": "Хранилище полно. Удалите слот сохранения, чтобы освободить место.",
    "The rest is up to you, Operator.": "Остальное за вами, Оператор.",
    "◆ MYTHIC CACHE": "◆ MYTHIC ТАЙНИК",
    "RICOCHET!": "РИКОШЕТ!",
    "__patterns": [
        ["^(-?\\d+) HEADSHOT! x2!$", "$1 Хедшот! x2!"],
        ["^(-?\\d+) HEADSHOT!$", "$1 Хедшот!"],
        ["^(-?\\d+) (L\\.ARM|R\\.ARM|L\\.LEG|R\\.LEG|BODY|HEAD|THORAX|STOMACH) EXHAUSTION!$", "$1 $2 Истощение!", "T"],
        ["^(-?\\d+) (L\\.ARM|R\\.ARM|L\\.LEG|R\\.LEG|BODY)$", "$1 $2", "T"],
        ["^No (.+) weapon equipped, using (.+)$", "Без $1, использую $2", "T"],
        ["^\\+(\\d+) ECHO POINTS?$", "+$1 очков Echo"],
        ["^(.+) cannot fit this item type\\.$", "$1 не может принять этот тип предметов."],
        ["^(.+) has no key now$", "$1 больше нет ключа"],
        ["^(.+) is used in raids or the workbench$", "$1 используется в RAID или на верстаке"],
        ["^(\\d+) item\\(s\\) held, go to GUNSMITH QUESTS to claim$", "$1 предмет(ов) удержан, перейдите в GUNSMITH QUESTS, чтобы забрать"],
        ["^(.+) returned to stash\\.$", "$1 возвращен в хранилище."],
        ["^Auto-refuel needs \\$([\\d.,]+)$", "Автозаправка требует $$$1"],
        ["^Current filters saved to slot (\\d+)$", "Текущие фильтры сохранены в слот $1"],
        ["^Filter preset (\\d+) applied$", "Применен пресет фильтра $1"],
        ["^Found: (.+)$", "Найдено: $1"],
        ["^Insurance costs \\$([\\d.,]+)$", "Страховка стоит $$$1"],
        ["^Level (\\d+) \\+(\\d+) Skill Points?$", "Уровень $1, +$2 очков навыков"],
        ["^Need \\$([\\d.,]+) · ([\\d.,]+) flux · ([\\d.,]+) insanity$", "Нужно $$$1 · $2 flux · $3 insanity"],
        ["^Need \\$([\\d.,]+)$", "Нужно $$$1"],
        ["^Prestige points follow main progression here \\(P(\\d+) = (\\d+) points\\)\\. Your mastery was reset for free, re-allocate anytime\\.$", "Очки Prestige теперь следуют основной прогрессии (P$1 = $2 очков). Ваше мастерство было сброшено бесплатно, перераспределите в любое время."],
        ["^Saved to slot (.+)$", "Сохранено в слот $1"],
        ["^(.+) transferred\\. Keep moving\\.$", "$1 перенесено. Двигайтесь дальше."],
        ["^(\\d+) item\\(s\\) lost: stash full$", "$1 предмет(ов) потерян: хранилище полно"],
        ["^(\\d+) slots? equipped$", "$1 слот(ов) экипировано"],
        ["^Fight Warden CL(\\d+) ready \\((\\d+)/(\\d+) available\\)$", "Бой с WARDEN CL$1 готов ($2/$3 доступно)"],
        ["^Insufficient funds for healing\\. Need \\$([\\d.,]+) to recover\\.$", "Недостаточно средств для лечения. Нужно $$$1 для восстановления."],
        ["^SALVAGED (.+)$", "РАЗОБРАНО: $1"],
        ["^CL(\\d+) UNLOCKED!$", "CL$1 РАЗБЛОКИРОВАНО!"],
        ["^(PAINKILLER|SECOND WIND) \\+(\\d+) HP$", "$1 +$2 ОЗ", "T"],
        ["^SWITCHED: (.+)$", "ПЕРЕКЛЮЧЕНО: $1", "T"],
        ["^BURST (\\d+)$", "ВЗРЫВ $1"],
        ["^CLONE (\\d+)$", "КЛОН $1"],
        ["^DBL \\+(\\d+)$", "X2 +$1"],
        ["^DEFLECT (\\d+)$", "ОТБИТИЕ $1"],
        ["^MELTDOWN (\\d+)$", "РАСПЛАВЛЕНИЕ $1"],
        ["^ORBITAL (\\d+)$", "ОРБИТАЛЬНЫЙ УДАР $1"],
        ["^QUANTUM (\\d+)$", "КВАНТОВЫЙ $1"],
        ["^REFLECT (\\d+)$", "ОТРАЖЕНИЕ $1"],
        ["^STRIKE \\+(\\d+)$", "УДАР +$1"],
        ["^TAP \\+(\\d+)$", "КЛИК +$1"],
        ["^AUTO-CLICKER ([IVX]+)$", "АВТО-КЛИКЕР $1"],
        ["^(-?\\d+) (HEAD|THORAX|STOMACH|LEFT ARM|RIGHT ARM|LEFT LEG|RIGHT LEG|FULL BODY) EXHAUSTION!$", "$1 $2 Истощение!", "T"],
        ["^(-?\\d+) (HEAD|THORAX|STOMACH|LEFT ARM|RIGHT ARM|LEFT LEG|RIGHT LEG|FULL BODY)$", "$1 $2", "T"],
        ["^ROCKET (\\d+)$", "РАКЕТА $1"],
        ["^SLAM (\\d+)$", "УДАР ОБ ЗЕМЛЮ $1"],
        ["^ORB (\\d+)$", "СФЕРА $1"],
        ["^(\\d+) weapon\\(s\\)$", "$1(ов) оружие(й)"],
        ["^> ESCAPE_ROUTE: (\\d+)/(\\d+)$", "> ПУТЬ ОТХОДА: $1/$2"],
        ["^(.+): (.+) \\((\\d+:\\d+)\\)$", "$1: $2 ($3)", "T"],
        ["^(.+): (.+) ×(\\d+)$", "$1: $2 ×$3", "T"],
        ["^FRENZY (\\d+)/(\\d+): \\+(\\d+)% DMG per kill$", "БЕШЕНСТВО $1/$2: +$3% урона за убийство"],
        ["^IRON (\\d+)/(\\d+): \\+(\\d+) AC per hit taken$", "ЖЕЛЕЗНАЯ КОЖА $1/$2: +$3 брони за полученный удар"],
        ["^NANO (\\d+)/(\\d+): \\+(\\d+) AC \\(adaptive armor\\)$", "НАНО $1/$2: +$3 брони (адаптивная броня)"],
        ["^RAGE (\\d+)/(\\d+): \\+(\\d+)% DMG$", "ЯРОСТЬ $1/$2: +$3% урона"],
        ["^CHAIN (\\d+)/(\\d+): \\+(\\d+)% melee DMG$", "КОМБО $1/$2: +$3% урона в ближнем бою"],
        ["^CHAIN (\\d+)/(\\d+): \\+(\\d+)% ranged DMG$", "КОМБО $1/$2: +$3% урона в дальнем бою"],
        ["^SURGE (\\d+)/(\\d+): bonus DMG shots$", "ВСПЛЕСК $1/$2: бонусные выстрелы с уроном"],
        ["^COIN: (.+), match type \\+50% DMG$", "МОНЕТА: $1, тип совпадения +50% урона"],
        ["^BET: (.+), \\+30% attack speed$", "СТАВКА: $1, +30% к темпу стрельбы"],
        ["^BET: (.+), \\+30% damage reduction$", "СТАВКА: $1, +30% снижения урона"],
        ["^OVERLOAD (\\d+)/(\\d+): max stacks → all elements$", "ПЕРЕГРУЗКА $1/$2: макс. стаки → все стихии"],
        ["^Raid damage \\+(\\d+)% \\(permanent\\)\\. Every 10 rebirths adds \\+(\\d+)%\\. Crown complete\\.$", "Урон RAID +$1% (перманентно). Каждые 10 перерождений добавляет +$2%. Корона собрана."],
        ["^Raid damage \\+(\\d+)% \\(permanent\\)\\. Every 10 rebirths adds \\+(\\d+)%, up to \\+100%\\.$", "Урон RAID +$1% (перманентно). Каждые 10 перерождений добавляет +$2%, макс. +100%."],
        ["^EVOLUTION COMPLETE · PRESTIGE (\\d+)$", "ЭВОЛЮЦИЯ ЗАВЕРШЕНА · PRESTIGE $1"],
        ["^\\+([A-Z].{2,})$", "+$1", "T"],
        ["^(\\d+)% \\(cap\\) ×([\\d.]+)$", "$1% (кап) ×$2"],
        ["^-(\\d+)% map below level$", "-$1% (карта ниже вашего уровня)"],
        ["^FOUND: (.+)$", "НАЙДЕНО: $1"],
        ["^SCOUTED: (.+)$", "РАЗВЕДЕНО: $1"],
        ["^(.+) FOUND (\\d+) ITEMS$", "$1 НАШЕЛ $2 предметов"],
        ["^TURRET (\\d+)$", "ТУРЕЛЬ $1"],
        ["^Auto-fires (\\d+)x at (\\d+)% player DMG every ([\\d.]+)s\\.$", "Авто-огонь $1 раз каждые $3 сек., наносит $2% урона игроку."],
        ["^Install: ([\\d.]+) clicks/sec$", "Установка: $1 клик/сек"],
        ["^([\\d.]+) clicks/sec \\(MAX\\)$", "$1 клик/сек (МАКС)"],
        ["^([\\d.]+) → ([\\d.]+) clicks/sec$", "$1 → $2 клик/сек"],
        ["^([\\d.,K]+%) → ([\\d.,K]+%) raid damage$", "Урон RAID $1 → $2"],
        ["^([\\d.]+)% HP/sec$", "$1% ОЗ/сек"],
        ["^([\\d.]+)% \\(full\\)$", "$1% (полно)"],
        ["^HOLLOW CROWN ([IVX]+): \\+(\\d+)% raid damage \\(MAX\\)$", "HOLLOW CROWN $1: +$2% урона RAID (МАКС)"],
        ["^HOLLOW CROWN ([IVX]+): \\+(\\d+)% raid damage · next \\+(\\d+)% at rebirth (\\d+)$", "HOLLOW CROWN $1: +$2% урона RAID · след. +$3% при перерождении ($4)"],
        ["^> (\\d+) EP per first-time CL clear \\(warden kill\\) on each map · (\\d+) nodes, tree costs more than the max (\\d+) EP pool$", "> $1 EP за первое прохождение CL на каждой карте (убийство WARDEN) · $2 узлов, стоимость древа выше макс. пула в $3 EP"],
        ["^> Permanent upgrades bought with INSANITY · rank cost grows ×([\\d.]+) · earned in the INSANITY terminal$", "> Постоянные улучшения за INSANITY · цена ранга растет ×$1 · добывается в терминале INSANITY"],
        ["^Cost: ([\\d.,]+) Flux$", "Стоимость: $1 Flux"],
        ["^RESET MASTERY · ([\\d.,]+) FLUX$", "СБРОС МАСТЕРСТВА · $1 FLUX"],
        ["^RESPEC · ([\\d.,]+) FLUX$", "ПЕРЕРАСПРЕДЕЛЕНИЕ · $1 FLUX"],
        ["^ALLOCATE · ([\\d.,]+) EP$", "РАСПРЕДЕЛЕНИЕ · $1 EP"],
        ["^ALLOCATE · ([\\d.,]+) INS$", "РАСПРЕДЕЛЕНИЕ · $1 INS"],
        ["^COMBO x(\\d+)$", "КОМБО x$1"],
        ["^FLUX: ([\\d.,]+)$", "FLUX: $1"],
        ["^INSANITY: ([\\d.,]+)$", "INSANITY: $1"],
        ["^ECHO POINTS: (\\d+)/(\\d+)$", "ECHO POINTS: $1/$2"],
        ["^✓ (.+)$", "✓ $1", "T"],
        ["^\\((module|combo|grid|core)\\)$", "($1)", "T"],
        ["^([A-Z]+) SLOT$", "$1 СЛОТ", "T"],
        ["^Holds: (.+) \\(unlocks with the condition\\)$", "Вместимость: $1 (разблокируется при условии)", "T"],
        ["^Holds: (.+)$", "Вместимость: $1", "T"],
        ["^GRID BONUS: (.+)$", "БОНУС СЕТКИ: $1", "T"],
        ["^GRID: (.+)$", "СЕТКА: $1", "T"],
        ["^\\+(\\d+) rows$", "+$1 ряд(ов)"],
        ["^Expand stash \\(\\+(\\d+) rows\\) \\[Lv(\\d+)/(\\d+)\\]$", "Расширить хранилище (+$1 ряд(ов)) [Lv$2/$3]"],
        ["^BOOST PROTO \\+([\\d.]+)% \\$([\\d.,]+)$", "PROTO усиление +$1% $$$2"],
        ["^GAMBLE \\$([\\d.,]+)$", "АВАНТЮРА $$$1"],
        ["^([\\d,.]+) FLX$", "$1 FLX"],
        ["^([\\d,.]+) INS$", "$1 INS"],
        ["^(.+): \\$([\\d.,]+) · ([\\d.,]+) FLX · ([\\d.,]+) INS$", "$1: $$$2 · $3 FLX · $4 INS", "T"],
        ["^([\\d.,]+) items → \\$([\\d.,]+) from (.+)$", "$1 предмет(ов) → $$$2 (из $3)"],
        ["^BULK SALVAGE: ([\\d.,]+) items$", "МАССОВЫЙ РАЗБОР: $1 предмет(ов)"],
        ["^(\\d+)\\. empty (\\.+)$", "$1. пусто $2"],
        ["^PROTOTYPE SYNC: ([\\d.]+)%$", "СИНХРОНИЗАЦИЯ PROTOTYPE: $1%"],
        ["^SYNC: ([\\d.]+)%$", "СИНХРОНИЗАЦИЯ: $1%"],
        ["^\\[([A-Z]+)\\]$", "[$1]", "T"],
        ["^· (.+) · placing (.+) \\($", "· $1 · установка $2 (", "T"],
        ["^([A-Za-z][A-Za-z ]+) \\+([\\d.,]+)$", "$1 +$2", "T"],
        ["^LOCKED: REACH LV (\\d+)$", "ЗАБЛОКИРОВАНО: нужен LV $1"],
        ["^LAYER (\\d+)$", "СЛОЙ $1"],
        ["^LVL (\\d+)$", "LVL $1"],
        ["^LVL\\.(\\d+)$", "LVL $1"],
        ["^CHECKPOINT: (\\d+)$", "ЧЕКПОИНТ: $1"],
        ["^ENHANCE TO \\+(\\d+)$", "УЛУЧШИТЬ ДО +$1"],
        ["^TASK (\\d+)/(\\d+)$", "ЗАДАЧА $1/$2"],
        ["^PHASE (\\d+)$", "ФАЗА $1"],
        ["^SEC: (.+)$", "СЕКТОР: $1"],
        ["^SECTOR: (.+)$", "СЕКТОР: $1", "T"],
        ["^ROOT works on STANDARD gear only\\. This item is ([A-Z]+)\\.$", "ROOT работает только на STANDARD снаряжении. Этот предмет — $1."],
        ["^AUTO-I(NSANITY)? OVERCLOCK$", "АВТО-OVERCLOCK (INSANITY)"],
        ["^REWARD: (.+)$", "НАГРАДА: $1"],
        ["^WAVE (\\d+)$", "ВОЛНА $1"],
        ["^SLOT (\\d+)$", "СЛОТ $1"],
        ["^RANK (\\d+)$", "Ранг $1"],
        ["^\\+(\\d+) INSANITY$", "+$1 INSANITY"],
        ["^(\\d+) KILLS$", "$1 УБИЙСТВ"],
        ["^REBIRTH #(\\d+)$", "ПЕРЕРОЖДЕНИЕ #$1"],
        ["^Rebirths: (\\d+)$", "Перерождений: $1"],
        ["^REQ: P(\\d+) · CL(\\d+)$", "ТРЕБУЕТСЯ: P$1 · CL$2"],
        ["^COMBO x(\\d+)$", "КОМБО x$1"],
        ["^HEAL \\((.+)\\)$", "ЛЕЧЕНИЕ ($1)"],
        ["^LAYER (\\d+) - CLAIMED$", "СЛОЙ $1 - ПОЛУЧЕНО"],
        ["^OPERATIVE (.+)$", "ОПЕРАТИВНИК $1"],
        ["^QUEST COMPLETE: (.+)$", "ЗАДАНИЕ ВЫПОЛНЕНО: $1", "T"],
        ["^\\+([\\d.]+)(%?) (.+) per point, max \\+([\\d.]+)%$", "+$1$2 $3 за очко, макс. +$4%", "T"],
        ["^\\+([\\d.]+)(%?) (.+) per point$", "+$1$2 $3 за очко", "T"],
        ["^\\+([\\d.]+)% (.+)$", "+$1% $2", "T"],
        ["^\\+([\\d.]+) (.+)$", "+$1 $2", "T"],
        ["^-([\\d.]+)% (.+)$", "-$1% $2", "T"],
        ["^(.+): (\\d+)/(\\d+)$", "$1: $2/$3", "T"],
        ["^(.+) standing \\+(\\d+)$", "$1 престиж +$2"],
        ["^Kill (\\d+) enemies$", "Убей $1 врага(ов)"],
        ["^Kill (\\d+) enemies on (.+)$", "Убей $1 врага(ов) на $2", "T"],
        ["^Kill (\\d+) at CL(\\d+)\\+$", "Убей $1 на CL$2+"],
        ["^Extract (\\d+) times$", "Эвакуация $1 раз(а)"],
        ["^Extract from (.+)$", "Эвакуация из $1", "T"],
        ["^Loot items worth \\$(\\d+)$", "Собрать добычу на $$$1"],
        ["^Salvage (\\d+) items$", "Разобрать $1 предмет(ов)"],
        ["^Sell \\$(\\d+) to any trader$", "Продать за $$$1 любому торговцу"],
        ["^Loot a (.+)\\+ item$", "Найти предмет $1+", "T"],
        ["^Extract with \\$(\\d+)\\+ loot value$", "Эвакуироваться с добычей на $$$1+"],
        ["^(.+) Boss$", "$1 БОСС", "T"],
        ["^ECHO (.+)$", "ЭХО $1", "T"],
        ["^\\[ (.+) \\]$", "[ $1 ]", "T"],
        ["^(.+): (\\d+) ?/ ?(\\d+)$", "$1: $2/$3", "T"],
        ["^(.+) \\((\\d+)/(\\d+)\\)$", "$1 ($2/$3)", "T"],
        ["^(.+) FOUND (\\d+) ITEMS$", "$1 НАШЕЛ $2 предметов"],
        ["^(.+) instantly finds (\\d+) items at the start of every raid\\. Mark what to search for[:：]$", "$1 мгновенно находит $2 предмета в начале каждого RAID. Отметьте, что искать:"],
        ["^Quicksave (\\d+)/(\\d+) (\\d+):(\\d+)$", "Быстрое сохранение $1/$2 $3:$4"],
        ["^This keystone belongs to (.+)$", "Этот ключевой навык принадлежит $1", "T"],
        ["^When your HP drops below (\\d+)%,$", "Когда ваши ОЗ падают ниже $1%,"],
        ["^instantly recover (\\d+)% of your Maximum HP\\.$", "мгновенно восстановить $1% макс. ОЗ."],
        ["^recover (\\d+)% of your Maximum HP\\.$", "восстановить $1% макс. ОЗ."],
        ["^While above (\\d+)% HP,$", "Пока ОЗ выше $1%,"],
        ["^While below (\\d+)% HP,$", "Пока ОЗ ниже $1%,"],
        ["^gain (\\d+)% increased (.+?)\\.?$", "получить +$1% к $2.", "T"],
        ["^Take (\\d+)% reduced Damage\\.$", "получать на $1% меньше урона."],
        ["^\\+(\\d+)% increased (.+) for this combat\\.$", "+$1% к $2 на этот бой.", "T"],
        ["^Stacks up to (\\d+)%\\.$", "Стаки до $1%."],
        ["^capped at \\+(\\d+)%\\.$", "лимит +$1%."],
        ["^\\+(\\d+)% (.+) per (\\d+) (.+),$", "+$1% к $2 за каждый $3 $4,", "T"],
        ["^Gamble effects are (\\d+)% less extreme$", "Эффекты азартных игр менее экстремальны на $1%"],
        ["^(\\d+)% increased Damage\\.$", "+$1% к урону."],
        ["^Restore (.+) to full durability\\?$", "Восстановить $1 до полной прочности?", "T"],
        ["^Prototypes only \\((\\d+) items?\\)$", "Только PROTOTYPE ($1 шт.)"],
        ["^Total: \\$([\\d.,]+)$", "Итого: $$$1"],
        ["^room for (\\d+)$", "место для $1"],
        ["^\\[Stash: (\\d+)\\]$", "[Хранилище: $1]"],
        ["^Standing Lv\\.(\\d+)$", "Престиж Lv.$1"],
        ["^REBIRTHS: (\\d+) · ×(\\d+) DMG & HP$", "ПЕРЕРОЖДЕНИЯ: $1 · ×$2 DMG и HP"],
        ["^Reach layer (\\d+) this cycle \\(now (\\d+)\\)$", "Достичь слоя $1 в этом цикле (сейчас $2)"],
        ["^RESTOCK \\$(\\d+)K$", "ПОПОЛНЕНИЕ $$$1K"],
        ["^UPGRADE \\$(\\d+)K$", "УЛУЧШЕНИЕ $$$1K"],
        ["^RIG-(\\d+)$", "RIG-$1"],
        ["^(\\S+) (Smartframe|Vanta|Kestrel|Ironclad|RustTek) (.+)$", "$1 $2 $3", "T"],
        ["^(Smartframe|Vanta|Kestrel|Ironclad|RustTek) (\\w+)( T\\d)?$", "$1 $2$3", "T"],
        ["^✦ GOLDEN (.+)$", "✦ GOLDEN $1", "T"],
        ["^GOLDEN (.+)$", "GOLDEN $1", "T"],
        ["^(Swift|Heavy|Armored|Shielded|Enraged|Fortified) (.+)$", "$1$2", "T"],
        ["^Raid movement speed: \\+(\\d+)% per point, max \\+(\\d+)%$", "Скорость движения в RAID: +$1% за очко, макс. +$2%"],
        ["^\\+([\\d.]+) (.+) and \\+([\\d.]+) (.+) per point$", "+$1 $2 и +$3 $4 за очко", "T"],
        ["^Deal (\\d+)% increased (.+?)\\.?$", "Наносит +$1% к $2.", "T"],
        ["^to enemies above (\\d+)% HP\\.$", "(врагам с HP выше $1%)"],
        ["^Execute enemies below (\\d+)% HP\\.$", "Казнит врагов с HP ниже $1%."],
        ["^Gain (\\d+) (.+?)\\.$", "Получено $1 $2.", "T"],
        ["^Your attacks ignore an additional (\\d+)% Armor\\.$", "Ваши атаки игнорируют дополнительные $1% брони."],
        ["^grants \\+(\\d+)% (?:increased )?(.+?)\\.?$", "дает +$1% к $2.", "T"],
        ["^grants \\+(\\d+)% (.+), up to (\\d+)%\\.$", "дает +$1% к $2, макс. до $3%.", "T"],
        ["^gain (\\d+)% increased (.+?) for (\\d+) seconds?\\.$", "получает +$1% к $2 на $3 сек.", "T"],
        ["^you have a (\\d+)% chance to gain (\\d+)% increased (.+)$", "шанс $1% получить +$2% к $3", "T"],
        ["^and a (\\d+)% chance to gain (\\d+)% (.+)$", "и шанс $1% получить $2% $3", "T"],
        ["^you have a (\\d+)% chance to take (\\d+)% reduced damage$", "шанс $1% получить на $2% меньше урона"],
        ["^deals (\\d+)% reduced Damage\\.$", "наносит на $1% меньше урона."],
        ["^If HP falls below (\\d+)% during combat:$", "Если ОЗ упадут ниже $1% во время боя:"],
        ["^(\\d+)% chance to heal (\\d+)% of max HP\\. Cooldown: (\\d+) Seconds$", "$1% шанс восстановить $2% макс. ОЗ. КД: $3 сек"],
        ["^%(\\d+) chance to (gain|reduce|take) (.+)$", "%$1 шанс $2 $3", "T"],
        ["^Each hit grants (\\d+) Overload points?\\.$", "Каждое попадание дает $1 очко Overload."],
        ["^At (\\d+) Overload, your weapon discharges on the enemy,$", "При достижении $1 Overload, ваше оружие разряжается в противника,"],
        ["^Your first attack deals double damage and stuns for (\\d+) seconds?\\.$", "Ваша первая атака наносит двойной урон и оглушает на $1 сек."],
        ["^The enemy is stunned for (\\d+) seconds? and takes (\\d+)% increased damage\\.$", "Враг оглушен на $1 сек. и получает на $2% больше урона."],
        ["^Consumes (\\d+) Stamina\\.$", "Потребляет $1 выносливости."],
        ["^Cooldowns?: (\\d+) [Ss]econds?\\.?$", "Перезарядка: $1 сек."],
        ["^Gamble wins are (\\d+)% stronger\\. Gamble losses are (\\d+)% softer\\.$", "Выигрыши в азартных играх сильнее на $1%. Проигрыши мягче на $2%."],
        ["^Enemies deal (\\d+)% increased Damage to you\\.$", "Враги наносят вам на $1% больше урона."],
        ["^SEED CACHE ×(\\d+)$", "SEED CACHE ×$1"],
        ["^OPEN AGAIN \\((\\d+)\\)$", "ОТКРЫТЬ СНОВА ($1)"],
        ["^CL(\\d+) (.+)$", "CL$1 $2", "T"],
        ["^EQUIPPED · (.+)$", "ЭКИПИРОВАНО · $1", "T"],
        ["^SALVAGED (.+)$", "РАЗОБРАНО $1", "T"],
        ["^(\\d+) new objectives?$", "$1 новых задач"],
        ["^iLvl: (\\d+)$", "iLvl: $1"],
        ["^Install: (.+)$", "Установка: $1", "T"],
        ["^KERNELS \\[(\\d+)/(\\d+)\\]$", "ЯДРА [$1/$2]"],
        ["^PATCHES \\[(\\d+)/(\\d+)\\]$", "ПАТЧИ [$1/$2]"],
        ["^INJECT Q \\((\\d+)/(\\d+)\\)$", "ОЧЕРЕДЬ ИНЪЕКЦИЙ ($1/$2)"],
        ["^QUEUED (\\d+)/(\\d+)$", "В ОЧЕРЕДИ $1/$2"],
        ["^(\\d+)x (.+)$", "$1x $2", "T"],
        ["^\\+([A-Z][A-Z ]+)$", "+$1", "T"],
        ["^(\\d+) empty \\.+$", "$1 пусто..."],
        ["^Expected: (.+)$", "Ожидается: $1"],
        ["^element +(\\d+)% chance to infuse with element\\.$", "элемент  $1% шанс наполнения стихией."],
        ["^glitch code +-> use 'glitch' to corrupt the selected item$", "glitch-код   -> используйте 'glitch', чтобы повредить предмет"],
        ["^anchor code +-> use 'anchor <mod_name>' to lock a mod$", "anchor-код   -> используйте 'anchor <имя_мода>', чтобы заблокировать мод"],
        ["^kernel codes +-> use 'kernel' \\(Enhanced -> Custom upgrade\\)$", "kernel-коды   -> используйте 'kernel' (Enhanced -> Custom Upgrade)"],
        ["^patch codes +-> use 'flash' / 'slot' / etc on Enhanced item$", "patch-коды   -> используйте 'flash' / 'slot' и т.д. на Enhanced предметах"],
        ["^Example: Queue (\\d+) kernel codes -> use 'kernel' on item -> both apply\\.$", "Пример: поставьте $1 kernel-код в очередь -> используйте 'kernel' на предмете -> применятся оба."],
        ["^═+ TECH CRAFT v(\\d+) COMMANDS ═+$", "═══════════ КОМАНДЫ TECH CRAFT v$1 ═══════════"],
        ["^║ +TECH TERMINAL v(\\d+) - INITIALIZED +║$", "║         TECH TERMINAL v$1 - ИНИЦИАЛИЗИРОВАНО         ║"],
        ["^© (\\d+) UNHUMAN\\. All Rights Reserved\\.$", "© $1 UNHUMAN. Все права защищены."],
        ["^◣ (.+) · LAYER (\\d+) ◢$", "◣ $1 · СЛОЙ $2 ◢", "T"],
        ["^(.+) ×(\\d+)$", "$1 ×$2", "T"],
        ["^(.+) \\((\\d+)m\\)$", "$1 ($2 мин.)", "T"],
        ["^AUTO-CLICKER (I{1,3}|IV|V)$", "АВТО-КЛИКЕР $1"],
        ["^AUTO-(I{1,3}|IV|V) OVERCLOCK$", "АВТО-OVERCLOCK $1"],
        ["^REBIRTH #(\\d+) · ×([\\d.,]+)$", "ПЕРЕРОЖДЕНИЕ #$1 · ×$2"],
        ["^REBIRTHS: (\\d+) · ×([\\d.,]+) DMG & HP$", "ПЕРЕРОЖДЕНИЯ: $1 · ×$2 DMG и HP"],
        ["^Reset to layer (\\d+) · gain ×([\\d.,]+) \\(→ ×([\\d.,]+)\\)$", "Сброс до слоя $1 · получение ×$2 (→ ×$3)"],
        ["^ALLOCATE · (\\d+) INS$", "РАСПРЕДЕЛЕНИЕ · $1 INS"],
        ["^RESET MASTERY · (\\d+) FLUX$", "СБРОС МАСТЕРСТВА · $1 FLUX"],
        ["^RESPEC · (\\d+) FLUX$", "ПЕРЕРАСПРЕДЕЛЕНИЕ · $1 FLUX"],
        ["^Requires: (.+?) (\\d+)$", "Требуется: $1 $2", "T"],
        ["^(\\d+) FLX$", "$1 FLX"],
        ["^FLUX: (\\d+)$", "FLUX: $1"],
        ["^INSANITY: (\\d+)$", "INSANITY: $1"],
        ["^PRESTIGE POINTS: (\\d+)/(\\d+)$", "ОЧКИ PRESTIGE: $1/$2"],
        ["^([\\d.,]+)/sec$", "$1/сек"],
        ["^(\\d+) \\(capped\\)$", "$1 (кап)"],
        ["^(\\d+) clicks/sec \\(MAX\\)$", "$1 клик/сек (МАКС)"],
        ["^crit ×([\\d.,]+) → ×([\\d.,]+)$", "крит ×$1 → ×$2"],
        ["^(\\d+) flux \\+ (.+)$", "$1 FLUX + $2", "T"],
        ["^(\\d+)% CHANCE$", "$1% ШАНС"],
        ["^(\\d+)K?% → (\\d+)K?% (.+)$", "$1% → $2% $3", "T"],
        ["^(\\d+)× (.+?) → unlocks an ABILITY SLOT$", "$1× $2 → разблокирует слот способности", "T"],
        ["^(.+?) \\+ (.+?) → unlocks an ABILITY SLOT$", "$1 + $2 → разблокирует слот способности", "T"],
        ["^(.+?) \\+ (.+?) → (.+)$", "$1 + $2 → $3", "T"],
        ["^(.+) has no key now$", "$1 больше нет клавиши", "T"],
        ["^(STANDARD|ENHANCED|CUSTOM|GLITCH|PROTOTYPE|MYTHIC) (GEAR|WEAPON)$", "$1 $2", "T"],
        ["^(\\S+) (SMARTFRAME|VANTA|KESTREL|IRONCLAD|RUSTTEK) (.+)$", "$1 $2 $3", "T"],
        ["^(.+) → STASH$", "$1 → ХРАНИЛИЩЕ", "T"],
        ["^Grid (\\d+)×(\\d+)$", "Сетка $1×$2"],
        ["^UPGRADE → (\\d+)×(\\d+)$", "УЛУЧШЕНИЕ → $1×$2"],
        ["^· (.+) · click a module, then hover the grid$", "· $1 · кликните на модуль, затем наведите на сетку", "T"],
        ["^Synergy tags: (.+)$", "Теги синергии: $1", "T"],
        ["^(\\w+) · (\\S+)$", "$1 · $2", "T"],
        ["^(\\w+) · (\\S+) \\((\\d+)×(\\d+)\\) · (\\w+)$", "$1 · $2 ($3×$4) · $5", "T"],
        ["^Complete any ability combo \\((.+)\\)$", "Завершите любое комбо способностей ($1)", "T"],
        ["^Consumes (\\d+)% stamina\\.$", "Потребляет $1% выносливости."],
        ["^gain \\+(\\d+)% increased (.+?) for this combat\\.?$", "получает +$1% к $2 в этом бою.", "T"],
        ["^Fires (\\d+) rockets dealing (\\d+) damage each\\. (\\d+)s CD\\.$", "Выпускает $1 ракет(ы) по $2 урона каждая. КД $3 сек."],
        ["^Fires (\\d+) burst shots at combat start\\. (\\d+)s CD\\.$", "Выпускает $1 залп(ов) в начале боя. КД $2 сек."],
        ["^Massive hit dealing (\\d+)% player damage\\. (\\d+)s CD\\.$", "Мощный удар, наносящий $1% урона игроку. КД $2 сек."],
        ["^Cloak for (\\d+)s\\. First hit \\+(\\d+)% crit\\.$", "Невидимость на $1 сек. Первый удар +$2% крита."],
        ["^Every (\\d+)th hit: \\+(\\d+)% bonus damage \\+ (\\d+)s stun\\.$", "Каждый $1-й удар: +$2% урона + $3 сек. оглушения."],
        ["^Spawns phantom clones, stunning enemy for (\\d+)s\\. (\\d+)s CD\\.$", "Создает фантомных клонов, оглушая врага на $1 сек. КД $2 сек."],
        ["^Revive once per raid at (\\d+)% HP\\.$", "Воскрешение раз за RAID при $1% ОЗ."],
        ["^Auto-fires (\\d+)x at (\\d+)% player DMG every (\\d+)s\\.$", "Авто-огонь $1 раз каждые $3 сек., наносит $2% урона игроку."],
        ["^Applies (\\d+)% max HP DoT over (\\d+)s\\. Max (\\d+) stacks\\.$", "Наносит $1% макс. ОЗ в сек. в течение $2 сек. Макс. $3 стака."],
        ["^First (\\d+) shots deal \\+(\\d+)% damage\\. (\\d+)s CD\\.$", "Первые $1 выстрелов наносят +$2% урона. КД $3 сек."],
        ["^First hit -(\\d+)%\\. \\+(\\d+) AC per hit taken \\(max (\\d+)\\)\\.$", "Первый удар -$1%. +$2 брони за полученный удар (макс. $3)."],
        ["^Regenerate (\\d+) HP out of combat\\. (\\d+)% faster healing\\.$", "Восстанавливает $1 ОЗ вне боя. Скорость лечения +$2%."],
        ["^Regenerate (\\d+) HP/s during combat\\. (\\d+)% damage reduction\\.$", "Восстанавливает $1 ОЗ/сек в бою. Снижение урона $2%."],
        ["^Increases loot speed by (\\d+)% \\(max (\\d+)%\\)\\.$", "Скорость сбора добычи +$1% (макс. $2%)."],
        ["^Passively increases damage by (\\d+)%\\.$", "Пассивно увеличивает урон на $1%."],
        ["^Auto-scans on map entry, revealing (\\d+) enemies\\.$", "Авто-сканирование при входе на карту: обнаружено $1 врага."],
        ["^Stun immunity\\. \\+(\\d+) bonus HP\\.$", "Иммунитет к оглушению. +$1 бонусного ОЗ."],
        ["^(\\d+)% lifesteal\\. \\+(\\d+) HP on kill\\.$", "$1% вампиризма. +$2 ОЗ при убийстве."],
        ["^(\\d+)% auto-dodge chance\\. Immune to ambushes\\.$", "$1% шанс авто-уклонения. Иммунитет к засадам."],
        ["^\\+(\\d+)% fire rate for (\\d+)s\\. (\\d+)s CD\\.$", "+$1% темпа стрельбы на $2 сек. КД $3 сек."],
        ["^\\+(\\d+)% damage per kill\\. Max (\\d+) stacks\\. Persists through raid\\.$", "+$1% урона за убийство. Макс. $2 стака. Действует весь RAID."],
        ["^\\+(\\d+)% AC, HP & Damage\\. (\\d+)% damage reduction\\.$", "+$1% брони, ОЗ и урона. $2% снижения урона."],
        ["^\\+(\\d+)% augment skill damage\\. (\\d+)% cooldown reduction\\.$", "+$1% урона способностей аугментаций. $2% CDR."],
        ["^\\+(\\d+)kg weight capacity\\. \\+(\\d+) SCV\\.$", "+$1кг к грузоподъемности. +$2 к SCV."],
        ["^\\+(\\d+) accuracy\\. \\+(\\d+) handling\\.$", "+$1 точности. +$2 к управляемости."],
        ["^\\+(\\d+) AC per hit\\. Max (\\d+) stacks\\.$", "+$1 брони за попадание. Макс. $2 стака."],
        ["^\\+(\\d+) damage, \\+(\\d+) armor pen$", "+$1 урона, +$2 пробития брони"],
        ["^\\+(\\d+) permanent damage per kill this raid$", "Постоянный +$1 урона за каждое убийство в этом RAID"],
        ["^\\+(\\d+)% damage vs enemies above (\\d+)% HP$", "+$1% урона врагам с HP выше $2%"],
        ["^\\+(\\d+)% max HP per second$", "+$1% макс. ОЗ в секунду"],
        ["^\\+(\\d+)% move speed\\. \\+(\\d+) evasion\\.$", "+$1% скорости движения. +$2 к уклонению."],
        ["^FIELD NOTES (\\d+)/(\\d+): (.+)$", "ПОЛЕВЫЕ ЗАМЕТКИ $1/$2: $3", "T"],
        ["^(.+?) Hit NEXT when you're ready\\.$", "$1 Жми ДАЛЕЕ, когда будешь готов.", "T"],
        ["^(.+?) Try it now\\.$", "$1 попробуйте сейчас.", "T"],
        ["^(.+?) Open it now\\.$", "$1 откройте сейчас.", "T"],
        ["^(.+?) Go on, click one\\.$", "$1 давайте, кликните на один.", "T"],
        ["^([+\\/-]) (.+)$", "$1 $2", "T"],
        ["^(.+) \\/ (.+)$", "$1 / $2", "T"],
        ["^(.+) -([\\d.]+)(%?)$", "$1 -$2$3", "T"],
        ["^(.+) \\[([A-Z+]+)\\]$", "$1 [$2]", "T"],
        ["^Insure (.+) against loss on death\\?$", "Застраховать $1 от потери при смерти?", "T"],
        ["^Gain (\\d+)% increased (.+)\\.$", "$2 увеличено на $1%.", "T"],
        ["^FOUND: (.+)$", "НАЙДЕНО: $1", "T"],
        ["^FROM: (.+) \\/\\/ (.+)$", "ИЗ: $1 // $2", "T"],
        ["^FROM: (.+)$", "ИЗ: $1", "T"],
        ["^(\\d+) items?$", "$1 шт."],
        ["^BULK SELL: (\\d+) items?$", "МАССОВАЯ ПРОДАЖА: $1 шт."],
        ["^(\\d+) items? → \\$([\\d.,]+) from (.+)$", "$1 шт. → $$$2 из $3"],
        ["^Glitch and below \\((\\d+) items?\\)$", "GLITCH и ниже ($1 шт.)"],
        ["^Mythic and below \\((\\d+) items?\\)$", "MYTHIC и ниже ($1 шт.)"],
        ["^Mythics only \\((\\d+) items?\\) · (\\d+)% module$", "Только MYTHIC ($1 шт.) · $2% модуль"],
        ["^Junk only, keeps artifacts \\((\\d+) items?\\)$", "Только хлам, сохраняет артефакты ($1 шт.)"],
        ["^(\\d+)% chance to return on death$", "$1% шанс вернуть при смерти"],
        ["^\\$([\\d.,]+) transferred\\. Keep moving\\.$", "$$$1 переведено. Двигайтесь дальше."],
        ["^\\$([\\d.,]+) \\+ (.+) transferred\\. Keep moving\\.$", "$$$1 + $2 переведено. Двигайтесь дальше.", "T"],
        ["^\\+(\\d+) FLUX transferred\\. Keep moving\\.$", "+$1 FLUX перенесено. Двигайтесь дальше."],
        ["^(\\d+) ROOT, (\\d+) FLASH, (\\d+) KERNEL chips transferred\\. Spend them\\.$", "$1 ROOT, $2 FLASH, $3 KERNEL чипов перенесено. Потратьте их."],
        ["^\\+\\$([\\d.,]+) earned$", "+$$$1 получено"],
        ["^\\+(\\d+) (.+) standing XP$", "+$1 $2 опыта престижа"],
        ["^GAMBLE \\$([\\d.,]+)$", "АВАНТЮРА $$$1"],
        ["^BOOST PROTO \\+(\\d+)% \\$([\\d.,]+)$", "УСИЛЕНИЕ PROTO +$1% $$$2"],
        ["^I want \\$([\\d.,]+)$", "Мне нужно $$$1"],
        ["^Need (\\d+) points? \\(have (\\d+)\\)$", "Нужно $1 очков? (есть $2)"],
        ["^LVL (\\d+)\\+$", "LVL $1+"],
        ["^LAYER (\\d+) · BOSS$", "СЛОЙ $1 · БОСС"],
        ["^LAYER (\\d+) ◦ CLAIMED$", "СЛОЙ $1 ◦ ПОЛУЧЕНО"],
        ["^Level (\\d+) \\+(\\d+) Skill Points?$", "Уровень $1 +$2 очков навыков"],
        ["^P(\\d+) · Lv(\\d+) · (\\d+) Aug (.+)$", "P$1 · Lv$2 · $3 аугментация $4"],
        ["^> (.+)$", "> $1", "T"],
        ["^\"(.+)\"$", "\"$1\"", "T"],
        ["^(.+) \\[DONE\\]$", "$1 [ГОТОВО]", "T"],
        ["^([A-Z]+)·([A-Z]+)$", "$1·$2", "T"],
        ["^(\\d+)\\. (.+)$", "$1. $2", "T"],
        ["^(\\d+) ACTIVE$", "$1 активно"],
        ["^Cost: (\\d+) points?$", "Стоимость: $1 очков"],
        ["^(\\d+)pts$", "$1 очк."],
        ["^(\\d+) (\\w[\\w \/]*)$", "$1 $2", "T"],
        ["^([\\d.]+)(%?) → ([\\d.]+)(%?) (.+)$", "$1$2 → $3$4 $5", "T"],
        ["^([\\d.]+)× → ([\\d.]+)× (.+)$", "$1× → $2× $3", "T"],
        ["^Class: (.+) \\(YOUR CLASS\\)$", "Класс: $1 (ВАШ КЛАСС)", "T"],
        ["^Class: (.+) \\(RESTRICTED\\)$", "Класс: $1 (ОГРАНИЧЕНО)", "T"],
        ["^Automatically heal to full HP after raid \\(\\$([\\d.,]+)\\)$", "Авто-лечение до полного ОЗ после RAID ($$$1)", ""],
        ["^Basic T(\\d) gear issued and wounds treated\\. Available again after your next raid if still broke\\.$", "Выдано базовое снаряжение T$1 и оказана помощь. Если вы все еще без гроша, получите его снова после следующего RAID."],
        ["^Elemental Effects last (\\d+)% longer\\.$", "Эффекты стихий длятся на $1% дольше."],
        ["^(.+):$", "$1:", "T"],
        ["^(0x[0-9A-F]+): (.+)$", "$1: $2", "T"],
        ["^(.+) \\+([\\d.,]+)(%?)$", "$1 +$2$3", "T"],
        ["^(.+) and below \\((\\d+) items?\\)$", "$1 и ниже ($2 шт.)", "T"],
        ["^\\$([\\d.,]+) \\+ (.+)$", "$$ $1 + $2", "T"]
    ],
