    // ==== часть 13: остаток описаний мусора + описания древа лута/мастерства + советы ментора по RAID ====
    "Password-protected. Someone died keeping this secret.": "Защищено паролем. Кто-то умер, храня эту тайну.",
    "Hand-drawn. Routes crossed out. One circled in red.": "Нарисовано от руки. Маршруты зачеркнуты. Один обведен красным.",
    "Last words recorded: 'What the hell is—'": "Последние записанные слова: «Что, черт возьми...»",
    "Translation: 'They're not coming to save us.'": "Перевод: «Они не придут нас спасать.»",
    "EYES ONLY. Every eye that read this is now closed.": "ТОЛЬКО ДЛЯ ГЛАЗ. Каждые глаза, прочитавшие это, теперь закрыты.",
    "Heads: a symbol you don't recognize. Tails: the same symbol.": "Орел: символ, который вы не узнаете. Решка: тот же символ.",
    "Nobody remembers what it does. Probably important.": "Никто не помнит, что это делает. Вероятно, это важно.",
    "Stores more data than a server farm. Size of a marble.": "Хранит больше данных, чем серверная ферма. Размером с мраморный шарик.",
    "Plays the same 3 seconds on loop. A voice saying 'don't'.": "Постоянно проигрывает одни и те же 3 секунды. Голос, говорящий «не надо».",
    "Touch it and your watch runs backwards for a second.": "Коснитесь этого, и ваши часы на секунду пойдут назад.",
    "Triple-sealed glass. It moves when you're not looking.": "Тройная герметичная стеклянная упаковка. Она движется, когда вы не смотрите.",
    "The space inside is bigger than the space outside.": "Пространство внутри больше, чем пространство снаружи.",
    "+5%/rank junk & artifact value": "+5%/ранг к стоимости мусора и артефактов",
    "+3%/rank chance: enemy kills drop a second item": "+3%/ранг шанс: убийства врагов дают второй предмет",
    "+5%/rank currency drop chance (POI + kills)": "+5%/ранг шанс выпадения валюты (POI + убийства)",
    "+4%/rank chance: POI yields +1 item": "+4%/ранг шанс: POI дает +1 предмет",
    "Double loot procs have 25% chance to drop a third item": "При срабатывании двойного лута есть 25% шанс выпадения третьего предмета",
    "+2%/rank double loot (stacks with Echo Harvest mastery)": "+2%/ранг к двойному луту (стакается с мастерством Echo Harvest)",
    "+3%/rank sell price at traders": "+3%/ранг к цене продажи у торговцев",
    "All dropped loot value x1.20": "Стоимость всего выпавшего лута x1.20",
    "Mythic module drop chances x1.5 (warden/boss/Ironfall)": "Шанс выпадения MYTHIC модулей x1.5 (WARDEN/босс/Ironfall)",
    "On CL5+ maps, Standard gear drops become Enhanced": "На картах CL5+ снаряжение Standard заменяется на Enhanced",
    "Failed uplift rolls retry once": "Неудачные попытки повышения тира повторяются один раз",
    "+10%/rank Prototype roll weight": "+10%/ранг к весу выпадения Prototype",
    "+5% value on all dropped loot": "+5% к стоимости всего выпавшего лута",
    "+10%/rank salvage yield": "+10%/ранг к выходу при разборе",
    "Artifact drop chance 0.5% → 0.75% per kill": "Шанс выпадения артефакта 0.5% → 0.75% за убийство",
    "+1 POI on every map": "+1 POI на каждой карте",
    "Press E to open your raid inventory. Open it now.": "Нажмите E, чтобы открыть инвентарь RAID. Откройте его сейчас.",
    "Now close the inventory. Press E again.": "Теперь закройте инвентарь. Снова нажмите E.",
    "Q switches between primary, secondary and melee.": "Q переключает между основным, вторичным и ближним оружием.",
    "+2% damage per CL per level": "+2% урона за каждый CL на каждом уровне",
    "+5% double loot chance per level": "+5% шанс двойного лута за каждый уровень",
    "+10% flux earned per level": "+10% FLUX за каждый уровень",
    "+5% loot rarity per CL per level": "+5% редкости лута за каждый CL на каждом уровне",
    "+6% Prototype effectiveness per level (base: 40%)": "+6% эффективности Prototype за каждый уровень (база: 40%)",
    "+10% Signal Static resistance per level": "+10% сопротивления помехам сигнала за каждый уровень",
    "+10% damage vs Wardens per level": "+10% урона по WARDEN за каждый уровень",
    "One weapon. On the house. First and last time.": "Одно оружие. В подарок. Первый и последний раз.",
    "Fifteen targets. Any map. Show me consistency, not luck.": "Пятнадцать целей. Любая карта. Покажи мне стабильность, а не удачу.",
    "Ten extractions. Luck runs out. Patience doesn't.": "Десять эвакуаций. Удача заканчивается. Терпение — нет.",
