    // ==== chunk 01: sinerji / endgame / düşman öneki ====
    "Endurance Protocol": "耐力协议",
    "Shadow Assault": "暗影突袭",
    "War Machine": "战争机器",
    "Berserker": "狂战士",
    "Fortress": "堡垒",
    "Ghost": "幽灵",
    "Predator": "掠食者",
    "Technomancer": "科技术士",
    "God Protocol": "神明协议",
    "Neural Commerce": "神经贸易",
    "Armored": "装甲",
    "Enraged": "狂怒",
    "Fortified": "强固",
