    // ==== chunk 08: statik UI (terminal süsleri/hex/birimler/bölünmüş node'lar BİLİNÇLİ atlandı) ====
    "! WARNING: LOW VITALS": "！警告：生命体征过低",
    "! WARNING: NO WEAPON": "！警告：未携带武器",
    "\"Are you absolutely certain? We are crossing a line here...\"": "“你完全确定吗？我们正在越过一条线……”",
    "\"Flesh is weak. Let me fix that.\"": "“血肉苦弱。让我来修正。”",
    "\"Fortune favors the reckless.\"": "“财富眷顾莽夫。”",
    "\"I know. You became the strongest. There are people out there who worship you now. But... have you ever looked at yourself in a mirror? Do you even realize what you've become?\"": "“我知道。你成了最强的那个。外面有人把你当神明崇拜。可是……你照过镜子吗？你意识到自己变成了什么吗？”",
    "\"Need something that goes boom?\"": "“需要能爆炸的玩意儿吗？”",
    "\"Please, don't take this the wrong way... but don't you think it's time to rest?\"": "“拜托，别误会……但你不觉得是时候休息了吗？”",
    "\"Take him. Take care of him. You've done enough.\"": "“带上它。照顾好它。你做得够多了。”",
    "\"The signal speaks...\"": "“信号在低语……”",
    "(grid modules are kept).": "（网格模块会保留。）",
    "(per pt)": "（每点）",
    "+0.5% Elemental DMG": "+0.5% 元素伤害",
    "+1 Handling, +0.5 Evasion": "+1 操控性，+0.5 闪避",
    "+3 HP, +0.2 Armor": "+3 生命，+0.2 护甲",
    "ALLOCATED": "已分配",
    "APPLY": "应用",
    "AUDIO": "音频",
    "AUTO": "自动",
    "AUTO-DEPLOYING IN": "自动部署倒计时",
    "AVAILABLE": "可用",
    "Additional Damage:": "附加伤害：",
    "All game data will be permanently deleted.": "所有游戏数据将被永久删除。",
    "All operators in the field": "战场上的所有干员",
    "Are you sure?": "你确定吗？",
    "BACK": "返回",
    "BARGAIN": "议价",
    "BASELINE": "基准",
    "BODY": "躯干",
    "BOSS SKIP": "头目跳过",
    "BUILT WITH": "构建工具",
    "Boss layers rewind to checkpoint instantly (farm mode). No boss kills, no boss cache drops.": "头目层立即回退到检查点（刷怪模式）。不击杀头目，无头目补给箱掉落。",
    "CALLSIGN:": "呼号：",
    "CANCEL": "取消",
    "CENTER": "居中",
    "CHANGE SECTOR": "更换区域",
    "CHECKPOINT: 1": "检查点：1",
    "CLASS:": "职业：",
    "CLEAR": "清除",
    "CLICK TO NAVIGATE": "点击导航",
    "CLOSE": "关闭",
    "CODE VAULT": "代码保险库",
    "CONFIRM RESET": "确认重置",
    "CONFIRMATION": "确认",
    "CONTINUE": "继续",
    "CREDITS": "制作人员",
    "CURRENT RANK": "当前等级",
    "CYBORG MK.1": "义体人 MK.1",
    "DANGER:": "危险：",
    "DATE:": "日期：",
    "DECODING": "解码中",
    "DEPLOY": "部署",
    "DEPLOY TO RAID": "部署进入 RAID",
    "DEVELOPED BY": "开发者",
    "DISPLAY": "显示",
    "DURABILITY:": "耐久：",
    "Don't show this again": "不再显示",
    "EXTRACTING...": "撤离中……",
    "Ensure": "投保",
    "FILTER ▾": "筛选 ▾",
    "FUEL": "燃料",
    "GAMEPLAY": "游戏性",
    "GEAR INVENTORY": "装备栏",
    "GENERATOR": "发电机",
    "GET YOUR DOG AND TAKE A REST": "带上你的狗，好好休息",
    "HEALING...": "治疗中……",
    "HUMAN": "人类",
    "I NEED TIME": "我需要时间",
    "IDLE": "挂机",
    "IDLE MODE / REDUCED LOOT": "挂机模式 / 战利品减少",
    "INCOMING TRANSMISSION // PRIORITY: PERSONAL": "来电传输 // 优先级：私人",
    "INITIALIZE SYSTEM": "初始化系统",
    "INJECTING...": "注入中……",
    "Inspect": "检视",
    "KEYBINDS": "按键绑定",
    "KILL VAHLEN": "杀死 VAHLEN",
    "KILLS:": "击杀：",
    "Keystones": "楔石",
    "LAYER 1": "第 1 层",
    "LEVEL:": "等级：",
    "LOCKED": "已锁定",
    "LOCKPICKING": "撬锁",
    "LOOT:": "战利品：",
    "Lives:": "生命数：",
    "MINING": "挖矿",
    "MINING RIG": "矿机",
