    // ==== JS_UI часть 9: реплики торговцев + аудит 1-й волны ====
    "Bring cash. I don't accept hope.": "Приноси наличные. Надежду я не принимаю.",
    "Cheap thrills cost fifty thousand.": "Дешевые развлечения стоят пятьдесят тысяч.",
    "Don't ask where I get them. Ask what they can do.": "Не спрашивай, где я их беру. Спрашивай, на что они способны.",
    "Don't think. Just pay and pray.": "Не думай. Просто плати и молись.",
    "Every corruption carries a gift. For those who can afford it.": "Каждая коррупция несет в себе дар. Для тех, кто может себе это позволить.",
    "Every roll is a fresh chance at glory.": "Каждый бросок — это новый шанс на славу.",
    "Everything works… until you start asking for guarantees.": "Все работает... пока не начнешь требовать гарантий.",
    "Fifty grand says you're feeling lucky.": "Ставлю пятьдесят штук, что ты сегодня везунчик.",
    "Flux flows. I merely redirect.": "FLUX течет. Я лишь направляю его.",
    "Fortune doesn't knock. She charges admission.": "Удача не стучится в дверь. Она берет плату за вход.",
    "Hold steady. The future doesn't wait for shaking hands.": "Держись уверенно. Будущее не ждет дрожащих рук.",
    "I can smell an empty wallet from across the room.": "Я чувствую запах пустого кошелька даже из другого конца комнаты.",
    "I don't care where you got shot.": "Мне плевать, куда тебя ранили.",
    "I don't fix people. I refit them.": "Я не чиню людей. Я их пересобираю.",
    "If it fits, it leaves.": "Если влезет — забирай.",
    "If you're shopping, you're already losing.": "Если ты начал тратить, ты уже проиграл.",
    "Next.": "Следующий.",
    "No refunds. No reversals. Choose with your eyes open.": "Без возвратов. Без отмен. Выбирай с открытыми глазами.",
    "Prices change when the streets get hungry.": "Цены меняются, когда улицы начинают голодать.",
    "Quiet hands. Quick choices.": "Руки не дрожат. Выбор быстрый.",
    "Rare costs more. Fear costs even more.": "Редкое стоит дорого. Страх стоит еще дороже.",
    "Rarity is just probability wearing a disguise.": "Редкость — это всего лишь вероятность под маской.",
    "Reality bends for a price. My price.": "Реальность прогибается за цену. За мою цену.",
    "Sit still. I'm not here to comfort you.": "Сиди смирно. Я здесь не для того, чтобы тебя утешать.",
    "Straps. Buckles. Done.": "Ремни. Застежки. Готово.",
    "The deeper you go, the more I can offer.": "Чем глубже ты заходишь, тем больше я могу предложить.",
    "The house always wins. But sometimes, so do you.": "Казино всегда в выигрыше. Но иногда выигрываешь и ты.",
    "The signal chose me. Your flux chooses what I share.": "Сигнал выбрал меня. Твой FLUX выбирает, чем я поделюсь.",
    "The signal remembers what the flesh forgets.": "Сигнал помнит то, что забывает плоть.",
    "These aren't tools. They're keys to what's underneath.": "Это не инструменты. Это ключи к тому, что скрыто внизу.",
    "This is an upgrade, not a miracle.": "Это апгрейд, а не чудо.",
    "Try it. Pay. Move.": "Попробуй. Плати. Иди.",
    "Walk away rich or walk away lighter. Your call.": "Уйти богачом или уйти с пустыми руками. Решать тебе.",
    "You hear static? I hear opportunity.": "Слышишь помехи? Я слышу возможность.",
    "You want it cheap? Go wish somewhere else.": "Хочешь подешевле? Иди загадывай желания в другое место.",
    "You'll pay twice out there if you try to save here.": "Там ты заплатишь вдвойне, если попытаешься сэкономить здесь.",
    "You'll walk out improved, just not the way you imagined.": "Ты выйдешь отсюда улучшенным, но не совсем так, как ты себе представлял.",
    "Your body's behind schedule. I can catch it up.": "Твое тело отстает от графика. Я могу его догнать.",
    "Your standing here? It tips the scales.": "Твой статус здесь? Он меняет правила игры.",
    "Enemy Detection Range": "Дистанция обнаружения врага",
    "Autosave": "Автосохранение",
    "* INJECT QUEUE": "* Очередь инъекции",
    "AUGMENTED": "АУГМЕНТИРОВАН",
    "Accessories": "Аксессуары",
    "Backpacks": "Рюкзаки",
    "Body Armor": "Броня",
    "Ambusher": "Засадник",
    "Any unsaved progress will be lost.": "Любой несохраненный прогресс будет потерян.",
    "Are you sure you want to reset the skill tree?": "Вы уверены, что хотите сбросить дерево навыков?",
    "Chance to avoid attacks": "Шанс избежать атаки",
    "Chance to hit vital areas": "Шанс попадания в жизненно важные зоны",
    "Damage multiplier on headshots": "Множитель урона при хедшотах",
    "Assassinate": "Убийство",
    "Deflect": "Отражение",
    "Edge of Death": "Грань смерти",
    "Chop Chop!": "Живее!",
    "DEPLOY ANYWAY": "ВСЁ РАВНО РАЗВЕРНУТЬ",
    "INS": "INS",
    "Tech": "Tech",
    "HP/sec": "HP/сек",
    "boss cache chance": "шанс на босс-кеш",
    "crit chance": "шанс крита",
    "raid damage": "урон в RAID",
    "damage taken": "полученный урон",
    "cases per open": "кейсов за открытие",
    "clicks/sec": "кликов/сек",
    "nodes remaining": "осталось узлов",
    "Standing XP": "Опыт репутации",
    "When you spot an enemy first, you sneak behind them and deal double damage on your first hit.": "Когда вы обнаруживаете врага первым, вы незаметно подкрадываетесь к нему сзади и наносите двойной урон при первом ударе.",
    "Codes injected via vault are guaranteed in the next roll.": "Коды, введенные через хранилище, гарантированно выпадут при следующем броске.",
    "Open Code Vault tab. Click a code to add it to inject queue.": "Откройте вкладку Code Vault. Нажмите на код, чтобы добавить его в очередь инъекции.",
    "Switch to Terminal tab. Use the matching currency:": "Переключитесь на вкладку Terminal. Используйте соответствующую валюту:",
