    // ==== часть 15: мифические модули + реплики торговцев + UI древа навыков + разделенные части узлов ====
    "+0.4 HS multiplier": "+0.4 множитель хедшотов",
    "+0.4 attack speed": "+0.4 скорость атаки",
    "+2% accuracy per hit (max +30%)": "+2% точности за попадание (макс. +30%)",
    "+20 HP on enemy kill": "+20 ОЗ при убийстве врага",
    "+30% extra items from POI": "+30% доп. предметов из POI",
    "+40% POI search speed": "+40% скорость поиска в POI",
    "+50% currency from salvage": "+50% валюты при разборке",
    "+55 damage (shock synergy)": "+55 урона (синергия с шоком)",
    "+70 damage (bleed synergy)": "+70 урона (синергия с кровотечением)",
    "+80% carry capacity": "+80% к грузоподъемности",
    "-70% POI search time": "-70% время поиска в POI",
    "15% chance to stun for 0.5s": "15% шанс оглушения на 0.5 сек",
    "2% chance instant kill (not bosses)": "2% шанс мгновенного убийства (не боссы)",
    "25% chance for free 2nd hit": "25% шанс бесплатного второго удара",
    "5-10% life steal on hit": "5-10% вампиризма при попадании",
    "50% chance to upgrade drop rarity +1": "50% шанс повысить редкость дропа на +1",
    "70-80% headshot chance": "70-80% шанс хедшота",
    "Countdown; at zero all map enemies die (boss excluded)": "Обратный отсчет; при достижении нуля все враги на карте погибают (боссы исключены)",
    "Deletes 3 enemies at raid start; their loot goes straight to your bag (bosses excluded)": "Уничтожает 3 врагов в начале RAID; их добыча сразу попадает в ваш инвентарь (боссы исключены)",
    "Faster heat buildup; overheat releases a nova + instant cooldown": "Быстрее накапливается тепло; перегрев вызывает взрыв новой и мгновенную перезарядку",
    "Glitch Clone": "Глитч-клон",
    "If you want clean work, stop asking dirty questions.": "Если хочешь чистой работы, перестань задавать грязные вопросы.",
    "Breathe in. Don't waste my precision.": "Сделай вдох. Не трать мою точность впустую.",
    "The new part will take. Your pride might not.": "Новая деталь приживется. А вот твоя гордость — вряд ли.",
    "Don't tell me your story. Tell me your budget.": "Не рассказывай мне свою историю. Называй бюджет.",
    "I don't lie. I just charge for the truth.": "Я не лгу. Я просто беру плату за правду.",
    "Size.": "Размер.",
    "Point to what you want.": "Покажи, что тебе нужно.",
    "Don't waste my time with opinions.": "Не трать мое время на свое мнение.",
    "You want comfort? Buy a pillow.": "Хочешь комфорта? Купи подушку.",
    "Trade carefully. The signal doesn't forgive mistakes.": "Торгуй осторожно. Сигнал не прощает ошибок.",
    "I've seen legends born from a single roll.": "Я видел, как легенды рождались из одного броска.",
    "SKILL_TREE.exe": "SKILL_TREE.exe",
    "RESET_TREE": "Сброс дерева навыков",
    "REFUND_MODE": "РЕЖИМ ВОЗВРАТА",
    "PLAN_MODE": "РЕЖИМ ПЛАНИРОВАНИЯ",
    "RESET_CONFIRM": "ПОДТВЕРДИТЬ СБРОС",
    "Search nodes...": "Поиск узлов...",
    "Expand stash by": "Расширить хранилище на",
    ", press R to rotate)": ", нажмите R для вращения)",
    "· click a module, then hover the grid": "· кликните на модуль, затем наведите на сетку",
    "⚡ ABILITIES": "⚡ СПОСОБНОСТИ",
    "✦ MYTHIC AFFIXES": "✦ MYTHIC Аффиксы",
    "HS Mult": "Множитель HS",
    "Pen": "Пробитие",
    "Reach": "Дистанция",
    "> Gain Rage when you hit an enemy.\n> Rage lasts until the raid ends.\n> Each Rage grants:\n +2% Damage\n +2% RPM\n> Maximum Rage: 25": "> Получайте Ярость при попадании по врагу.\n> Ярость длится до конца RAID.\n> Каждая единица Ярости дает:\n +2% к урону\n +2% к темпу стрельбы (RPM)\n> Макс. Ярость: 25",
