    // ==== часть 03: уникальные названия мифических/прото-предметов ====
    "Nemesis Mk.Ω": "Немезида Mk.Ω",
    "Leviathan Warframe": "Боевой каркас Leviathan",
    "Godspike Railgun": "Рельсотрон Godspike",
    "Oblivion Marksman": "Марксман Oblivion",
    "Ascendant Neural Crown": "Нейронная корона Ascendant",
    "Reality Cleaver": "Рассекатель реальности",
    "Singularity Sidearm": "Пистолет Сингулярности",
    "Apocalypse Breacher": "Прорывник Апокалипсиса",
    "Wraith Stormneedle": "Штормовая игла Wraith",
    "Spectre Mk.X": "Спектр Mk.X",
    "Titan Exoframe": "Экзокаркас Титан",
    "Railspike": "Railspike",
    "Deadlock Marksman": "Марксман Deadlock",
    "Wraith Neural Helm": "Нейрошлем Wraith",
    "Obsidian Edge": "Обсидиановое лезвие",
    "Phantom": "Фантом",
    "Hellstorm Breacher": "Прорывник Hellstorm",
    "Viper Needler": "Иглострел Viper",
