    // ==== JS_UI parça 4: karışık etiketler (filtreler, mythic modüller, POI'ler, insanity düşmanları) ====
    "Ability Slots": "能力槽位",
    "Ablative Plate": "烧蚀装甲板",
    "Adaptive Calibration": "自适应校准",
    "Active quest items are never sold": "进行中的任务物品永不出售",
    "Add items to SELL first, then bargain": "先添加要出售的物品，再议价",
    "Added to stash": "已放入仓库",
    "Adjacent AMMO modules give +50% more": "相邻弹药模块效果 +50%",
    "Adult": "成年",
    "Aegis": "神盾",
    "Alert When Warden Available": "WARDEN 可挑战时提醒",
    "All Elemental Damage": "全元素伤害",
    "All Rarities": "所有稀有度",
    "All Types": "所有类型",
    "All enemies visible on map": "地图上显示所有敌人",
    "Ammo Feed": "供弹机构",
    "Amount": "数量",
    "Amplifier Node": "增幅节点",
    "Anchor Lock": "锚定锁",
    "Ancient Artifact": "远古造物",
    "Armor (ARM)": "护甲 (ARM)",
    "Armor Penetration": "护甲穿透",
    "Armor Shatter": "碎甲",
    "Armor Shredder": "撕甲者",
    "Attacks cost no stamina": "攻击不消耗耐力",
    "Auto (default)": "自动（默认）",
    "Auto Deploy": "自动部署",
    "Auto Sprint": "自动冲刺",
    "Auto-Buy Mag": "自动购买弹匣",
    "Auto-Heal After Raid": "RAID 后自动治疗",
    "Auto-Medic": "自动医疗",
    "Auto-Recover on Death": "死亡时自动找回",
    "Auto-Repair Nanites": "自动修理纳米机器人",
    "Auto-Repair Weapons": "自动修理武器",
    "Auto-Rush to Extraction": "自动冲向撤离点",
    "Auto-Salvage Gear": "自动拆解装备",
    "Auto-Sell Loot": "自动出售战利品",
    "Auto-Use Adrenaline": "自动使用肾上腺素",
    "Auto-Use Medkit": "自动使用急救包",
    "Autosave": "自动存档",
    "Balance after": "结算后余额",
    "Base Price:": "基础价格：",
    "Below": "低于",
    "Below 20% HP: 90% damage reduction (5s)": "低于 20% 生命：90% 减伤（5 秒）",
    "Below 30% HP: +100% damage": "低于 30% 生命：+100% 伤害",
    "Berserker Protocol": "狂战士协议",
    "Bit Rot": "比特腐蚀",
    "Blink Hunter": "闪现猎手",
    "Block Raider": "街区掠夺者",
    "Bloodthirst": "嗜血",
    "Body": "躯干",
    "Boosts each adjacent module by +10%": "相邻模块各 +10%",
    "Bulwark Protocol": "壁垒协议",
    "Bunker": "地堡",
    "Cannot Be Stunned": "免疫眩晕",
    "Cannot Headshot": "无法爆头",
    "Cheat Death Chance": "免死概率",
    "Clean Patch Swap": "无损补丁替换",
    "Click anywhere to continue": "点击任意处继续",
    "Click items in YOUR STASH or drag to add": "点击你仓库中的物品或拖入添加",
    "Click to continue": "点击继续",
    "Click to use": "点击使用",
    "Combat Stimulant": "战斗兴奋剂",
    "Combat start: stun the enemy 1.5s": "战斗开始：眩晕敌人 1.5 秒",
    "Combos": "组合",
    "Complete \"Man's Best Friend\" quest": "完成「人类最好的朋友」任务",
    "Complete first EVOLUTION to unlock": "完成首次进化以解锁",
    "Contact: WEAVER @ TRADERS": "联系人：WEAVER @ 商人",
    "Coolant Cell": "冷却剂电池",
    "Core Reactor": "核心反应堆",
    "Corner Stabilizer": "转角稳定器",
    "Corrupted Reroll": "侵蚀重掷",
    "Cost": "花费",
    "Credits": "点数",
    "Critical Edge": "致命锋刃",
    "Cryo Damage": "冰霜伤害",
    "Cryo Infusion": "冰霜灌注",
    "Cyclic Booster": "循环增压器",
    "DMG +50% | REGEN +50% | AC +25%": "伤害 +50% | 回复 +50% | 护甲 +25%",
    "Damage (DMG)": "伤害 (DMG)",
    "Damage Amplifier": "伤害增幅器",
    "Damage Taken": "受到伤害",
    "Danger Sense": "危险感知",
    "Data Loss": "数据丢失",
    "Data Terminal": "数据终端",
    "Data Vampire": "数据吸血鬼",
    "Deadeye": "神射手",
    "Death Loop Protection": "死亡循环保护",
    "Designate identification tag:": "指定识别标签：",
    "Do not pick up loot below this rarity": "不拾取低于此稀有度的战利品",
    "Dodge first hit in each combat": "闪避每场战斗的第一击",
    "Don't ask again (glitch+ still confirms)": "不再询问（GLITCH+ 仍会确认）",
    "Doom Clock": "末日时钟",
    "Double Tap Chip": "双击芯片",
    "Double Tap Module": "双击模块",
    "Double loot quantity from enemies": "敌人战利品数量翻倍",
    "EMP Overload": "EMP 过载",
    "Eagle Eye HUD": "鹰眼 HUD",
    "Echo-Tap Routine": "回响窃听例程",
    "Edge + Bleed → +120 damage": "锋刃 + 流血 → +120 伤害",
    "Electro Damage": "电击伤害",
    "Electronics Only": "仅电子产品",
    "Elemental Sync": "元素同步",
    "Encrypted Data Drive": "加密数据驱动器",
    "Enemy takes a DoT that doubles every 2s": "敌人受到每 2 秒翻倍的持续伤害",
    "Entire raid runs at 2x speed": "整场 RAID 以 2 倍速进行",
    "Escape": "逃跑",
    "Evasion (EVA)": "闪避 (EVA)",
    "Every POI search yields +1 bonus item": "每次 POI 搜索额外 +1 件物品",
    "Executioner": "处刑者",
    "Extended Coil Mag": "加长线圈弹匣",
    "Extraction Accelerator": "撤离加速器",
    "Extraction Guard": "撤离守卫",
    "Fatal Error": "致命错误",
    "Fee:": "费用：",
    "Field Med Tent": "战地医疗帐篷",
    "Fire Rate": "射速",
    "Flamer Unit": "喷火单元",
    "Fortress Wall": "堡垒之墙",
    "Full repair after each raid": "每次 RAID 后完全修理",
    "Gas Station": "加油站",
    "Ghost Weave": "幽灵织物",
    "Gold Bar": "金条",
    "Hallway Sentry": "走廊哨卫",
    "Handling": "操控性",
    "Harvester Mech": "收割机甲",
    "Headshot Multiplier": "爆头倍率",
    "Heal 15% max HP after every combat": "每场战斗后回复 15% 最大生命",
    "Heals you periodically during combat": "战斗中周期性治疗你",
    "Hemorrhage": "大出血",
    "Hidden Wall Safe": "暗墙保险柜",
    "Hospital": "医院",
    "House": "民宅",
    "Hypervelocity": "超高速",
    "Ignore 70% of enemy armor": "无视敌人 70% 护甲",
    "Ignore ALL enemy armor": "无视敌人全部护甲",
    "Ignore items below this value": "忽略低于此价值的物品",
    "Infinite Magazine": "无限弹匣",
    "Insanity (INS)": "疯狂 (INS)",
    "Install:": "安装：",
    "Instant Loot": "即时拾取",
    "Instant extraction": "立即撤离",
    "Instantly finds 10 items per raid": "每场 RAID 立即找到 10 件物品",
    "Ironfall Artillery Core": "铁陨火炮核心",
    "Ironfall Commander": "铁陨指挥官",
    "Ironfall War Mech": "铁陨战争机甲",
    "Item Effects": "物品效果",
    "Items:": "物品：",
    "Jam Chance": "卡壳率",
    "Juggernaut": "重装悍将",
    "Junk Picker": "垃圾捡拾者",
    "Kernel Slot Injection": "内核槽注入",
    "Laser Convergence": "激光汇聚",
    "Last Stand": "背水一战",
    "Last Stand Protocol": "背水一战协议",
    "Level": "等级",
    "Lifesteal a % of all damage dealt": "将造成伤害的一定比例转为生命偷取",
    "Locked Safe": "上锁的保险柜",
    "Loot Multiplier": "战利品倍率",
    "Loot Quantity": "战利品数量",
    "Loot Rarity": "战利品稀有度",
    "Loot Sense": "战利品感知",
    "Magnetic Receiver": "磁力接收器",
    "Maintenance Drone": "维护无人机",
    "Malware Injection": "恶意软件注入",
    "Max HP": "最大生命",
    "Max Rarity": "最高稀有度",
    "Max Status Stacks": "最大状态层数",
    "Med + Plate → +180 health, +60 armor": "医疗 + 装甲板 → +180 生命，+60 护甲",
    "Med-Injector": "医疗注射器",
    "Medical Only": "仅医疗品",
    "Melee Damage": "近战伤害",
    "Midas Protocol": "点金协议",
    "Military Plans": "军事计划",
    "Min Loot Rarity": "最低战利品稀有度",
    "Min Loot Value": "最低战利品价值",
    "Minigame Idle Mode": "小游戏挂机模式",
    "Module Class Flip": "模块类型翻转",
    "Module drop rate x2": "模块掉率 x2",
    "Modules": "模块",
    "Monomol Edge": "单分子刃",
    "Mortar Tech": "迫击炮技师",
    "Nanite Weave": "纳米织物",
    "Nano Swarm": "纳米虫群",
    "Nano-Regen Matrix": "纳米再生矩阵",
    "Navigate obstacles to flee": "绕过障碍逃离",
    "Neural Hijack": "神经劫持",
    "Never Miss": "永不落空",
    "No GPUs in stash": "仓库中没有显卡",
    "No active quests": "没有进行中的任务",
    "No active synergies": "没有生效的协同",
    "No modules owned": "未拥有模块",
    "No quests for this trader": "该商人没有任务",
    "No reload, unlimited ammo": "无需装填，弹药无限",
    "No stored augments for this slot": "该槽位没有存放的义体",
    "None": "无",
    "Null Result": "空结果",
    "Off": "关",
    "Old Mainframe": "旧主机",
    "One-Tap Protocol": "一击协议",
    "Orbital Nuke": "轨道核弹",
    "Overcharge Protocol": "过载协议",
    "Overclock Chip": "超频芯片",
    "Overheat Meltdown": "过热熔毁",
    "Overkill": "过度杀伤",
    "Overkiller": "过度杀手",
    "Overload Surge": "过载涌流",
    "Overwatch": "警戒",
    "Penetrator Core": "穿透者核心",
    "Penetrator Rounds": "穿透者弹药",
    "Phantom Implicit": "幻影固有词条",
    "Phantom Weave": "幻影织物",
    "Phase Shift": "相位偏移",
    "Piercing + Barrel → +80 armor pen": "穿刺 + 枪管 → +80 护甲穿透",
    "Piercing Rounds": "穿刺弹药",
    "Plate + Shield → +150 armor, +120 health": "装甲板 + 护盾 → +150 护甲，+120 生命",
    "Points": "点数",
    "Police Station": "警察局",
    "Power + Flux → unlocks an ABILITY SLOT": "能量 + FLUX → 解锁一个能力槽",
    "Power Cell": "能量电池",
    "Pre-load Autosave": "载入前自动存档",
    "Press GAMBLE to roll random gear": "按下赌一把掷出随机装备",
    "Primary Only": "仅主武器",
    "Prioritize specific item types": "优先特定物品类型",
    "Protect Base Tier": "保护基础品阶",
    "Protect Rarity": "保护稀有度",
    "Protect T1 only": "仅保护 T1",
    "Protect T1-T2": "保护 T1-T2",
    "Protect T1-T3": "保护 T1-T3",
    "Protect T1-T4": "保护 T1-T4",
    "Prototype Chip": "原型芯片",
    "Pulse Emitter": "脉冲发射器",
    "Puppy": "幼犬",
    "Purchased": "已购买",
    "Pyro Infusion": "烈焰灌注",
    "Quantum Crit": "量子暴击",
    "Railbreaker": "破轨者",
    "Railgun Pierce": "轨道炮穿透",
    "Railtuned Barrel": "轨道调校枪管",
    "Rarity Amplifier": "稀有度增幅器",
    "Reach Prestige 9+, farm high CL / bosses": "达到 PRESTIGE 9+，刷高 CL / 头目",
    "Reactive Weave": "反应织物",
    "Reality Delete": "现实删除",
    "Reaper Actuator": "收割者致动器",
    "Recoil": "后坐力",
    "Recon Drone Mk.I": "侦察无人机 Mk.I",
    "Recon Drone Mk.II": "侦察无人机 Mk.II",
    "Redline": "红线",
    "Reflex": "反射",
    "Regenerator": "再生者",
    "Reinforced Casing": "强化外壳",
    "Reload Speed": "装填速度",
    "Remove from Rig": "从矿机移除",
    "Repair Bay": "维修间",
    "Requires: Level 88": "需求：等级 88",
    "Return Rate": "返还率",
    "Returns to stash on death": "死亡时返回仓库",
    "Reveals all enemies on the map": "显示地图上所有敌人",
    "Revive once per raid at 50% HP": "每场 RAID 以 50% 生命复活一次",
    "Ricochet Chance": "跳弹概率",
    "Rig Gunner": "矿场炮手",
    "Rocket Barrage": "火箭弹幕",
    "Rows": "行数",
    "Salvage Scanner": "拆解扫描仪",
    "Salvage Types": "拆解类型",
    "Scav Drifter": "拾荒游民",
    "Scav Magnet": "拾荒磁铁",
    "Scavenger Core": "拾荒者核心",
    "Scavenging (SCV)": "拾荒 (SCV)",
    "Search Speed Overdrive": "搜索速度超频",
    "Second Wind": "重振旗鼓",
    "Secondary": "副武器",
    "Select GPU": "选择显卡",
    "Select a quest to view details": "选择一个任务查看详情",
    "Select a slot to view locker": "选择一个槽位查看储物柜",
    "Select an item from STOCK to bargain": "从库存中选择一件物品议价",
    "Select an item to purchase": "选择要购买的物品",
    "Sell Below Value": "低于价值出售",
    "Sell Types": "出售类型",
    "Sell Value": "出售价值",
    "Sell loot after each raid": "每次 RAID 后出售战利品",
    "Sell/salvage this rarity and below": "出售/拆解此稀有度及以下",
    "Serrated Fang": "锯齿獠牙",
    "Servo + Ammo → +fire rate & attack speed": "伺服 + 弹药 → +射速与攻速",
    "Servo Hands": "伺服之手",
    "Shield Capacitor": "护盾电容器",
    "Shockwave Slam": "冲击波猛击",
    "Signal Overclock": "信号超频",
    "Skill Point Drive": "技能点驱动器",
    "Skip Minigame Caches": "跳过小游戏补给箱",
    "Skip Quest Items": "跳过任务物品",
    "Soulbound": "灵魂绑定",
    "Soulbound Core": "灵魂绑定核心",
    "Soulbound Plating": "灵魂绑定镀甲",
    "Speed (SPD)": "速度 (SPD)",
    "Sprint Resume At": "冲刺恢复阈值",
    "Stagger Protocol": "踉跄协议",
    "Stamina": "耐力",
    "Standard": "标准",
    "Starting Weapon": "起始武器",
    "Stasis Lock": "静滞锁定",
    "Stats reduced, upgrade Prototype Sync": "属性被削减，升级原型同步",
    "Status Duration": "状态持续时间",
    "Status Power": "状态强度",
    "Stealth (STL)": "潜行 (STL)",
    "Stock:": "库存：",
    "Store": "商店",
    "Storm Infusion": "风暴灌注",
    "Success: 50% chance | CD: 60s": "成功率：50% | 冷却：60 秒",
    "System Ready": "系统就绪",
    "Targeting AI": "瞄准 AI",
    "Targeting Module": "瞄准模块",
    "Tent": "帐篷",
    "Thermal Damage": "热能伤害",
    "Thermal Optic": "热感瞄具",
    "Thermal Shock": "热震",
    "Thor's Might": "雷神之力",
    "Tier": "品阶",
    "Tier Cleanup": "品阶清理",
    "Titan Rounds": "泰坦弹药",
    "Transit Enforcer": "中转站执法者",
    "Trench Raider": "战壕掠夺者",
    "Triage Matrix": "分诊矩阵",
    "Tunnel Sniper": "隧道狙击手",
    "Type Preference": "类型偏好",
    "Undying": "不死",
    "Unlimited Ammo": "无限弹药",
    "Valuables Only": "仅贵重品",
    "Vampiric Coating": "吸血涂层",
    "Vampiric Rounds": "吸血弹药",
    "Vampiric Surge": "吸血涌流",
    "Vibro Core": "振动核心",
    "Villa": "别墅",
    "Viral Strike": "病毒打击",
    "Volatile Rounds": "不稳定弹药",
    "Warehouse": "仓库大楼",
    "Warp Extraction": "跃迁撤离",
    "Weapons Only": "仅武器",
    "Weight Negator": "重量抵消器",
    "Weighted Core": "配重核心",
    "Wildcard Protocol": "万能牌协议",
    "X-Ray Scanner": "X 光扫描仪",
    "XP Bonus": "经验加成",
    "YOU TRADED YOUR DOG FOR AN UPGRADE": "你用你的狗换了一次升级",
    "Zero Stamina": "零耐力消耗",
    "Zero stamina consumption": "零耐力消耗",
    "[ ABILITIES ]": "[ 能力 ]",
    "[ AUGMENTATION MODULE ]": "[ 义体模块 ]",
    "[ CLEAR ]": "[ 清除 ]",
    "[ CLICK TO BEGIN ]": "[ 点击开始 ]",
    "[ COMPANION MODULE ]": "[ 同伴模块 ]",
    "[ CONFIRM DESIGNATION ]": "[ 确认代号 ]",
    "[ EQUIPMENT ]": "[ 装备 ]",
    "[ GROWTH DATA ]": "[ 成长数据 ]",
    "[ INITIATE UPGRADE ]": "[ 开始升级 ]",
    "[ MAX GROWTH ACHIEVED ]": "[ 已达最大成长 ]",
    "[ NEW COMPANION DETECTED ]": "[ 检测到新同伴 ]",
    "[ SEARCH TARGET ]": "[ 搜索目标 ]",
    "[ SIGNAL MASTERY ]": "[ 信号精通 ]",
    "[ VITAL SIGNS ]": "[ 生命体征 ]",
    "[LOCKED]": "[已锁定]",
    "[OTHER]": "[其他]",
    "— EMPTY —": "－ 空 －",
    "◆ COMPONENTS": "◆ 部件",
    "◇ READY TO ROLL": "◇ 准备掷点",
    "◈ MAX GRID 10×10": "◈ 最大网格 10×10",
    "★ PROTOTYPE AFFIXES": "★ PROTOTYPE 词条",
    "⚔ COMBAT ENGAGED ⚔": "⚔ 进入战斗 ⚔",
    "✦ MYTHIC DROP": "✦ MYTHIC 掉落",
