    // ==== chunk 03: item adları (marka Latin + tür çevrili) ====
    "Smartframe Pack T1": "Smartframe 背包 T1",
    "Vanta Pack T2": "Vanta 背包 T2",
    "Kestrel Pack T3": "Kestrel 背包 T3",
    "Ironclad Pack T4": "Ironclad 背包 T4",
    "RustTek Pack T5": "RustTek 背包 T5",
    "Smartframe Armor T1": "Smartframe 护甲 T1",
    "Vanta Armor T2": "Vanta 护甲 T2",
    "Kestrel Armor T3": "Kestrel 护甲 T3",
    "Ironclad Armor T4": "Ironclad 护甲 T4",
    "RustTek Armor T5": "RustTek 护甲 T5",
    "Smartframe Bolt-Action": "Smartframe 栓动步枪",
    "Vanta Bolt-Action": "Vanta 栓动步枪",
    "Kestrel Bolt-Action": "Kestrel 栓动步枪",
    "Ironclad Bolt-Action": "Ironclad 栓动步枪",
    "RustTek Bolt-Action": "RustTek 栓动步枪",
    "Smartframe AR": "Smartframe 突击步枪",
    "Vanta AR": "Vanta 突击步枪",
    "Kestrel AR": "Kestrel 突击步枪",
    "Ironclad AR": "Ironclad 突击步枪",
    "RustTek AR": "RustTek 突击步枪",
    "Smartframe DMR": "Smartframe 精射步枪",
    "Vanta DMR": "Vanta 精射步枪",
    "Kestrel DMR": "Kestrel 精射步枪",
    "Ironclad DMR": "Ironclad 精射步枪",
    "RustTek DMR": "RustTek 精射步枪",
    "Smartframe Pistol": "Smartframe 手枪",
    "Vanta Pistol": "Vanta 手枪",
    "Kestrel Pistol": "Kestrel 手枪",
    "Ironclad Pistol": "Ironclad 手枪",
    "RustTek Pistol": "RustTek 手枪",
    "Smartframe Shotgun": "Smartframe 霰弹枪",
    "Vanta Shotgun": "Vanta 霰弹枪",
    "Kestrel Shotgun": "Kestrel 霰弹枪",
    "Ironclad Shotgun": "Ironclad 霰弹枪",
    "RustTek Shotgun": "RustTek 霰弹枪",
    "Smartframe SMG": "Smartframe 冲锋枪",
    "Vanta SMG": "Vanta 冲锋枪",
    "Kestrel SMG": "Kestrel 冲锋枪",
    "Ironclad SMG": "Ironclad 冲锋枪",
    "RustTek SMG": "RustTek 冲锋枪",
    "Smartframe Blade": "Smartframe 刀锋",
    "Vanta Blade": "Vanta 刀锋",
    "Kestrel Blade": "Kestrel 刀锋",
    "Ironclad Blade": "Ironclad 刀锋",
    "RustTek Blade": "RustTek 刀锋",
    "Smartframe Helmet T1": "Smartframe 头盔 T1",
    "Vanta Helmet T2": "Vanta 头盔 T2",
    "Kestrel Helmet T3": "Kestrel 头盔 T3",
    "Ironclad Helmet T4": "Ironclad 头盔 T4",
    "RustTek Helmet T5": "RustTek 头盔 T5",
    "Smartframe Headset T1": "Smartframe 耳机 T1",
    "Vanta Headset T2": "Vanta 耳机 T2",
    "Kestrel Headset T3": "Kestrel 耳机 T3",
    "Ironclad Headset T4": "Ironclad 耳机 T4",
    "RustTek Headset T5": "RustTek 耳机 T5",
    "Smartframe Rig T1": "Smartframe 战术背心 T1",
    "Vanta Rig T2": "Vanta 战术背心 T2",
    "Kestrel Rig T3": "Kestrel 战术背心 T3",
    "Ironclad Rig T4": "Ironclad 战术背心 T4",
    "RustTek Rig T5": "RustTek 战术背心 T5",
    "Scav Pistol": "拾荒者手枪",
    "Scav Helmet": "拾荒者头盔",
    "Scav Vest": "拾荒者背心",
    "Scav Webbing": "拾荒者挂具",
    "Scav Satchel": "拾荒者挎包",
    "Loyal Dog": "忠犬",
    "Dog Kibble": "狗粮",
    "Premium Dog Food": "优质狗粮",
    "Gourmet Steak": "顶级牛排",
    "Tennis Ball": "网球",
    "Chew Bone": "磨牙骨",
    "Rope Toy": "绳结玩具",
    "Tactical Goggles": "战术护目镜",
    "Tactical Mask": "战术面罩",
    "Mining GPU T1": "矿用显卡 T1",
    "Mining GPU T2": "矿用显卡 T2",
    "Mining GPU T3": "矿用显卡 T3",
    "Healing Stim": "治疗针",
    "Adrenaline": "肾上腺素",
    "AR Magazine": "突击步枪弹匣",
    "SMG Magazine": "冲锋枪弹匣",
    "DMR Magazine": "精射步枪弹匣",
    "Pistol Magazine": "手枪弹匣",
    "Shotgun Magazine": "霰弹枪弹匣",
    "Bolt-Action Clip": "栓动步枪弹夹",
    "Prototype Magazine": "原型弹匣",
    "Chassis Plate": "底盘装甲板",
    "Mount Capacitor": "挂载电容器",
    "Neural Fragment": "神经碎片",
    "Perfect Core": "完美核心",
    "Quantum Processor": "量子处理器",
    "Servo Core": "伺服核心",
    "Singularity Shard": "奇点碎片",
    "Stabilizer Core": "稳定核心",
    "Synth Tissue": "合成组织",
    "Void Crystal": "虚空晶体",
    "Core Container": "核心安全箱",
    "Root Access Chip": "根权限芯片",
