    // ==== JS_UI часть 14: описания keystone для SKILL_TREE_JSON (точно по источнику, 46 блоков) ====
    "Gain 20% increased Status Effect Power.": "Увеличивает силу эффектов состояния на 20%.",
    "Elemental Effects last 30% longer.": "Длительность стихийных эффектов увеличена на 30%.",
    "Each active Elemental Stack\ngrants +3% increased Elemental Damage.": "Каждый активный стихийный стак\nдает +3% к стихийному урону.",
    "Gain 20% increased Elemental Damage.\nElemental Effects deal 10% increased Damage.": "Увеличивает стихийный урон на 20%.\nСтихийные эффекты наносят на 10% больше урона.",
    "Deal 25% increased Damage\nto enemies above 70% HP.": "Наносит на 25% больше урона\nврагам с HP выше 70%.",
    "When your HP drops below 40%,\ninstantly recover 10% of your Maximum HP.\nThis effect can only trigger once per combat.": "Когда ваше HP опускается ниже 40%,\nмгновенно восстановите 10% от макс. HP.\nЭтот эффект может сработать только один раз за бой.",
    "Gain 10 Armor Penetration.\nYour attacks ignore an additional 10% Armor.": "Дает 10 пробития брони.\nВаши атаки игнорируют дополнительные 10% брони.",
    "Each consecutive hit on the same enemy\ngrants +5% Damage, up to 25%.": "Каждое последовательное попадание по одному и тому же врагу\nдает +5% к урону, максимум до 25%.",
    "> +50% Damage\n> -30% Maximum HP": "> +50% к урону\n> -30% к макс. HP",
    "> Your shots never miss.\n> You can no longer deal Headshots.": "> Ваши выстрелы никогда не промахиваются.\n> Вы больше не можете наносить хедшоты.",
    "%15 chance to gain +20% Damage for this combat.": "15% шанс получить +20% к урону на этот бой.",
    "> %50 chance to reduce damage by 30%\n> %50 chance to take 30% more damage": "> 50% шанс снизить входящий урон на 30%\n> 50% шанс получать на 30% больше урона",
    "When combat begins,\nyou have a 50% chance to gain 30% increased Attack Speed\nand a 50% chance to gain 30% Damage Reduction for this combat.": "При начале боя\nу вас есть 50% шанс получить +30% к скорости атаки\nи 50% шанс получить 30% снижения урона на этот бой.",
    "If HP falls below 40% during combat:\n25% chance to heal 15% of max HP. Cooldown: 30 Seconds": "Если HP опускается ниже 40% во время боя:\n25% шанс восстановить 15% макс. HP. Перезарядка: 30 сек.",
    "> 50% chance to deal double damage.\n> 50% chance to deal greatly reduced damage.": "> 50% шанс нанести двойной урон.\n> 50% шанс нанести значительно сниженный урон.",
    "> Toss a coin when combat starts.\n> 50% chance:\n> +100% Melee Damage\n> -50% Ranged Damage\n>\n> 50% chance:\n> +100% Ranged Damage\n> -50% Melee Damage\n>\n> You cannot switch weapons during combat.": "> Подбросьте монетку в начале боя.\n> 50% шанс:\n> +100% к урону в ближнем бою\n> -50% к урону в дальнем бою\n>\n> 50% шанс:\n> +100% к урону в дальнем бою\n> -50% к урону в ближнем бою\n>\n> Вы не можете менять оружие во время боя.",
    "Deal 30% increased Melee Damage.": "Наносит на 30% больше урона в ближнем бою.",
    "Gain 10% increased Maximum HP.": "Увеличивает макс. HP на 10%.",
    "+1% MeMe Damage per 5 Armor,\ncapped at +15%.": "+1% к урону в ближнем бою за каждые 5 ед. брони,\nмакс. +15%.",
    "You cannot be stunned.\nTake 10% reduced Damage.": "Вас нельзя оглушить.\nПолучаемый урон снижен на 10%.",
    "> -20% Damage Taken\n> 5% Chance to Deflect incoming damage\n> +30% Stamina Cost": "> -20% входящего урона\n> 5% шанс отразить входящий урон\n> +30% к расходу выносливости",
    "> +50% Maximum HP\n> +20 Armor\n> -30% RPM\n> -20% Movement Speed": "> +50% к макс. HP\n> +20 к броне\n> -30% к скорострельности (RPM)\n> -20% к скорости передвижения",
    "Gain 25% increased Damage.": "Увеличивает урон на 25%.",
    "When your HP drops below 40%,\nrecover 15% of your Maximum HP.\n\nTriggers once per combat.": "Когда ваше HP опускается ниже 40%,\nвосстанавливает 15% от макс. HP.\n\nСрабатывает один раз за бой.",
    "Gamble effects are 10% less extreme\n(both bonuses and penalties).": "Эффекты азарта на 10% менее экстремальны\n(как бонусы, так и штрафы).",
    "Gain 25% increased Melee Damage.": "Увеличивает урон в ближнем бою на 25%.",
    "Gain 25% increased Evasion.": "Увеличивает уклонение на 25%.",
    "Each successful Melee hit grants\n+6% increased Melee Damage for this combat.\nStacks up to 30%.": "Каждое успешное попадание в ближнем бою\nдает +6% к урону в ближнем бою на этот бой.\nСтакается до 30%.",
    "When combat begins,\ngain 30% increased Evasion for 5 second.": "При начале боя\nдает +30% к уклонению на 5 секунд.",
    "> +50% Attack Speed\n> -30% Maximum HP": "> +50% к скорости атаки\n> -30% к макс. HP",
    "> When you spot an enemy first, you sneak behind them and deal double damage on your first hit.": "> Если вы первым заметили врага, вы незаметно подкрадываетесь к нему сзади и наносите двойной урон при первом ударе.",
    "Gain 50% increased Melee Damage.": "Увеличивает урон в ближнем бою на 50%.",
    "Your first attack in combat deals\n30% increased Damage.": "Ваша первая атака в бою\nнаносит на 30% больше урона.",
    "Execute enemies below 10% HP.": "Казнит врагов, у которых HP ниже 10%.",
    "> Gain Rage when you hit an enemy.\n> Rage lasts until the raid ends.\n> Each Rage grants:\n +2% Damage\n +2% RPM\n> Maximum Rage: 25\n": "> Получайте Ярость при попадании по врагу.\n> Ярость длится до конца RAID.\n> Каждый стак Яростьи дает:\n +2% к урону\n +2% к скорострельности\n> Макс. Ярость: 25\n",
    "Occasionally loses control and throws a bottle at the enemy, stunning them briefly and switching to fists.\n\nWhile fistfighting, your punches use your weapon's damage and deal 100% increased damage.\n\nChance to trigger: 10%\nCooldown: 30 seconds": "Иногда теряет контроль и бросает бутылку во врага, ненадолго оглушая его и переходя на кулаки.\n\nВ режиме драки на кулаках ваши удары используют урон оружия и наносят на 100% больше урона.\n\nШанс срабатывания: 10%\nПерезарядка: 30 секунд",
    "Gamble wins are 20% stronger. Gamble losses are 20% softer.\nEnemies deal 20% increased Damage to you.": "Выигрыши в азартных играх на 20% сильнее. Проигрыши - на 20% мягче.\nВраги наносят вам на 20% больше урона.",
    "When combat begins,\nyou have a 30% chance to take 50% reduced damage\nfor the first hit you receive in this combat.": "При начале боя\nу вас есть 30% шанс снизить входящий урон на 50%\nдля первого удара, полученного в этом бою.",
    "> When combat begins, you charge at the enemy.\n> Your first attack deals double damage and stuns for 2 seconds.\n> Consumes 80% Stamina.\n> Cannot trigger if you don't have enough Stamina.\n> Cooldown: 30 seconds": "> При начале боя вы бросаетесь на врага.\n> Ваша первая атака наносит двойной урон и оглушает на 2 секунды.\n> Расходует 80% выносливости.\n> Не может сработать при нехватке выносливости.\n> Перезарядка: 30 секунд",
    "Each time you take damage,\ngain +5% increased Melee Damage for this combat.\nStacks up to 25%.": "Каждый раз, когда вы получаете урон,\nполучайте +5% к урону в ближнем бою на этот бой.\nСтакается до 25%.",
    "While above 50% HP,\ngain 20% increased Damage Reduction.\nWhile below 50% HP,\ngain 30% increased Melee Damage.": "Пока HP выше 50%,\nполучайте +20% к снижению урона.\nПока HP ниже 50%,\nполучайте +30% к урону в ближнем бою.",
    "> You hook the enemy and pull them toward you.\n> The enemy is stunned for 1 second and takes 100% increased damage.\n> Cooldown: 30 seconds": "> Вы цепляете врага и притягиваете его к себе.\n> Враг оглушен на 1 секунду и получает на 100% больше урона.\n> Перезарядка: 30 секунд",
    "The first hit you take in combat\ndeals 20% reduced Damage.": "Первый удар, полученный вами в бою,\nнаносит на 20% меньше урона.",
    "If you spot the enemy first,\ngain 40% increased Melee Damage for this combat.": "Если вы первым заметили врага,\nполучайте +40% к урону в ближнем бою на этот бой.",
    "> Hitting enemies generates Overload.\n> Each hit grants 2 Overload points.\n> At 20 Overload, your weapon discharges on the enemy,\n> applying maximum stacks of all elemental effects.": "> Попадания по врагам накапливают Перегрузку.\n> Каждое попадание дает 2 очка Перегрузки.\n> При 20 очках Перегрузки ваше оружие разряжается в противника,\n> накладывая максимальное количество всех стихийных эффектов.",
    "> +3 Maximum Elemental Stacks\n> +50% Elemental Effect Power": "> +3 к макс. количеству стихийных стаков\n> +50% к силе стихийного эффекта",
