    // ==== часть 07: цели заданий (спец. имена боссов/торговцев на латинице, чтобы совпадали с неймплейтами) ====
    "Kill 1 enemy": "Убей 1 врага",
    "Kill 5 enemies": "Убей 5 врагов",
    "Kill 15 enemies": "Убей 15 врагов",
    "Kill 30 enemies": "Убей 30 врагов",
    "Kill 15 enemies at CL1+": "Убей 15 врагов на CL1+",
    "Kill 30 enemies at CL2+": "Убей 30 врагов на CL2+",
    "Kill 50 enemies at CL3+": "Убей 50 врагов на CL3+",
    "Kill 60 enemies at CL4+": "Убей 60 врагов на CL4+",
    "Kill 10 enemies in Frontline Outskirts": "Убей 10 врагов в Frontline Outskirts",
    "Kill 25 enemies in Greyhall District": "Убей 25 врагов в Greyhall District",
    "Kill 30 enemies in Greyhall District": "Убей 30 врагов в Greyhall District",
    "Kill 40 enemies in Redline Fields": "Убей 40 врагов в Redline Fields",
    "Kill 40 enemies in Deadflare Zone": "Убей 40 врагов в Deadflare Zone",
    "Kill 80 enemies in Ironfall Perimeter": "Убей 80 врагов в Ironfall Perimeter",
    "Kill 100 enemies in Ironfall Perimeter": "Убей 100 врагов в Ironfall Perimeter",
    "Kill a Signal Warden": "Убей Signal Warden",
    "Kill 2 Signal Wardens": "Убей 2 Signal Warden",
    "Kill 3 Signal Wardens": "Убей 3 Signal Warden",
    "Kill 5 Signal Wardens": "Убей 5 Signal Warden",
    "Kill 8 Signal Wardens": "Убей 8 Signal Warden",
    "Kill 3 Bosses": "Убей 3 босса",
    "Kill the Nexus Avatar": "Убей Nexus Avatar",
    "Kill the Blackstar Warlord": "Убей Blackstar Warlord",
    "Kill the Eclipse Core": "Убей Eclipse Core",
    "Extract from Silent Expanse": "Эвакуируйся из Silent Expanse",
    "Extract 3 times": "Эвакуируйся 3 раза",
    "Extract 5 times": "Эвакуируйся 5 раз(а)",
    "Extract 10 times": "Эвакуируйся 10 раз(а)",
    "Extract 20 times": "Эвакуируйся 20 раз(а)",
    "Extract 5 times from Rustveil Transit": "Эвакуируйся 5 раз(а) из Rustveil Transit",
    "Extract 5 times from Eclipse Bastion": "Эвакуируйся 5 раз(а) из Eclipse Bastion",
    "Extract 8 times from Greyhall District": "Эвакуируйся 8 раз(а) из Greyhall District",
    "Extract 10 times from Redline Fields": "Эвакуируйся 10 раз(а) из Redline Fields",
    "Extract 10 times from Deadflare Zone": "Эвакуируйся 10 раз(а) из Deadflare Zone",
    "Reach Corruption Level 1": "Достигни уровня Corruption 1",
    "Reach Corruption Level 3": "Достигни уровня Corruption 3",
    "Reach Corruption Level 5": "Достигни уровня Corruption 5",
    "Reach Corruption Level 7": "Достигни уровня Corruption 7",
    "Reach Corruption Level 8": "Достигни уровня Corruption 8",
    "Reach Corruption Level 9": "Достигни уровня Corruption 9",
    "Reach Corruption Level 10": "Достигни уровня Corruption 10",
    "Turn in The First Flame": "Сдай The First Flame",
    "Turn in Ghost Frequency": "Сдай Ghost Frequency",
    "Turn in The Architect's Core": "Сдай The Architect's Core",
    "Turn in Null Shard": "Сдай Null Shard",
    "Turn in Omega Protocol": "Сдай Omega Protocol",
    "Speak with Vulture": "Поговори с Vulture",
    "Upgrade any augment to +3": "Улучши любую аугментацию до +3",
    "Upgrade any augment to +7": "Улучши любую аугментацию до +7",
    "Loot $3,000 worth of items in raids": "Собери предметов на $3,000 в RAID",
    "Loot $8,000 worth of items in raids": "Собери предметов на $8,000 в RAID",
    "Loot $20,000 worth of items in raids": "Собери предметов на $20,000 в RAID",
    "Sell $5,000 worth to traders": "Продай торговцам лут на $5,000",
    "Salvage 5 items": "Разбери 5 предметов",
    "Salvage 25 items": "Разбери 25 предметов",
    "Find Nano-Tape": "Найди Nano-Tape",
    "Find Matches": "Найди спички",
    "Find 2x Nano-Tape": "Найди 2x Nano-Tape",
    "Find 3x Dog Treats": "Найди 3x лакомства для собак",
    "Use the Tech Table once": "Используй Tech Table 1 раз",
    "Use the Tech Table 3 times": "Используй Tech Table 3 раза",
    "Find a Prototype item in raid": "Найди PROTOTYPE предмет в RAID",
    "Find a Custom+ item in raid": "Найди Custom+ предмет в RAID",
