    // ==== chunk 02: düşman affix/adları ====
    "Shielded": "护盾",
    "of Iron": "之铁",
    "of Fury": "之怒",
    "of Vitality": "之活力",
    "of Steel": "之钢",
    "of the Brute": "之蛮力",
    "of Endurance": "之坚韧",
    "GUARD": "警卫",
    "SECURITY": "保安",
    "PATROL": "巡逻兵",
    "ENFORCER": "执法者",
    "SENTINEL": "哨卫",
    "AMBUSHER": "伏击者",
    "TRAP SCAV": "陷阱拾荒者",
    "LURKER": "蛰伏者",
    "SHADOW": "影子",
    "PREDATOR": "掠食者",
    "SCAV": "拾荒者",
    "RAIDER": "掠夺者",
    "BANDIT": "匪徒",
    "LOOTER": "抢掠者",
    "DRIFTER": "游荡者",
    "STALKER": "潜行者",
    "ROGUE": "亡命徒",
