    // ==== часть 08: статичный UI (декорации терминала/гекс/единицы/разделенные узлы НАМЕРЕННО пропущены) ====
    "! WARNING: LOW VITALS": "! ВНИМАНИЕ: НИЗКИЕ ПОКАЗАТЕЛИ ЖИЗНЕДЕЯТЕЛЬНОСТИ",
    "! WARNING: NO WEAPON": "! ВНИМАНИЕ: ОРУЖИЕ НЕ ЭКИПИРОВАНО",
    "\"Are you absolutely certain? We are crossing a line here...\"": "«Ты абсолютно уверен? Мы переходим черту...»",
    "\"Flesh is weak. Let me fix that.\"": "«Плоть слаба. Позволь мне это исправить.»",
    "\"Fortune favors the reckless.\"": "«Удача любит безрассудных.»",
    "\"I know. You became the strongest. There are people out there who worship you now. But... have you ever looked at yourself in a mirror? Do you even realize what you've become?\"": "«Я знаю. Ты стал сильнейшим. Там, снаружи, тебя почитают как бога. Но... ты когда-нибудь смотрел на себя в зеркало? Ты вообще понимаешь, во что ты превратился?»",
    "\"Need something that goes boom?\"": "«Нужно что-нибудь взрывное?»",
    "\"Please, don't take this the wrong way... but don't you think it's time to rest?\"": "«Пожалуйста, не пойми меня неправильно... но не думаешь ли ты, что пора отдохнуть?»",
    "\"Take him. Take care of him. You've done enough.\"": "«Забери его. Позаботься о нем. Ты сделал достаточно.»",
    "\"The signal speaks...\"": "«Сигнал говорит...»",
    "(grid modules are kept).": "(модули сетки сохраняются.)",
    "(per pt)": "(за очко)",
    "+0.5% Elemental DMG": "+0.5% урона стихиями",
    "+1 Handling, +0.5 Evasion": "+1 к управляемости, +0.5 к уклонению",
    "+3 HP, +0.2 Armor": "+3 ОЗ, +0.2 Брони",
    "ALLOCATED": "РАСПРЕДЕЛЕНО",
    "APPLY": "ПРИМЕНИТЬ",
    "AUDIO": "АУДИО",
    "AUTO": "АВТО",
    "AUTO-DEPLOYING IN": "АВТО-РАЗВЕРТЫВАНИЕ ЧЕРЕЗ",
    "AVAILABLE": "ДОСТУПНО",
    "Additional Damage:": "Доп. урон:",
    "All game data will be permanently deleted.": "Все игровые данные будут безвозвратно удалены.",
    "All operators in the field": "Все оперативники на поле боя",
    "Are you sure?": "Вы уверены?",
    "BACK": "НАЗАД",
    "BARGAIN": "ТОРГ",
    "BASELINE": "БАЗОВЫЙ УРОВЕНЬ",
    "BODY": "ТУЛОВИЩЕ",
    "BOSS SKIP": "ПРОПУСК БОССА",
    "BUILT WITH": "СОЗДАНО С ПОМОЩЬЮ",
    "Boss layers rewind to checkpoint instantly (farm mode). No boss kills, no boss cache drops.": "Слои боссов мгновенно возвращаются к чекпоинту (режим фарма). Без убийств боссов, без выпадения тайников боссов.",
    "CALLSIGN:": "ПОЗЫВНОЙ:",
    "CANCEL": "ОТМЕНА",
    "CENTER": "ЦЕНТР",
    "CHANGE SECTOR": "СМЕНИТЬ СЕКТОР",
    "CHECKPOINT: 1": "ЧЕКПОИНТ: 1",
    "CLASS:": "КЛАСС:",
    "CLEAR": "ОЧИСТИТЬ",
    "CLICK TO NAVIGATE": "КЛИКНИТЕ ДЛЯ НАВИГАЦИИ",
    "CLOSE": "ЗАКРЫТЬ",
    "CODE VAULT": "СХРОН КОДОВ",
    "CONFIRM RESET": "ПОДТВЕРДИТЬ СБРОС",
    "CONFIRMATION": "ПОДТВЕРЖДЕНИЕ",
    "CONTINUE": "ПРОДОЛЖИТЬ",
    "CREDITS": "ТИТРЫ",
    "CURRENT RANK": "ТЕКУЩИЙ РАНГ",
    "CYBORG MK.1": "КИБОРГ MK.1",
    "DANGER:": "ОПАСНОСТЬ:",
    "DATE:": "ДАТА:",
    "DECODING": "ДЕКОДИРОВАНИЕ",
    "DEPLOY": "РАЗВЕРТЫВАНИЕ",
    "DEPLOY TO RAID": "РАЗВЕРТЫВАНИЕ В RAID",
    "DEVELOPED BY": "РАЗРАБОТАНО",
    "DISPLAY": "ЭКРАН",
    "DURABILITY:": "ПРОЧНОСТЬ:",
    "Don't show this again": "Больше не показывать",
    "EXTRACTING...": "ЭВАКУАЦИЯ...",
    "Ensure": "Застраховать",
    "FILTER ▾": "ФИЛЬТР ▾",
    "FUEL": "ТОПЛИВО",
    "GAMEPLAY": "ГЕЙМПЛЕЙ",
    "GEAR INVENTORY": "ИНВЕНТАРЬ СНАРЯЖЕНИЯ",
    "GENERATOR": "ГЕНЕРАТОР",
    "GET YOUR DOG AND TAKE A REST": "ВОЗЬМИ СОБАКУ И ОТДОХНИ",
    "HEALING...": "ЛЕЧЕНИЕ...",
    "HUMAN": "ЧЕЛОВЕК",
    "I NEED TIME": "МНЕ НУЖНО ВРЕМЯ",
    "IDLE": "ПОКОЙ",
    "IDLE MODE / REDUCED LOOT": "РЕЖИМ ПОКОЯ / МЕНЬШЕ ЛУТА",
    "INCOMING TRANSMISSION // PRIORITY: PERSONAL": "ВХОДЯЩАЯ ПЕРЕДАЧА // ПРИОРИТЕТ: ЛИЧНОЕ",
    "INITIALIZE SYSTEM": "ИНИЦИАЛИЗАЦИЯ СИСТЕМЫ",
    "INJECTING...": "ИНЪЕКЦИЯ...",
    "Inspect": "Осмотреть",
    "KEYBINDS": "УПРАВЛЕНИЕ",
    "KILL VAHLEN": "УБИТЬ VAHLEN",
    "KILLS:": "УБИЙСТВ:",
    "Keystones": "Ключевые навыки",
    "LAYER 1": "СЛОЙ 1",
    "LEVEL:": "УРОВЕНЬ:",
    "LOCKED": "ЗАБЛОКИРОВАНО",
    "LOCKPICKING": "ВЗЛОМ",
    "LOOT:": "ЛУТ:",
    "Lives:": "Жизни:",
    "MINING": "ДОБЫЧА",
    "MINING RIG": "ДОБЫВАЮЩАЯ УСТАНОВКА",
