    // ==== chunk 03: mythic/proto benzersiz adlar ====
    "Nemesis Mk.Ω": "复仇女神 Mk.Ω",
    "Leviathan Warframe": "利维坦战甲",
    "Godspike Railgun": "神钉轨道炮",
    "Oblivion Marksman": "湮灭射手",
    "Ascendant Neural Crown": "飞升神经王冠",
    "Reality Cleaver": "现实劈裂者",
    "Singularity Sidearm": "奇点手枪",
    "Apocalypse Breacher": "天启破门者",
    "Wraith Stormneedle": "幽魂风暴针",
    "Spectre Mk.X": "鬼影 Mk.X",
    "Titan Exoframe": "泰坦外骨骼",
    "Railspike": "轨钉",
    "Deadlock Marksman": "死锁射手",
    "Wraith Neural Helm": "幽魂神经盔",
    "Obsidian Edge": "黑曜石之刃",
    "Phantom": "幻影",
    "Hellstorm Breacher": "地狱风暴破门者",
    "Viper Needler": "毒蛇针枪",
