    // ==== JS_UI parça 8: 4. tur (CL mekanikleri, combat text, hack minigame, statlar, field stats) ====
    "SELECT SLOT TO LOAD": "选择要载入的存档位",
    "SELECT SAVE SLOT": "选择存档位",
    "Left an IFAK in your stash. On the house.": "在你仓库里放了一个急救包。算我请的。",
    "Enemies regenerate HP each combat tick": "敌人每个战斗刻回复生命",
    "Enemy hits reduce your armor temporarily": "敌人命中会暂时削减你的护甲",
    "Healing effectiveness reduced by 30%": "治疗效果降低 30%",
    "Enemies below 30% HP deal +50% damage": "生命低于 30% 的敌人造成 +50% 伤害",
    "Enemies spawn with a shield equal to 15% of max HP": "敌人出生时携带相当于最大生命 15% 的护盾",
    "Random damage ticks during movement between POIs": "在 POI 之间移动时受到随机伤害",
    "15% chance killed enemies spawn a clone": "被击杀的敌人有 15% 概率生成分身",
    "10% chance enemy hits bypass armor and evasion": "敌人命中有 10% 概率无视护甲和闪避",
    "Signal Static becomes more frequent and intense": "信号静噪变得更频繁、更强烈",
    "All damage has ±50% variance": "所有伤害有 ±50% 浮动",
    "ALARM!": "警报！",
    "AMBUSH!": "伏击！",
    "CHEAT DEATH!": "免死！",
    "DANGER SENSE!": "危险感知！",
    "DODGED!": "闪避！",
    "DOUBLE!": "双倍！",
    "LAST STAND!": "背水一战！",
    "MELTDOWN!": "熔毁！",
    "MISS!": "未命中！",
    "NOTHING!": "一无所获！",
    "ONE-TAP!": "一击必杀！",
    "OVERHEAT!": "过热！",
    "PAINKILLER!": "止痛剂！",
    "SECOND WIND!": "重振旗鼓！",
    "SLIDE!": "滑铲！",
    "WEAPON BROKEN!": "武器损坏！",
    "+1 INS · BLOOD TITHE": "+1 疯狂 · 血税",
    "ENCRYPTED": "已加密",
    "BLOCKED": "已阻断",
    "DENIED": "已拒绝",
    "TIMEOUT": "超时",
    "ACCESS_PORT": "接入端口",
    "Press SPACE when cursor is on ACCESS_PORT!": "光标位于接入端口时按空格键！",
    "[SPACE] EXECUTE": "[空格] 执行",
    "EXECUTE": "执行",
    "HP": "生命",
    "HP:": "生命：",
    "Headshot Chance": "爆头率",
    "Headshot Mult": "爆头倍率",
    "Maximum Vitals": "生命上限",
    "Weight Capacity": "负重上限",
    "Scavenging": "拾荒",
    "Stealth": "潜行",
    "Speed": "速度",
    "elemental damage": "元素伤害",
    "Damage Dealt": "造成伤害",
    "Deaths": "死亡次数",
    "Items Looted": "拾取物品数",
    "Items Salvaged": "拆解物品数",
    "Money Earned": "赚取金钱",
    "Flux Earned": "获得通量",
    "Highest CL": "最高 CL",
    "Corrupted Raids": "受蚀 RAID 次数",
    "Wardens Defeated": "击败 WARDEN 数",
    "Salvage all items up to a rarity tier?": "拆解所有低于某稀有度的物品？",
    "for crafting materials?": "以获取制作材料？",
    "Expected:": "预期：",
    "custom weapon": "定制武器",
    "custom armor": "定制护甲",
    "player level": "玩家等级",
    "Reload": "装填",
    "Mag Size": "弹匣容量",
    "STATIC": "静噪",
    "DISTORTION": "畸变",
    "FEEDBACK": "反馈",
