    // ==== часть 01: названия заданий на аугментацию ====
    "Optic Calibration": "Калибровка оптики",
    "Neural Sync": "Нейросинхронизация",
    "Hive Frequency": "Частота Улья",
    "Adaptive Skin": "Адаптивная кожа",
    "Reactor Integration": "Интеграция реактора",
    "Nanite Infusion": "Инфузия нанитов",
    "Shock Dampening": "Гашение ударов",
    "Carbon Reinforcement": "Углеродное усиление",
    "Fusion Core": "Термоядерное ядро",
    "Plasma Armament": "Плазменное вооружение",
    "Quantum Sight": "Квантовое зрение",
    "Predictive Override": "Прогнозный перехват",
    "Dermal Graft": "Дермальный трансплантат",
    "Regenerative Protocol": "Протокол регенерации",
    "Void Integration": "Интеграция Пустоты",
    "Precision Engineering": "Прецизионная инженерия",
    "Phase Walk": "Фазовый шаг",
    "Adamantine Spine": "Адамантитовый позвоночник",
    "Bio-Filtration": "Биофильтрация",
    "Orbital Link": "Орбитальная связь",
    "Core Implant": "Имплант ядра",
    "Arm Augmentation": "Аугментация рук",
    "Leg Enhancement": "Усиление ног",
    "Frame Reconstruction": "Реконструкция каркаса",
    "Organ Replacement": "Замена органов",
    "Mount Installation": "Установка креплений",
    "Thermal Recalibration": "Термическая перекалибровка",
