    // ==== chunk 14: augment quest / harita / mentor / trader açıklamaları ====
    "Fifteen kills. I don't put a Hawkeye in someone who can't shoot straight.": "十五个击杀。我不会给一个枪都打不直的人装鹰眼。",
    "Five extractions from Rustveil. The signal noise there does half my calibration work.": "从锈幕中转站撤离五次。那里的信号噪声能帮我做一半的校准工作。",
    "Fifty kills at CL3+. Hive Mind Core is hungry for combat data. Don't come back early.": "在 CL3+ 击杀五十个。蜂群思维核心渴求战斗数据。别提前回来。",
    "Eight Greyhall extractions. The urban static trains the Chameleon Mesh better than I ever could.": "从灰厅区撤离八次。城市静噪训练变色龙网膜的效果比我强多了。",
    "Forty kills in Deadflare. The radiation primes the reactor cells. I'd go myself, but I like my skin.": "在死耀区击杀四十个。辐射能给反应堆电池预充能。我本想亲自去，但我爱惜自己的皮。",
    "Nanite Swarm Arms. Five Warden kills to break them in. Nanites are picky about their hosts.": "纳米虫群臂。先杀五个 WARDEN 磨合。纳米机器人对宿主很挑剔。",
    "Shock Absorbers. Sixty kills at CL4+. Your legs need to learn what real impact feels like.": "避震装置。在 CL4+ 击杀六十个。你的腿得学会什么叫真正的冲击。",
    "Carbon fiber. Lighter than titanium, stronger too. Ten Redline extractions for stress data.": "碳纤维。比钛轻，也比钛强。从红线原野撤离十次，我要应力数据。",
    "Fusion cell goes in your chest. Reach CL9 first. Not negotiable.": "聚变电池要装进你胸腔。先达到 CL9。没得商量。",
    "Eighty kills in Ironfall. Plasma turret needs EM calibration and that place is swimming in it.": "在铁陨防线击杀八十个。等离子炮塔需要电磁校准，那地方的电磁多到淹脚。",
    "Quantum Lens sees through everything. Kill the Eclipse Core. Its signal distortion is the activation key.": "量子透镜能看穿一切。杀掉 Eclipse Core。它的信号畸变就是激活密钥。",
    "Predictive Matrix. Ten Deadflare extractions. Time moves different out there. The implant needs that.": "预测矩阵。从死耀区撤离十次。那里的时间流速不一样。植入体需要这个。",
    "Nanoweave bonds better to damaged skin. Thirty kills, CL2 minimum. Come back roughed up.": "纳米织层和受损皮肤结合得更好。三十个击杀，至少 CL2。带着伤回来。",
    "Kill the Blackstar Warlord. The membrane needs biomass from something that size to seed the growth culture.": "杀掉 Blackstar Warlord。再生膜需要那种体量的生物质来培育生长基。",
    "Void Heart runs on dark matter. Kill the Nexus Avatar. Its void energy is the only ignition source.": "虚空之心靠暗物质运转。杀掉 Nexus Avatar。它的虚空能量是唯一的点火源。",
    "Precision Servos. CL7. The quantum gyroscopes need heavy signal interference to lock in.": "精密伺服。CL7。量子陀螺仪需要高强度信号干扰才能锁定。",
    "Phase Striders. Walk through walls. Kill the Eclipse Core. Its energy threads the dimensional weave.": "相位跃行腿。穿墙而行。杀掉 Eclipse Core。它的能量能穿引维度之网。",
    "Adamantine spine. Nothing breaks it. Kill the Nexus Avatar. Its gravity is the only forge that works.": "精金脊柱。没什么能弄断它。杀掉 Nexus Avatar。它的重力是唯一能锻造它的熔炉。",
    "Eight Warden kills. Bio-Filter needs corrupted signal residue to prime. No substitute.": "杀八个 WARDEN。生物过滤器需要侵蚀信号残渣来预充。没有替代品。",
    "Orbital strikes from space. Kill the Nexus Avatar. Its signal frequency is the uplink key. Last augment I'll ever need to build you.": "来自太空的轨道打击。杀掉 Nexus Avatar。它的信号频率就是上行链路密钥。这是我要给你造的最后一件义体。",
    "I'm replacing your ribcage. Two Warden kills first. Need to know your body can take the shock.": "我要换掉你的肋骨架。先杀两个 WARDEN。我得确认你的身体扛得住这种冲击。",
    "Redline Fields, forty kills. Hydraulic Crushers need real recoil data, not lab simulations.": "红线原野，四十个击杀。液压碎击臂需要真实的后坐数据，不是实验室模拟。",
    "Grav-Drive legs learn from how you move. Twenty extractions. The more you run, the better they fit.": "重力驱动腿会学习你的移动方式。撤离二十次。你跑得越多，它们越合脚。",
    "Kill the Blackstar Warlord, then we talk titanium. Full skeleton swap. Your old bones earned the rest.": "杀掉 Blackstar Warlord，然后我们再谈钛合金。整副骨架置换。你的旧骨头该退休了。",
    "Synthetic adrenaline gland. Reach CL8. If your organs survive that corruption, they'll survive the implant.": "合成肾上腺体。达到 CL8。你的器官要是能扛过那种侵蚀，就能扛过植入。",
    "Shoulder rockets. Kill the Nexus Avatar first. After that fight, the surgery's a vacation.": "肩挂火箭。先杀掉 Nexus Avatar。打完那一仗，手术就跟度假一样。",
    "Hawkeye was step one. Thermal Oculus needs heat data from real fights. Three Warden kills.": "鹰眼只是第一步。热感目镜需要真实战斗的热数据。杀三个 WARDEN。",
    "Cloaks at combat start. First hit deals bonus headshot damage.": "战斗开始时隐身。首次攻击附加爆头伤害。",
    "Vahlen's final gift. Twin thermal lances behind your eyes. One look is enough.": "Vahlen 最后的礼物。双眼后的成对热能矛。看一眼就够了。",
    "Quantum phase technology creates phantom clones to confuse enemies.": "量子相位科技制造幻影分身迷惑敌人。",
    "Combat prediction system with auto-dodge and ambush immunity.": "战斗预测系统，自动闪避并免疫伏击。",
    "Auto-scans on map entry, revealing 1-2 enemies. +1 Scavenging, +5% Damage.": "进入地图时自动扫描，显示 1-2 名敌人。+1 拾荒，+5% 伤害。",
    "Premium steak for your companion. Fully restores hunger. Lasts 3 hours.": "给同伴的顶级牛排。完全恢复饱食度。持续 3 小时。",
    "Long-lasting chew bone. +10 happiness per pet. 200 durability.": "持久磨牙骨。每次抚摸 +10 快乐值。耐久 200。",
    "Military-grade healing stimulant. Fully restores all body parts. Single use.": "军规治疗兴奋剂。完全恢复所有身体部位。一次性。",
    "Reinforced armor plate. Used for Torso/Skeleton augment upgrades (+1-+3).": "强化装甲板。用于躯干/骨架义体升级（+1 至 +3）。",
    "High-capacity power cell. Used for Shoulder augment upgrades (+1-+3).": "大容量电池。用于肩部义体升级（+1 至 +3）。",
    "Salvaged neural components. Used for Brain/Eye augment upgrades (+1-+3).": "回收的神经组件。用于大脑/眼部义体升级（+1 至 +3）。",
    "Advanced quantum computing chip. Used for any augment upgrade (+4-+6).": "先进量子计算芯片。用于任意义体升级（+4 至 +6）。",
    "Precision servo mechanism. Used for Arms/Legs augment upgrades (+1-+3).": "精密伺服机构。用于手臂/腿部义体升级（+1 至 +3）。",
    "Fragment of compressed spacetime. Used for any augment upgrade (+9-+10).": "压缩时空的碎片。用于任意义体升级（+9 至 +10）。",
    "Quantum-locked stabilizer. Prevents level loss on upgrade failure. Consumed on use.": "量子锁定稳定器。升级失败时防止等级损失。使用后消耗。",
    "Synthetic organic tissue. Used for Skin/Internal augment upgrades (+1-+3).": "合成有机组织。用于皮肤/内脏义体升级（+1 至 +3）。",
    "Crystallized void energy. Used for any augment upgrade (+7-+8).": "结晶化的虚空能量。用于任意义体升级（+7 至 +8）。",
    "Universal prototype magazine. Grants infinite ammo to any weapon. Multiple stack additively.": "通用原型弹匣。为任意武器提供无限弹药。多个可叠加。",
    "Sector 7 went dark the night this was removed. The logs say 'scheduled maintenance'. There was no maintenance scheduled.": "它被取下的那晚，第 7 区陷入黑暗。日志上写着'例行维护'。根本没有安排过维护。",
    "A signal from a station destroyed 20 years ago. It broadcasts coordinates. They change every night.": "来自一座 20 年前被摧毁的电台的信号。它在广播坐标。坐标每晚都在变。",
    "The AI that designed this city never stopped running. The street layout spells something if you look from above.": "设计这座城市的 AI 从未停机。从高空俯瞰，街道布局拼出了某种东西。",
    "Found in a room that doesn't appear on any blueprint. The door only opens when no one is watching.": "发现于一个不存在于任何图纸上的房间。那扇门只在没人看的时候打开。",
    "Final page reads: 'If you're reading this, it worked.' The rest of the document is blank. Or seems to be.": "最后一页写着：'如果你在读这段话，说明成功了。'其余部分是空白的。或者看起来是。",
    "A bag of tasty dog treats. Your furry friend will love these.": "一袋美味狗零食。你的毛茸茸朋友会爱死它们。",
    "Three meters of honest copper. Worth more than most promises.": "三米实打实的铜。比大多数承诺都值钱。",
    "64 cores, zero dignity. Spent its best years mining shitcoins.": "64 核，零尊严。把最好的年华花在了挖垃圾币上。",
    "Once rendered entire worlds. Now it just renders regret. Too far gone to mine with, but scrappers pay well for the rare earths.": "曾渲染过整个世界。现在只渲染悔恨。烧得没法再挖矿了，但回收商愿为里面的稀土出好价钱。",
    "Flexible, durable, and the most boring item you'll ever loot.": "柔韧、耐用，也是你能捡到的最无聊的东西。",
    "Construction material or firewood. Depends on how cold it gets.": "建材或柴火。取决于天有多冷。",
    "Lab-grown molecular adhesive. Bonds anything to anything. Permanently.": "实验室培育的分子粘合剂。什么都能粘。永久地。",
    "Eats through steel in seconds. Handle with gloves. Thick gloves.": "几秒内蚀穿钢铁。戴手套操作。厚手套。",
    "Protection from biological threats. Not from existential ones.": "防得住生物威胁。防不住存在主义危机。",
    "Three stars on the collar. Rank insignia torn off. Someone didn't want to be identified.": "领口三颗星。军衔章被撕掉了。有人不想被认出来。",
    "Lock screen says 'I miss you'. Battery's been dead for years.": "锁屏上写着'我想你'。电池已经死了很多年。",
    "25% chance to infuse weapon with random element. Consumed on use.": "25% 概率为武器注入随机元素。使用后消耗。",
    "Hold it to your ear. You'll hear something. Everyone hears something different.": "把它贴在耳边。你会听到些什么。每个人听到的都不一样。",
    "Contents: biological. Status: classified. Temperature: wrong.": "内容物：生物性。状态：机密。温度：不对劲。",
    "Proto weapon salvage component 35% → 45%, mythic salvage module 25% → 30%": "原型武器拆解出部件 35% → 45%，MYTHIC 拆解出模块 25% → 30%",
    "+2%/rank chance: gear drop upgrades one rarity tier (caps at Prototype)": "每级 +2% 概率：掉落装备提升一个稀有度（上限 PROTOTYPE）",
    "Locked/terminal POIs open instantly: no minigame, no wait, no idle penalty": "上锁/终端 POI 立即打开：无小游戏，无等待，无挂机惩罚",
    "Warlord's compound welded together from ship hulls. The Blackstar Warlord runs the place and doesn't like visitors.": "用船体焊起来的军阀大院。Blackstar Warlord 统治着这里，而且不喜欢访客。",
    "Still burning from a conflict nobody remembers starting. Automated turrets shoot at anything with a pulse. Great loot though, so people keep going back.": "一场没人记得如何开始的冲突，至今仍在燃烧。自动炮塔见活物就打。但战利品够肥，所以人们还是一趟趟往里跑。",
    "Research bunker that went dark decades ago. The AI inside kept running, kept building. Whatever it made down there, it's not happy about company.": "几十年前失联的研究地堡。里面的 AI 从未停转，从未停止建造。不管它在下面造了什么，它都不欢迎访客。",
    "Where the quiet ends. Scav crews run supply lines through here, shoot first and don't bother asking later. Decent pickings if you're quick.": "寂静的尽头。拾荒者车队在这里跑补给线，先开枪，懒得问。手快的话收获不错。",
    "Collapsed civic quarter full of raiders who think they own the place. They put up flags and everything. Almost cute if they weren't trying to kill you.": "塌了一半的市政区，满是自以为是地主的掠夺者。他们还挂了旗子什么的。要不是想杀你，还挺可爱。",
    "Perimeter of a dead fortress where they just keep coming. Endless waves. Pack twice the ammo you think you'll need, then pack more.": "死去要塞的外围，敌人源源不绝。无尽的浪潮。带上你认为需要的两倍弹药，然后再多带点。",
    "Something underground leaks energy that fries unshielded gear. A corp tried to extract it, failed, and left a whole base worth of equipment behind. Their loss.": "地下有什么东西在泄漏能量，能烧毁无屏蔽的装备。某公司试图开采，失败了，扔下了整整一基地的设备。他们的损失。",
    "Pre-war metro tunnels, half-flooded and pitch dark past the first junction. Smugglers move hardware down here that definitely fell off a truck.": "战前的地铁隧道，半淹在水里，过了第一个岔口就一片漆黑。走私者在下面倒腾那些'从卡车上掉下来'的硬件。",
    "Quiet stretch on the city's edge. Mostly picked clean. Good place to learn the ropes, bad place to find anything exciting.": "城市边缘的安静地带。基本被搜刮干净了。适合练手，别指望找到什么刺激的。",
    "Before anything else: grab this window and drag it wherever suits you. Hold my portrait or the title bar. I'll stay out of your way. Mostly.": "先说最重要的：抓住这个窗口，把它拖到你顺手的地方。按住我的头像或标题栏就行。我不会碍你的事。基本上。",
    "Open SKILLS and pick a class that fits how you fight. Lock it in, then spend a skill point in the tree. Respec exists: nothing is forever. Almost nothing.": "打开技能，选一个适合你打法的职业。锁定它，然后在天赋树里花一个技能点。可以洗点：没什么是永恒的。几乎没什么。",
    "Ready for the deep end? That INSANITY terminal in the hub isn't decoration. Jack in and put down 10 horrors.": "准备好跳进深水区了？基地里那台 INSANITY 终端不是摆设。接入，干掉 10 个恐怖玩意。",
    "Now crack open that SEED CACHE I just paid for. The reels are rigged in interesting ways.": "现在打开我刚掏钱买的那个种子补给箱。转盘被动过手脚，动得很有意思。",
    "TRADERS keep you breathing out there. The GUNSMITH runs a welcome job. Accept it, finish it, claim the reward. Never leave quest money on the table.": "商人是你在外面活命的本钱。GUNSMITH 有个迎新差事。接下它，完成它，领取奖励。永远别把任务钱留在桌上。",
    "One more thing: every trader's quests share that one screen. You can always auto accept and auto complete quests from Options > GAMEPLAY.": "还有一件事：所有商人的任务共用同一个界面。你随时可以在 选项 > 游戏性 里开启任务自动接受和自动完成。",
    "The field. I'll walk you through it once, then you're on your own.": "战场。我带你走一遍，之后就靠你自己了。",
    "Click a POI icon on the map. You'll route there and start searching on arrival. Go on, click one.": "点击地图上的 POI 图标。你会自动前往并在抵达后开始搜索。来，点一个。",
    "Done looting? Route to EXTRACT and leave alive. Dying costs you the bag. Good hunting.": "搜刮完了？前往撤离点，活着离开。死了就丢包。祝你狩猎愉快。",
    "Clicks stack into a route queue. Double-click a POI to drop the queue and head straight there.": "点击会叠加成路线队列。双击一个 POI 可清空队列并直奔那里。",
    "SHIFT toggles auto sprint. Faster legs, hungrier stamina. Try it now.": "SHIFT 切换自动冲刺。腿更快，耐力消耗更凶。现在试试。",
    "Top left HUD shows your gun, its magazine and ammo. Reloads live there, watch it in fights.": "左上角 HUD 显示你的枪、弹匣和弹药。装填信息也在那里，战斗中盯紧它。",
    "Active quest objectives are listed under your weapon HUD, top left.": "进行中的任务目标列在左上角武器 HUD 下方。",
    "Now the real thing. Rule one: the field pays better than it kills, if you're smart. Pick a map, run a raid, come back breathing.": "现在来真的。第一法则：只要你够聪明，战场给的比它夺走的多。选张地图，跑一次 RAID，活着回来。",
    "Which brings me to this: favorite gun? LOCK it before you fat-finger a bulk sell. The padlock button in your stash sidebar does it. Trust me on this one.": "所以说到这个：有心爱的枪？在你手滑批量出售之前锁上它。仓库侧栏的挂锁按钮就是干这个的。这条听我的。",
    "Attune to the void: unlocks Echo Harvest. CL10 itself opens at Prestige 8": "与虚空调谐：解锁回响收割。CL10 本身在 PRESTIGE 8 开启",
    "Kill one hostile. Bring proof you know which end the bullet comes from.": "杀一个敌人。证明你分得清子弹从哪头出来。",
    "Blackstar Warlord. One kill. When it's done, you'll have earned the right to see what I keep in the back.": "Blackstar Warlord。杀一次。搞定之后，你就有资格看看我在后屋藏了什么。",
    "Eclipse Core. The real thing. Kill it and there's nothing left I can teach you.": "Eclipse Core。真家伙。杀了它，我就没什么可教你的了。",
    "Frontline Outskirts. Ten kills. That zone filters out tourists. Don't be one.": "前线外围。十个击杀。那片区域专门过滤游客。别当游客。",
    "Five successful extractions. Any map. Dead operators don't buy guns.": "五次成功撤离。地图随意。死掉的干员不买枪。",
    "Thirty kills. By now you should be efficient. If you're not, we're done talking.": "三十个击杀。到这地步你该有效率了。没有的话，我们没什么好谈的。",
    "CL1 or higher. Fifteen kills. Corrupted targets hit different. Adapt or die.": "CL1 或更高。十五个击杀。受蚀目标的打击感不一样。适应，或者死。",
    "Greyhall District. Thirty contacts. The district breeds harder targets. Good testing ground.": "灰厅区。三十个目标。那个区养出更硬的敌人。绝佳的试验场。",
    "Three Wardens. Not one. Three. Each one teaches you something the last one didn't.": "三个 WARDEN。不是一个。三个。每一个都会教你上一个没教的东西。",
    "Deadflare Zone. Forty kills. That place doesn't forgive mistakes. Neither do I.": "死耀区。四十个击杀。那地方不原谅错误。我也不。",
    "Push an augment to level 3. That's where the synthetic starts talking back. If your brain doesn't reject it by then, you're golden. Mostly.": "把一件义体升到 3 级。到那个等级，合成体就开始顶嘴了。如果那时你的大脑还没排异，你就稳了。基本上。",
    "Bring me 3000 worth of anything. Scrap, junk, whatever. My supply chains are thin and every piece of garbage has a buyer somewhere.": "给我带 3000 块的任何东西。废料、垃圾、随便。我的供应链很紧，而每件垃圾在某处都有买家。",
    "Salvage five pieces of gear. Rip 'em apart. I need the raw materials more than you need another rusted vest collecting dust in your stash.": "拆解五件装备。撕碎它们。比起你仓库里又一件积灰的锈背心，我更需要原材料。",
    "Move 5000 worth of product through any trader. Doesn't matter which one. I need to know you can circulate value, not just hoard it like a rat.": "通过任意商人出手 5000 块的货。哪个商人无所谓。我得知道你会让价值流通，而不是像耗子一样囤着。",
    "Signal Corruption. CL1, baby's first nightmare. Get in there, survive it, extract. The static changes things. Changes people. I want to see how it changes you.": "信号侵蚀。CL1，宝宝的第一个噩梦。进去，活下来，撤离。静噪会改变事物。也改变人。我想看看它怎么改变你。",
    "Kill a Warden. Those things don't go down easy. When you're standing over its body, you'll understand why I charge what I charge.": "杀一个 WARDEN。那些东西不好对付。当你站在它尸体上时，你就会明白我为什么收这个价。",
    "Tape and matches. Don't ask why. Neural calibration isn't pretty. Your first implant. After this, there's no going back to factory settings.": "胶带和火柴。别问为什么。神经校准不是什么好看的活。你的第一件植入体。这之后，就再也回不到出厂设置了。",
    "Greyhall District. 25 bodies. Chrome needs real combat data to calibrate properly. Greyhall's got enough hostiles to stress-test your new wiring.": "灰厅区。25 具尸体。义体需要真实战斗数据才能校准。灰厅区的敌人够多，正好压力测试你的新线路。",
    "The signal has a frequency. Most can't hear it. CL1. The first threshold. Cross it and report back. I'll know if you're lying.": "信号有一个频率。大多数人听不见。CL1。第一道门槛。跨过去，回来汇报。你撒谎我会知道。",
    "CL3. Where the static starts whispering. Some operators hear voices. Others hear nothing. Both should worry you.": "CL3。静噪开始低语的地方。有些干员听到人声。有些什么也听不到。两种情况都该让你担心。",
    "CL5. The signal folds back on itself here. Reality starts bending. Push through. What you find on the other side pays for itself.": "CL5。信号在这里向内折叠。现实开始弯曲。挺过去。另一边的发现物有所值。",
    "CL8. The corruption stops pretending to be natural. It knows you're there. It doesn't like visitors. Go anyway.": "CL8。侵蚀不再伪装成自然现象。它知道你在那里。它不喜欢访客。照样去。",
    "CL10. The void. Where the signal originated. No one has mapped what's beyond. Be the first. Or don't. The signal doesn't care either way.": "CL10。虚空。信号的发源地。没人绘制过更深处的地图。做第一个。或者别做。信号反正无所谓。",
    "Two rolls of nano-tape. Good quality. I'll have something for you when you're back.": "两卷纳米胶带。要好货。你回来时我会有东西给你。",
    "Three extractions. Any map. Come back alive each time, that's all I ask.": "三次撤离。地图随意。每次都活着回来，我只求这个。",
    "Find a prototype. People kill for those. Try not to be one of them.": "找一件原型装备。有人会为它杀人。尽量别成为其中之一。",
    "Eclipse Bastion. Five extractions. The armor that comes out of there, I can't buy it anywhere. Bring me samples.": "蚀日堡垒。五次撤离。从那里流出的护甲，我在哪都买不到。给我带样品来。",
    "The dog follows my shipments. Seems to like you. Bring three treats and it's yours. Don't make me repeat myself.": "那条狗一直跟着我的货队。它好像喜欢你。带三份狗零食来，它就归你了。别让我说第二遍。",
