    // ==== chunk 09: statik UI devam ====
    "MYTHIC MODS": "MYTHIC 模组",
    "MYTHIC gear in your stash and equipment is destroyed too": "仓库和装备中的 MYTHIC 装备也会被摧毁",
    "Modify": "改装",
    "Mythic Mods": "MYTHIC 模组",
    "NEXT RANK": "下一等级",
    "NO WEAPON": "无武器",
    "NONE": "无",
    "NOT NOW": "暂不",
    "No keystones selected": "未选择楔石",
    "No saved plans": "没有已保存的方案",
    "No stats yet": "暂无数据",
    "OBJECTIVES": "目标",
    "OFF": "关",
    "OFFLINE": "离线",
    "ON": "开",
    "ONLINE": "在线",
    "OPEN AGAIN": "再次打开",
    "OPERATION:": "行动：",
    "OPERATIVE:": "干员：",
    "OPERATOR IDENTIFICATION REQUIRED": "需要干员身份验证",
    "PAUSED": "已暂停",
    "PHOTOSENSITIVITY WARNING": "光敏性癫痫警告",
    "PLAN SUMMARY": "方案摘要",
    "POINTS:": "点数：",
    "PRESS F TO INTERACT": "按 F 互动",
    "PROCEED WITH SURGERY": "进行手术",
    "PURCHASE": "购买",
    "Press SPACE when pin is in the green zone!": "当指针进入绿色区域时按空格键！",
    "Progress:": "进度：",
    "QUEST": "任务",
    "QUESTS": "任务",
    "RAID COMPLETE": "RAID 完成",
    "RAID FILTERS": "RAID 筛选",
    "REDEPLOY": "重新部署",
    "REFLEX": "反射",
    "RESET": "重置",
    "RESET ALL DATA": "重置所有数据",
    "Repair": "修理",
    "SAFE": "安全",
    "SAVE": "保存",
    "SAVED PLANS": "已保存方案",
    "SCREEN SHAKE": "屏幕震动",
    "SEARCH": "搜索",
    "SEARCHING...": "搜索中……",
    "SELECT AVATAR:": "选择头像：",
    "SELL": "出售",
    "SERVER STATUS:": "服务器状态：",
    "SIGNAL CORRUPTION": "信号侵蚀",
    "SIGNAL LOST": "信号丢失",
    "SILENT EXPANSE": "寂静旷野",
    "SKILLS": "技能",
    "SKIP": "跳过",
    "SPECIAL THANKS": "特别鸣谢",
    "STANDARD": "标准",
    "STASH": "仓库",
    "STATS ▾": "属性 ▾",
    "STOCK": "库存",
    "SWITCH": "切换",
    "SYSTEM CONFIGURATION": "系统设置",
    "Salvage": "拆解",
    "Select an item to begin": "选择一件物品开始",
    "Select an item to view details": "选择一件物品查看详情",
    "Sell": "出售",
    "Stats": "属性",
    "Stats, Money, Level, Skill Tree, Class, Stash and Equipment will be reset.": "属性、金钱、等级、技能树、职业、仓库和装备都将被重置。",
    "Store in Locker": "存入储物柜",
    "TECH": "科技",
    "TERMINAL": "终端",
    "TEXT SIZE": "文字大小",
    "TIER": "品阶",
    "TIER:": "品阶：",
    "TIME:": "时间：",
    "TRADERS": "商人",
    "TRANSCEND YOUR LIMITS": "超越你的极限",
    "This action cannot be undone!": "此操作无法撤销！",
    "This game contains flashing lights, rapid screen effects,": "本游戏包含闪烁灯光、快速屏幕特效，",
    "UNKNOWN": "未知",
    "UPGRADE": "升级",
    "Unlock": "解锁",
    "Unlocks Augment:": "解锁义体：",
    "Use": "使用",
    "VALUE:": "价值：",
    "VERSION": "版本",
    "VITALS": "生命体征",
    "WAIT": "等待",
    "WEIGHT:": "重量：",
    "YOUR STASH": "你的仓库",
    "LOADOUT": "配装",
    "[ BACK ]": "[ 返回 ]",
    "[ CANCEL ]": "[ 取消 ]",
    "[ CLOSE ]": "[ 关闭 ]",
    "[ COMBAT ]": "[ 战斗 ]",
    "[ CONFIRM ]": "[ 确认 ]",
    "[ CONTINUE ]": "[ 继续 ]",
    "[ CREDITS ]": "[ 制作人员 ]",
    "[ EXIT ]": "[ 退出 ]",
    "[ JOIN DISCORD ]": "[ 加入 DISCORD ]",
    "[ LOAD GAME ]": "[ 载入游戏 ]",
    "[ LOADOUT ]": "[ 配装 ]",
    "[ NEW GAME ]": "[ 新游戏 ]",
    "[ OPERATIONS ONLINE ]": "[ 行动网络在线 ]",
    "[ OPERATIONS ]": "[ 行动 ]",
    "[ OPTIONS ]": "[ 选项 ]",
    "[ QUESTS ]": "[ 任务 ]",
    "[ SKILLS ]": "[ 技能 ]",
