    // ==== часть 04: предметы мусора ====
    "Flash Drive": "Флешка",
    "Matches": "Спички",
    "Paradox Engine": "Двигатель Парадокса",
    "Echo Drive": "Echo Drive",
    "The First Flame": "Первое пламя",
    "Ghost Frequency": "Частота Призрака",
    "The Architect's Core": "Ядро Архитектора",
    "Null Shard": "Осколок Пустоты",
    "Omega Protocol": "Протокол Омега",
    "Dog Treats": "Лакомства для собак",
    "Screw Nut": "Гайка",
    "Pack of Nails": "Пачка гвоздей",
    "Copper Wire": "Медная проволока",
    "Dirty AlloyMesh Screen": "Грязный экран AlloyMesh",
    "Nano-Tape": "Нанолента",
    "Mini Repair Wedge": "Мини-ремонтный клин",
    "Old CPU": "Старый процессор",
    "Servo Motor": "Сервомотор",
    "PMC Dogtag": "Жетон PMC",
    "Expansion Slot": "Слот расширения",
    "Encrypted SSD": "Зашифрованный SSD",
    "Burnt-Out GPU": "Сгоревшая видеокарта",
    "Empty Bottle": "Пустая бутылка",
    "Plastic Sheet": "Пластиковая пластина",
    "Rubber Strip": "Резиновая лента",
    "Warped Plank": "Изогнутая доска",
    "Scrap Metal": "Металлолом",
    "Carbon Fiber Rod": "Углеродный стержень",
    "Fiber Optic Cable": "Оптоволоконный кабель",
    "Kernel Override": "Kernel Override",
    "Alloy Plate": "Пластина из сплава",
    "Titanium Bar": "Титановый слиток",
    "Rusty Gear": "Ржавая шестерня",
    "Coiled Spring": "Спиральная пружина",
    "Pressure Valve": "Напорный клапан",
    "Pipe Fitting": "Трубная арматура",
    "Cracked Watch": "Разбитые часы",
    "Precision Bearings": "Прецизионные подшипники",
    "Gyroscope": "Гироскоп",
    "Actuator Assembly": "Узел актуатора",
    "Mil-Grade Capacitor": "Военный конденсатор",
    "Hydraulic Pump": "Гидравлический насос",
    "Zippo Lighter": "Зажигалка Zippo",
    "Flathead Screwdriver": "Шлицевая отвертка",
    "Rusty Pliers": "Ржавые плоскогубцы",
    "Bent Wrench": "Погнутый ключ",
    "Wire Cutter": "Кусачки",
    "Rigged Multitool": "Самодельный мультитул",
    "Soldering Iron": "Паяльник",
    "Pocket Arc Welder": "Карманный дуговой сварочный аппарат",
    "Lockpick Set": "Набор отмычек",
    "System Recompiler": "Рекомпилятор системы",
    "Dead Batteries": "Разряженные батареи",
    "Adhesive Tube": "Тюбик клея",
    "Industrial Detergent": "Промышленное моющее средство",
    "Motor Oil": "Моторное масло",
    "Chemical Solvent": "Химический растворитель",
    "Thermite Paste": "Термитная паста",
    "Solid Propellant": "Твердое топливо",
    "Synthetic Compound": "Синтетическое соединение",
    "Corrosive Acid": "Коррозийная кислота",
    "Dirty Rag": "Грязная тряпка",
    "Optimizer AI": "ИИ-оптимизатор",
    "Torn Face Mask": "Разорванная маска",
    "Torn Fabric": "Обрывки ткани",
    "Old Boot": "Старый ботинок",
    "Work Gloves": "Рабочие перчатки",
    "Worn Jacket": "Поношенная куртка",
    "Camo Pants": "Камуфляжные штаны",
    "Torn Tactical Vest": "Разорванный тактический жилет",
    "Kevlar Patch": "Кевларовая заплатка",
    "Hazmat Hood": "Капюшон химзащиты",
    "Officer's Coat": "Пальто офицера",
    "Unstable Glitch Mote": "Нестабильная частица GLITCH",
    "Ballistic Weave": "Бронеткань",
    "Frayed USB Cable": "Перетертый USB-кабель",
    "Dead LED Strip": "Сгоревшая светодиодная лента",
    "Broken Keyboard": "Сломанная клавиатура",
    "Cracked Phone": "Разбитый телефон",
    "RAM Stick": "Модуль оперативной памяти",
    "Burnt Circuit Board": "Обгоревшая печатная плата",
    "Old Hard Drive": "Старый жесткий диск",
    "Signal Antenna": "Сигнальная антенна",
    "Drone Camera": "Камера дрона",
    "Factory Reset Drive": "Диск с заводскими настройками",
    "Broken Holo-Projector": "Сломанный голопроектор",
    "Mil. Encryption Chip": "Военный чип шифрования",
    "Faded Photograph": "Выцветшая фотография",
    "Crumpled Note": "Смятая записка",
    "Expired ID Card": "Просроченное удостоверение",
    "Field Report": "Полевой отчет",
    "Encrypted Data Stick": "Зашифрованный накопитель",
    "Tactical Map": "Тактическая карта",
    "Flight Recorder": "Бортовой самописец",
    "Decoded Signal Log": "Декодированный журнал сигналов",
    "Elemental Catalyst": "Элементальный катализатор",
    "Classified Documents": "Секретные документы",
    "Whispering Stone": "Шепчущий камень",
    "Strange Coin": "Странная монета",
    "Pre-War Relic": "Реликт довоенных времен",
    "Data Crystal": "Кристалл данных",
    "Signal Fragment": "Фрагмент сигнала",
    "Cryo-Preserved Vial": "Криогенная ампула",
    "Temporal Shard": "Временной осколок",
    "Anomaly Sample": "Образец аномалии",
    "Void Fragment": "Фрагмент Пустоты",
