    // ==== часть 03: названия предметов (бренд на латинице + перевод типа) ====
    "Smartframe Pack T1": "Рюкзак Smartframe T1",
    "Vanta Pack T2": "Рюкзак Vanta T2",
    "Kestrel Pack T3": "Рюкзак Kestrel T3",
    "Ironclad Pack T4": "Рюкзак Ironclad T4",
    "RustTek Pack T5": "Рюкзак RustTek T5",
    "Smartframe Armor T1": "Броня Smartframe T1",
    "Vanta Armor T2": "Броня Vanta T2",
    "Kestrel Armor T3": "Броня Kestrel T3",
    "Ironclad Armor T4": "Броня Ironclad T4",
    "RustTek Armor T5": "Броня RustTek T5",
    "Smartframe Bolt-Action": "Винтовка Smartframe Bolt-Action",
    "Vanta Bolt-Action": "Винтовка Vanta Bolt-Action",
    "Kestrel Bolt-Action": "Винтовка Kestrel Bolt-Action",
    "Ironclad Bolt-Action": "Винтовка Ironclad Bolt-Action",
    "RustTek Bolt-Action": "Винтовка RustTek Bolt-Action",
    "Smartframe AR": "Штурмовая винтовка Smartframe AR",
    "Vanta AR": "Штурмовая винтовка Vanta AR",
    "Kestrel AR": "Штурмовая винтовка Kestrel AR",
    "Ironclad AR": "Штурмовая винтовка Ironclad AR",
    "RustTek AR": "Штурмовая винтовка RustTek AR",
    "Smartframe DMR": "Марксманская винтовка Smartframe DMR",
    "Vanta DMR": "Марксманская винтовка Vanta DMR",
    "Kestrel DMR": "Марксманская винтовка Kestrel DMR",
    "Ironclad DMR": "Марксманская винтовка Ironclad DMR",
    "RustTek DMR": "Марксманская винтовка RustTek DMR",
    "Smartframe Pistol": "Пистолет Smartframe",
    "Vanta Pistol": "Пистолет Vanta",
    "Kestrel Pistol": "Пистолет Kestrel",
    "Ironclad Pistol": "Пистолет Ironclad",
    "RustTek Pistol": "Пистолет RustTek",
    "Smartframe Shotgun": "Дробовик Smartframe",
    "Vanta Shotgun": "Дробовик Vanta",
    "Kestrel Shotgun": "Дробовик Kestrel",
    "Ironclad Shotgun": "Дробовик Ironclad",
    "RustTek Shotgun": "Дробовик RustTek",
    "Smartframe SMG": "ПП Smartframe SMG",
    "Vanta SMG": "ПП Vanta SMG",
    "Kestrel SMG": "ПП Kestrel SMG",
    "Ironclad SMG": "ПП Ironclad SMG",
    "RustTek SMG": "ПП RustTek SMG",
    "Smartframe Blade": "Клинок Smartframe",
    "Vanta Blade": "Клинок Vanta",
    "Kestrel Blade": "Клинок Kestrel",
    "Ironclad Blade": "Клинок Ironclad",
    "RustTek Blade": "Клинок RustTek",
    "Smartframe Helmet T1": "Шлем Smartframe T1",
    "Vanta Helmet T2": "Шлем Vanta T2",
    "Kestrel Helmet T3": "Шлем Kestrel T3",
    "Ironclad Helmet T4": "Шлем Ironclad T4",
    "RustTek Helmet T5": "Шлем RustTek T5",
    "Smartframe Headset T1": "Гарнитура Smartframe T1",
    "Vanta Headset T2": "Гарнитура Vanta T2",
    "Kestrel Headset T3": "Гарнитура Kestrel T3",
    "Ironclad Headset T4": "Гарнитура Ironclad T4",
    "RustTek Headset T5": "Гарнитура RustTek T5",
    "Smartframe Rig T1": "Разгрузка Smartframe T1",
    "Vanta Rig T2": "Разгрузка Vanta T2",
    "Kestrel Rig T3": "Разгрузка Kestrel T3",
    "Ironclad Rig T4": "Разгрузка Ironclad T4",
    "RustTek Rig T5": "Разгрузка RustTek T5",
    "Scav Pistol": "Пистолет Scav",
    "Scav Helmet": "Шлем Scav",
    "Scav Vest": "Жилет Scav",
    "Scav Webbing": "Снаряжение Scav",
    "Scav Satchel": "Сумка Scav",
    "Loyal Dog": "Верный пес",
    "Dog Kibble": "Корм для собак",
    "Premium Dog Food": "Премиум корм для собак",
    "Gourmet Steak": "Изысканный стейк",
    "Tennis Ball": "Теннисный мяч",
    "Chew Bone": "Кость для жевания",
    "Rope Toy": "Игрушка-веревка",
    "Tactical Goggles": "Тактические очки",
    "Tactical Mask": "Тактическая маска",
    "Mining GPU T1": "Видеокарта для майнинга T1",
    "Mining GPU T2": "Видеокарта для майнинга T2",
    "Mining GPU T3": "Видеокарта для майнинга T3",
    "Healing Stim": "Лечебный стимулятор",
    "Adrenaline": "Адреналин",
    "AR Magazine": "Магазин для AR",
    "SMG Magazine": "Магазин для SMG",
    "DMR Magazine": "Магазин для DMR",
    "Pistol Magazine": "Магазин для пистолета",
    "Shotgun Magazine": "Магазин для дробовика",
    "Bolt-Action Clip": "Обойма Bolt-Action",
    "Prototype Magazine": "Прототипный магазин",
    "Chassis Plate": "Пластина шасси",
    "Mount Capacitor": "Конденсатор крепления",
    "Neural Fragment": "Нейронный фрагмент",
    "Perfect Core": "Идеальное ядро",
    "Quantum Processor": "Квантовый процессор",
    "Servo Core": "Сервоядро",
    "Singularity Shard": "Осколок сингулярности",
    "Stabilizer Core": "Стабилизирующее ядро",
    "Synth Tissue": "Синтетическая ткань",
    "Void Crystal": "Кристалл Пустоты",
    "Core Container": "Контейнер для ядер",
    "Root Access Chip": "Чип корневого доступа",
