    // ==== часть 02: аффиксы/имена врагов ====
    "Shielded": "Щитованный",
    "of Iron": "Железа",
    "of Fury": "Ярости",
    "of Vitality": "Жизненной силы",
    "of Steel": "Стали",
    "of the Brute": "Грубой силы",
    "of Endurance": "Стойкости",
    "GUARD": "ГВАРДЕЕЦ",
    "SECURITY": "ОХРАНА",
    "PATROL": "ПАТРУЛЬНЫЙ",
    "ENFORCER": "ИСПОЛНИТЕЛЬ",
    "SENTINEL": "ЧАСОВОЙ",
    "AMBUSHER": "ДИВЕРСАНТ",
    "TRAP SCAV": "СКАВ С ЛОВУШКАМИ",
    "LURKER": "СКРЫТНИК",
    "SHADOW": "ТЕНЬ",
    "PREDATOR": "ХИЩНИК",
    "SCAV": "СКАВ",
    "RAIDER": "РЕЙДЕР",
    "BANDIT": "БАНДИТ",
    "LOOTER": "МАРОДЕР",
    "DRIFTER": "СТРАННИК",
    "STALKER": "СТАЛКЕР",
    "ROGUE": "РАЗБОЙНИК",
