    // ==== chunk 04: junk itemleri ====
    "Flash Drive": "U盘",
    "Matches": "火柴",
    "Paradox Engine": "悖论引擎",
    "Echo Drive": "回响驱动器",
    "The First Flame": "初火",
    "Ghost Frequency": "幽灵频率",
    "The Architect's Core": "架构师核心",
    "Null Shard": "空无碎片",
    "Omega Protocol": "欧米茄协议",
    "Dog Treats": "狗零食",
    "Screw Nut": "螺母",
    "Pack of Nails": "一包钉子",
    "Copper Wire": "铜线",
    "Dirty AlloyMesh Screen": "脏污 AlloyMesh 屏幕",
    "Nano-Tape": "纳米胶带",
    "Mini Repair Wedge": "迷你修理楔",
    "Old CPU": "旧CPU",
    "Servo Motor": "伺服电机",
    "PMC Dogtag": "PMC 狗牌",
    "Expansion Slot": "扩展插槽",
    "Encrypted SSD": "加密固态硬盘",
    "Burnt-Out GPU": "烧毁的显卡",
    "Empty Bottle": "空瓶",
    "Plastic Sheet": "塑料板",
    "Rubber Strip": "橡胶条",
    "Warped Plank": "变形木板",
    "Scrap Metal": "废金属",
    "Carbon Fiber Rod": "碳纤维杆",
    "Fiber Optic Cable": "光纤线缆",
    "Kernel Override": "内核超控",
    "Alloy Plate": "合金板",
    "Titanium Bar": "钛锭",
    "Rusty Gear": "生锈齿轮",
    "Coiled Spring": "卷簧",
    "Pressure Valve": "压力阀",
    "Pipe Fitting": "管件",
    "Cracked Watch": "破裂手表",
    "Precision Bearings": "精密轴承",
    "Gyroscope": "陀螺仪",
    "Actuator Assembly": "致动器组件",
    "Mil-Grade Capacitor": "军规电容",
    "Hydraulic Pump": "液压泵",
    "Zippo Lighter": "Zippo 打火机",
    "Flathead Screwdriver": "一字螺丝刀",
    "Rusty Pliers": "生锈钳子",
    "Bent Wrench": "弯曲扳手",
    "Wire Cutter": "剪线钳",
    "Rigged Multitool": "拼装多功能工具",
    "Soldering Iron": "电烙铁",
    "Pocket Arc Welder": "袖珍电弧焊机",
    "Lockpick Set": "撬锁工具组",
    "System Recompiler": "系统重编译器",
    "Dead Batteries": "废电池",
    "Adhesive Tube": "胶水管",
    "Industrial Detergent": "工业洗涤剂",
    "Motor Oil": "机油",
    "Chemical Solvent": "化学溶剂",
    "Thermite Paste": "铝热剂膏",
    "Solid Propellant": "固体推进剂",
    "Synthetic Compound": "合成化合物",
    "Corrosive Acid": "腐蚀酸",
    "Dirty Rag": "脏抹布",
    "Optimizer AI": "优化器AI",
    "Torn Face Mask": "撕裂面罩",
    "Torn Fabric": "破布料",
    "Old Boot": "旧靴子",
    "Work Gloves": "工作手套",
    "Worn Jacket": "破旧夹克",
    "Camo Pants": "迷彩裤",
    "Torn Tactical Vest": "破损战术背心",
    "Kevlar Patch": "凯夫拉补片",
    "Hazmat Hood": "防化头罩",
    "Officer's Coat": "军官大衣",
    "Unstable Glitch Mote": "不稳定 GLITCH 微尘",
    "Ballistic Weave": "防弹织物",
    "Frayed USB Cable": "磨损USB线",
    "Dead LED Strip": "报废LED灯条",
    "Broken Keyboard": "坏键盘",
    "Cracked Phone": "碎屏手机",
    "RAM Stick": "内存条",
    "Burnt Circuit Board": "烧焦电路板",
    "Old Hard Drive": "旧硬盘",
    "Signal Antenna": "信号天线",
    "Drone Camera": "无人机摄像头",
    "Factory Reset Drive": "出厂重置盘",
    "Broken Holo-Projector": "损坏的全息投影仪",
    "Mil. Encryption Chip": "军用加密芯片",
    "Faded Photograph": "褪色照片",
    "Crumpled Note": "揉皱的字条",
    "Expired ID Card": "过期证件",
    "Field Report": "战地报告",
    "Encrypted Data Stick": "加密数据棒",
    "Tactical Map": "战术地图",
    "Flight Recorder": "飞行记录仪",
    "Decoded Signal Log": "已解码信号日志",
    "Elemental Catalyst": "元素催化剂",
    "Classified Documents": "机密文件",
    "Whispering Stone": "低语之石",
    "Strange Coin": "奇异硬币",
    "Pre-War Relic": "战前遗物",
    "Data Crystal": "数据水晶",
    "Signal Fragment": "信号碎片",
    "Cryo-Preserved Vial": "低温保存试管",
    "Temporal Shard": "时间碎片",
    "Anomaly Sample": "异常样本",
    "Void Fragment": "虚空残片",
