    // ==== JS_UI parça 6: kullanıcı 2. tur bulguları ====
    "HULL PLATING": "船体镀甲",
    "CRIT LENS": "暴击透镜",
    "DAMAGE AMP": "伤害增幅",
    "< HUB": "＜ 基地",
    "GHOST": "幽灵",
    "OPEN": "打开",
    "GLITCH FLASH": "GLITCH 闪光",
    "DR": "减伤",
    "STA": "耐力",
    "USE": "使用",
    "NO SIGNAL": "无信号",
    "SEARCH...": "搜索……",
    "EXTRACTION SUCCESSFUL": "撤离成功",
    "QUEST COMPLETE:": "任务完成：",
    "FIELD NOTES: CHECK THE MENTOR PANEL": "战地笔记：查看导师面板",
    "// DID YOU KNOW?": "// 你知道吗？",
    "DID YOU KNOW?": "你知道吗？",
    "Enemy Regen": "敌人回复",
    "Armor Shred": "破甲",
    "Heal Suppression": "治疗压制",
    "Enemy Enrage": "敌人激怒",
    "Corruption Shields": "侵蚀护盾",
    "Signal Static": "信号静噪",
    "Death Echo": "死亡回响",
    "Phantom Strike": "幻影打击",
    "Signal Overdrive": "信号超载",
    "Reality Fracture": "现实裂隙",
    "Fresh body, familiar face. Want my guided onboarding on this character? The tasks pay real rewards: cash, custom gear, FLUX and INSANITY.": "新的身体，熟悉的面孔。要在这个角色上开启我的引导教程吗？任务给的是真金白银：现金、定制装备、通量和疯狂值。",
    "Click the SILENT EXPANSE marker on the map, then hit DEPLOY on the right. Extract alive to keep the loot.": "点击地图上的寂静旷野标记，然后按右侧的部署。活着撤离才能保住战利品。",
    "Finish a raid; the summary screen lists HEAL, LOADOUT, REDEPLOY and CONTINUE.": "完成一场 RAID；结算界面会列出治疗、配装、重新部署和继续。",
    "HUB > TRADERS: pick GUNSMITH, open his QUEST tab, complete the Welcome Gift job.": "基地 > 商人：选择 GUNSMITH，打开他的任务页，完成欢迎礼物差事。",
    "HUB: LOADOUT. Shift-click gear to equip; drag mags into the backpack container.": "基地：配装。Shift+点击装备穿戴；把弹匣拖进背包容器。",
    "Options > GAMEPLAY: Auto Accept and Complete Quests.": "选项 > 游戏性：任务自动接受与完成。",
    "Silent Expanse is preset to corruption level 1. Click the marker, then hit DEPLOY on the right and clear the raid.": "寂静旷野已预设为侵蚀等级 1。点击标记，然后按右侧的部署并通关这场 RAID。",
    "Boss got you stuck? Pump DAMAGE AMP and HULL PLATING in the shop. Better raid gear raises your base stats too.": "被头目卡住了？在商店里堆伤害增幅和船体镀甲。更好的 RAID 装备也会提升你的基础属性。",
    "INSANITY terminal: the shop panel on the right. DAMAGE AMP and CRIT LENS under OFFENSE, HULL PLATING under DEFENSE.": "疯狂终端：右侧的商店面板。攻击栏下是伤害增幅和暴击透镜，防御栏下是船体镀甲。",
    "Stow a magazine and a medkit in your containers": "把一个弹匣和一个急救包放进你的容器",
    "Skip this task? You will not get its reward.": "跳过这个任务？你将不会获得它的奖励。",
    ">_ SELECT_CLASS": ">_ 选择职业",
    "Speed & Precision": "速度与精准",
    "Raw Damage": "纯粹伤害",
    "Elemental Mastery": "元素精通",
    "Defense & Sustain": "防御与续航",
    "High Risk, High Reward": "高风险，高回报",
    "+3 HP and +0.2 Armor per point": "每点 +3 生命和 +0.2 护甲",
    "RPM": "射速",
    "Armor Pen": "护甲穿透",
    "Cold Damage": "寒冷伤害",
    "Lightning Damage": "闪电伤害",
    "Fire Damage": "火焰伤害",
    "Total Raids": "总 RAID 次数",
    "Extractions": "撤离次数",
    "Failed": "失败次数",
    "Success Rate": "成功率",
    "Hostiles Eliminated": "消灭敌人",
    "Highest Single Hit": "最高单次伤害",
    "Sort items": "整理物品",
    "All items": "所有物品",
    "Gear only": "仅装备",
    "Junk only": "仅垃圾",
    "Salvage multiple items": "批量拆解物品",
    "Sell multiple items": "批量出售物品",
    "Lock items": "锁定物品",
