    // ==== часть 09: продолжение статичного UI ====
    "MYTHIC MODS": "MYTHIC модули",
    "MYTHIC gear in your stash and equipment is destroyed too": "MYTHIC снаряжение в хранилище и экипировке также будет уничтожено",
    "Modify": "Модифицировать",
    "Mythic Mods": "MYTHIC модули",
    "NEXT RANK": "СЛЕДУЮЩИЙ РАНГ",
    "NO WEAPON": "НЕТ ОРУЖИЯ",
    "NONE": "НЕТ",
    "NOT NOW": "НЕ СЕЙЧАС",
    "No keystones selected": "Ключевые навыки не выбраны",
    "No saved plans": "Нет сохраненных планов",
    "No stats yet": "Статистики пока нет",
    "OBJECTIVES": "ЦЕЛИ",
    "OFF": "ВЫКЛ",
    "OFFLINE": "ОФЛАЙН",
    "ON": "ВКЛ",
    "ONLINE": "ОНЛАЙН",
    "OPEN AGAIN": "ОТКРЫТЬ СНОВА",
    "OPERATION:": "ОПЕРАЦИЯ:",
    "OPERATIVE:": "ОПЕРАТИВНИК:",
    "OPERATOR IDENTIFICATION REQUIRED": "ТРЕБУЕТСЯ ИДЕНТИФИКАЦИЯ ОПЕРАТОРА",
    "PAUSED": "ПАУЗА",
    "PHOTOSENSITIVITY WARNING": "ПРЕДУПРЕЖДЕНИЕ О СВЕТОЧУВСТВИТЕЛЬНОСТИ",
    "PLAN SUMMARY": "РЕЗЮМЕ ПЛАНА",
    "POINTS:": "ОЧКИ:",
    "PRESS F TO INTERACT": "НАЖМИТЕ F ДЛЯ ВЗАИМОДЕЙСТВИЯ",
    "PROCEED WITH SURGERY": "ПРОДОЛЖИТЬ ОПЕРАЦИЮ",
    "PURCHASE": "КУПИТЬ",
    "Press SPACE when pin is in the green zone!": "Нажмите SPACE, когда стрелка окажется в зеленой зоне!",
    "Progress:": "Прогресс:",
    "QUEST": "ЗАДАНИЕ",
    "QUESTS": "ЗАДАНИЯ",
    "RAID COMPLETE": "RAID ЗАВЕРШЕН",
    "RAID FILTERS": "ФИЛЬТРЫ RAID",
    "REDEPLOY": "ПЕРЕДИСЛОКАЦИЯ",
    "REFLEX": "РЕФЛЕКС",
    "RESET": "СБРОС",
    "RESET ALL DATA": "СБРОСИТЬ ВСЕ ДАННЫЕ",
    "Repair": "Ремонт",
    "SAFE": "БЕЗОПАСНО",
    "SAVE": "СОХРАНИТЬ",
    "SAVED PLANS": "СОХРАНЕННЫЕ ПЛАНЫ",
    "SCREEN SHAKE": "ТРЯСКА ЭКРАНА",
    "SEARCH": "ПОИСК",
    "SEARCHING...": "ПОИСК...",
    "SELECT AVATAR:": "ВЫБЕРИТЕ АВАТАР:",
    "SELL": "ПРОДАТЬ",
    "SERVER STATUS:": "СТАТУС СЕРВЕРА:",
    "SIGNAL CORRUPTION": "ПОМЕХИ СИГНАЛА",
    "SIGNAL LOST": "СИГНАЛ ПОТЕРЯН",
    "SILENT EXPANSE": "SILENT EXPANSE",
    "SKILLS": "НАВЫКИ",
    "SKIP": "ПРОПУСТИТЬ",
    "SPECIAL THANKS": "ОСОБАЯ БЛАГОДАРНОСТЬ",
    "STANDARD": "STANDARD",
    "STASH": "ХРАНИЛИЩЕ",
    "STATS ▾": "ХАРАКТЕРИСТИКИ ▾",
    "STOCK": "ЗАПАС",
    "SWITCH": "ПЕРЕКЛЮЧИТЬ",
    "SYSTEM CONFIGURATION": "НАСТРОЙКИ СИСТЕМЫ",
    "Salvage": "Разбор",
    "Select an item to begin": "Выберите предмет, чтобы начать",
    "Select an item to view details": "Выберите предмет, чтобы просмотреть детали",
    "Sell": "Продать",
    "Stats": "Характеристики",
    "Stats, Money, Level, Skill Tree, Class, Stash and Equipment will be reset.": "Характеристики, деньги, уровень, древо навыков, класс, хранилище и снаряжение будут сброшены.",
    "Store in Locker": "Положить в шкафчик",
    "TECH": "ТЕХНО",
    "TERMINAL": "ТЕРМИНАЛ",
    "TEXT SIZE": "РАЗМЕР ТЕКСТА",
    "TIER": "ТИР",
    "TIER:": "ТИР:",
    "TIME:": "ВРЕМЯ:",
    "TRADERS": "ТОРГОВЦЫ",
    "TRANSCEND YOUR LIMITS": "ПРЕВЫШАЙ СВОИ ПРЕДЕЛЫ",
    "This action cannot be undone!": "Это действие нельзя отменить!",
    "This game contains flashing lights, rapid screen effects,": "Эта игра содержит мигающий свет, быстрые эффекты экрана,",
    "UNKNOWN": "НЕИЗВЕСТНО",
    "UPGRADE": "УЛУЧШИТЬ",
    "Unlock": "Разблокировать",
    "Unlocks Augment:": "Разблокирует аугментацию:",
    "Use": "Использовать",
    "VALUE:": "СТОИМОСТЬ:",
    "VERSION": "ВЕРСИЯ",
    "VITALS": "ПОКАЗАТЕЛИ ЖИЗНИ",
    "WAIT": "ПОДОЖДИТЕ",
    "WEIGHT:": "ВЕС:",
    "YOUR STASH": "ВАШЕ ХРАНИЛИЩЕ",
    "LOADOUT": "СНАРЯЖЕНИЕ",
    "[ BACK ]": "[ НАЗАД ]",
    "[ CANCEL ]": "[ ОТМЕНА ]",
    "[ CLOSE ]": "[ ЗАКРЫТЬ ]",
    "[ COMBAT ]": "[ БОЙ ]",
    "[ CONFIRM ]": "[ ПОДТВЕРДИТЬ ]",
    "[ CONTINUE ]": "[ ПРОДОЛЖИТЬ ]",
    "[ CREDITS ]": "[ ТИТРЫ ]",
    "[ EXIT ]": "[ ВЫХОД ]",
    "[ JOIN DISCORD ]": "[ ПРИСОЕДИНИТЬСЯ К DISCORD ]",
    "[ LOAD GAME ]": "[ ЗАГРУЗИТЬ ИГРУ ]",
    "[ LOADOUT ]": "[ СНАРЯЖЕНИЕ ]",
    "[ NEW GAME ]": "[ НОВАЯ ИГРА ]",
    "[ OPERATIONS ONLINE ]": "[ СЕТЬ ОПЕРАЦИЙ ОНЛАЙН ]",
    "[ OPERATIONS ]": "[ ОПЕРАЦИИ ]",
    "[ OPTIONS ]": "[ НАСТРОЙКИ ]",
    "[ QUESTS ]": "[ ЗАДАНИЯ ]",
    "[ SKILLS ]": "[ НАВЫКИ ]",
