    // ==== часть 01: названия ядер ====
    "Agility Response System": "Система отклика ловкости",
    "Balanced Defense Profile": "Сбалансированный профиль защиты",
    "Balanced Combat Profile": "Сбалансированный боевой профиль",
    "Balanced Profile": "Сбалансированный профиль",
    "Covert Operations Mesh": "Сеть скрытых операций",
    "Deflection Array Controller": "Контроллер массива отклонения",
    "Ergonomics Suite": "Эргономичный набор",
    "Weight Capacity Upgrade": "Улучшение грузоподъемности",
    "Feed Amplifier": "Усилитель подачи",
    "Grip-Lock Firmware": "Прошивка Grip-Lock",
    "Hardened Shell Framework": "Структура закаленного корпуса",
    "Heavy Impact Routine": "Протокол тяжелого удара",
    "Heavy Bolt Routine": "Протокол тяжелого затвора",
    "Impact Compiler": "Компилятор удара",
    "Lightweight Combat Mesh": "Легкая боевая сеть",
    "Loot Optimization Engine": "Движок оптимизации лута",
    "Penetration Geometry Stack": "Стек геометрии пробития",
    "Mobility Override Protocol": "Протокол перехвата мобильности",
    "Monoblade Edge Map": "Карта кромки монолезвия",
    "Nomad Framework": "Структура Nomad",
    "Nomad": "Nomad",
    "Smart Organizer Protocol": "Протокол умной организации",
    "Overdrive Scheduler": "Планировщик Перегрузки",
    "Packrat Protocol": "Протокол Packrat",
    "Penetration Stack": "Стек пробития",
    "Piercing Calibration": "Калибровка пробития",
    "Composite Plating Matrix": "Матрица композитной брони",
    "Quick-Draw System": "Система быстрого извлечения",
    "Quick-Cycle Loader": "Быстроцикловый загрузчик",
    "Reach Extender Calibration": "Калибровка удлинителя дистанции",
    "Quick-Recovery Algorithm": "Алгоритм быстрого восстановления",
    "Scavenger Suite Firmware": "Прошивка набора Scavenger",
    "Servo-Assist Actuators": "Сервоприводы с поддержкой",
    "Shadow Weave Integrator": "Интегратор Shadow Weave",
    "Armor-Shear Protocol": "Протокол Armor-Shear",
    "Smuggler's Partition": "Отсек контрабандиста",
    "Streamlined Carry System": "Оптимизированная система переноски",
    "Tactical Mobility System": "Система тактической мобильности",
    "Vital Strike Suite": "Набор критических ударов",
    "Vital Targeting Suite": "Набор уязвимых целей",
    "Vitality Amplifier Core": "Ядро усилителя жизненных сил",
