    // ==== JS_UI часть 6: результаты 2-го тура пользователя ====
    "HULL PLATING": "Бронирование корпуса",
    "CRIT LENS": "Крит. линза",
    "DAMAGE AMP": "Усиление урона",
    "< HUB": "< HUB",
    "GHOST": "Призрак",
    "OPEN": "Открыть",
    "GLITCH FLASH": "Вспышка GLITCH",
    "DR": "Сниж. урона",
    "STA": "Выносливость",
    "USE": "Использовать",
    "NO SIGNAL": "Нет сигнала",
    "SEARCH...": "Поиск...",
    "EXTRACTION SUCCESSFUL": "Эвакуация успешна",
    "QUEST COMPLETE:": "Задание выполнен:",
    "FIELD NOTES: CHECK THE MENTOR PANEL": "Полевые заметки: проверьте панель наставника",
    "// DID YOU KNOW?": "// А ВЫ ЗНАЛИ?",
    "DID YOU KNOW?": "А ВЫ ЗНАЛИ?",
    "Enemy Regen": "Регенерация врага",
    "Armor Shred": "Разрушение брони",
    "Heal Suppression": "Подавление лечения",
    "Enemy Enrage": "Ярость врага",
    "Corruption Shields": "Щиты коррупции",
    "Signal Static": "Помехи сигнала",
    "Death Echo": "Эхо смерти",
    "Phantom Strike": "Призрачный удар",
    "Signal Overdrive": "Перегрузка сигнала",
    "Reality Fracture": "Разлом реальности",
    "Fresh body, familiar face. Want my guided onboarding on this character? The tasks pay real rewards: cash, custom gear, FLUX and INSANITY.": "Новое тело, знакомое лицо. Хотите, я проведу вводный инструктаж по этому персонажу? За задачи дают реальные награды: деньги, кастомное снаряжение, FLUX и INSANITY.",
    "Click the SILENT EXPANSE marker on the map, then hit DEPLOY on the right. Extract alive to keep the loot.": "Нажмите на маркер SILENT EXPANSE на карте, а затем нажмите DEPLOY справа. Эвакуируйтесь живым, чтобы сохранить добычу.",
    "Finish a raid; the summary screen lists HEAL, LOADOUT, REDEPLOY and CONTINUE.": "Завершите RAID; на экране итогов будут указаны HEAL, LOADOUT, REDEPLOY и CONTINUE.",
    "HUB > TRADERS: pick GUNSMITH, open his QUEST tab, complete the Welcome Gift job.": "HUB > TRADERS: выберите GUNSMITH, откройте его вкладку QUEST и выполните задание «Welcome Gift».",
    "HUB: LOADOUT. Shift-click gear to equip; drag mags into the backpack container.": "HUB: LOADOUT. Shift+клик по снаряжению, чтобы экипировать; перетащите магазины в контейнер рюкзака.",
    "Options > GAMEPLAY: Auto Accept and Complete Quests.": "Настройки > GAMEPLAY: Автоматический прием и выполнение заданий.",
    "Silent Expanse is preset to corruption level 1. Click the marker, then hit DEPLOY on the right and clear the raid.": "SILENT EXPANSE предустановлен на уровень коррупции 1. Нажмите на маркер, затем нажмите DEPLOY справа и завершите RAID.",
    "Boss got you stuck? Pump DAMAGE AMP and HULL PLATING in the shop. Better raid gear raises your base stats too.": "Застряли на боссе? Прокачайте DAMAGE AMP и HULL PLATING в магазине. Лучшее RAID-снаряжение также повышает ваши базовые характеристики.",
    "INSANITY terminal: the shop panel on the right. DAMAGE AMP and CRIT LENS under OFFENSE, HULL PLATING under DEFENSE.": "Терминал INSANITY: панель магазина справа. DAMAGE AMP и CRIT LENS находятся в разделе OFFENSE, HULL PLATING - в разделе DEFENSE.",
    "Stow a magazine and a medkit in your containers": "Поместите магазин и аптечку в свои контейнеры",
    "Skip this task? You will not get its reward.": "Пропустить задание? Вы не получите награду.",
    ">_ SELECT_CLASS": ">_ ВЫБОР_КЛАССА",
    "Speed & Precision": "Скорость и точность",
    "Raw Damage": "Чистый урон",
    "Elemental Mastery": "Мастерство стихий",
    "Defense & Sustain": "Защита и живучесть",
    "High Risk, High Reward": "Высокий риск - высокая награда",
    "+3 HP and +0.2 Armor per point": "+3 HP и +0.2 брони за единицу",
    "RPM": "выстр./мин",
    "Armor Pen": "Пробитие брони",
    "Cold Damage": "Урон холодом",
    "Lightning Damage": "Урон молнией",
    "Fire Damage": "Урон огнем",
    "Total Raids": "Всего RAID",
    "Extractions": "Эвакуаций",
    "Failed": "Провалено",
    "Success Rate": "Процент успеха",
    "Hostiles Eliminated": "Уничтожено врагов",
    "Highest Single Hit": "Макс. разовый урон",
    "Sort items": "Сортировать предметы",
    "All items": "Все предметы",
    "Gear only": "Только снаряжение",
    "Junk only": "Только хлам",
    "Salvage multiple items": "Массовый разбор предметов",
    "Sell multiple items": "Массовая продажа предметов",
    "Lock items": "Заблокировать предметы",
