    // ==== chunk 02: insanity boost/cache/mastery ====
    "2× AUTO SPEED": "2× 自动速度",
    "2× DAMAGE": "2× 伤害",
    "GOLD RUSH": "淘金热",
    "2× INSANITY": "2× 疯狂",
    "AEGIS CACHE": "神盾补给箱",
    "ARMORY CACHE": "军械补给箱",
    "MYTHIC CACHE": "神话补给箱",
    "POWER CACHE": "能量补给箱",
    "PROTO CACHE": "原型补给箱",
    "SCRAP CACHE": "废料补给箱",
    "SEED CACHE": "种子补给箱",
    "BLOOD DEBT": "血债",
    "BLOOD TITHE": "血税",
    "CACHE INSTINCT": "补给直觉",
    "CROWN'S EDGE": "王冠之刃",
    "CROWN RESONANCE": "王冠共鸣",
    "DEAD CALM": "死寂",
    "DULLED PAIN": "钝痛",
    "FAST HANDS": "快手",
    "GHOST STEP": "鬼步",
    "GOLDEN MADNESS": "黄金疯狂",
    "HOLLOW SHELL": "空壳",
    "LUCID NIGHTMARE": "清醒噩梦",
    "PLATED HUSK": "装甲躯壳",
    "RAGE SIGNAL": "狂怒信号",
    "RIGGED COIN": "灌铅硬币",
    "SIN FRENZY": "罪孽狂热",
    "SIN SIPHON": "罪孽虹吸",
    "THICK SKIN": "厚皮",
    "TRIGGER DISCIPLINE": "扳机纪律",
    "VOID BARGAIN": "虚空交易",
    "WARDEN'S BANE": "WARDEN克星",
    "SERVO TUNING": "伺服调校",
    "DEAD EYE": "死眼",
    "NEURAL SPIKE": "神经尖刺",
    "SIN HARVESTER": "罪孽收割者",
