    // ==== chunk 12: augment/item/junk açıklamaları (tier etiketleri [Standard] vb. Latin) ====
    "+3% insanity gain (permanent)": "+3% 疯狂获取（永久）",
    "Indestructible spine with crowd control immunity.": "坚不可摧的脊柱，免疫控制效果。",
    "Artificial gland for combat adrenaline surge.": "人工腺体，战斗中激发肾上腺素。",
    "Embedded trauma unit that activates during combat.": "内置创伤单元，战斗中自动激活。",
    "Lightweight frame with balanced stat enhancement.": "轻量化骨架，均衡强化各项属性。",
    "Power core that supercharges combat abilities.": "为战斗技能超载供能的能量核心。",
    "Heavy-duty frame with emergency revival system.": "重型骨架，附带紧急复苏系统。",
    "Unlimited power source for skill enhancement.": "为技能强化提供无限能源。",
    "Anti-gravity propulsion for enhanced mobility.": "反重力推进，大幅提升机动性。",
    "Enhanced targeting optics. Passively increases damage.": "强化瞄准光学系统。被动提升伤害。",
    "Neural network that amplifies damage with each kill.": "神经网络，每次击杀都会放大伤害。",
    "Every 5th strike triggers devastating power strike.": "每第 5 次攻击触发毁灭性的强力打击。",
    "Shoulder-mounted rocket launcher.": "肩挂式火箭发射器。",
    "Nanite-infused arms that apply corrosive damage over time.": "注入纳米机器人的手臂，施加持续腐蚀伤害。",
    "Calls orbital bombardment at combat start.": "战斗开始时呼叫轨道轰炸。",
    "Automated turret that attacks nearby enemies.": "自动炮塔，攻击附近的敌人。",
    "High-precision servo motors for perfect aim.": "高精度伺服电机，实现完美瞄准。",
    "Quantum tech fires rapid burst at combat start.": "量子科技，战斗开始时打出急速连发。",
    "Adaptive armor that hardens on impact.": "自适应护甲，受击时硬化。",
    "Bio-synthetic skin with rapid healing capabilities.": "生物合成皮肤，具备快速愈合能力。",
    "Each hit taken increases armor, stacking through combat.": "每次受击提升护甲，战斗中持续叠加。",
    "Neural boost for faster looting and movement.": "神经加速，拾取和移动更快。",
    "Industrial-grade skeleton for increased carrying capacity.": "工业级骨骼，提升负重能力。",
    "Dark energy core that drains life from enemies.": "暗能量核心，从敌人身上汲取生命。",
    "Helps you find items and detects enemies up ahead.": "帮你寻找物品，并探测前方的敌人。",
    "Basic dog food. Restores 50% hunger. Lasts 1 hour.": "基础狗粮。恢复 50% 饱食度。持续 1 小时。",
    "High quality dog food. Fully restores hunger. Lasts 2 hours.": "优质狗粮。完全恢复饱食度。持续 2 小时。",
    "A classic tennis ball. +5 happiness per pet. 100 durability.": "经典网球。每次抚摸 +5 快乐值。耐久 100。",
    "Durable rope toy. +8 happiness per pet. 150 durability.": "耐用绳结玩具。每次抚摸 +8 快乐值。耐久 150。",
    "Basic mining GPU. +0.0001 BTC/min. Install in mining rig.": "基础矿用显卡。+0.0001 BTC/分钟。安装到矿机中。",
    "Advanced mining GPU. +0.0002 BTC/min. Higher hash rate.": "进阶矿用显卡。+0.0002 BTC/分钟。更高算力。",
    "Elite mining GPU. +0.0003 BTC/min. Maximum performance.": "精英矿用显卡。+0.0003 BTC/分钟。极致性能。",
    "Universal AR magazine. Standard capacity.": "通用突击步枪弹匣。标准容量。",
    "Bolt-action stripper clip. For internal magazines.": "栓动步枪桥夹。用于内置弹仓。",
    "Universal DMR magazine. Round count varies by weapon.": "通用精射步枪弹匣。装弹数因武器而异。",
    "Universal pistol magazine. Ammo count varies by weapon.": "通用手枪弹匣。装弹数因武器而异。",
    "Universal shotgun magazine. Shell count varies by weapon.": "通用霰弹枪弹匣。装弹数因武器而异。",
    "Universal SMG magazine. High capacity.": "通用冲锋枪弹匣。大容量。",
    "Flawless energy core. Doubles upgrade success chance.": "完美无瑕的能量核心。升级成功率翻倍。",
    "Multiple First Aid Kit. 400 uses.": "多人急救包。400 次使用。",
    "Advanced First Aid Kit. 200 uses.": "高级急救包。200 次使用。",
    "Individual First Aid Kit. 100 uses.": "单兵急救包。100 次使用。",
    "You feel like you can conquer the world.": "你感觉自己能征服全世界。",
    "Jailbreaks [Standard] gear to [Enhanced].": "将 [Standard] 装备越狱升级为 [Enhanced]。",
    "Reflashes properties on [Enhanced] gear.": "重刷 [Enhanced] 装备的属性。",
    "Some men just want to watch the world burn.": "有些人只想看着世界燃烧。",
    "Outputs more energy than it receives. Physics hates this.": "输出的能量比输入的还多。物理学恨透了它。",
    "Records events before they happen. Playback not recommended.": "在事件发生之前就记录下来。不建议回放。",
    "Deez nuts.": "就这玩意儿。",
    "Rusty, bent, and sharp. Like everyone else in this city.": "生锈、弯曲、锋利。跟这座城里的每个人一样。",
    "Corroded beyond recognition. Might be art, might be trash.": "锈蚀到面目全非。可能是艺术品，也可能是垃圾。",
    "Holds the world together. Every pipe, every wall, every lie.": "维系着整个世界。每根管道，每面墙，每个谎言。",
    "Hit it until it works. Engineering 101.": "敲到能用为止。工程学入门第一课。",
    "Still spins when you touch it. No one knows why.": "碰一下还会转。没人知道为什么。",
    "RIP": "安息吧",
    "Solders a new mod onto [Enhanced] gear.": "在 [Enhanced] 装备上焊接一个新模组。",
    "I bet there is 100 BTC in there.": "我打赌里面有 100 BTC。",
    "An experimental core that seems to bend reality around it.": "一枚实验核心，似乎在扭曲周围的现实。",
    "Half empty or half full? Completely empty.": "半空还是半满？完全是空的。",
    "Keeps the rain out. That's about it.": "能挡雨。仅此而已。",
    "Could be a car door. Could be a fridge. Nobody remembers.": "可能是车门，也可能是冰箱。没人记得了。",
    "Lighter than guilt, stronger than excuses.": "比愧疚更轻，比借口更强。",
    "Data once moved through this faster than bad news.": "数据曾在这里面跑得比坏消息还快。",
    "Upgrades [Enhanced] to [Custom] with new mod.": "将 [Enhanced] 升级为 [Custom] 并附带新模组。",
    "Military-grade. Built by the lowest bidder.": "军规品质。最低价中标商制造。",
    "Worth more than you. Per gram, at least.": "比你值钱。至少按克算是。",
    "Doesn't mesh with anything. Story of my life.": "跟什么都咬合不上。我的人生写照。",
    "Still has some bounce. Unlike morale around here.": "还有点弹性。不像这里的士气。",
    "Red means stop. Green means go. Both are stuck.": "红色停，绿色行。俩都卡死了。",
    "Connects nothing to nowhere. Essential infrastructure.": "把虚无连接到乌有。关键基础设施。",
    "Stopped at 3:47 AM. Someone's last bad night.": "停在凌晨 3:47。某人最后一个糟糕的夜晚。",
    "Smooth. Unlike everything else around here.": "顺滑。不像这附近的其他一切。",
    "Keeps spinning no matter which way the world tilts.": "无论世界往哪边倾斜，它都继续旋转。",
    "The muscle behind every door that slammed in your face.": "每一扇摔在你脸上的门背后的肌肉。",
    "Overclocks [Custom] gear with a powerful mod.": "用一个强力模组为 [Custom] 装备超频。",
    "Enough pressure to move a wall. Or what's left of one.": "压力足以推动一面墙。或者墙的残骸。",
    "Still sparks. Some things refuse to die.": "还能打出火花。有些东西就是不肯死。",
    "Wrong head for every screw you'll ever find.": "对你能找到的每颗螺丝来说都是错的刀头。",
    "Grip strength of a desperate man.": "绝望之人的握力。",
    "Every mechanic's first and last resort.": "每个技工的第一选择，也是最后手段。",
    "Cuts wire. Also cuts fingers if you're not careful.": "剪电线。不小心的话也剪手指。",
    "14 tools in one. 13 of them are knives.": "十四合一工具。其中十三个是刀。",
    "Tip's seen better days. Haven't we all.": "烙铁头早已不复当年。我们又何尝不是。",
    "Fixes metal. Fixes people too, technically.": "修金属。严格来说，也能修人。",
    "Every locked door is an opportunity. This makes it official.": "每扇锁着的门都是机会。这套工具让它名正言顺。",
    "Completely resets and rebuilds a [Custom] item.": "完全重置并重构一件 [Custom] 物品。",
    "0% charge, 100% optimism.": "电量 0%，乐观 100%。",
    "Sticks to everything except what you want.": "什么都粘，就是不粘你想粘的。",
    "Cleans everything except your conscience.": "什么都能洗净，除了你的良心。",
    "Smells like progress. Don't ask how it tastes.": "闻起来像进步。别问尝起来怎么样。",
    "Dissolves bonds. Molecular and emotional.": "溶解一切联结。分子层面的，情感层面的。",
    "Apply, ignite, stand back. Way back.": "涂抹，点燃，后退。退远点。",
    "Handle with care. Or don't. Natural selection.": "小心轻放。不小心也行。自然选择。",
    "Could be a shirt. Could be a bandage. Probably both.": "可能是衬衫，也可能是绷带。八成两者都是。",
    "Optimizes the numeric performance of mods.": "优化模组的数值表现。",
    "Filtered air for about a week. Now it's decoration.": "过滤了大概一周的空气。现在是装饰品。",
    "Thread count: don't ask.": "织物支数：别问。",
    "One boot. Size unknown. Dreams of being a pair.": "一只靴子。尺码不明。梦想凑成一双。",
    "Left hand only. Somewhere out there is a lonely right one.": "只有左手。世上某处有一只孤独的右手。",
    "Three bullet holes and a coffee stain. Lived a full life.": "三个弹孔和一块咖啡渍。度过了充实的一生。",
    "Six pockets. Four have holes. Two have secrets.": "六个口袋。四个有洞。两个有秘密。",
    "Plates are gone. Carrier's still good. Mostly.": "插板没了。背心还能用。大概吧。",
    "Peeled off someone's vest. He doesn't need it anymore.": "从某人背心上撕下来的。他用不着了。",
    "Corrupts an item. Unpredictable outcomes. Locks item.": "侵蚀一件物品。结果不可预测。物品将被锁定。",
    "Fabric that stops bullets. Doesn't stop bad decisions.": "能挡子弹的织物。挡不住糟糕的决定。",
    "Type-C. No wait, micro. Actually, who knows anymore.": "Type-C 的。不对，是 micro。算了，谁还分得清。",
    "Once lit up someone's gaming setup. RGB dreams, dead.": "曾点亮过某人的电竞桌。RGB 之梦，已死。",
    "Missing the W, A, S, and D keys. Gamer confirmed.": "缺了 W、A、S、D 四个键。实锤是玩家。",
    "8 gigs of memories. None of them yours.": "8G 的回忆。没有一段属于你。",
    "Smells like ambition and burnt silicon.": "闻起来像野心和烧糊的硅。",
    "50 terabytes. Contents unknown. Probably memes.": "50TB。内容不明。多半是梗图。",
    "Picks up frequencies that shouldn't exist.": "接收着不该存在的频率。",
    "4K resolution. Last footage: someone running.": "4K 分辨率。最后的画面：有人在逃跑。",
    "Removes all properties, reverting item to [Standard].": "移除所有属性，将物品还原为 [Standard]。",
    "Still projects, but only static and sadness.": "还能投影，但只剩雪花和悲伤。",
    "256-bit encryption. The password is probably 'admin'.": "256 位加密。密码八成是 'admin'。",
    "A family. Smiling. From before.": "一家人。微笑着。来自从前。",
    "Reads: 'If you find this, I'm already gone.'": "上面写着：'如果你看到这个，我已经不在了。'",
    "Photo doesn't match anyone alive.": "照片对不上任何活着的人。",
    "Redacted so heavily it's basically abstract art.": "涂黑得太狠，基本算抽象艺术了。",
