    // ==== часть 06: оставшиеся названия заданий ====
    "Meat Grinder": "Мясорубка",
    "Overclock": "Оверклокинг",
    "Beyond Human": "За пределами человеческого",
    "Scrap Run": "Вылазка за ломом",
    "Chop Shop": "Цех разборки",
    "First Dose": "Первая доза",
    "Static in the Blood": "Статика в крови",
    "Cage Fight": "Бой в клетке",
    "Protocol: UNHUMAN": "Протокол: UNHUMAN",
    "First Chrome": "Первый хром",
    "Nerve Damage": "Повреждение нервов",
    "First Signal": "Первый сигнал",
    "Interference": "Помехи",
    "Feedback Loop": "Петля обратной связи",
    "Cascade Event": "Каскадное событие",
    "Singularity": "Сингулярность",
    "Thread Count": "Подсчет нитей",
    "Quiet Run": "Тихая вылазка",
    "Prototype Weave": "Прототип плетения",
    "Iron Veil": "Железная завеса",
    "Man's Best Friend": "Лучший друг человека",
    "Supply Chain": "Цепочка поставок",
    "Terminal Access": "Доступ к терминалу",
    "Big Haul": "Большая добыча",
    "Deep Pockets": "Глубокие карманы",
    "Glitch Touch": "Прикосновение GLITCH",
    "Salvage King": "Король разборки",
    "Rare Thread": "Редкая нить",
