    // ==== parça 16: mythic modül/combo tam metinleri + karakter tooltipleri + mastery/harvest reset + insanity shop ====
    "+25 magazine capacity": "+25 弹匣容量",
    "+90 damage, +20 armor pen": "+90 伤害，+20 护甲穿透",
    "+60 armor penetration": "+60 护甲穿透",
    "+110 damage, +30 armor pen": "+110 伤害，+30 护甲穿透",
    "+70 damage, +1.0 reach": "+70 伤害，+1.0 攻击距离",
    "+40 fire rate / +0.2 attack speed": "+40 射速 / +0.2 攻击速度",
    "+40 damage": "+40 伤害",
    "+90 armor": "+90 护甲",
    "+45 armor, +10 evasion": "+45 护甲，+10 闪避",
    "+70 health, periodic combat heal": "+70 生命，战斗中定期治疗",
    "+120 health": "+120 生命",
    "Optic + Servo → +20 evasion, +0.5 HS mult": "瞄具 + 伺服 → +20 闪避，+0.5 爆头倍率",
    "Bleed + Optic → unlocks an ABILITY SLOT": "流血 + 瞄具 → 解锁一个能力插槽",
    "3× Power → unlocks an ABILITY SLOT": "3× 能量 → 解锁一个能力插槽",
    "All Elemental": "全元素",
    "All Stats": "全属性",
    "Bonus cold damage": "冰霜伤害加成",
    "Bonus fire damage": "火焰伤害加成",
    "Bonus lightning damage": "闪电伤害加成",
    "Bonus to all elements": "所有元素加成",
    "Chance for extra loot drops": "额外战利品掉落概率",
    "Chance for higher tier drops": "更高品阶掉落概率",
    "Chance to ricochet bullets": "子弹跳弹概率",
    "Chance to survive a fatal hit": "抵挡致命一击的概率",
    "Cheat Death": "欺骗死亡",
    "Damage Bonus": "伤害加成",
    "Equilibrium-type passives: multiplies Armor, HP and Damage by this percent. Included in the values shown": "均衡类被动：护甲、生命与伤害按此百分比加乘。已计入显示的数值",
    "HP recovered from damage dealt": "按造成伤害的比例回复生命",
    "Max Stacks": "最大叠层",
    "Maximum status effect stacks": "状态效果最大叠层数",
    "No weapon equipped": "未装备武器",
    "RPM Bonus": "射速加成",
    "Skill tree damage bonus": "技能树伤害加成",
    "Skill tree fire rate bonus": "技能树射速加成",
    "Status effect duration": "状态效果持续时间",
    "Status effect strength": "状态效果强度",
    "INTERFERENCE": "干扰",
    "MELTDOWN": "熔毁",
    "VOID": "虚空",
    "SINGULAR": "奇点",
    "CDR": "冷却",
    "DMG%": "伤害%",
    "WPN": "武器",
    "LVL": "等级",
    "Reset ALL mastery nodes? Returns all Prestige Points.": "重置所有精通节点？将退还全部转生点数。",
    "Reset ALL Signal Harvest nodes? Echo Points are refunded.": "重置信号收割的所有节点？回声点数将全额退还。",
    "Reset ALL Madness Protocol nodes? Spent insanity is fully refunded.": "重置疯狂协议的所有节点？已花费的疯狂将全额退还。",
    "module": "模块",
    "combo": "连携",
    "grid": "网格",
    "core": "核心",
