    // ==== JS_UI parça 11: audit 3 (mentor prog, keystone, settings tam açıklamalar, chip'ler) ====
    "S sells, X salvages the hovered item. NEVER skips every prompt, mythic included: a misclick is final.": "S 出售、X 拆解悬停的物品。从不 会跳过所有确认（含 MYTHIC）：手滑即成定局。",
    "Takes and finishes every quest you qualify for, raids included. Needs stash room for the rewards. Prestige, endgame and reward-choice quests stay yours.": "自动接下并完成所有符合条件的任务（RAID 中也是）。奖励需要仓库空间。转生、终局和需选择奖励的任务仍由你决定。",
    "Caps internal update work to save CPU. Display output follows your monitor's refresh rate (engine limit): for a hard FPS cap use your GPU driver's frame limiter.": "限制内部更新以节省 CPU。画面输出跟随显示器刷新率（引擎限制）：如需硬性帧率上限，请使用显卡驱动的帧率限制器。",
    "Reduces recoil per shot. Also sets your headshot chance: handling / 5, capped at 20%": "降低每发后坐力。同时决定你的爆头率：操控性 / 5，上限 20%",
    "Protections always win, then Tier Cleanup force-sells bad bases, then Max Rarity sells the rest": "保护规则永远优先，随后品阶清理强制出售劣质基底，最后由最高稀有度出售其余",
    "Run a raid and come back alive": "跑一次 RAID 并活着回来",
    "Press HEAL on the extraction screen": "在撤离界面按下治疗",
    "Use root, flash and kernel on a STANDARD item": "在一件 STANDARD 物品上使用 root、flash 和 kernel",
    "Spend a skill point in the skill tree": "在技能树中花费一个技能点",
    "Click to allocate": "点击分配",
    "Must connect to allocated node": "必须连接到已分配的节点",
    "Start nodes are assigned by class": "起始节点由职业决定",
    "Sharp Edge": "锋利刀刃",
    "Relentless Strikes": "无情连击",
    "Unshakable": "不可动摇",
    "Unstable Power": "不稳定之力",
    "House Edge": "庄家优势",
    "Stacker": "叠层者",
    "Weight of Steel": "钢铁之重",
    "Damage Reduction": "减伤",
    "Elemental Damage": "元素伤害",
    "This effect can only trigger once per combat.": "此效果每场战斗只能触发一次。",
    "Triggers once per combat.": "每场战斗触发一次。",
    "You cannot be stunned.": "你不会被眩晕。",
    "Each time you take damage,": "每次受到伤害时，",
    "Each successful Melee hit grants": "每次近战命中都会给予",
    "If you spot the enemy first,": "若你先发现敌人，",
    "(both bonuses and penalties).": "（增益与惩罚皆是）。",
    "Elemental Effects deal": "元素效果造成",
    "Restart interface to apply language? Progress is saved.": "重启界面以应用语言？进度已保存。",
    "This cannot be undone.": "此操作无法撤销。",
    "Overwrite": "覆盖",
    "Delete": "删除",
    "Show completed": "显示已完成",
    "Skip the rest of the field notes?": "跳过其余的战地笔记？",
    "Sell all items up to a rarity tier?": "出售所有低于某稀有度的物品？",
    "Not enough money": "金钱不足",
    "[AUTO:ON]": "[自动:开]",
    "RLD": "装填",
    "STL": "潜行",
    "SCV": "拾荒",
    "HND": "操控",
    "HS": "爆头",
    "HSM": "爆头",
    "RCH": "距离",
    "SLT": "槽位",
    "RCO": "跳弹",
    "WGT": "重量",
    "WEI": "重量",
    "STIM": "兴奋剂",
    "SHOTGUN": "霰弹枪",
    "SMALL": "小",
    "CURRENCY": "货币",
    "Weapons": "武器类",
    "Tactical Rigs": "战术背心类",
    "Pack": "背包",
    "Helmet": "头盔",
    "Pistol": "手枪",
    "Rig": "战术背心",
    "Headset": "耳机",
    "AMB": "伏击",
    "BLO": "血拳",
    "BLU": "蛮牛",
    "DoN": "孤注",
    "EDG": "死缘",
    "ELE": "元素",
    "EXE": "处刑",
    "GHO": "幽灵",
    "HEA": "沉重",
    "HOU": "庄家",
    "IRO": "铁躯",
    "PAI": "止痛",
    "REL": "无情",
    "SEC": "重振",
    "SHA": "锋刃",
    "UNS": "不摇",
    "Rounds per minute": "每分钟射弹数",
    "Weapon damage range": "武器伤害范围",
    "Total health points": "总生命值",
    "Reduces enemy detection chance": "降低被敌人发现的概率",
    "Raids start with sprint enabled (same stamina rules; SHIFT still toggles mid-raid)": "RAID 开始时自动开启冲刺（耐力规则相同；RAID 中 SHIFT 仍可切换）",
    "Repair equipped weapons after raid ($)": "RAID 后修理已装备武器（$）",
    "Strapped your crafted piece on you. The old one is in your stash.": "把你制作的装备穿到了你身上。旧的那件在仓库里。",
