    // ==== chunk 01: kernel adları ====
    "Agility Response System": "敏捷响应系统",
    "Balanced Defense Profile": "均衡防御配置",
    "Balanced Combat Profile": "均衡战斗配置",
    "Balanced Profile": "均衡配置",
    "Covert Operations Mesh": "隐蔽行动网层",
    "Deflection Array Controller": "偏转阵列控制器",
    "Ergonomics Suite": "人体工学套件",
    "Weight Capacity Upgrade": "负重扩容升级",
    "Feed Amplifier": "供弹增幅器",
    "Grip-Lock Firmware": "锁握固件",
    "Hardened Shell Framework": "硬化外壳框架",
    "Heavy Impact Routine": "重击例程",
    "Heavy Bolt Routine": "重型枪机例程",
    "Impact Compiler": "冲击编译器",
    "Lightweight Combat Mesh": "轻量战斗网层",
    "Loot Optimization Engine": "战利品优化引擎",
    "Penetration Geometry Stack": "穿透几何堆栈",
    "Mobility Override Protocol": "机动超控协议",
    "Monoblade Edge Map": "单分子刃缘映射",
    "Nomad Framework": "流浪者框架",
    "Nomad": "流浪者",
    "Smart Organizer Protocol": "智能整理协议",
    "Overdrive Scheduler": "超频调度器",
    "Packrat Protocol": "囤积者协议",
    "Penetration Stack": "穿透堆栈",
    "Piercing Calibration": "穿刺校准",
    "Composite Plating Matrix": "复合装甲矩阵",
    "Quick-Draw System": "速拔系统",
    "Quick-Cycle Loader": "速循装填器",
    "Reach Extender Calibration": "延距校准",
    "Quick-Recovery Algorithm": "快速恢复算法",
    "Scavenger Suite Firmware": "拾荒者套件固件",
    "Servo-Assist Actuators": "伺服辅助致动器",
    "Shadow Weave Integrator": "暗影织网集成器",
    "Armor-Shear Protocol": "破甲协议",
    "Smuggler's Partition": "走私者暗格",
    "Streamlined Carry System": "流线携行系统",
    "Tactical Mobility System": "战术机动系统",
    "Vital Strike Suite": "要害打击套件",
    "Vital Targeting Suite": "要害瞄准套件",
    "Vitality Amplifier Core": "生命增幅核心",
