name: Merge I18N Parts → Release

on:
  workflow_dispatch: # 👈 Кнопка "Run workflow"
  # push:
  #   branches: [ main ]

permissions:
  contents: write # Обязательно для создания релизов

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0

      - name: Run merge script
        run: python merge_i18n.py -i parts -o merged_dict.js

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: merged-i18n
          path: merged_dict.js

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: i18n-v${{ github.run_number }}
          files: zh.js
          name: Русификатор v${{ github.run_number }}
          generate_release_notes: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
